/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.in by autoheader.  */

/* Define to 1 if you have the <dirent.h> header file, and it defines `DIR'.
   */
#define HAVE_DIRENT_H 1

/* Define to 1 if you have the <ndir.h> header file, and it defines `DIR'. */
/* #undef HAVE_NDIR_H */

/* Define to 1 if you have the <sys/dir.h> header file, and it defines `DIR'.
   */
/* #undef HAVE_SYS_DIR_H */

/* Define to 1 if you have the <sys/ndir.h> header file, and it defines `DIR'.
   */
/* #undef HAVE_SYS_NDIR_H */

/* Name of package */
#define PACKAGE "kulic"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "2berny@seznam.cz"

/* Define to the full name of this package. */
#define PACKAGE_NAME "configure.in"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "configure.in 1.0"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "configure-in"

/* Define to the version of this package. */
#define PACKAGE_VERSION "1.0"

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Version number of package */
#define VERSION "1.0"
