/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.ac by autoheader.  */

/* Define to 1 if you have the `atexit' function. */
#define HAVE_ATEXIT 1

/* Define to 1 if you don't have `vprintf' but do have `_doprnt.' */
/* #undef HAVE_DOPRNT */

/* Define to 1 if you have the <fcntl.h> header file. */
#define HAVE_FCNTL_H 1

/* Define to 1 if you have the `floor' function. */
/* #undef HAVE_FLOOR */

/* Define to 1 if you have the <inttypes.h> header file. */
/* #undef HAVE_INTTYPES_H */

/* Define to 1 if you have the `HeartOfGold' library (-lHeartOfGold). */
/* #undef HAVE_LIBHEARTOFGOLD */

/* Define to 1 if you have the `SDL' library (-lSDL). */
/* #undef HAVE_LIBSDL */

/* Define to 1 if you have the `SDL_image' library (-lSDL_image). */
/* #undef HAVE_LIBSDL_IMAGE */

/* Define to 1 if you have the `SDL_mixer' library (-lSDL_mixer). */
/* #undef HAVE_LIBSDL_MIXER */

/* Define to 1 if you have the <memory.h> header file. */
/* #undef HAVE_MEMORY_H */

/* Define to 1 if you have the `memset' function. */
#define HAVE_MEMSET 1

/* Define to 1 if you have the `mkdir' function. */
#define HAVE_MKDIR 1

/* Define to 1 if you have the <SDL/SDL.h> header file. */
#define HAVE_SDL_SDL_H 1

/* Define to 1 if you have the <SDL/SDL_image.h> header file. */
#define HAVE_SDL_SDL_IMAGE_H 1

/* Define to 1 if you have the <SDL/SDL_mixer.h> header file. */
#define HAVE_SDL_SDL_MIXER_H 1

/* Define to 1 if you have the `sqrt' function. */
/* #undef HAVE_SQRT */

/* Define to 1 if you have the <stdint.h> header file. */
/* #undef HAVE_STDINT_H */

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the `strdup' function. */
#define HAVE_STRDUP 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define to 1 if you have the `vprintf' function. */
#define HAVE_VPRINTF 1

/* Name of package */
#define PACKAGE "orbital_eunuchs_sniper"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "zakk@timedoctor.org"

/* Define to the full name of this package. */
#define PACKAGE_NAME "orbital_eunuchs_sniper"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "orbital_eunuchs_sniper 1.29"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "orbital_eunuchs_sniper"

/* Define to the version of this package. */
#define PACKAGE_VERSION "1.29"

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Version number of package */
#define VERSION "1.29"

/* Define to 1 if the X Window System is missing or not being used. */
#define X_DISPLAY_MISSING 1

/* Define to empty if `const' does not conform to ANSI C. */
/* #undef const */
