CC= g++
LD= $(CC)
DEL= rm
MV= mv
CPPFLAGS= -g0 -O2
LFLAGS= -lSDL -lopengl32 -lglu32
MAIN= BeastieWorker.exe

HEADERFILES = main.h

OBJS = menu.o cursor.o font.o main.o matrixmath.o model3d.o player.o scene.o sound.o strings.o texture.o sky.o

SRCS = menu.cpp cursor.cpp font.cpp main.cpp matrixMath.cpp model3d.cpp player.cpp scene.cpp sound.cpp strings.cpp texture.cpp sky.cpp

all : ${MAIN}
	${MV} $(MAIN) ../$(MAIN)

clean :
	${DEL} -rf *.o

${MAIN} : ${OBJS}
	$(LD) -o $@ ${OBJS} ${LFLAGS}
