:NO|
UNLOCKCONTROLS|
IDLE|
:ZONELABEL1|
LOCKCONTROLS|
[ "This exhibit gives a brief"|
[ "overview on the Phi-Che Conflict."|
] "Sure, what didn't they tell me?" YES|
] "No, I know enough already" NO|
GOTO NO|
:YES|
[ "On Arn. 3, the most dreadful accident"|
[ "in Yanhan history occured."|
[|
[ "A high-ranking Yanhan official declared"|
[ "war on the small city-state of Phi-Che,"|
[ "a small strip of land thirty miles from"|
[ "Colony 5."|
[ "The Phi-Che used an ultra-safe, ultra-"|
[ "efficent nuclear reactor, which"|
[ "produced no waste and created"|
[ "no immediate danger."|
[ "He sent two hoverjets to attack"|
[ "the city, ordering them to fire"|
[ "on the reactor and destroy it, then"|
[ "contain the radiation as best as possible."|
[ "Unfortunately, the attack caused"|
[ "the reactor's core to drop into"|
[ "Yanha."|
[|
[ "The reaction continued, and eventually"|
[ "began to heat up the planet's"|
[ "interior to the melting point."|
[|
[ "Attempts were made to stop the reaction,"|
[ "but none succeeded.  Many brave men"|
[ "and women risked their lives to stop"|
[ "this catastrophe from destroying Yanha."|
GOTO NO|
