:NO|
UNLOCKCONTROLS|
IDLE|
:ZONELABEL1|
LOCKCONTROLS|
[ "This is an exhibit on the military"|
[ "history of modern Yanha.  View it?"|
] "Yes, please" YES|
] "No thank you" NO|
GOTO NO|
:YES|
[ "As with most Yanhan technology,"|
[ "seafaring military vessels were"|
[ "developed first, with their intent"|
[ "to destroy land-based defenses."|
[ "Rockets could be launched from these"|
[ "ships, and could deliver any size"|
[ "payload of any explosive material."|
[|
[ "Flight came into play about seventy"|
[ "years ago, when the first solid"|
[ "fuel multistage rockets were developed."|
[|
[ "Their destructive power was many times"|
[ "that of the sea-based rockets."|
[|
[ "Jets and hoverjets were developed"|
[ "after anti-gravity technology was"|
[ "created."|
[|
[ "These vehicles, along with the development"|
[ "of nuclear power, created a time bomb"|
[ "waiting to go off at the push"|
[ "of a button."|
GOTO NO|
