.TH KOBODL 6 "8 February 2003"
.SH NAME
kobodl - Kobo Deluxe, an enhanced version of the scrolling game XKobo
.SH SYNOPSIS
.B kobodl
[
.I options
]
.SH DESCRIPTION
Kobo Deluxe is a 3'rd person  scrolling 2D shooter with a simple
and responsive control system  - which you'll need to tackle the
tons of enemy ships that shoot at you,  chase you, circle around
you shooting,  or even  launch other ships at you,  while you're
trying to  destroy the  labyrinth  shaped  bases.  There  are 50
action packed  levels with  smoothly increasing  difficulty, and
different combinations of enemies that require different tactics
to be dealt with successfully.
.P
Kobo Deluxe has an improved graphics engine that can take full
advantage  of any video  frame rate,  without affecting the game
logic and timing. It also adds sound effects, flashy "dashboard"
graphics,  full-screen mode and various  other features expected
from a modern game.  Kobo Deluxe is based on SDL,  and therefore
builds and runs on all major operating systems,  as well as some
more unusual platforms.
.P
In short,  Kobo Deluxe is loads of  classical arcade style fun
for just about any machine with graphics and sound!
.SH CONTROLS
The ship can be controlled with the keyboard, or optionally a mouse or
joystick. With the keyboard, the arrow keys move the ship, and the shift
key shoots. Escape can be used to exit the game.
.SH OPTIONS
Note that most options can be configured in the game or via the config
file.
.TP
.B \-hiscores
.TP
.B \-highscores
List high scores.
.TP
.B \-showcfg
Display configuration file.
.TP
.B \-noframe
Don't display frame around play field.
.TP
.B \-fps
Display frames per second in corner of window.
.TP
.B \-maxfps n
Limit the framerate (fps). Saves power on laptops. 75 works well.
.TP
.B \-debug
Display more debug output.
.TP
.B \-[no]fullscreen
Enable/disable full screen mode.
.TP
.B \-buffer n
Display buffer mode.
.TP
.B \-depth n
Display depth.
.TP
.B \-[no]filter
Enable/disable motion interpolation filter.
.TP
.B \-[no]cheat
Enable/disable cheat mode, which allows any level to be played and does not
update high score file.
.TP
.B \-[no]indicator
Enable/disable collision testing mode.
.TP
.B \-wait n
Set game speed.
.TP
.B \-[no]sound
Enable/disable sound.
.TP
.B \-latency n
Set sound latency.
.TP
.B \-vol n
Set sound volume.
.TP
.B \-reverb n
Set reverb level.
.TP
.B \-threshold n
Set limiter gain.
.TP
.B \-release n
Set limiter speed.
.TP
.B \-files
Specify the root path of the game.
.TP
.B \-gfx
Specify the path to the game's graphics data.
.TP
.B \-sfx
Specify the path to the game's sound data.
.TP
.B \-scores
Specify the path to the game's score file.
.TP
.B \-[no]joystick
Enable/disable joystick control.
.SH FILES
.TP
.B ~/.kobodlrc
The per-user configuration file for Kobo Deluxe.
.SH AUTHORS
Originally written by
Akira Higuchi (a-higuti@math.hokudai.ac.jp), XKobo was turned into Kobo
Deluxe by David Olofson <david@olofson.net>
.SH COPYRIGHT
Copyright (c) 1995,1996, Akira Higuchi
.P
Copyright (c) 2001-2003, David Olofson
.P
\fBKobo Deluxe\fP is free software; you can redistribute it and/or modify it
under the terms of the GNU General Public License.
