
       ***                     *********          ********
      *****                   ***********        **********
       ***                     ***   ***          **     ***
       ***                      ***   *           **      ***
       ***                       ***              **      ***
       ***                        ***             **      ***
       ***      *      *       *   ***      *     **      ***   *
      *****    ***    ***     ***   ***    ***    **     ***   ***
      *************  *****   ***********  *****  **********   *****
       ***********    ***     *********    ***    ********     ***
                       *                    *                   *

                   DAZ SON OF MORSECODE PRESENTS:-

                     THE SOLUTION OF MAGIC WORLD

        ********        ***     ********     ********    ***     ***
       **********      *****   **********   **********  *****   *****
        **     ***      ***          ***          ***    ***     ***
        **      ***     ***         ***          ***      ***   ***
        **      ***     ***        ***          ***        *** ***
        **      ***     ***       ***          ***          *****
        **      ***     ***      ***          ***            ***
        **     ***      ***     ***          ***             ***
       **********      *****   **********   **********      *****
        ********        ***     ********     ********        ***



 GENERAL HELPS:-

 -ALWAYS COLLECT GEMS BECAUSE THEY RESTORE ANY LOST ENERGY AND ALSO
PLAY AN IMPORTANT PART IN LATER GAME.

 -TO WALK ACROSS CLOUDS ALWAYS JUMP UP THEN WALK A LITTLE WAY ACROSS
THEN JUMP UP AGAIN.

 -WHEN I SAY JUMP OF EDGE, I MEAN PLACE DIZZY ON EDGE ON ITEM TO JUMP
OFF AND JUMP UP AND THE PUSH ANGLED DIRECTION WHILST IN THE AIR.

 -JUMP ACROSS WELL. YOU STAND A LITTLE BIT AWAY FROM EGDE OF WELL AND
JUMP ONTO EGDE OF WELL AND THEN JUMP OVER WELL GAP. FOR RETURN JOURNEY
ALWAYS USE THE CLOUDS SINCE THIS IS SAFER THAN JUMPING OVER THE WELL.

-USING SHARK TO CROSS MOAT. JUMP SLIGHTY BEFORE THE SHARK FIN REACHES
THE BANK AND WHEN YOU LAND ON THE FIN CONTINUE PUSHING DIRECTION IN
WHICH FIN IS TRAVELLING, OTHERWISE YOU WILL FALL INTO WATER. ALSO ON
RETURN JOURNEY USE CLOUDS SINCE SAFER.

-TO USE DRAWBRIDGE AT LEFT OFF CASTLE. BREAK LEVER SO THAT THE
DRAWBRIDGE GOES IN AND OUT. NEVER CROSS DRAWBRIDGE FROM RIGHT TO LEFT
ALWAYS USE CLOUDS IN TOWER ABOVE (NO POINT IN TALKING RISKS). ON
CROSSING THE BRIDGE FROM LEFT TO RIGHT ALWAYS JUMP ONTO THE BRIDGE
BEFORE IT REACHES THE BANK IF IT SEEMS THE BRIDGE IS CATCHING YOU UP
JUMP DIAGONALLY JUST BEFORE BRIDGE DROPS OUT FROM UNDER YOU.


 NOW FOR THE COMPLETE SOLOUTION......


 -TO OPEN CASTLE:- USE BACKDOOR KEY FOUND ON MONOLITH. IGNORE RUBBISH
AND MILKBOTTLE.

 -TO RESCUE DORA:- FIRST GOTO THE WATCH TOWER IN THE CASTLE AND
COLLECT THE POWER PILL. GOTO TO THE EDGE OF THE BANK BY WHERE GHOSTS
ARE. IF YOU ARE CARRYING THE POWER PILL THE GHOSTS WILL BE FLASHING
ANDTHEY CAN BE KILLED IF THEY TOUCH YOU. JUMP OF EDGE OF BANK AND EGDE
OF FIRST LILY PAD UNTIL YOU ARE ON SECOND LILY PAD. COLLECT FROG AND
KILL THE GHOSTS IF YOU HAVE NOT ALREADY DONE SO.NOW RETURN TO THE
CASTLE VIA SHARK FIN AND USE FROG WITH PRINCE CHARMING. DROP POWER
PILL.

 -TO RESCUE DENZIL:- FIRST GOTO TO TOWER IS RIGHT OF CASTLE AND JUMP
ONTO CLOUD WALK ALONG CLOUD USING METHOD SUGGESTED ABOVE UNTIL YOU ARE
ON THE EDGE AND JUMP RIGHT WHILST ON THIS SCREEN COLLECT DUSTER. THEN
THERE IS A MIDDLE LEVEL OF CLOUDS ON THIS LEVEL WHERE THERE ARE TWO
CLOUDS JUMP TO THE RIGHT OF THE EGDE OF THE SECOND CLOUDS. YOU ARE NOW
ON THE SCREEN CALLEN ON THE TREE (IF I SAY GOTO ON THE TREE USE THIS
METHOD). ON THIS SCREEN THERE IS A PLATFORM TO THE RIGHT OF AND UNDER
THE PLATFORM WHERE THE MONKEY IS SITTING ON THE HOUSE. ON THIS
PLATFORM IS A BIG STICK. NOW GO UP FROM THIS SCREEN (BY STANDING ON
THE RIGHT  EDGE OF THE LEFT UPMOST PLATFORM AND JUMPING RIGHT).JUMP
RIGHT OF THE RIGHT EDGE OF THE UPPER RIGHT PLATFORM AND THEN WALK TO
THE EDGE OF THE CLOUD (USING METHOD IN GENERAL TIPS) AND JUMP TO THE
RIGHT ONCE YOU ARE ON THE MONOLITH, JUMP UP TO WHERE THE CAT IS AND
COLLECT CAT THEN JUMP OF MONOLITH.GO AND DROP THE DUSTER BY THE WELL.
GO TO THE CHAPEL IN THE CASTLE AND PICK UP THE GOLDEN CROSS LEAVE VIA
WINDOW IN THE WATCH TOWER TO THE LEFT.NOW GOTO THE SCREEN WHERE THE
TROLL IS AND STAND BY THE REAR END OF THE GOAT AND HIT IT WITH THE BIG
STICK. NOW CONTINUE LEFT UNTIL YOU ARE IN THE MIDDLE OF THE SCREEN
WHERE DENZIL IS AND DROP THE CROSS. NOW GO BACK TO THE CASTLE AND PICK
UP THE HANDLE AND GOTO THE WELL. JUMP TO THE LEFT SIDE OF THE WELL AND
USE HANDLE AND THEN COLLECT BUCKET. NOW GOTO THE GOOD WITCH'S ISLAND
AND GIVE THE CAT TO HER. SHE GIVES YOU INFO ON HOW TO FREE DILLON (SEE
LATER). NOW JUMP ONTO THE CENTRE OF THE LILY PAD TO RIGHT OF ISLAND
AND JUMP RIGHT. TO CROSS THIS SWAMP SCREEN JUMP OF EDGE OF EACH OF THE
LILY PADS (WHILE TRAVELING LEFT TO RIGHT BUT WHEN GOING FROM RIGHT TO
LEFT JUMP FROM THE CENTRE OF THE LAST LILY PAD OFF THE SCREEN).ONCE
YOU REACH THE BANK OF THE SWAMP GO RIGHT AND PICK UP THE DRINK ME
BOTTLE AND USE THE BUCKET WITH THE HOT WATER GEYSER. NOW GO BACK TO
DENZIL AND POUR THE WATER OVER HIM.DROP STERIO IN WATCH TOWER OF
CASTLE.


 -TO RESCUE DAISY:-PICK UP THE CROSS AND ENTER THE ICE PALACE GO DOWN
TO THE CRYPT. DROP THE CROSS OPPOSITE THE VAMPIRE. GO DOWN AND PICK UP
THE TORCH AND THE GO RIGHT AND GIVE DAISY THE DRINK ME POTION.


 -TO RESUE DILLON:- GO AND PICK THE APPLE BY DOZY AND THEN GOTO TO ON
THE TREE (VIA CLOUDS) AND THEN TO MONOLITH (VIA CLOUD) AND STANDING ON
THE EDGE OF THE PLATFORM (BELOW WHERE THE CAT WAS) BEFORE THE ORB JUMP
ON TO THE CLOUD AND THEN WALK TO THE EDGE AND JUMP OF THE RIGHT EDGE
OF THE CLOUD. YOU WILL LAND ON STRANGE HENGE. GET DAGGER AND GOTO BUSH
WHERE DILLON IS TRAPPED AND USE DAGGER TO GET A LEAF. DROP DAGGER AND
PICK UP LEAF. NOW GOTO THE WITCH'S ISLAND AND GIVE THE APPLE,LEAF AND
TORCH TO GLENDA.GET THE POTION AND GO AND POUR THE WEEDKILLER ON
DILLON'S BUSH.


 -TO RESCUE DOZY:- GOTO HIGHEST TOWER IN THE CASTLE AND GET THE
LIGHTNING CONDUCTOR AND THEN GOTO THE WATCH TOWER AND GET STERIO AND
JUMP OFF LEFT EDGE OF CLOUD AND THEN GOTO BARD'S HOUSE AND GIVE STERIO
TO BARD AND GET PIPES. GOTO WHERE DOZY LIES ASLEEP AND DROP CONDUCTOR
ON HIM AND THEN GOTO THE WELL AND PICK UP DUSTER AND FALL DOWN THE
WELL FROM LEFT TO RIGHT PUSHING RIGHT AS YOU FALL. YOU WILL LAND ON A
LEDGE AND THEN WHEN YOU PLAY THE PIPES THE MOUSE JUMPS INTO THE WATER.
NOW GO INTO THE SECRET PASSAGE WAY BEHIND WHERE THE MOUSE WAS AND GET
THE SOMETHING STICK AND THE GO LEFT. NOW CAREFULLY PICK UP THE LAMP
MAKING SURE YOU DONT GET DRIPPED ON. NOW JUMP UP ONTO THE PLATFORM AND
THE OFF THE TOP OF THE SCREEN. YOU NOW GOTO WHERE DOZY IS AND THEN
DROP THE DUSTER AND PICK UP THE DUSTER THREE TIMES AND THEN DROP LAMP
AND DUSTER.

 -TO RESCUE GRANDPA:- GOTO TO THEN STONE WHERE EXCALIBUR IS AND READ
STONE AND THE PICK UP SWORD (THIS IS NOW EASILY DONE BECAUSE OF THE
SOMETHING STICKY). NOW GOTO TO ROOM IN PALACE JUST BELOW MIRROR MIRROR
SCREEN AND WHEN YOU ARE STANDING AT THE TOP LEFT OF THIS ROOM JUMP
LEFT AND YOU WILL FIND YOU SELF THROUGH THE MIRROR IN A ROOM CALLED
THE CHESSBOARD WALK THROUGH THIS ROOM. YOU WILL TAKW THE QUEEN SINCE
YOU ARE NOW A KING (BECAUSE OF SWORD). NOW TO RESCUE GRANDPA FROM THE
ROOM CALLED CURIOUSIER AND CURIOSIER, JUST TALK TO HIM.

 -ON FREEING EVERYONE ZAK WILL TELL YOU THAT YOU WILL NEVER LEAVE THE
ISLAND.

 -TO KILL ZAC AND FREE THE DEVIL:-GOTO THE VOLCANO AND CROSS VOLCANO
VIA MOVING CLOUDS DODGING FIREBALLS (REMEMBER GEMS HEAL ENERGY) AND
THEN GO DOWN INTO CAVE PAST THE RIGHT OF THE VOLCANO AND TALK TO THE
DEVIL. GET THE TRIDENT AND GO AND KILL ZAK DODGING HIS LIGHTNING BOLT
AND THEN GET HIS RING AND GO BACK TO THE DEVIL AND TALK TO HIM. THEN
BRING THE RING TO THE SCREEN TO THE LEFT ON DEVIL AND THROW THE RING
THROUGH THE HOLE ON THE LEFT SIDE OF THIS ROOM.

 -TO GO HOME :- NOW YOUR TASK HAS FINISH YOU ONLY GO AND TALK TO THE
DEVIL AND HE WILL TELL YOU THAT YOU NEED 30 GEMS FOR THE SPELL TO
TRAVEL HOME WHEN YOU HAVE THE GEMS RETURN TO THE DEVIL AND WAIT FOR
THE CONGRATZ.

 TYPED BY DAZ SON OF MORSECODE FOR LSD ON 8/12/91
