@echo off
MegaZeux -lffedv_a.mzx
cls
echo **************************************************
echo * Thank you for playing Final Fantasy EdVenture! *
echo * Copyright 1997 Duky Incorporated               * 
echo * By Luke Drelick                                *
echo * Duky@worldnet.att.net                          *
echo * http://www.chocobo.org/~butz                   *
echo **************************************************
