//////////////////////////////////////////////////////////////////////
// XLogical - A puzzle game
//
// Copyright (C) 2000 Neil Brown, Tom Warkentin
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
// or at the website: http://www.gnu.org
//
////////////////////////////////////////////////////////////////////////

#include "defs.h"

char *imageFiles[] = {
#ifndef __MORPHOS__
	DATA_DIR PATHSEP "images" PATHSEP "arrow_d.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "arrow_l.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "arrow_r.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "arrow_u.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "background_complete.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "background_game.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "background_gameover.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "background_hiscore.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "background_start.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "background_time.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "background_won.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "ball_c1.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "ball_c2.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "ball_c3.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "ball_c4.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "ballmove3_0.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "ballmove3_1.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "ballmove3_2.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "ballmove3_3.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "ballmove4_0.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "ballmove4_1.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "ballmove4_2.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "ballmove4_3.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "ballmove4_4.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "ballmove5_0.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "ballmove5_1.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "ballmove5_2.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "ballmove5_3.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "ballmove5_4.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "ballmove5_5.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "block_base.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "cover_center.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "cover_d.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "cover_l.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "cover_r.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "cover_u.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "finish_1.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "finish_2.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "finish_3.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "finish_4.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "font_1.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "font_2.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "font_3.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "font_4.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "gem_c1.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "gem_c2.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "gem_c3.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "gem_c4.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "next_base.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "numbers.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "order_disp.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "paint_base.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "pattern_disp.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "scrollblock.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "sel_back_1.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "sel_back_2.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "sel_back_3.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "sel_back_4.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "slider.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "slider_thumb.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "spin_0.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "spin_1.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "spin_2.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "spincover_0.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "spincover_1.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "spincover_2.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "spincoverred_0.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "spincoverred_1.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "spincoverred_2.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "spindark.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "spinred_0.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "spinred_1.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "spinred_2.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "spinring.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "spinring_d.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "spinring_l.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "spinring_r.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "spinring_u.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "spintopoff.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "spintopon.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "start_c.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "start_d.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "start_l.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "start_r.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "starttimer_00.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "starttimer_01.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "starttimer_02.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "starttimer_03.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "starttimer_04.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "starttimer_05.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "starttimer_06.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "starttimer_07.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "starttimer_08.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "starttimer_09.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "starttimer_10.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "starttimer_11.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "starttimer_12.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "starttimer_13.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "starttimer_14.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "starttimer_15.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "starttimer_16.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "starttimer_17.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "starttimer_18.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "starttimer_19.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "starttimer_20.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "start_u.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "teleport_base.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "teleport_lr.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "teleport_ud.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "timer.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "title_text_1.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "title_text_2.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "title_text_3.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "title_text_4.jpg",
	DATA_DIR PATHSEP "images" PATHSEP "track_d.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "track_dl.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "track_dlr.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "track_dr.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "track_l.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "track_lr.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "track_r.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "track_u.bmp" ,
	DATA_DIR PATHSEP "images" PATHSEP "track_ud.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "track_udl.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "track_udlr.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "track_udr.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "track_ul.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "track_ulr.bmp",
	DATA_DIR PATHSEP "images" PATHSEP "track_ur.bmp"
#else
	"Progdir:images/arrow_d.bmp",
	"Progdir:images/arrow_l.bmp",
	"Progdir:images/arrow_r.bmp",
	"Progdir:images/arrow_u.bmp",
	"Progdir:images/background_complete.bmp",
	"Progdir:images/background_game.bmp",
	"Progdir:images/background_gameover.bmp",
	"Progdir:images/background_hiscore.bmp",
	"Progdir:images/background_start.bmp",
	"Progdir:images/background_time.bmp",
	"Progdir:images/background_won.bmp",
	"Progdir:images/ball_c1.bmp",
	"Progdir:images/ball_c2.bmp",
	"Progdir:images/ball_c3.bmp",
	"Progdir:images/ball_c4.bmp",
	"Progdir:images/ballmove3_0.bmp",
	"Progdir:images/ballmove3_1.bmp",
	"Progdir:images/ballmove3_2.bmp",
	"Progdir:images/ballmove3_3.bmp",
	"Progdir:images/ballmove4_0.bmp",
	"Progdir:images/ballmove4_1.bmp",
	"Progdir:images/ballmove4_2.bmp",
	"Progdir:images/ballmove4_3.bmp",
	"Progdir:images/ballmove4_4.bmp",
	"Progdir:images/ballmove5_0.bmp",
	"Progdir:images/ballmove5_1.bmp",
	"Progdir:images/ballmove5_2.bmp",
	"Progdir:images/ballmove5_3.bmp",
	"Progdir:images/ballmove5_4.bmp",
	"Progdir:images/ballmove5_5.bmp",
	"Progdir:images/block_base.bmp",
	"Progdir:images/cover_center.bmp",
	"Progdir:images/cover_d.bmp",
	"Progdir:images/cover_l.bmp",
	"Progdir:images/cover_r.bmp",
	"Progdir:images/cover_u.bmp",
	"Progdir:images/finish_1.bmp",
	"Progdir:images/finish_2.bmp",
	"Progdir:images/finish_3.bmp",
	"Progdir:images/finish_4.bmp",
	"Progdir:images/font_1.bmp",
	"Progdir:images/font_2.bmp",
	"Progdir:images/font_3.bmp",
	"Progdir:images/font_4.bmp",
	"Progdir:images/gem_c1.bmp",
	"Progdir:images/gem_c2.bmp",
	"Progdir:images/gem_c3.bmp",
	"Progdir:images/gem_c4.bmp",
	"Progdir:images/next_base.bmp",
	"Progdir:images/numbers.bmp",
	"Progdir:images/order_disp.bmp",
	"Progdir:images/paint_base.bmp",
	"Progdir:images/pattern_disp.bmp",
	"Progdir:images/scrollblock.bmp",
	"Progdir:images/sel_back_1.bmp",
	"Progdir:images/sel_back_2.bmp",
	"Progdir:images/sel_back_3.bmp",
	"Progdir:images/sel_back_4.bmp",
	"Progdir:images/slider.bmp",
	"Progdir:images/slider_thumb.bmp",
	"Progdir:images/spin_0.bmp",
	"Progdir:images/spin_1.bmp",
	"Progdir:images/spin_2.bmp",
	"Progdir:images/spincover_0.bmp",
	"Progdir:images/spincover_1.bmp",
	"Progdir:images/spincover_2.bmp",
	"Progdir:images/spincoverred_0.bmp",
	"Progdir:images/spincoverred_1.bmp",
	"Progdir:images/spincoverred_2.bmp",
	"Progdir:images/spindark.bmp",
	"Progdir:images/spinred_0.bmp",
	"Progdir:images/spinred_1.bmp",
	"Progdir:images/spinred_2.bmp",
	"Progdir:images/spinring.bmp",
	"Progdir:images/spinring_d.bmp",
	"Progdir:images/spinring_l.bmp",
	"Progdir:images/spinring_r.bmp",
	"Progdir:images/spinring_u.bmp",
	"Progdir:images/spintopoff.bmp",
	"Progdir:images/spintopon.bmp",
	"Progdir:images/start_c.bmp",
	"Progdir:images/start_d.bmp",
	"Progdir:images/start_l.bmp",
	"Progdir:images/start_r.bmp",
	"Progdir:images/starttimer_00.bmp",
	"Progdir:images/starttimer_01.bmp",
	"Progdir:images/starttimer_02.bmp",
	"Progdir:images/starttimer_03.bmp",
	"Progdir:images/starttimer_04.bmp",
	"Progdir:images/starttimer_05.bmp",
	"Progdir:images/starttimer_06.bmp",
	"Progdir:images/starttimer_07.bmp",
	"Progdir:images/starttimer_08.bmp",
	"Progdir:images/starttimer_09.bmp",
	"Progdir:images/starttimer_10.bmp",
	"Progdir:images/starttimer_11.bmp",
	"Progdir:images/starttimer_12.bmp",
	"Progdir:images/starttimer_13.bmp",
	"Progdir:images/starttimer_14.bmp",
	"Progdir:images/starttimer_15.bmp",
	"Progdir:images/starttimer_16.bmp",
	"Progdir:images/starttimer_17.bmp",
	"Progdir:images/starttimer_18.bmp",
	"Progdir:images/starttimer_19.bmp",
	"Progdir:images/starttimer_20.bmp",
	"Progdir:images/start_u.bmp",
	"Progdir:images/teleport_base.bmp",
	"Progdir:images/teleport_lr.bmp",
	"Progdir:images/teleport_ud.bmp",
	"Progdir:images/timer.bmp",
	"Progdir:images/title_text_1.bmp",
	"Progdir:images/title_text_2.bmp",
	"Progdir:images/title_text_3.bmp",
	"Progdir:images/title_text_4.jpg",
	"Progdir:images/track_d.bmp",
	"Progdir:images/track_dl.bmp",
	"Progdir:images/track_dlr.bmp",
	"Progdir:images/track_dr.bmp",
	"Progdir:images/track_l.bmp",
	"Progdir:images/track_lr.bmp",
	"Progdir:images/track_r.bmp",
	"Progdir:images/track_u.bmp" ,
	"Progdir:images/track_ud.bmp",
	"Progdir:images/track_udl.bmp",
	"Progdir:images/track_udlr.bmp",
	"Progdir:images/track_udr.bmp",
	"Progdir:images/track_ul.bmp",
	"Progdir:images/track_ulr.bmp",
	"Progdir:images/track_ur.bmp"
#endif
};
