# Generated automatically from Makefile.in by configure.
# Makefile.in generated automatically by automake 1.5 from Makefile.am.

# Copyright 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001
# Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.



SHELL = /bin/sh

srcdir = .
top_srcdir = ..
prefix = /usr/local
exec_prefix = ${prefix}

bindir = ${exec_prefix}/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = ${prefix}/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/info
mandir = ${prefix}/man
includedir = ${prefix}/include
oldincludedir = /usr/include
pkgdatadir = $(datadir)/mangopeeler
pkglibdir = $(libdir)/mangopeeler
pkgincludedir = $(includedir)/mangopeeler
top_builddir = ..

ACLOCAL = ${SHELL} /Varasto/Lähdekoodit/SDL/mangoquest-0.6.4/mangopeeler/missing --run aclocal
AUTOCONF = ${SHELL} /Varasto/Lähdekoodit/SDL/mangoquest-0.6.4/mangopeeler/missing --run autoconf
AUTOMAKE = ${SHELL} /Varasto/Lähdekoodit/SDL/mangoquest-0.6.4/mangopeeler/missing --run automake
AUTOHEADER = ${SHELL} /Varasto/Lähdekoodit/SDL/mangoquest-0.6.4/mangopeeler/missing --run autoheader

INSTALL = /bin/install -c
INSTALL_PROGRAM = ${INSTALL}
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_SCRIPT = ${INSTALL_PROGRAM}
INSTALL_HEADER = $(INSTALL_DATA)
transform = s,x,x,
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
AMTAR = ${SHELL} /Varasto/Lähdekoodit/SDL/mangoquest-0.6.4/mangopeeler/missing --run tar
AWK = awk
CC = gcc -noixemul
CFLAGS =  -noixemul -I/usr/include/SDL -Wall -fomit-frame-pointer -ffast-math -fexpensive-optimizations -noixemul -I/usr/include/SDL -Wall -fomit-frame-pointer -ffast-math -fexpensive-optimizations
DEPDIR = .deps
EXEEXT = 
INSTALL_STRIP_PROGRAM = ${SHELL} $(install_sh) -c -s
OBJEXT = o
SDL_CFLAGS = -noixemul -I/usr/include/SDL
SDL_CONFIG = /usr/bin/sdl-config
SDL_LIBS = -L/usr/lib -noixemul -ljpeg -lpng -ltiff -lSDL -lfreetype -lz -lm
am__include = include
am__quote = 
install_sh = /Varasto/Lähdekoodit/SDL/mangoquest-0.6.4/mangopeeler/install-sh

CXX = g++
LIBS = -lz  -L/usr/lib -noixemul -ljpeg -lpng -ltiff -lSDL -lfreetype -lz -lm -lSDL_image -lSDL_ttf 

PACKAGE = mangopeeler
VERSION = 0.6.4

DATA_PREFIX = $(pkgdatadir)/../mangoquest/
ED_DATA_PREFIX = $(pkgdatadir)/
DEFS = -DVERSION=\"0.6.4\"

CXXFLAGS =  -Wall -fomit-frame-pointer -ffast-math -fexpensive-optimizations -Wall -fomit-frame-pointer -ffast-math -fexpensive-optimizations -Wall \
 -DSHXMAN_DATA=\"$(DATA_PREFIX)\" \
 -DSHXEDIT_DATA=\"$(ED_DATA_PREFIX)\"


bin_PROGRAMS = mangopeeler
mangopeeler_SOURCES = main.cpp share.cpp editeur.cpp carte.cpp \
	clique.cpp polices.cpp ch_tout.cpp SDLStretch.cpp \
	volet.cpp volet_bonus.cpp volet_textures.cpp volet_special.cpp \
	sge_draw.cpp labyr.cpp geom.cpp portals.cpp secteur.cpp bonus.cpp \
	file_utils.cpp config_file.cpp


mangopeeler_CFLAGS = CXXFLAGS
mangopeeler_LIBS = LIBS
subdir = src
mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
CONFIG_HEADER = $(top_builddir)/config.h
CONFIG_CLEAN_FILES =
bin_PROGRAMS = mangopeeler$(EXEEXT)
PROGRAMS = $(bin_PROGRAMS)

am_mangopeeler_OBJECTS = main.$(OBJEXT) share.$(OBJEXT) \
	editeur.$(OBJEXT) carte.$(OBJEXT) clique.$(OBJEXT) \
	polices.$(OBJEXT) ch_tout.$(OBJEXT) SDLStretch.$(OBJEXT) \
	volet.$(OBJEXT) volet_bonus.$(OBJEXT) volet_textures.$(OBJEXT) \
	volet_special.$(OBJEXT) sge_draw.$(OBJEXT) labyr.$(OBJEXT) \
	geom.$(OBJEXT) portals.$(OBJEXT) secteur.$(OBJEXT) \
	bonus.$(OBJEXT) file_utils.$(OBJEXT) config_file.$(OBJEXT)
mangopeeler_OBJECTS = $(am_mangopeeler_OBJECTS)
mangopeeler_LDADD = $(LDADD)
mangopeeler_DEPENDENCIES =
mangopeeler_LDFLAGS =
DEFAULT_INCLUDES =  -I. -I$(srcdir) -I$(top_builddir)
CPPFLAGS =  
LDFLAGS = 
depcomp = $(SHELL) $(top_srcdir)/depcomp
DEP_FILES = $(DEPDIR)/SDLStretch.Po $(DEPDIR)/bonus.Po \
	$(DEPDIR)/carte.Po $(DEPDIR)/ch_tout.Po \
	$(DEPDIR)/clique.Po $(DEPDIR)/config_file.Po \
	$(DEPDIR)/editeur.Po $(DEPDIR)/file_utils.Po \
	$(DEPDIR)/geom.Po $(DEPDIR)/labyr.Po \
	$(DEPDIR)/main.Po $(DEPDIR)/polices.Po \
	$(DEPDIR)/portals.Po $(DEPDIR)/secteur.Po \
	$(DEPDIR)/sge_draw.Po $(DEPDIR)/share.Po \
	$(DEPDIR)/volet.Po $(DEPDIR)/volet_bonus.Po \
	$(DEPDIR)/volet_special.Po \
	$(DEPDIR)/volet_textures.Po
CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
CXXLD = $(CXX)
CXXLINK = $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_LDFLAGS) $(LDFLAGS) \
	-o $@
DIST_SOURCES = $(mangopeeler_SOURCES)
DIST_COMMON = Makefile.am Makefile.in
SOURCES = $(mangopeeler_SOURCES)

all: all-am

.SUFFIXES:
.SUFFIXES: .cpp .o .obj
$(srcdir)/Makefile.in:  Makefile.am  $(top_srcdir)/configure.in $(ACLOCAL_M4)
	cd $(top_srcdir) && \
	  $(AUTOMAKE) --foreign  src/Makefile
Makefile:  $(srcdir)/Makefile.in  $(top_builddir)/config.status
	cd $(top_builddir) && \
	  CONFIG_HEADERS= CONFIG_LINKS= \
	  CONFIG_FILES=$(subdir)/$@ $(SHELL) ./config.status
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(bindir)
	@list='$(bin_PROGRAMS)'; for p in $$list; do \
	  p1=`echo $$p|sed 's/$(EXEEXT)$$//'`; \
	  if test -f $$p \
	  ; then \
	    f=`echo $$p1|sed '$(transform);s/$$/$(EXEEXT)/'`; \
	   echo " $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$p $(DESTDIR)$(bindir)/$$f"; \
	   $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$p $(DESTDIR)$(bindir)/$$f; \
	  else :; fi; \
	done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; for p in $$list; do \
	  f=`echo $$p|sed 's/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/'`; \
	  echo " rm -f $(DESTDIR)$(bindir)/$$f"; \
	  rm -f $(DESTDIR)$(bindir)/$$f; \
	done

clean-binPROGRAMS:
	-test -z "$(bin_PROGRAMS)" || rm -f $(bin_PROGRAMS)
mangopeeler$(EXEEXT): $(mangopeeler_OBJECTS) $(mangopeeler_DEPENDENCIES) 
	@rm -f mangopeeler$(EXEEXT)
	$(CXXLINK) $(mangopeeler_LDFLAGS) $(mangopeeler_OBJECTS) $(mangopeeler_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT) core *.core

distclean-compile:
	-rm -f *.tab.c

#include $(DEPDIR)/SDLStretch.Po
#include $(DEPDIR)/bonus.Po
#include $(DEPDIR)/carte.Po
#include $(DEPDIR)/ch_tout.Po
#include $(DEPDIR)/clique.Po
#include $(DEPDIR)/config_file.Po
#include $(DEPDIR)/editeur.Po
#include $(DEPDIR)/file_utils.Po
#include $(DEPDIR)/geom.Po
#include $(DEPDIR)/labyr.Po
#include $(DEPDIR)/main.Po
#include $(DEPDIR)/polices.Po
#include $(DEPDIR)/portals.Po
#include $(DEPDIR)/secteur.Po
#include $(DEPDIR)/sge_draw.Po
#include $(DEPDIR)/share.Po
#include $(DEPDIR)/volet.Po
#include $(DEPDIR)/volet_bonus.Po
#include $(DEPDIR)/volet_special.Po
#include $(DEPDIR)/volet_textures.Po

distclean-depend:
	-rm -rf $(DEPDIR)

.cpp.o:
	source='$<' object='$@' libtool=no \
	depfile='$(DEPDIR)/$*.Po' tmpdepfile='$(DEPDIR)/$*.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXXCOMPILE) -c -o $@ `test -f $< || echo '$(srcdir)/'`$<

.cpp.obj:
	source='$<' object='$@' libtool=no \
	depfile='$(DEPDIR)/$*.Po' tmpdepfile='$(DEPDIR)/$*.TPo' \
	$(CXXDEPMODE) $(depcomp) \
	$(CXXCOMPILE) -c -o $@ `cygpath -w $<`
CXXDEPMODE = depmode=gcc
uninstall-info-am:

tags: TAGS

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	mkid -fID $$unique $(LISP)

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	test -z "$(ETAGS_ARGS)$$unique$(LISP)$$tags" \
	  || etags $(ETAGS_ARGS) $$tags  $$unique $(LISP)

GTAGS:
	here=`CDPATH=: && cd $(top_builddir) && pwd` \
	  && cd $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) $$here

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH

DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)

top_distdir = ..
distdir = $(top_distdir)/$(PACKAGE)-$(VERSION)

distdir: $(DISTFILES)
	@for file in $(DISTFILES); do \
	  if test -f $$file; then d=.; else d=$(srcdir); fi; \
	  dir=`echo "$$file" | sed -e 's,/[^/]*$$,,'`; \
	  if test "$$dir" != "$$file" && test "$$dir" != "."; then \
	    $(mkinstalldirs) "$(distdir)/$$dir"; \
	  fi; \
	  if test -d $$d/$$file; then \
	    cp -pR $$d/$$file $(distdir) \
	    || exit 1; \
	  else \
	    test -f $(distdir)/$$file \
	    || cp -p $$d/$$file $(distdir)/$$file \
	    || exit 1; \
	  fi; \
	done
check-am: all-am
check: check-am
all-am: Makefile $(PROGRAMS)

installdirs:
	$(mkinstalldirs) $(DESTDIR)$(bindir)

install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	  `test -z '$(STRIP)' || \
	    echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:

clean-generic:

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES) stamp-h stamp-h[0-9]*

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-binPROGRAMS clean-generic mostlyclean-am

distclean: distclean-am

distclean-am: clean-am distclean-compile distclean-depend \
	distclean-generic distclean-tags

dvi: dvi-am

dvi-am:

info: info-am

info-am:

install-data-am:

install-exec-am: install-binPROGRAMS

install-info: install-info-am

install-man:

installcheck-am:

maintainer-clean: maintainer-clean-am

maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic

uninstall-am: uninstall-binPROGRAMS uninstall-info-am

.PHONY: GTAGS all all-am check check-am clean clean-binPROGRAMS \
	clean-generic distclean distclean-compile distclean-depend \
	distclean-generic distclean-tags distdir dvi dvi-am info \
	info-am install install-am install-binPROGRAMS install-data \
	install-data-am install-exec install-exec-am install-info \
	install-info-am install-man install-strip installcheck \
	installcheck-am installdirs maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic tags uninstall uninstall-am \
	uninstall-binPROGRAMS uninstall-info-am

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
