; DNA Install-script 0.5

    (message "This script will install DNA on your HD\n>-----------------------------<\nDNA_Installer V0.5   (11-Dec-1997)\n\nMade by\nLennart Johannesson\n95lenjo@ostrabo.uddevallla.se\n\n")

    (complete 0)


;MAKES THE "DNA" DIRECTORY

    (set dest_dir
      (tackon (askdir
                (prompt "Where do you want to install DNA?\n"
                        "A drawer called DNA will be created.")
                (help @askdir-help)
                (default "ram:")
                (disk)
              )
              "DNA"
      )
    )

    (set @default-dest dest_dir)
    (makedir dest_dir)



; COPIES THE DNA FILES & DNA.GUIDE & ICONS TO THE DESTINATION DIRETORY

    (copyfiles
      (source "Start_DNA")
      (dest (dest_dir))
      (infos)
    )

    (copyfiles
      (source "DNA.guide")
      (dest (dest_dir))
      (infos)
    )


    (complete 25)

    (askdisk
      (prompt ("Please insert DNA disk 1"))
      (dest "Disk1")
      (help @askdisk-help)
    )


    (copyfiles
      (source "Disk1:DNA_INTRO")
      (dest (dest_dir))
      (infos)
    )


    (complete 50)

    (askdisk
      (prompt ("Please insert DNA disk 2"))
      (dest "Disk2")
      (help @askdisk-help)
    )

    (copyfiles
      (source "Disk2:DNA")
      (dest (dest_dir))
      (infos)
    )


    (complete 75)

    (askdisk
      (prompt ("Please insert DNA disk 3"))
      (dest "Disk3")
      (help @askdisk-help)
    )

    (copyfiles
      (source "Disk3:CONGRATS")
      (dest (dest_dir))
      (infos)
    )
 
    (complete 100)
    (message "\nEnjoy playing DNA from your HD!\n\nFor comments about the installer mail to:\nLennart Johannesson\n95lenjo@ostrabo.uddevalla.se\n\nAlso try Aminet:game/think/NeverMind.lha")
    (exit)
