49
English Grammar and Usage questions
5
Which is the correct pronoun in the following sentence:
It is _____ whom you should ask for advice.
65
 her
 she
0
2
5
Which is the correct pronoun in the following sentence:
Just between you and ______, Ellen dislikes Grace.
65
 I
 me
0
2
5
Which is the correct pronoun in the following sentence:
Let's you and _____ go to the show tonight.
65
 I
 me
0
2
5
Which is the correct pronoun in the following sentence:
If you were ______, what would you do?
65
 he
 him
0
1
5
Which is the correct pronoun in the following sentence:
Whatever may happen, ______ friends must stay together.
65
 we
 us
0
1
5
Which of the following words is a conjunction?
Snow and cold weather arrived today after a pleasant, mild fall.
255
 Snow
 and
 arrived
 after
 ,
 today
 mild
 fall
4
2
5
Which of the following words is a conjunction?
I would like to go, but I must study for tomorrow's test.
255
 I
 would
 to go
 but
 must
 for
 study
 tomorrow's
4
4
5
Which of the following words is a conjunction?
Don't leave until you put the dishes into the cabinet.
255
 Don't
 leave
 until
 you
 put
 the
 into
 cabinet
4
3
5
Which of the following words is a conjunction?
The dog always barks when Ted enters the yard behind the house.
255
 The
 dog
 always barks
 when
 enters
 the
 yard
 behind
4
4
27
Identify the word or phrase that maintains parallel construction in each
sentence:
The new president was neither efficient in organization _____ decisive in
thought.
65
 or
 nor
0
2
11
Identify the word or phrase that maintains parallel construction in each
sentence:
What he says and ____ he does are not consistent.
65
 all that
 what
0
2
27
Identify the word or phrase that maintains parallel construction in each
sentence:
Jane is a police officer ______ a lively personality and who exerts a subtle
force of leadership.
65
 with
 who has
0
2
27
Identify the word or phrase that maintains parallel construction in each
sentence:
The job of this section is to examine receipts, to investigate discrepancies,
and ____ the obvious errors to accounting.
65
 referring
 to refer
0
2
11
Identify the word or phrase that maintains parallel construction in each
sentence:
Bill is intelligent, aggressive and ______
65
 will get the job done.
 capable.
0
2
5
Identify the correct verb form in the following sentence:
Yesterday I ____ in the shade all afternoon
65
 lay
 laid
0
1
5
Identify the correct verb form in the following sentence:
Let the baby _____ on my bed until he awakens.
65
 lie
 lay
0
1
5
Identify the correct verb form in the following sentence:
Your scarf is ____ under the table.
65
 laying
 lying
0
2
5
Identify the correct verb form in the following sentence:
You should not have _____ in the sun so long.
65
 laid
 lain
0
2
5
Identify the correct verb form in the following sentence:
Don't _____ anything on the wet window sill.
65
 lay
 lie
0
1
5
Identify the indirect object of the verb in the following sentence:
Give Matthew another cup of coffee.
63
 Give
 Matthew
 another
 cup
 of
 coffee.
4
2
5
Identify the indirect object of the verb in the following sentence:
Jones & Company sent me a refund.
255
 Jones
 &
 Company
 sent
 me
 a
 refund.
 NONE OF THE ABOVE
4
5
5
Identify the indirect object of the verb in the following sentence:
Our parents bought Joan a new car.
255
 Our
 Parents
 bought
 Joan
 a
 new
 car.
 NONE OF THE ABOVE
4
4
5
Identify the indirect object of the verb in the following sentence:
Clark's doctor gave him a new prescription.
255
 Clark's
 doctor
 gave
 him
 a
 new
 prescription.
 NONE OF THE ABOVE
4
4
5
Identify the indirect object of the verb in the following sentence:
They offered her an impressive starting salary.
255
 They
 offered
 her
 an
 impressive
 starting
 salary.
 NONE OF THE ABOVE
4
3
5
Identify the correctly punctuated item for the following sentence:
You will find the reference on _______
65
 p 37.
 p. 37.
0
2
5
Identify the correctly punctuated item for the following sentence:
Please deliver this report by 8:00 ______ tomorrow.
65
 A.M.
 AM
0
1
5
Identify the correctly punctuated item for the following sentence:
____ you only say that because you're rich.
65
 O
 O!
0
1
13
Identify the correctly punctuated item for the following sentence:
You will find the pertinent information in the sentence beginning,
"There are several ______
65
 factors."
 factors...."
0
2
5
Identify the correctly punctuated item for the following sentence:
_____ The plane is falling.
65
 Oh!
 Oh
0
1
5
Identify the subject of the infinitive in the following sentence:
Didn't you hear me call you to dinner?
255
 Didn't
 you
 hear
 me
 call
 you
 to
 dinner?
4
4
5
Identify the subject of the infinitive in the following sentence:
Mother won't let me go to the dance.
255
 Mother
 won't
 let
 me
 go
 to
 the
 dance.
4
4
5
Identify the subject of the infinitive in the following sentence:
Don't expect us to leave early.
127
 Don't
 expect
 us
 to
 leave
 early.
 NONE OF THE ABOVE
4
3
5
Identify the subject of the infinitive in the following sentence:
His parents want him to return to college.
255
 His
 parents
 want
 him
 to
 return
 to
 college.
4
4
5
Identify the subject of the infinitive in the following sentence:
Grace and Mark asked me to sing at their wedding.
255
 Grace/Mark
 and
 asked
 me
 to
 sing
 at
 their
4
4
5
Identify the correct pronoun in the following sentence:
_____ do you think can do the best job?
65
 Who
 Whom
0
1
5
Identify the correct pronoun in the following sentence:
Both my brother and ____ have been ill recently.
65
 myself
 I
0
2
5
Identify the correct pronoun in the following sentence:
Mr. Williams redecorated the living room _______
65
 hisself.
 himself.
0
2
5
Identify the correct pronoun in the following sentence:
I want to invite _____ and your friend to the picnic.
65
 you
 yourself
0
1
5
Identify the correct pronoun in the following sentence:
He hurt _____ when he fell on the ice.
65
 him
 himself
0
2
5
Identify the correct pronoun in the following sentence:
They ______ admitted that they had not told the truth.
65
 theirselves
 themselves
0
2
5
Identify the correct pronoun in the following sentence:
I finally bought ____ the dress I had been admiring.
65
 me
 myself
0
2
5
Identify the correct pronoun in the following sentence:
Fred is the contenstant _____ I thought would win.
65
 who
 whom
0
1
5
Identify the correct pronoun in the following sentence:
_____ is that at the door?
65
 Who
 Whom
0
1
5
Identify the correct pronoun in the following sentence:
_____ did you see at the convention?
65
 Who
 Whom
0
2
5
Identify the correct pronoun in the following sentence:
_____ will you designate to represent you at the negotiations?
65
 Who
 Whom
0
2
5
Identify the simple subject of the following sentence:
My new secretary types rapidly and accurately.
255
 My
 new
 secretary
 types
 rapidly
 and
 accurately.
 NONE OF THE ABOVE
4
3
5
Identify the simple subject of the following sentence:
Under the desk lay the missing papers.
255
 Under
 the
 desk
 lay
 the
 missing
 papers.
 NONE OF THE ABOVE
4
7
5
Identify the simple subject of the following sentence:
Slowly the bewildered man turned away.
127
 Slowly
 the
 bewildered
 man
 turned
 away.
 NONE OF THE ABOVE
4
4
5
Identify the simple subject of the following sentence:
The most salient point, the entire group missed.
255
 The
 most
 salient
 point
 entire
 group
 missed.
 NONE OF THE ABOVE
4
6
5
Identify the simple subject of the following sentence:
"An excellent report!" exclaimed the chairman of the board.
255
 An
 excellent
 report
 exclaimed
 the
 chairman
 board
 NONE OF THE ABOVE
4
6
0
