39
English pronounciation questions
13
Identify the syllable that is stressed in correct pronounciation:
It was a fu-tile gesture
         -------
65
 fu
 tile
0
1
13
Identify the syllable that is stressed in correct pronounciation:
Evening fog left the hills silver and a-mor-phous.
                                      -----------
273
 a
 mor
 phous
1
2
13
Identify the syllable that is stressed in correct pronounciation:
No one believed the pro-phe-cy until it was too late.
                    ----------
273
 pro
 phe
 cy
1
1
13
Identify the syllable that is stressed in correct pronounciation:
There are very few am-bi-dex-trous tennis players.
                   ---------------
585
 am
 bi
 dex
 trous
2
3
13
Identify the syllable that is stressed in correct pronounciation:
Tom's objection was quite im-ma-ter-i-al.
                          --------------
341
 im
 ma
 ter
 i
 al
3
3
13
Identify the syllable that is stressed in correct pronounciation:
The rocket curved upward into the strat-o-sphere.
                                  --------------
273
 strat
 o
 sphere
1
1
27
Identify the correct pronounciation for the last syllable of the underlined
words:
The board gave her carte blanche in reorganizing the sales department.
                   -------------
65
 blahnsh
 blantch
0
1
27
Identify the correct pronounciation for the last syllable of the underlined
words:
The faux pas was greeted with a strong silence.
    --------
65
 pas
 pah
0
2
27
Identify the correct pronounciation for the last syllable of the underlined
words:
A piquant aroma wafted up from the bowl.
  -------
65
 kuhnt
 kwant
0
1
27
Identify the correct pronounciation for the last syllable of the underlined
words:
What do you suppose that silly clique is up to?
                               ------
65
 kleek
 klihk
0
1
27
Identify the correct pronounciation for the last syllable of the underlined
words:
She treated her boudoir like sacred ground.
                -------
65
 wahr
 oher
0
1
5
Identify the correct pronounciation of the following sentences:
The first syllable of flagrant is pronounced _____
65
 flag
 flay
0
2
5
Identify the correct pronounciation of the following sentences:
The first syllable of hilarious is pronounced _____
65
 high
 hill
0
2
5
Identify the correct pronounciation of the following sentences:
The first syllable of simultaneous rhymes with _____
65
 him
 high
0
2
7
Identify the correct pronounciation of the following sentences:
                              ,
The third syllable of applique  rhymes with ____
65
 say
 see
0
1
5
Identify the correct pronounciation of the following sentences:
The first syllable of entourage rhymes with ____
65
 den
 don
0
2
27
Enter the number of syllables of the underlined word when it is pronounced
correctly:
Tom is a mischievous boy
         -----------
341
 two
 three
 four
 five
 six
3
2
27
Enter the number of syllables of the underlined word when it is pronounced
correctly:
She was a superb piano accompanist.
                       -----------
341
 two
 three
 four
 five
 six
3
3
27
Enter the number of syllables of the underlined word when it is pronounced
correctly:
He represents the epitome of style.
                  -------
341
 two
 three
 four
 five
 six
3
3
27
Enter the number of syllables of the underlined word when it is pronounced
correctly:
The discussion about the controversial issue continued for a long time.
                         -------------
341
 two
 three
 four
 five
 six
3
3
27
Enter the number of syllables of the underlined word when it is pronounced
correctly:
The actor gave an extraordinary performance.
                  -------------
341
 two
 three
 four
 five
 six
3
4
15
Identify the syllable that is stressed in the underlined word:
                              ,
Her speech was one long cliche.
                        ------
65
 cli
 che
0
2
13
Identify the syllable that is stressed in the underlined word:
The adage was appropriate in this context.
    -----
65
 ad
 age
0
1
13
Identify the syllable that is stressed in the underlined word:
The gondola rocked softly in the water.
    -------
273
 gon
 do
 la
1
1
13
Identify the syllable that is stressed in the underlined word:
Stunted plant growth may be indicative of a soil pest.
                            ----------
585
 in
 dic
 a
 tive
2
2
13
Identify the syllable that is stressed in the underlined word:
The rain brought a brief respite from the heat.
                         -------
65
 res
 pite
0
1
13
Identify the syllable that is stressed in the underlined word:
The freighter disappeared over the horizon.
                                   -------
273
 ho
 ri
 zon
1
2
13
Identify the syllable that is stressed in the underlined word:
He refused to become a work ad-dict.
                            -------
65
 ad
 dict
0
1
13
Identify the syllable that is stressed in the underlined word:
We tried to con-duct ourselves with dignity.
            --------
65
 con
 duct
0
2
13
Identify the syllable that is stressed in the underlined word:
The pro-test failed from lack of attendance.
    --------
65
 pro
 test
0
1
13
Identify the syllable that is stressed in the underlined word:
I will never sub-ject myself to that embarrassment.
             --------
65
 sub
 ject
0
2
13
Identify the syllable that is stressed in the underlined word:
The rubber in-sert for this pressure cooker is missing.
           -------
65
 in
 sert
0
1
13
Identify the accented syllable in the underlined word:
It took considerable time to ab-stract the information from the book.
                             ---------
65
 ab
 stract
0
2
13
Identify the accented syllable in the underlined word:
A treaty is sometimes called a com-pact.
                               --------
65
 com
 pact
0
1
13
Identify the accented syllable in the underlined word:
The gold con-tent of the ore is negligible.
         --------
65
 con
 tent
0
1
13
Identify the accented syllable in the underlined word:
We must also consider the con-verse proposition.
                          ---------
65
 con
 verse
0
1
13
Identify the accented syllable in the underlined word:
The contract was found to be in-val-id
                             ---------
273
 in
 val
 id
1
2
13
Identify the accented syllable in the underlined word:
The critic described the pianist as a con-sum-mate musician.
                                      ------------
585
 con
 sum
 con or sum
 mate
2
3
13
Identify the accented syllable in the underlined word:
Don't look for mi-nute flaws in the glass.
               -------
65
 mi
 nute
0
2
13
Identify the accented syllable in the underlined word:
I shall never be able to per-fect my French.
                         --------
65
 per
 fect
0
2
0
