49
English vocabulary questions
5
Select the word that properly completes the following sentence:
A prohibition of commerce or shipping is a(n) __________.
255
 armada
 atoll
 bazaar
 embargo
 hacienda
 intaglio
 sarong
 slalom
4
4
5
Select the word that properly completes the following sentence:
A large Spanish home or estate is a(n) ________.
255
 armada
 atoll
 bazaar
 embargo
 hacienda
 intaglio
 sarong
 slalom
4
5
5
Select the word that properly completes the following sentence:
A design cut into stone or pressed into glass in a(n) _______.
255
 armada
 atoll
 bazaar
 embargo
 hacienda
 intaglio
 sarong
 slalom
4
6
5
Select the word that properly completes the following sentence:
Coral islands forming a reef around a lagoon are a(n) ________.
255
 armada
 atoll
 bazaar
 embargo
 hacienda
 intaglio
 sarong
 slalom
4
2
5
Select the word that properly completes the following sentence:
A skiing descent with sharp zigzag turns is a(n) ______.
255
 armada
 atoll
 bazaar
 embargo
 hacienda
 intaglio
 sarong
 slalom
4
8
5
Identify the correct word in the following sentence:
To save her embarrassment, Bill employed a ________.
65
 euphony
 euphemism
0
2
5
Identify the correct word in the following sentence:
It was not ________ to divide the estate equally between the children.
65
 equable
 equitable
0
2
5
Identify the correct word in the following sentence:
________ acts of disloyalty are committed openly.
65
 Covert
 Overt
0
2
5
Identify the correct word in the following sentence:
You will have to consult a _______ to find more books on that subject.
65
 biography
 bibliography
0
2
5
Identify the correct word in the following sentence:
His _______ remark was quite an embarrassment for everyone present.
65
 ingenuous
 ingenious
0
1
5
Select the word that correctly completes the following sentence:
Karen's ____ prevented her from crossing the wide, open field.
255
 acrophobia
 agoraphobia
 aphorism
 euphony
 neophyte
 philanthropist
 sycophant
 typography
4
2
5
Select the word that correctly completes the following sentence:
The _____ tried to gain the king's favor with servile flattery.
255
 acrophobia
 agoraphobia
 aphorism
 euphony
 neophyte
 philanthropist
 sycophant
 typography
4
7
13
Select the word that correctly completes the following sentence:
The ____ of Frost's poetry is especially noticeable when his work is read
aloud.
255
 acrophobia
 agoraphobia
 aphorism
 euphony
 neophyte
 philanthropist
 sycophant
 typography
4
4
5
Select the word that correctly completes the following sentence:
The ____ of the region made construction of the new highway very difficult.
255
 acrophobia
 agoraphobia
 aphorism
 euphony
 neophyte
 philanthropist
 sycophant
 typography
4
8
5
Select the word that correctly completes the following sentence:
The _____ donated much of her fortune to charities and needy organizations.
255
 acrophobia
 agoraphobia
 aphorism
 euphony
 neophyte
 philanthropist
 sycophant
 typography
4
6
1
The noun "progeny" means an extraordinary person, instance, deed or thing.
65
 True
 False
0
2
1
A "supercilious" person is one who is extremely affected and silly.
65
 True
 False
0
2
1
Canada is "contiguous" to the United States of America.
65
 True
 False
0
1
1
"Cupidity" means having ardent love for one of the opposite sex.
65
 True
 False
0
2
1
A "chronic" ailment or condition is one that continues for a long time.
65
 True
 False
0
1
5
Identify the word that correctly completes the sentence:
Juan is a real _____; He's always interested in other people.
65
 Introvert
 Extrovert
0
2
5
Identify the word that correctly completes the sentence:
The outer surface of a sphere is _______.
65
 concave
 convex
0
2
13
Identify the word that correctly completes the sentence:
The astute shopper was not deceived by the ______ reasoning of the glib
salesperson.
65
 tortuous
 torturous
0
1
13
Identify the word that correctly completes the sentence:
I am certain that your idea can be carried out, but I doubt whether it is
very _______.
65
 practicable
 practical
0
2
5
Identify the word that correctly completes the sentence:
The young violinist gave a _____ performance with the symphony orchestra.
65
 credible
 creditable
0
2
5
Identify the word that correctly completes the following sentence:
She handed me a(n) _____ that briefly explained the program.
255
 apropos
 avant-garde
 brochure
 coiffure
 debacle
 finesse
 impasse
 impromptu
4
3
5
Identify the word that correctly completes the following sentence:
With no time to rehearse, they presented a(n) ____ show.
255
 apropos
 avant-garde
 brochure
 coiffure
 debacle
 finesse
 impasse
 impromptu
4
8
5
Identify the word that correctly completes the following sentence:
The accomplished skier performed the maneuver with ______.
255
 apropos
 avant-garde
 brochure
 coiffure
 debacle
 finesse
 impasse
 impromptu
4
6
5
Identify the word that correctly completes the following sentence:
Margeret came from the hairdresser's with a stunning new ______.
255
 apropos
 avant-garde
 brochure
 coiffure
 debacle
 finesse
 impasse
 impromptu
4
4
5
Enter TRUE of FALSE for the following statement:
"Temerity" means audacity.
65
 True
 False
0
1
5
Enter TRUE of FALSE for the following statement:
"Enervating" means stimulating.
65
 True
 False
0
2
5
Enter TRUE of FALSE for the following statement:
"Prone" means lying face downward.
65
 True
 False
0
1
5
Enter TRUE of FALSE for the following statement:
"Infer" means to express indirectly.
65
 True
 False
0
2
5
Identify the correct word for the following sentence:
Since you ____ my advice, you must suffer the consequences.
65
 flaunted
 flouted
0
2
13
Identify the correct word for the following sentence:
The McMasters entertain in an _____ fashion; their parties are always very
successful.
65
 inimical
 inimitable
0
2
5
Identify the correct word for the following sentence:
The fashion model was photographed wearing ____ furs.
65
 luxurious
 luxuriant
0
1
5
Identify the correct word for the following sentence:
The physician advised the patient to move to a more ______ climate.
65
 healthful
 healthy
0
1
5
Identify the correct word for the following sentence:
The senator refused to ______ when wronged by his opponents.
65
 retaliate
 reciprocate
0
1
5
Identify the redundant word that should be deleted in this sentence:
We are assembled together to consider decisive action.
191
 We are
 assembled
 together
 to consider
 decisive
 action
 None of the above
4
3
5
Identify the redundant word that should be deleted in this sentence:
The consensus of opinion is that the recent developments need further study.
255
 The consensus
 of opinion
 is that
 the recent
 developments
 need
 further study
 None of the above
4
2
5
Identify the redundant word that should be deleted in this sentence:
I suggest that we postpone the projected trip until later
255
 I suggest
 that we
 postpone
 the
 projected
 trip
 until later
 None of the above
4
7
5
Identify the redundant word that should be deleted in this sentence:
Please refer back to the minutes of our previous meeting.
255
 Please
 refer
 back
 to the
 minutes
 of our
 previous
 meeting.
4
3
5
Identify the word that correctly completes the meaning of this sentence:
Your ____ decision renders future efforts useless.
65
 averse
 adverse
0
2
5
Identify the word that correctly completes the meaning of this sentence:
The _____ arrival of the important guest upset the routine of the household.
65
 eminent
 imminent
0
2
5
Identify the word that correctly completes the meaning of this sentence:
I have ____ confidence in Jack's good judgement.
65
 explicit
 implicit
0
2
5
Identify the word that correctly completes the meaning of this sentence:
Your explanation seems plausible _____ for the discrepancy in dates.
65
 except
 accept
0
1
5
Identify the word that correctly completes the meaning of this sentence:
He _____ unconcern, but I knew he was elated about the change in plans.
65
 effected
 affected
0
2
5
Identify the word that correctly completes the meaning of this sentence:
The deteriorating walls of the state _____ required extensive repairs.
65
 capitol
 capital
0
1
5
Identify the word that correctly completes the meaning of this sentence:
Eleanor was flattered by the ____ for her tasty meal.
65
 complement
 compliment
0
2
5
Identify the word that correctly completes the meaning of this sentence:
The police were unable to ____ any information from the reluctant witness.
65
 illicit
 elicit
0
2
0
