Level-Paßcodes:
Gruft des Todes: ªÚ ±§ ×Ø çÙ çÙ ªÚ      Insignien   : çÙ ±§ ×Ø çÙ çÙ ªÚ
Kanalisation   : ±§ ×Ø ªÚ ªÚ ×Ø çÙ      Öko-Bereich : çÙ ×Ø çÙ ªÚ ±§ ×Ø
Wasserquelle   : ×Ø çÙ ªÚ ±§ çÙ çÙ      Zentrale    : ±§ ±§ çÙ çÙ ×Ø ªÚ
Gefängnis      : çÙ ×Ø ±§ ªÚ ªÚ ±§      Labyrinth   : ªÚ ×Ø ªÚ çÙ ±§ ªÚ
Gruft          : ×Ø ±§ ±§ ×Ø ªÚ ±§      Unterschlupf: çÙ ªÚ ×Ø çÙ ±§ çÙ
Projekt Eden   : ±§ ªÚ çÙ ×Ø ×Ø ×Ø      Level-Skip* : ±§ çÙ ±§ ªÚ çÙ ªÚ ªÚ ªÚ

                                        * im Pause-Modus einzugeben.

Level 9: Die Kombination für die Lichtschranke lautet øù¡¢øùøù.
Die sieben Teleporter-Codes lauten:
1 ¡¢øùøù   2 øù¡¢¡¢   3 ¡¢¡¢øù   4 ¡¢øù¡¢   5 øù¡¢¡¢   6 øù¡¢¡¢   7 ¡¢¡¢øù
                                                                





