/* Generated by packpng from animation.pack. DO NOT EDIT */
{
  SDL_Surface * all = sdlutil::imgload("animation.png");
  if (!all) return false;
  SDL_SetAlpha(all, 0, 255);
  SDL_Rect r;

  r.x = 0;
  r.y = 0;
  r.w = 1;
  r.h = 1;
  nothing = sdlutil::makesurface(r.w, r.h);
  if (!nothing) return false;
  SDL_BlitSurface(all, &r, nothing, 0);

  r.x = 1;
  r.y = 0;
  r.w = 34;
  r.h = 30;
  bsphere_slide_lr = sdlutil::makesurface(r.w, r.h);
  if (!bsphere_slide_lr) return false;
  SDL_BlitSurface(all, &r, bsphere_slide_lr, 0);

  r.x = 35;
  r.y = 0;
  r.w = 36;
  r.h = 28;
  bsphere_slide_lr2 = sdlutil::makesurface(r.w, r.h);
  if (!bsphere_slide_lr2) return false;
  SDL_BlitSurface(all, &r, bsphere_slide_lr2, 0);

  r.x = 71;
  r.y = 0;
  r.w = 30;
  r.h = 34;
  bsphere_slide_ud = sdlutil::makesurface(r.w, r.h);
  if (!bsphere_slide_ud) return false;
  SDL_BlitSurface(all, &r, bsphere_slide_ud, 0);

  r.x = 101;
  r.y = 0;
  r.w = 28;
  r.h = 36;
  bsphere_slide_ud2 = sdlutil::makesurface(r.w, r.h);
  if (!bsphere_slide_ud2) return false;
  SDL_BlitSurface(all, &r, bsphere_slide_ud2, 0);

  r.x = 129;
  r.y = 0;
  r.w = 34;
  r.h = 30;
  gsphere_slide_lr = sdlutil::makesurface(r.w, r.h);
  if (!gsphere_slide_lr) return false;
  SDL_BlitSurface(all, &r, gsphere_slide_lr, 0);

  r.x = 163;
  r.y = 0;
  r.w = 36;
  r.h = 28;
  gsphere_slide_lr2 = sdlutil::makesurface(r.w, r.h);
  if (!gsphere_slide_lr2) return false;
  SDL_BlitSurface(all, &r, gsphere_slide_lr2, 0);

  r.x = 199;
  r.y = 0;
  r.w = 30;
  r.h = 34;
  gsphere_slide_ud = sdlutil::makesurface(r.w, r.h);
  if (!gsphere_slide_ud) return false;
  SDL_BlitSurface(all, &r, gsphere_slide_ud, 0);

  r.x = 229;
  r.y = 0;
  r.w = 28;
  r.h = 36;
  gsphere_slide_ud2 = sdlutil::makesurface(r.w, r.h);
  if (!gsphere_slide_ud2) return false;
  SDL_BlitSurface(all, &r, gsphere_slide_ud2, 0);

  r.x = 257;
  r.y = 0;
  r.w = 34;
  r.h = 30;
  rsphere_slide_lr = sdlutil::makesurface(r.w, r.h);
  if (!rsphere_slide_lr) return false;
  SDL_BlitSurface(all, &r, rsphere_slide_lr, 0);

  r.x = 291;
  r.y = 0;
  r.w = 36;
  r.h = 28;
  rsphere_slide_lr2 = sdlutil::makesurface(r.w, r.h);
  if (!rsphere_slide_lr2) return false;
  SDL_BlitSurface(all, &r, rsphere_slide_lr2, 0);

  r.x = 327;
  r.y = 0;
  r.w = 30;
  r.h = 34;
  rsphere_slide_ud = sdlutil::makesurface(r.w, r.h);
  if (!rsphere_slide_ud) return false;
  SDL_BlitSurface(all, &r, rsphere_slide_ud, 0);

  r.x = 357;
  r.y = 0;
  r.w = 28;
  r.h = 36;
  rsphere_slide_ud2 = sdlutil::makesurface(r.w, r.h);
  if (!rsphere_slide_ud2) return false;
  SDL_BlitSurface(all, &r, rsphere_slide_ud2, 0);

  r.x = 385;
  r.y = 0;
  r.w = 34;
  r.h = 30;
  sphere_slide_lr = sdlutil::makesurface(r.w, r.h);
  if (!sphere_slide_lr) return false;
  SDL_BlitSurface(all, &r, sphere_slide_lr, 0);

  r.x = 419;
  r.y = 0;
  r.w = 36;
  r.h = 28;
  sphere_slide_lr2 = sdlutil::makesurface(r.w, r.h);
  if (!sphere_slide_lr2) return false;
  SDL_BlitSurface(all, &r, sphere_slide_lr2, 0);

  r.x = 455;
  r.y = 0;
  r.w = 30;
  r.h = 34;
  sphere_slide_ud = sdlutil::makesurface(r.w, r.h);
  if (!sphere_slide_ud) return false;
  SDL_BlitSurface(all, &r, sphere_slide_ud, 0);

  r.x = 485;
  r.y = 0;
  r.w = 28;
  r.h = 36;
  sphere_slide_ud2 = sdlutil::makesurface(r.w, r.h);
  if (!sphere_slide_ud2) return false;
  SDL_BlitSurface(all, &r, sphere_slide_ud2, 0);

  r.x = 513;
  r.y = 0;
  r.w = 40;
  r.h = 25;
  yellow_slide_lr = sdlutil::makesurface(r.w, r.h);
  if (!yellow_slide_lr) return false;
  SDL_BlitSurface(all, &r, yellow_slide_lr, 0);

  r.x = 553;
  r.y = 0;
  r.w = 25;
  r.h = 36;
  yellow_slide_ud = sdlutil::makesurface(r.w, r.h);
  if (!yellow_slide_ud) return false;
  SDL_BlitSurface(all, &r, yellow_slide_ud, 0);

  r.x = 578;
  r.y = 0;
  r.w = 26;
  r.h = 36;
  yellow_stretch_ud = sdlutil::makesurface(r.w, r.h);
  if (!yellow_stretch_ud) return false;
  SDL_BlitSurface(all, &r, yellow_stretch_ud, 0);

  r.x = 604;
  r.y = 0;
  r.w = 38;
  r.h = 26;
  yellow_stretch_lr = sdlutil::makesurface(r.w, r.h);
  if (!yellow_stretch_lr) return false;
  SDL_BlitSurface(all, &r, yellow_stretch_lr, 0);

  r.x = 642;
  r.y = 0;
  r.w = 50;
  r.h = 46;
  zap0 = sdlutil::makesurface(r.w, r.h);
  if (!zap0) return false;
  SDL_BlitSurface(all, &r, zap0, 0);

  r.x = 692;
  r.y = 0;
  r.w = 50;
  r.h = 46;
  zap1 = sdlutil::makesurface(r.w, r.h);
  if (!zap1) return false;
  SDL_BlitSurface(all, &r, zap1, 0);

  r.x = 742;
  r.y = 0;
  r.w = 50;
  r.h = 46;
  zap2 = sdlutil::makesurface(r.w, r.h);
  if (!zap2) return false;
  SDL_BlitSurface(all, &r, zap2, 0);

  r.x = 792;
  r.y = 0;
  r.w = 50;
  r.h = 46;
  zap3 = sdlutil::makesurface(r.w, r.h);
  if (!zap3) return false;
  SDL_BlitSurface(all, &r, zap3, 0);

  r.x = 842;
  r.y = 0;
  r.w = 50;
  r.h = 46;
  zap4 = sdlutil::makesurface(r.w, r.h);
  if (!zap4) return false;
  SDL_BlitSurface(all, &r, zap4, 0);

  r.x = 892;
  r.y = 0;
  r.w = 40;
  r.h = 41;
  break0 = sdlutil::makesurface(r.w, r.h);
  if (!break0) return false;
  SDL_BlitSurface(all, &r, break0, 0);

  r.x = 932;
  r.y = 0;
  r.w = 40;
  r.h = 41;
  break1 = sdlutil::makesurface(r.w, r.h);
  if (!break1) return false;
  SDL_BlitSurface(all, &r, break1, 0);

  r.x = 972;
  r.y = 0;
  r.w = 40;
  r.h = 41;
  break2 = sdlutil::makesurface(r.w, r.h);
  if (!break2) return false;
  SDL_BlitSurface(all, &r, break2, 0);

  r.x = 1012;
  r.y = 0;
  r.w = 64;
  r.h = 64;
  smokepuff0 = sdlutil::makesurface(r.w, r.h);
  if (!smokepuff0) return false;
  SDL_BlitSurface(all, &r, smokepuff0, 0);

  r.x = 1076;
  r.y = 0;
  r.w = 64;
  r.h = 64;
  smokepuff1 = sdlutil::makesurface(r.w, r.h);
  if (!smokepuff1) return false;
  SDL_BlitSurface(all, &r, smokepuff1, 0);

  r.x = 1140;
  r.y = 0;
  r.w = 64;
  r.h = 64;
  smokepuff2 = sdlutil::makesurface(r.w, r.h);
  if (!smokepuff2) return false;
  SDL_BlitSurface(all, &r, smokepuff2, 0);

  r.x = 1204;
  r.y = 0;
  r.w = 64;
  r.h = 64;
  smokepuff3 = sdlutil::makesurface(r.w, r.h);
  if (!smokepuff3) return false;
  SDL_BlitSurface(all, &r, smokepuff3, 0);

  r.x = 1268;
  r.y = 0;
  r.w = 32;
  r.h = 32;
  greyshrink0 = sdlutil::makesurface(r.w, r.h);
  if (!greyshrink0) return false;
  SDL_BlitSurface(all, &r, greyshrink0, 0);

  r.x = 1300;
  r.y = 0;
  r.w = 32;
  r.h = 32;
  greyshrink1 = sdlutil::makesurface(r.w, r.h);
  if (!greyshrink1) return false;
  SDL_BlitSurface(all, &r, greyshrink1, 0);

  r.x = 1332;
  r.y = 0;
  r.w = 32;
  r.h = 32;
  greyshrink2 = sdlutil::makesurface(r.w, r.h);
  if (!greyshrink2) return false;
  SDL_BlitSurface(all, &r, greyshrink2, 0);

  r.x = 1364;
  r.y = 0;
  r.w = 32;
  r.h = 32;
  greyshrink3 = sdlutil::makesurface(r.w, r.h);
  if (!greyshrink3) return false;
  SDL_BlitSurface(all, &r, greyshrink3, 0);

  r.x = 1396;
  r.y = 0;
  r.w = 32;
  r.h = 32;
  shrinking_hole0 = sdlutil::makesurface(r.w, r.h);
  if (!shrinking_hole0) return false;
  SDL_BlitSurface(all, &r, shrinking_hole0, 0);

  r.x = 1428;
  r.y = 0;
  r.w = 32;
  r.h = 32;
  shrinking_hole1 = sdlutil::makesurface(r.w, r.h);
  if (!shrinking_hole1) return false;
  SDL_BlitSurface(all, &r, shrinking_hole1, 0);

  r.x = 1460;
  r.y = 0;
  r.w = 32;
  r.h = 32;
  shrinking_hole2 = sdlutil::makesurface(r.w, r.h);
  if (!shrinking_hole2) return false;
  SDL_BlitSurface(all, &r, shrinking_hole2, 0);

  r.x = 1492;
  r.y = 0;
  r.w = 32;
  r.h = 32;
  shrinking_hole3 = sdlutil::makesurface(r.w, r.h);
  if (!shrinking_hole3) return false;
  SDL_BlitSurface(all, &r, shrinking_hole3, 0);

  r.x = 1524;
  r.y = 0;
  r.w = 32;
  r.h = 32;
  shrinking_hole4 = sdlutil::makesurface(r.w, r.h);
  if (!shrinking_hole4) return false;
  SDL_BlitSurface(all, &r, shrinking_hole4, 0);

  r.x = 1556;
  r.y = 0;
  r.w = 32;
  r.h = 32;
  slider_rotating = sdlutil::makesurface(r.w, r.h);
  if (!slider_rotating) return false;
  SDL_BlitSurface(all, &r, slider_rotating, 0);

  r.x = 1588;
  r.y = 0;
  r.w = 32;
  r.h = 32;
  elecoff0 = sdlutil::makesurface(r.w, r.h);
  if (!elecoff0) return false;
  SDL_BlitSurface(all, &r, elecoff0, 0);

  r.x = 1620;
  r.y = 0;
  r.w = 32;
  r.h = 32;
  elecoff1 = sdlutil::makesurface(r.w, r.h);
  if (!elecoff1) return false;
  SDL_BlitSurface(all, &r, elecoff1, 0);

  r.x = 1652;
  r.y = 0;
  r.w = 32;
  r.h = 32;
  elecoff2 = sdlutil::makesurface(r.w, r.h);
  if (!elecoff2) return false;
  SDL_BlitSurface(all, &r, elecoff2, 0);

  r.x = 1684;
  r.y = 0;
  r.w = 32;
  r.h = 32;
  elecoff3 = sdlutil::makesurface(r.w, r.h);
  if (!elecoff3) return false;
  SDL_BlitSurface(all, &r, elecoff3, 0);

  r.x = 1716;
  r.y = 0;
  r.w = 32;
  r.h = 32;
  elecoff4 = sdlutil::makesurface(r.w, r.h);
  if (!elecoff4) return false;
  SDL_BlitSurface(all, &r, elecoff4, 0);

  r.x = 1748;
  r.y = 0;
  r.w = 32;
  r.h = 32;
  ongoesoff0 = sdlutil::makesurface(r.w, r.h);
  if (!ongoesoff0) return false;
  SDL_BlitSurface(all, &r, ongoesoff0, 0);

  r.x = 1780;
  r.y = 0;
  r.w = 32;
  r.h = 32;
  ongoesoff1 = sdlutil::makesurface(r.w, r.h);
  if (!ongoesoff1) return false;
  SDL_BlitSurface(all, &r, ongoesoff1, 0);

  r.x = 1812;
  r.y = 0;
  r.w = 32;
  r.h = 32;
  onezero_fade0 = sdlutil::makesurface(r.w, r.h);
  if (!onezero_fade0) return false;
  SDL_BlitSurface(all, &r, onezero_fade0, 0);

  r.x = 1844;
  r.y = 0;
  r.w = 32;
  r.h = 32;
  onezero_fade1 = sdlutil::makesurface(r.w, r.h);
  if (!onezero_fade1) return false;
  SDL_BlitSurface(all, &r, onezero_fade1, 0);

  r.x = 1876;
  r.y = 0;
  r.w = 32;
  r.h = 32;
  trap1_falls0 = sdlutil::makesurface(r.w, r.h);
  if (!trap1_falls0) return false;
  SDL_BlitSurface(all, &r, trap1_falls0, 0);

  r.x = 1908;
  r.y = 0;
  r.w = 32;
  r.h = 32;
  trap1_falls1 = sdlutil::makesurface(r.w, r.h);
  if (!trap1_falls1) return false;
  SDL_BlitSurface(all, &r, trap1_falls1, 0);

  r.x = 1940;
  r.y = 0;
  r.w = 32;
  r.h = 32;
  trap1_falls2 = sdlutil::makesurface(r.w, r.h);
  if (!trap1_falls2) return false;
  SDL_BlitSurface(all, &r, trap1_falls2, 0);

  r.x = 1972;
  r.y = 0;
  r.w = 32;
  r.h = 32;
  trap1_falls3 = sdlutil::makesurface(r.w, r.h);
  if (!trap1_falls3) return false;
  SDL_BlitSurface(all, &r, trap1_falls3, 0);

  r.x = 2004;
  r.y = 0;
  r.w = 35;
  r.h = 32;
  green_pushright0 = sdlutil::makesurface(r.w, r.h);
  if (!green_pushright0) return false;
  SDL_BlitSurface(all, &r, green_pushright0, 0);

  r.x = 2039;
  r.y = 0;
  r.w = 42;
  r.h = 32;
  green_pushright1 = sdlutil::makesurface(r.w, r.h);
  if (!green_pushright1) return false;
  SDL_BlitSurface(all, &r, green_pushright1, 0);

  r.x = 2081;
  r.y = 0;
  r.w = 56;
  r.h = 32;
  green_pushright2 = sdlutil::makesurface(r.w, r.h);
  if (!green_pushright2) return false;
  SDL_BlitSurface(all, &r, green_pushright2, 0);

  r.x = 2137;
  r.y = 0;
  r.w = 64;
  r.h = 32;
  green_pushright3 = sdlutil::makesurface(r.w, r.h);
  if (!green_pushright3) return false;
  SDL_BlitSurface(all, &r, green_pushright3, 0);

  r.x = 2201;
  r.y = 0;
  r.w = 64;
  r.h = 32;
  green_pushright4 = sdlutil::makesurface(r.w, r.h);
  if (!green_pushright4) return false;
  SDL_BlitSurface(all, &r, green_pushright4, 0);

  r.x = 2265;
  r.y = 0;
  r.w = 64;
  r.h = 32;
  green_pushleft0 = sdlutil::makesurface(r.w, r.h);
  if (!green_pushleft0) return false;
  SDL_BlitSurface(all, &r, green_pushleft0, 0);

  r.x = 2329;
  r.y = 0;
  r.w = 64;
  r.h = 32;
  green_pushleft1 = sdlutil::makesurface(r.w, r.h);
  if (!green_pushleft1) return false;
  SDL_BlitSurface(all, &r, green_pushleft1, 0);

  r.x = 2393;
  r.y = 0;
  r.w = 56;
  r.h = 32;
  green_pushleft2 = sdlutil::makesurface(r.w, r.h);
  if (!green_pushleft2) return false;
  SDL_BlitSurface(all, &r, green_pushleft2, 0);

  r.x = 2449;
  r.y = 0;
  r.w = 42;
  r.h = 32;
  green_pushleft3 = sdlutil::makesurface(r.w, r.h);
  if (!green_pushleft3) return false;
  SDL_BlitSurface(all, &r, green_pushleft3, 0);

  r.x = 2491;
  r.y = 0;
  r.w = 35;
  r.h = 32;
  green_pushleft4 = sdlutil::makesurface(r.w, r.h);
  if (!green_pushleft4) return false;
  SDL_BlitSurface(all, &r, green_pushleft4, 0);

  r.x = 2526;
  r.y = 0;
  r.w = 32;
  r.h = 35;
  green_pushdown0 = sdlutil::makesurface(r.w, r.h);
  if (!green_pushdown0) return false;
  SDL_BlitSurface(all, &r, green_pushdown0, 0);

  r.x = 2558;
  r.y = 0;
  r.w = 32;
  r.h = 41;
  green_pushdown1 = sdlutil::makesurface(r.w, r.h);
  if (!green_pushdown1) return false;
  SDL_BlitSurface(all, &r, green_pushdown1, 0);

  r.x = 2590;
  r.y = 0;
  r.w = 32;
  r.h = 56;
  green_pushdown2 = sdlutil::makesurface(r.w, r.h);
  if (!green_pushdown2) return false;
  SDL_BlitSurface(all, &r, green_pushdown2, 0);

  r.x = 2622;
  r.y = 0;
  r.w = 32;
  r.h = 64;
  green_pushdown3 = sdlutil::makesurface(r.w, r.h);
  if (!green_pushdown3) return false;
  SDL_BlitSurface(all, &r, green_pushdown3, 0);

  r.x = 2654;
  r.y = 0;
  r.w = 32;
  r.h = 64;
  green_pushdown4 = sdlutil::makesurface(r.w, r.h);
  if (!green_pushdown4) return false;
  SDL_BlitSurface(all, &r, green_pushdown4, 0);

  r.x = 2686;
  r.y = 0;
  r.w = 32;
  r.h = 64;
  green_pushup0 = sdlutil::makesurface(r.w, r.h);
  if (!green_pushup0) return false;
  SDL_BlitSurface(all, &r, green_pushup0, 0);

  r.x = 2718;
  r.y = 0;
  r.w = 32;
  r.h = 64;
  green_pushup1 = sdlutil::makesurface(r.w, r.h);
  if (!green_pushup1) return false;
  SDL_BlitSurface(all, &r, green_pushup1, 0);

  r.x = 2750;
  r.y = 0;
  r.w = 32;
  r.h = 56;
  green_pushup2 = sdlutil::makesurface(r.w, r.h);
  if (!green_pushup2) return false;
  SDL_BlitSurface(all, &r, green_pushup2, 0);

  r.x = 2782;
  r.y = 0;
  r.w = 32;
  r.h = 41;
  green_pushup3 = sdlutil::makesurface(r.w, r.h);
  if (!green_pushup3) return false;
  SDL_BlitSurface(all, &r, green_pushup3, 0);

  r.x = 2814;
  r.y = 0;
  r.w = 32;
  r.h = 35;
  green_pushup4 = sdlutil::makesurface(r.w, r.h);
  if (!green_pushup4) return false;
  SDL_BlitSurface(all, &r, green_pushup4, 0);

  r.x = 2846;
  r.y = 0;
  r.w = 32;
  r.h = 32;
  juicedwire_ns = sdlutil::makesurface(r.w, r.h);
  if (!juicedwire_ns) return false;
  SDL_BlitSurface(all, &r, juicedwire_ns, 0);

  r.x = 2878;
  r.y = 0;
  r.w = 32;
  r.h = 32;
  juicedwire_ns1 = sdlutil::makesurface(r.w, r.h);
  if (!juicedwire_ns1) return false;
  SDL_BlitSurface(all, &r, juicedwire_ns1, 0);

  r.x = 2910;
  r.y = 0;
  r.w = 32;
  r.h = 32;
  juicedwire_ne = sdlutil::makesurface(r.w, r.h);
  if (!juicedwire_ne) return false;
  SDL_BlitSurface(all, &r, juicedwire_ne, 0);

  r.x = 2942;
  r.y = 0;
  r.w = 32;
  r.h = 32;
  juicedwire_ne1 = sdlutil::makesurface(r.w, r.h);
  if (!juicedwire_ne1) return false;
  SDL_BlitSurface(all, &r, juicedwire_ne1, 0);

  r.x = 2974;
  r.y = 0;
  r.w = 32;
  r.h = 32;
  juicedwire_nw = sdlutil::makesurface(r.w, r.h);
  if (!juicedwire_nw) return false;
  SDL_BlitSurface(all, &r, juicedwire_nw, 0);

  r.x = 3006;
  r.y = 0;
  r.w = 32;
  r.h = 32;
  juicedwire_nw1 = sdlutil::makesurface(r.w, r.h);
  if (!juicedwire_nw1) return false;
  SDL_BlitSurface(all, &r, juicedwire_nw1, 0);

  r.x = 3038;
  r.y = 0;
  r.w = 32;
  r.h = 32;
  juicedwire_se = sdlutil::makesurface(r.w, r.h);
  if (!juicedwire_se) return false;
  SDL_BlitSurface(all, &r, juicedwire_se, 0);

  r.x = 3070;
  r.y = 0;
  r.w = 32;
  r.h = 32;
  juicedwire_se1 = sdlutil::makesurface(r.w, r.h);
  if (!juicedwire_se1) return false;
  SDL_BlitSurface(all, &r, juicedwire_se1, 0);

  r.x = 3102;
  r.y = 0;
  r.w = 32;
  r.h = 32;
  juicedwire_sw = sdlutil::makesurface(r.w, r.h);
  if (!juicedwire_sw) return false;
  SDL_BlitSurface(all, &r, juicedwire_sw, 0);

  r.x = 3134;
  r.y = 0;
  r.w = 32;
  r.h = 32;
  juicedwire_sw1 = sdlutil::makesurface(r.w, r.h);
  if (!juicedwire_sw1) return false;
  SDL_BlitSurface(all, &r, juicedwire_sw1, 0);

  r.x = 3166;
  r.y = 0;
  r.w = 32;
  r.h = 32;
  juicedwire_we = sdlutil::makesurface(r.w, r.h);
  if (!juicedwire_we) return false;
  SDL_BlitSurface(all, &r, juicedwire_we, 0);

  r.x = 3198;
  r.y = 0;
  r.w = 32;
  r.h = 32;
  juicedwire_we1 = sdlutil::makesurface(r.w, r.h);
  if (!juicedwire_we1) return false;
  SDL_BlitSurface(all, &r, juicedwire_we1, 0);

  r.x = 3230;
  r.y = 0;
  r.w = 48;
  r.h = 48;
  blue_lights0 = sdlutil::makesurface(r.w, r.h);
  if (!blue_lights0) return false;
  SDL_BlitSurface(all, &r, blue_lights0, 0);

  r.x = 3278;
  r.y = 0;
  r.w = 48;
  r.h = 48;
  blue_lights1 = sdlutil::makesurface(r.w, r.h);
  if (!blue_lights1) return false;
  SDL_BlitSurface(all, &r, blue_lights1, 0);

  r.x = 3326;
  r.y = 0;
  r.w = 48;
  r.h = 48;
  blue_lights2 = sdlutil::makesurface(r.w, r.h);
  if (!blue_lights2) return false;
  SDL_BlitSurface(all, &r, blue_lights2, 0);

  r.x = 3374;
  r.y = 0;
  r.w = 48;
  r.h = 48;
  blue_lights3 = sdlutil::makesurface(r.w, r.h);
  if (!blue_lights3) return false;
  SDL_BlitSurface(all, &r, blue_lights3, 0);

  r.x = 3422;
  r.y = 0;
  r.w = 48;
  r.h = 48;
  blue_lights4 = sdlutil::makesurface(r.w, r.h);
  if (!blue_lights4) return false;
  SDL_BlitSurface(all, &r, blue_lights4, 0);

  r.x = 3470;
  r.y = 0;
  r.w = 48;
  r.h = 48;
  blue_lights5 = sdlutil::makesurface(r.w, r.h);
  if (!blue_lights5) return false;
  SDL_BlitSurface(all, &r, blue_lights5, 0);

  r.x = 3518;
  r.y = 0;
  r.w = 48;
  r.h = 48;
  red_lights0 = sdlutil::makesurface(r.w, r.h);
  if (!red_lights0) return false;
  SDL_BlitSurface(all, &r, red_lights0, 0);

  r.x = 3566;
  r.y = 0;
  r.w = 48;
  r.h = 48;
  red_lights1 = sdlutil::makesurface(r.w, r.h);
  if (!red_lights1) return false;
  SDL_BlitSurface(all, &r, red_lights1, 0);

  r.x = 3614;
  r.y = 0;
  r.w = 48;
  r.h = 48;
  red_lights2 = sdlutil::makesurface(r.w, r.h);
  if (!red_lights2) return false;
  SDL_BlitSurface(all, &r, red_lights2, 0);

  r.x = 3662;
  r.y = 0;
  r.w = 48;
  r.h = 48;
  red_lights3 = sdlutil::makesurface(r.w, r.h);
  if (!red_lights3) return false;
  SDL_BlitSurface(all, &r, red_lights3, 0);

  r.x = 3710;
  r.y = 0;
  r.w = 48;
  r.h = 48;
  red_lights4 = sdlutil::makesurface(r.w, r.h);
  if (!red_lights4) return false;
  SDL_BlitSurface(all, &r, red_lights4, 0);

  r.x = 3758;
  r.y = 0;
  r.w = 48;
  r.h = 48;
  red_lights5 = sdlutil::makesurface(r.w, r.h);
  if (!red_lights5) return false;
  SDL_BlitSurface(all, &r, red_lights5, 0);

  r.x = 3806;
  r.y = 0;
  r.w = 48;
  r.h = 48;
  green_lights0 = sdlutil::makesurface(r.w, r.h);
  if (!green_lights0) return false;
  SDL_BlitSurface(all, &r, green_lights0, 0);

  r.x = 3854;
  r.y = 0;
  r.w = 48;
  r.h = 48;
  green_lights1 = sdlutil::makesurface(r.w, r.h);
  if (!green_lights1) return false;
  SDL_BlitSurface(all, &r, green_lights1, 0);

  r.x = 3902;
  r.y = 0;
  r.w = 48;
  r.h = 48;
  green_lights2 = sdlutil::makesurface(r.w, r.h);
  if (!green_lights2) return false;
  SDL_BlitSurface(all, &r, green_lights2, 0);

  r.x = 3950;
  r.y = 0;
  r.w = 48;
  r.h = 48;
  green_lights3 = sdlutil::makesurface(r.w, r.h);
  if (!green_lights3) return false;
  SDL_BlitSurface(all, &r, green_lights3, 0);

  r.x = 3998;
  r.y = 0;
  r.w = 48;
  r.h = 48;
  green_lights4 = sdlutil::makesurface(r.w, r.h);
  if (!green_lights4) return false;
  SDL_BlitSurface(all, &r, green_lights4, 0);

  r.x = 4046;
  r.y = 0;
  r.w = 48;
  r.h = 48;
  green_lights5 = sdlutil::makesurface(r.w, r.h);
  if (!green_lights5) return false;
  SDL_BlitSurface(all, &r, green_lights5, 0);

  r.x = 4094;
  r.y = 0;
  r.w = 32;
  r.h = 32;
  bluefloor0 = sdlutil::makesurface(r.w, r.h);
  if (!bluefloor0) return false;
  SDL_BlitSurface(all, &r, bluefloor0, 0);

  r.x = 4126;
  r.y = 0;
  r.w = 32;
  r.h = 32;
  bluefloor1 = sdlutil::makesurface(r.w, r.h);
  if (!bluefloor1) return false;
  SDL_BlitSurface(all, &r, bluefloor1, 0);

  r.x = 4158;
  r.y = 0;
  r.w = 32;
  r.h = 32;
  greenfloor0 = sdlutil::makesurface(r.w, r.h);
  if (!greenfloor0) return false;
  SDL_BlitSurface(all, &r, greenfloor0, 0);

  r.x = 4190;
  r.y = 0;
  r.w = 32;
  r.h = 32;
  greenfloor1 = sdlutil::makesurface(r.w, r.h);
  if (!greenfloor1) return false;
  SDL_BlitSurface(all, &r, greenfloor1, 0);

  r.x = 4222;
  r.y = 0;
  r.w = 32;
  r.h = 32;
  redfloor0 = sdlutil::makesurface(r.w, r.h);
  if (!redfloor0) return false;
  SDL_BlitSurface(all, &r, redfloor0, 0);

  r.x = 4254;
  r.y = 0;
  r.w = 32;
  r.h = 32;
  redfloor1 = sdlutil::makesurface(r.w, r.h);
  if (!redfloor1) return false;
  SDL_BlitSurface(all, &r, redfloor1, 0);

  r.x = 4286;
  r.y = 0;
  r.w = 32;
  r.h = 32;
  door_opens0 = sdlutil::makesurface(r.w, r.h);
  if (!door_opens0) return false;
  SDL_BlitSurface(all, &r, door_opens0, 0);

  r.x = 4318;
  r.y = 0;
  r.w = 32;
  r.h = 32;
  door_opens1 = sdlutil::makesurface(r.w, r.h);
  if (!door_opens1) return false;
  SDL_BlitSurface(all, &r, door_opens1, 0);

  r.x = 4350;
  r.y = 0;
  r.w = 32;
  r.h = 32;
  door_opens2 = sdlutil::makesurface(r.w, r.h);
  if (!door_opens2) return false;
  SDL_BlitSurface(all, &r, door_opens2, 0);

  r.x = 4382;
  r.y = 0;
  r.w = 32;
  r.h = 36;
  walk_forward_0 = sdlutil::makesurface(r.w, r.h);
  if (!walk_forward_0) return false;
  SDL_BlitSurface(all, &r, walk_forward_0, 0);

  r.x = 4414;
  r.y = 0;
  r.w = 32;
  r.h = 36;
  walk_forward_a = sdlutil::makesurface(r.w, r.h);
  if (!walk_forward_a) return false;
  SDL_BlitSurface(all, &r, walk_forward_a, 0);

  r.x = 4446;
  r.y = 0;
  r.w = 33;
  r.h = 36;
  walk_forward_a2 = sdlutil::makesurface(r.w, r.h);
  if (!walk_forward_a2) return false;
  SDL_BlitSurface(all, &r, walk_forward_a2, 0);

  r.x = 4479;
  r.y = 0;
  r.w = 32;
  r.h = 36;
  walk_forward_b = sdlutil::makesurface(r.w, r.h);
  if (!walk_forward_b) return false;
  SDL_BlitSurface(all, &r, walk_forward_b, 0);

  r.x = 4511;
  r.y = 0;
  r.w = 33;
  r.h = 36;
  walk_forward_b2 = sdlutil::makesurface(r.w, r.h);
  if (!walk_forward_b2) return false;
  SDL_BlitSurface(all, &r, walk_forward_b2, 0);

  r.x = 4544;
  r.y = 0;
  r.w = 26;
  r.h = 36;
  walk_right_0 = sdlutil::makesurface(r.w, r.h);
  if (!walk_right_0) return false;
  SDL_BlitSurface(all, &r, walk_right_0, 0);

  r.x = 4570;
  r.y = 0;
  r.w = 26;
  r.h = 36;
  walk_right_a = sdlutil::makesurface(r.w, r.h);
  if (!walk_right_a) return false;
  SDL_BlitSurface(all, &r, walk_right_a, 0);

  r.x = 4596;
  r.y = 0;
  r.w = 26;
  r.h = 36;
  walk_right_a2 = sdlutil::makesurface(r.w, r.h);
  if (!walk_right_a2) return false;
  SDL_BlitSurface(all, &r, walk_right_a2, 0);

  r.x = 4622;
  r.y = 0;
  r.w = 26;
  r.h = 36;
  walk_right_b = sdlutil::makesurface(r.w, r.h);
  if (!walk_right_b) return false;
  SDL_BlitSurface(all, &r, walk_right_b, 0);

  r.x = 4648;
  r.y = 0;
  r.w = 26;
  r.h = 36;
  walk_right_b2 = sdlutil::makesurface(r.w, r.h);
  if (!walk_right_b2) return false;
  SDL_BlitSurface(all, &r, walk_right_b2, 0);

  r.x = 4674;
  r.y = 0;
  r.w = 26;
  r.h = 36;
  walk_left_0 = sdlutil::makesurface(r.w, r.h);
  if (!walk_left_0) return false;
  SDL_BlitSurface(all, &r, walk_left_0, 0);

  r.x = 4700;
  r.y = 0;
  r.w = 26;
  r.h = 36;
  walk_left_a = sdlutil::makesurface(r.w, r.h);
  if (!walk_left_a) return false;
  SDL_BlitSurface(all, &r, walk_left_a, 0);

  r.x = 4726;
  r.y = 0;
  r.w = 26;
  r.h = 36;
  walk_left_a2 = sdlutil::makesurface(r.w, r.h);
  if (!walk_left_a2) return false;
  SDL_BlitSurface(all, &r, walk_left_a2, 0);

  r.x = 4752;
  r.y = 0;
  r.w = 26;
  r.h = 36;
  walk_left_b = sdlutil::makesurface(r.w, r.h);
  if (!walk_left_b) return false;
  SDL_BlitSurface(all, &r, walk_left_b, 0);

  r.x = 4778;
  r.y = 0;
  r.w = 26;
  r.h = 36;
  walk_left_b2 = sdlutil::makesurface(r.w, r.h);
  if (!walk_left_b2) return false;
  SDL_BlitSurface(all, &r, walk_left_b2, 0);

  r.x = 4804;
  r.y = 0;
  r.w = 26;
  r.h = 36;
  walk_backward_0 = sdlutil::makesurface(r.w, r.h);
  if (!walk_backward_0) return false;
  SDL_BlitSurface(all, &r, walk_backward_0, 0);

  r.x = 4830;
  r.y = 0;
  r.w = 26;
  r.h = 36;
  walk_backward_a = sdlutil::makesurface(r.w, r.h);
  if (!walk_backward_a) return false;
  SDL_BlitSurface(all, &r, walk_backward_a, 0);

  r.x = 4856;
  r.y = 0;
  r.w = 26;
  r.h = 36;
  walk_backward_a2 = sdlutil::makesurface(r.w, r.h);
  if (!walk_backward_a2) return false;
  SDL_BlitSurface(all, &r, walk_backward_a2, 0);

  r.x = 4882;
  r.y = 0;
  r.w = 26;
  r.h = 36;
  walk_backward_b = sdlutil::makesurface(r.w, r.h);
  if (!walk_backward_b) return false;
  SDL_BlitSurface(all, &r, walk_backward_b, 0);

  r.x = 4908;
  r.y = 0;
  r.w = 26;
  r.h = 36;
  walk_backward_b2 = sdlutil::makesurface(r.w, r.h);
  if (!walk_backward_b2) return false;
  SDL_BlitSurface(all, &r, walk_backward_b2, 0);

  r.x = 4934;
  r.y = 0;
  r.w = 32;
  r.h = 32;
  trap2_falls0 = sdlutil::makesurface(r.w, r.h);
  if (!trap2_falls0) return false;
  SDL_BlitSurface(all, &r, trap2_falls0, 0);

  r.x = 4966;
  r.y = 0;
  r.w = 32;
  r.h = 32;
  trap2_falls1 = sdlutil::makesurface(r.w, r.h);
  if (!trap2_falls1) return false;
  SDL_BlitSurface(all, &r, trap2_falls1, 0);

  r.x = 4998;
  r.y = 0;
  r.w = 33;
  r.h = 35;
  lasered0 = sdlutil::makesurface(r.w, r.h);
  if (!lasered0) return false;
  SDL_BlitSurface(all, &r, lasered0, 0);

  r.x = 5031;
  r.y = 0;
  r.w = 33;
  r.h = 35;
  lasered1 = sdlutil::makesurface(r.w, r.h);
  if (!lasered1) return false;
  SDL_BlitSurface(all, &r, lasered1, 0);

  r.x = 5064;
  r.y = 0;
  r.w = 33;
  r.h = 35;
  lasered2 = sdlutil::makesurface(r.w, r.h);
  if (!lasered2) return false;
  SDL_BlitSurface(all, &r, lasered2, 0);

  r.x = 5097;
  r.y = 0;
  r.w = 32;
  r.h = 37;
  hugbot_forward_0 = sdlutil::makesurface(r.w, r.h);
  if (!hugbot_forward_0) return false;
  SDL_BlitSurface(all, &r, hugbot_forward_0, 0);

  r.x = 5129;
  r.y = 0;
  r.w = 32;
  r.h = 37;
  hugbot_forward_1 = sdlutil::makesurface(r.w, r.h);
  if (!hugbot_forward_1) return false;
  SDL_BlitSurface(all, &r, hugbot_forward_1, 0);

  r.x = 5161;
  r.y = 0;
  r.w = 32;
  r.h = 37;
  dalek_forward_0 = sdlutil::makesurface(r.w, r.h);
  if (!dalek_forward_0) return false;
  SDL_BlitSurface(all, &r, dalek_forward_0, 0);

  r.x = 5193;
  r.y = 0;
  r.w = 32;
  r.h = 37;
  dalek_forward_1 = sdlutil::makesurface(r.w, r.h);
  if (!dalek_forward_1) return false;
  SDL_BlitSurface(all, &r, dalek_forward_1, 0);

  r.x = 5225;
  r.y = 0;
  r.w = 32;
  r.h = 32;
  deadrobot = sdlutil::makesurface(r.w, r.h);
  if (!deadrobot) return false;
  SDL_BlitSurface(all, &r, deadrobot, 0);


  SDL_FreeSurface(all);
}
