#include "escapex.h"
#include "level.h"
#include "sdlutil.h"

#include "util.h"
#include "font.h"
#include "extent.h"
#include "draw.h"
#include "pngsave.h"

#include <iostream>
#include <fstream>

/* XXX necessary? */
SDL_Surface * screen;
string self;

int main (int argc, char ** argv) {

  /* change to location of binary, so that we can find the
     images needed. */
  if (argc > 0) {
    string wd = util::pathof(argv[0]);
    util::changedir(wd);

#   if WIN32
    /* on win32, the ".exe" may or may not
       be present. Also, the file may have
       been invoked in any CaSe. */
    self = util::lcase(util::fileof(argv[0]));
    self = util::ensureext(self, ".exe");
#   else
    self = util::fileof(argv[0]);
#   endif

  }

  if (argc != 3) {
    printf("\n"
	   "Usage: packpng description.pack basename\n");
    printf("Creates a packed PNG graphic from each of the files in\n"
	   "description.pack. Produces:\n"
	   "   basename.png    (graphics)\n"
	   "   basename_defs.h (defines variables in class)\n"
	   "   basename_decs.h (declares the members as basename::pic)\n"
	   "   basename_load.h (code that loads the graphics)\n"
	   "\n"
	   "See packpng.cpp for details.\n\n");
    return 1;
  }

  /* we don't really need any SDL modules */
  if (SDL_Init (SDL_INIT_NOPARACHUTE) < 0) {
    printf("Unable to initialize SDL. (%s)\n", SDL_GetError());
    return 1;
  }


  string descname = argv[1];
  string basename = argv[2];

  printf("Packpng %s %s\n", descname.c_str(), basename.c_str());
 
  /* XXX we should make this part much smarter once
     we have a lot of animation frames or graphics of
     different sizes. The problem is probably NP hard
     in general but we can still do a better job with
     some greedy packing algorithm (keep a bit mask of
     'used' areas of the graphic) */

  /* make two passes, one to measure and one to load. */
  string name, file;
  int maxh = 1;
  int totalw = 0;

  {
    ifstream desc(descname.c_str());
    while (desc >> name >> file) {
      SDL_Surface * pic = IMG_Load(file.c_str());

      if (!pic) {
	printf ("Packpng error! Can't open image file '%s'\n",
		file.c_str());
	return 1;
      }

      if (pic->h > maxh) maxh = pic->h;
      totalw += pic->w;
    }
  }


  if (!totalw) totalw = 1;
  if (!maxh) maxh = 1;
  printf("Output will be %dx%d\n", totalw, maxh);

  SDL_Surface * packed = sdlutil::makesurface(totalw, maxh);
  
  sdlutil::clearsurface(packed,0xAA338833);

  if (!packed) {
    printf("Can't make surface\n");
    return -1;
  }

  /* now draw 'em */

  string defname  = basename + "_defs.h";
  string decname  = basename + "_decs.h";
  string loadname = basename + "_load.h";
  FILE * defs = fopen(defname.c_str(), "w");
  FILE * decs = fopen(decname.c_str(), "w");
  FILE * load = fopen(loadname.c_str(), "w");

  if (! (defs && decs && load)) {
    printf("Can't open output files.\n");
    return -1;
  }

  /* load needs some prelude */
  fprintf(load, 
	  "/* Generated by packpng from %s. DO NOT EDIT */\n"
	  "{\n"
	  "  SDL_Surface * all = sdlutil::imgload(\"%s.png\");\n"
	  "  if (!all) return false;\n"
	  "  SDL_SetAlpha(all, 0, 255);\n"
	  "  SDL_Rect r;\n",
	  descname.c_str(),
	  basename.c_str());

  fprintf(defs,
	  "/* Generated by packpng from %s. DO NOT EDIT */\n",
	  descname.c_str());

  fprintf(decs,
	  "/* Generated by packpng from %s. DO NOT EDIT */\n",
	  descname.c_str());

  int cx = 0;
  {
    ifstream desc(descname.c_str());
    while (desc >> name >> file) {
      SDL_Surface * pic = IMG_Load(file.c_str());
     
      if (!pic) {
	printf ("Packpng error! Can't open image file '%s'\n",
		file.c_str());
	exit(-1);
      }

      /* turn off source alpha. Otherwise, we'll
	 be blending against the background here */
      SDL_SetAlpha(pic, 0, 255);

      SDL_Rect rd;
      rd.x = cx;
      rd.y = 0;

      SDL_BlitSurface(pic, 0, packed, &rd);

      /* now print info to files */
      fprintf(defs, "static SDL_Surface * %s;\n", name.c_str());
      fprintf(decs, "SDL_Surface * %s::%s;\n",
	      basename.c_str(), name.c_str());
      
      fprintf(load,
	      "\n"
	      "  r.x = %d;\n"
	      "  r.y = 0;\n"
	      "  r.w = %d;\n"
	      "  r.h = %d;\n"
	      "  %s = sdlutil::makesurface(r.w, r.h);\n"
	      "  if (!%s) return false;\n"
	      "  SDL_BlitSurface(all, &r, %s, 0);\n",
	      cx, pic->w, pic->h, name.c_str(),
	      name.c_str(), name.c_str());

      cx += pic->w;
    }
  }

  /* postlude for load */
  fprintf(load, 
	  "\n\n"
	  "  SDL_FreeSurface(all);\n"
	  "}\n");

  fclose(load);
  fclose(defs);
  fclose(decs);

  printf("Saving...\n");
  fflush(stdout);

  if (!pngsave::save(basename + ".png", packed, true)) {
    printf("Couldn't write output PNG.\n");
    return -1;
  }

  /* clean up and exit */

  SDL_FreeSurface(packed);

  printf("Done!\n");


  return 0;
}
