/* Generated by packpng from sound.pack. DO NOT EDIT */

enum sound_t {
     S_REDLIGHT,
     S_GREENLIGHT,
     S_BLUELIGHT,
     S_FLY,
     S_PUSH,
     S_JIGGLE,
     S_BREAKS,
     S_SWAP,
     S_WALK,
     S_PRESS,
     S_STAND,
     S_TOGGLE,
     S_BUTTON,
     S_TRAP,
     S_PUSHGREEN,
     S_LITEWIRE,
     S_OPENDOOR,
     S_LASERED,
     S_WINNER,
     NUM_SOUND,
};

