macro68 fmain.asm -o fmain.o -c "g"
;macro68 fmain.asm -o fmain.o
sc link from stub.c fmain.o to fmain nostartup debug=full parm=reg nostackcheck smalldata optimize opttime
;sc link from stub.c fmain.o to fmain nostartup nodebug parm=reg nostackcheck smalldata optimize opttime stringmerge
copy fmain "The Faery Tale Adventure/" clone
sc link from read_tracks.c to read_tracks nodebug optimize opttime parm=reg nostackcheck stringmerge smallcode smalldata
