.\"     Title: comet
.\"    Author: Jens Granseuer <jensgr@gmx.net>
.\" Generator: DocBook XSL Stylesheets v1.71.1 <http://docbook.sf.net/>
.\"      Date: January 20 2007
.\"    Manual: 
.\"    Source: 
.\"
.TH "COMET" "6" "January 20 2007" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
comet \- a mission editor for Crimson Fields
.SH "SYNOPSIS"
.HP 6
\fBcomet\fR [\-\-level\ \fIlevel\fR] [\-\-width\ \fIwidth\fR] [\-\-height\ \fIwidth\fR] [\-\-fullscreen\ 1|0] [\-\-sound\ 1|0]
.HP 6
\fBcomet\fR {\-\-help | \-\-version}
.SH "DESCRIPTION"
.PP
\fBcomet\fR
(the Crimson Fields Map Editing Tool) is a mission editor for Crimson Fields.
.SH "OPTIONS"
.PP
\fB\-\-level\fR \fIlevel\fR
.RS 4
Start the editor with the
\fIlevel\fR
loaded.
.RE
.PP
\fB\-\-width\fR \fIw\fR
.RS 4
Set screen width to
\fIw\fR. Minimum screen width is 320. Default is 800.
.RE
.PP
\fB\-\-height\fR \fIh\fR
.RS 4
Set screen height to
\fIh\fR. Minimum screen height is 240. Default is 600.
.RE
.PP
\fB\-\-fullscreen\fR 1|0
.RS 4
Turn fullscreen mode on/off. The default is to start in windowed mode.
.RE
.PP
\fB\-\-sound\fR 1|0
.RS 4
Turn sound on/off. The default is on.
.RE
.PP
\fB\-\-help\fR
.RS 4
Print a usage message on standard output and exit.
.RE
.PP
\fB\-\-version\fR
.RS 4
Print version information on standard output and exit.
.RE
.SH "SEE ALSO"
.PP

\fBcfed\fR(6),
\fBcrimson\fR(6)
.SH "COPYRIGHT"
.PP
Copyright \(co 2002\-2007 Jens Granseuer
.PP
This software is distributed under the terms of the
\fIGNU General Public License\fR\&[1]
(GPL).
.SH "AUTHOR"
.PP
\fBJens Granseuer\fR <\&jensgr@gmx.net\&>
.sp -1n
.IP "" 4
Author.
.SH "REFERENCES"
.IP " 1." 4
GNU General Public License
.RS 4
\%http://www.gnu.org/copyleft/gpl.html
.RE
