**********************************************
**** 3D_Core Level Resource Loader Script ****
**** Copyright (c) Jonathan Gregory  1996 ****
****       Version 1.82  14/03/98         ****
**********************************************

Note the equals symbol is a reserved symbol within this
script all lines without it are ignored !!!!

The lines that do contain it are checked for valid key
words.  The order in which the keywords appear IS critical
defining scripts in a different order WILL result is crashes

*** Flush all objects,images & samples etc ***
FLUSH=YES

*** Load Samples and Images ***

SAMPLE=Samples/Scream.Samp
SAMPLE=Samples/Boom1.Samp
SAMPLE=Samples/Launch1.Samp
SAMPLE=Samples/Launch2.Samp
SAMPLE=Samples/Fire.Samp

IMAGE=Chunky/bullet.Chnk

IMAGE=Chunky/GravTank1_01.Chnk
IMAGE=Chunky/GravTank1_02.Chnk
IMAGE=Chunky/GravTank1_03.Chnk
IMAGE=Chunky/GravTank1_04.Chnk
IMAGE=Chunky/GravTank1_05.Chnk
IMAGE=Chunky/GravTank1_06.Chnk
IMAGE=Chunky/GravTank1_07.Chnk
IMAGE=Chunky/GravTank1_08.Chnk
IMAGE=Chunky/GravTank1_09.Chnk
IMAGE=Chunky/GravTank1_10.Chnk
IMAGE=Chunky/GravTank1_11.Chnk
IMAGE=Chunky/GravTank1_12.Chnk
IMAGE=Chunky/GravTank1_13.Chnk
IMAGE=Chunky/GravTank1_14.Chnk
IMAGE=Chunky/GravTank1_15.Chnk
IMAGE=Chunky/GravTank1_16.Chnk

IMAGE=Chunky/Turret1_01.Chnk
IMAGE=Chunky/Turret1_02.Chnk
IMAGE=Chunky/Turret1_03.Chnk
IMAGE=Chunky/Turret1_04.Chnk
IMAGE=Chunky/Turret1_05.Chnk
IMAGE=Chunky/Turret1_06.Chnk
IMAGE=Chunky/Turret1_07.Chnk
IMAGE=Chunky/Turret1_08.Chnk
IMAGE=Chunky/Turret1_09.Chnk
IMAGE=Chunky/Turret1_10.Chnk
IMAGE=Chunky/Turret1_11.Chnk
IMAGE=Chunky/Turret1_12.Chnk
IMAGE=Chunky/Turret1_13.Chnk
IMAGE=Chunky/Turret1_14.Chnk
IMAGE=Chunky/Turret1_15.Chnk
IMAGE=Chunky/Turret1_16.Chnk

IMAGE=Chunky/SFCargoPod1_01.Chnk
IMAGE=Chunky/SFCargoPod1_02.Chnk
IMAGE=Chunky/SFCargoPod1_03.Chnk
IMAGE=Chunky/SFCargoPod1_04.Chnk
IMAGE=Chunky/SFCargoPod1_05.Chnk
IMAGE=Chunky/SFCargoPod1_06.Chnk
IMAGE=Chunky/SFCargoPod1_07.Chnk
IMAGE=Chunky/SFCargoPod1_08.Chnk
IMAGE=Chunky/SFCargoPod1_09.Chnk
IMAGE=Chunky/SFCargoPod1_10.Chnk
IMAGE=Chunky/SFCargoPod1_11.Chnk
IMAGE=Chunky/SFCargoPod1_12.Chnk
IMAGE=Chunky/SFCargoPod1_13.Chnk
IMAGE=Chunky/SFCargoPod1_14.Chnk
IMAGE=Chunky/SFCargoPod1_15.Chnk
IMAGE=Chunky/SFCargoPod1_16.Chnk

IMAGE=Chunky/Explode1_01.Chnk
IMAGE=Chunky/Explode1_02.Chnk
IMAGE=Chunky/Explode1_03.Chnk
IMAGE=Chunky/Explode1_04.Chnk
IMAGE=Chunky/Explode1_05.Chnk
IMAGE=Chunky/Explode1_06.Chnk
IMAGE=Chunky/Explode1_07.Chnk
IMAGE=Chunky/Explode1_08.Chnk
IMAGE=Chunky/Explode1_09.Chnk

IMAGE=Chunky/Explode2_01.Chnk
IMAGE=Chunky/Explode2_02.Chnk
IMAGE=Chunky/Explode2_03.Chnk
IMAGE=Chunky/Explode2_04.Chnk
IMAGE=Chunky/Explode2_05.Chnk
IMAGE=Chunky/Explode2_06.Chnk
IMAGE=Chunky/Explode2_07.Chnk
IMAGE=Chunky/Explode2_08.Chnk
IMAGE=Chunky/Explode2_09.Chnk

IMAGE=Chunky/MissileA_01.Chnk
IMAGE=Chunky/MissileA_02.Chnk
IMAGE=Chunky/MissileA_03.Chnk
IMAGE=Chunky/MissileA_04.Chnk
IMAGE=Chunky/MissileA_05.Chnk
IMAGE=Chunky/MissileA_06.Chnk
IMAGE=Chunky/MissileA_07.Chnk
IMAGE=Chunky/MissileA_08.Chnk
IMAGE=Chunky/MissileA_09.Chnk
IMAGE=Chunky/MissileA_10.Chnk
IMAGE=Chunky/MissileA_11.Chnk
IMAGE=Chunky/MissileA_12.Chnk
IMAGE=Chunky/MissileA_13.Chnk
IMAGE=Chunky/MissileA_14.Chnk
IMAGE=Chunky/MissileA_15.Chnk
IMAGE=Chunky/MissileA_16.Chnk

IMAGE=Chunky/BlueBolt1_01.Chnk
IMAGE=Chunky/BlueBolt1_02.Chnk
IMAGE=Chunky/RedBolt1_01.Chnk
IMAGE=Chunky/RedBolt1_02.Chnk

IMAGE=Chunky/Flame1_01.Chnk
IMAGE=Chunky/Flame1_02.Chnk
IMAGE=Chunky/Flame1_03.Chnk
IMAGE=Chunky/Flame1_04.Chnk
IMAGE=Chunky/Flame1_05.Chnk
IMAGE=Chunky/Flame1_06.Chnk
IMAGE=Chunky/Flame1_07.Chnk
IMAGE=Chunky/Flame1_08.Chnk
IMAGE=Chunky/Flame1_09.Chnk
IMAGE=Chunky/Flame1_10.Chnk
IMAGE=Chunky/Flame1_11.Chnk
IMAGE=Chunky/Flame1_12.Chnk

IMAGE=Chunky/Tower1_01.Chnk
IMAGE=Chunky/Tower1_02.Chnk
IMAGE=Chunky/Tower1_03.Chnk
IMAGE=Chunky/Tower1_04.Chnk

IMAGE=Chunky/YelLight01.Chnk
IMAGE=Chunky/YelLight02.Chnk
IMAGE=Chunky/YelLight03.Chnk
IMAGE=Chunky/YelLight04.Chnk

IMAGE=Chunky/Blank.Chnk
IMAGE=Chunky/Tree1.Chnk
IMAGE=Chunky/Bush1.Chnk
IMAGE=Chunky/Bush2.Chnk
IMAGE=Chunky/Barrel1.Chnk
IMAGE=Chunky/MineDisk1.Chnk

IMAGE=Chunky/Floor01.Chnk
IMAGE=Chunky/SkyLine01.Chnk
IMAGE=Chunky/Font6x9.Chnk
IMAGE=Chunky/CamoGreen.Chnk

IMAGE=Chunky/Test.Chnk

*** Load ObjDefs and bind to images ***
OBJDEF=ObjDef.Data

*** Setup FlrObj Data Prior to Buildin templates ***

NOTE - If FLROBJDENSITY set to 0 FlrObjects are dissabled
       FLROBJRANGE is in worlds unit not map units and must be
       less than ACTRANGE * 65536 or objects will be dissabled

FLROBJDENSITY=50
FLROBJRANGE=120000
FLROBJ=1009,-30
FLROBJ=1010,-30

*** Setup Backdrop/Font Image ID's ***
NOTE:These ID's may go anywhere in this file after images loaded

SKYIMAGE=5001
FLRIMAGE=5000
FONT6X9IMAGE=5002

*** Build Basic Object Templates (i.e prior to 1st ColWobj) ***
TEMPLATES=BUILD

*** Load WObject map and bind to ObjDefs & Handlers ***
MAP=Test.Map

*** Build VP object data (i.e. after 1st ColWobj) ***
NOTE: INITVP=Xcoord,Ycoord,height,heading (Co-ords in Map units)

INITVP=132,481,0,512

*** ACTRANGE Sets Object vissibility (Active) range in block ***
NOTE: Distance is in blocks - 1 block=256x256 map units or 65536x65536 world units
      Default is 5 blocks, this attrib can be set anywhere in the script

ACTRANGE=6

*** Load Colour Trans Tables (EHB-64c) ***
NOTE: May go anywhere in the file

LOADCT64=RedCTran.Table
