GLOGET 40 @FIRSTTIME|
IF @FIRSTTIME = 0 FIRSTTIME|

:LOOP|
GOTO LOOP|

:ZONELABEL0|
RND @TEMP 20|
MATH @TEMP + 35|
[ "The day sure is pretty.  The"|
[ "thermometer says its only %1 right now." @TEMP|
[ "It never gets over 60 degrees Farenheit"|
[ "on this side of Mars, even with the"|
[ "Solar Infuser on full power."|
GOTO LOOP|

:FIRSTTIME|
[ "Little Green Men 25% Edition..."|
GLOSET 40 1|
GOTO LOOP|
