SubWindow, playerinputwin = WindowObject,
    MUIA_Window_Title, "New player details",
    MUIA_Window_ID   , MAKE_ID('P','L','D','E'),
    MUIA_Window_Width , MUIV_Window_Width_Default,
    MUIA_Window_Height, MUIV_Window_Height_Default,
    MUIA_Window_ScreenTitle, "Connect 4",
    MUIA_Window_CloseGadget, FALSE,

    WindowContents,
         VGroup,
             Child, HGroup,
                 Child, ColGroup(1),
                     Child, Label2("Name:"),
                     Child, Label2("Type:"),
                 End,
                 Child, RowGroup(2),
                     Child, piw_name = StringObject,
                         MUIA_String_Format, MUIV_String_Format_Left,
                         MUIA_String_MaxLen, NAME_LEN,
                         MUIA_Frame, MUIV_Frame_String,
                         MUIA_CycleChain, 1,
                         MUIA_String_AdvanceOnCR, TRUE,
                     End,
                     Child, HGroup,
                         Child, piw_cycle = CycleObject,
                             MUIA_Cycle_Entries, cycle_playertype_strings,
                         End,
                         Child, piw_detail = StringObject,
                             MUIA_String_Format, MUIV_String_Format_Left,
                             MUIA_String_MaxLen, DETAIL_LEN,
                             MUIA_Frame, MUIV_Frame_String,
                             MUIA_CycleChain, 1,
                             MUIA_String_AdvanceOnCR, TRUE,
                         End,
                     End,
                 End,
             End,
             Child, HGroup,
                 Child, piw_okbutton = TextObject,
                          MUIA_Text_Contents, MUIX_C"OK",
                          MUIA_Frame, MUIV_Frame_Button,
                          MUIA_InputMode, MUIV_InputMode_RelVerify,
                          MUIA_Background, MUII_ButtonBack,
                          MUIA_CycleChain, 1,
                 End,
                 Child, RectangleObject,
                     MUIA_HorizWeight, 200,
                 End,
                 Child, piw_cancelbutton = TextObject,
                          MUIA_Text_Contents, MUIX_C"Cancel",
                          MUIA_Frame, MUIV_Frame_Button,
                          MUIA_InputMode, MUIV_InputMode_RelVerify,
                          MUIA_Background, MUII_ButtonBack,
                          MUIA_CycleChain, 1,
                 End,
             End,
         End,
End,

