SubWindow, winnerwin = WindowObject,
    MUIA_Window_Title, "The Winner",
    MUIA_Window_ID   , MAKE_ID('W','I','N','W'),
    MUIA_Window_Width , MUIV_Window_Width_Default,
    MUIA_Window_Height, MUIV_Window_Height_Default,
    MUIA_Window_ScreenTitle, "Connect 4",
    MUIA_Window_CloseGadget, FALSE,

    WindowContents,
        VGroup,
            Child, HGroup,
                MUIA_Frame, MUIV_Frame_Text,
                MUIA_Background, MUII_TextBack,
                Child, RectangleObject, End,
                Child, VGroup,
                    Child, TextObject,
                        MUIA_Text_Contents, MUIX_C"\nContratulations\n",
                    End,
                    Child, winnertext = TextObject, End,
                    Child, TextObject,
                        MUIA_Text_Contents, MUIX_C"\nYou are the WINNER!\n",
                    End,
                End,
                Child, RectangleObject, End,
            End,
            Child, HGroup,
                Child, RectangleObject, End,
                Child, winw_ok=TextObject,
                         MUIA_Text_Contents, MUIX_C"OK",
                         MUIA_Frame, MUIV_Frame_Button,
                         MUIA_InputMode, MUIV_InputMode_RelVerify,
                         MUIA_Background, MUII_ButtonBack,
                         MUIA_CycleChain, 1,
                End,
                Child, RectangleObject, End,
            End,
        End,
End,

