// generated by Fast Light User Interface Designer (fluid) version 1.0106

#include "mainwindow.h"

Fl_Browser *ScoreBoard=(Fl_Browser *)0;

Fl_Output *MeOut=(Fl_Output *)0;

Fl_Output *YouOut=(Fl_Output *)0;

Fl_Box *P0A0=(Fl_Box *)0;

Fl_Box *P0A1=(Fl_Box *)0;

Fl_Box *P0A2=(Fl_Box *)0;

Fl_Box *P0A3=(Fl_Box *)0;

Fl_Box *P010=(Fl_Box *)0;

Fl_Box *P02=(Fl_Box *)0;

Fl_Box *P12=(Fl_Box *)0;

Fl_Box *P1A0=(Fl_Box *)0;

Fl_Box *P1A1=(Fl_Box *)0;

Fl_Box *P1A2=(Fl_Box *)0;

Fl_Box *P1A3=(Fl_Box *)0;

Fl_Box *P110=(Fl_Box *)0;

Fl_Progress *Progress=(Fl_Progress *)0;

Fl_Double_Window* make_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(640, 480, "casino");
    w = o;
    { Fl_Group* o = new Fl_Group(0, 0, 640, 45);
      o->box(FL_PLASTIC_DOWN_BOX);
      { Fl_Button* o = new Fl_Button(5, 5, 100, 35, "New game");
        o->box(FL_PLASTIC_UP_BOX);
        o->down_box(FL_PLASTIC_DOWN_BOX);
        o->labeltype(FL_ENGRAVED_LABEL);
        o->labelfont(8);
        o->labelsize(20);
        o->callback((Fl_Callback*)cb_new);
      }
      { Fl_Button* o = new Fl_Button(205, 5, 100, 35, "Help");
        o->box(FL_PLASTIC_UP_BOX);
        o->down_box(FL_PLASTIC_DOWN_BOX);
        o->labeltype(FL_ENGRAVED_LABEL);
        o->labelfont(8);
        o->labelsize(20);
        o->callback((Fl_Callback*)cb_help);
      }
      { Fl_Button* o = new Fl_Button(305, 5, 100, 35, "Exit");
        o->box(FL_PLASTIC_UP_BOX);
        o->down_box(FL_PLASTIC_DOWN_BOX);
        o->labeltype(FL_ENGRAVED_LABEL);
        o->labelfont(8);
        o->labelsize(20);
        o->callback((Fl_Callback*)cb_exit);
      }
      { Fl_Group* o = new Fl_Group(425, 5, 210, 35);
        o->end();
        Fl_Group::current()->resizable(o);
      }
      { Fl_Button* o = new Fl_Button(105, 5, 100, 35, "Hint");
        o->box(FL_PLASTIC_UP_BOX);
        o->down_box(FL_PLASTIC_DOWN_BOX);
        o->labeltype(FL_ENGRAVED_LABEL);
        o->labelfont(8);
        o->labelsize(20);
        o->callback((Fl_Callback*)cb_hint);
      }
      o->end();
    }
    { Desk* o = new Desk(0, 45, 500, 400, "Click \'New Game\' to start !");
      o->box(FL_DOWN_BOX);
      o->color(FL_BACKGROUND_COLOR);
      o->selection_color(FL_BACKGROUND_COLOR);
      o->labeltype(FL_SHADOW_LABEL);
      o->labelfont(11);
      o->labelsize(42);
      o->labelcolor(FL_BLACK);
      o->align(FL_ALIGN_CENTER);
      o->when(FL_WHEN_RELEASE);
      Fl_Group::current()->resizable(o);
    }
    { Fl_Group* o = new Fl_Group(500, 45, 140, 400);
      { Fl_Browser* o = ScoreBoard = new Fl_Browser(500, 90, 140, 305);
        o->box(FL_PLASTIC_DOWN_FRAME);
        o->textfont(4);
        o->textsize(20);
        Fl_Group::current()->resizable(o);
      }
      { Fl_Output* o = MeOut = new Fl_Output(500, 65, 70, 25, "Me:");
        o->box(FL_PLASTIC_DOWN_BOX);
        o->labelfont(8);
        o->labelsize(20);
        o->textfont(8);
        o->textsize(20);
        o->align(FL_ALIGN_TOP);
      }
      { Fl_Output* o = YouOut = new Fl_Output(570, 65, 70, 25, "You:");
        o->box(FL_PLASTIC_DOWN_BOX);
        o->labelfont(8);
        o->labelsize(20);
        o->textfont(8);
        o->textsize(20);
        o->align(FL_ALIGN_TOP);
      }
      { Fl_Button* o = new Fl_Button(570, 395, 70, 50, "Drop");
        o->box(FL_PLASTIC_UP_BOX);
        o->down_box(FL_PLASTIC_DOWN_BOX);
        o->labeltype(FL_ENGRAVED_LABEL);
        o->labelfont(8);
        o->labelsize(20);
        o->callback((Fl_Callback*)cb_drop);
      }
      { Fl_Button* o = new Fl_Button(500, 395, 70, 50, "Get");
        o->box(FL_PLASTIC_UP_BOX);
        o->down_box(FL_PLASTIC_DOWN_BOX);
        o->labeltype(FL_ENGRAVED_LABEL);
        o->labelfont(8);
        o->labelsize(20);
        o->callback((Fl_Callback*)cb_get);
      }
      o->end();
    }
    { Fl_Group* o = new Fl_Group(0, 445, 640, 35);
      { Fl_Box* o = P0A0 = new Fl_Box(0, 445, 35, 35, "A");
        o->box(FL_PLASTIC_UP_BOX);
        o->labeltype(FL_SHADOW_LABEL);
        o->labelfont(9);
        o->labelsize(32);
      }
      { Fl_Box* o = P0A1 = new Fl_Box(35, 445, 35, 35, "A");
        o->box(FL_PLASTIC_UP_BOX);
        o->labeltype(FL_SHADOW_LABEL);
        o->labelfont(9);
        o->labelsize(32);
      }
      { Fl_Box* o = P0A2 = new Fl_Box(70, 445, 35, 35, "A");
        o->box(FL_PLASTIC_UP_BOX);
        o->labeltype(FL_SHADOW_LABEL);
        o->labelfont(9);
        o->labelsize(32);
      }
      { Fl_Box* o = P0A3 = new Fl_Box(105, 445, 35, 35, "A");
        o->box(FL_PLASTIC_UP_BOX);
        o->labeltype(FL_SHADOW_LABEL);
        o->labelfont(9);
        o->labelsize(32);
      }
      { Fl_Box* o = P010 = new Fl_Box(140, 445, 40, 35, "10");
        o->box(FL_PLASTIC_UP_BOX);
        o->labeltype(FL_SHADOW_LABEL);
        o->labelfont(9);
        o->labelsize(32);
      }
      { Fl_Box* o = P02 = new Fl_Box(180, 445, 40, 35, "2");
        o->box(FL_PLASTIC_UP_BOX);
        o->labeltype(FL_SHADOW_LABEL);
        o->labelfont(9);
        o->labelsize(32);
      }
      { Fl_Box* o = P12 = new Fl_Box(420, 445, 40, 35, "2");
        o->box(FL_PLASTIC_UP_BOX);
        o->labeltype(FL_SHADOW_LABEL);
        o->labelfont(9);
        o->labelsize(32);
      }
      { Fl_Box* o = P1A0 = new Fl_Box(605, 445, 35, 35, "A");
        o->box(FL_PLASTIC_UP_BOX);
        o->labeltype(FL_SHADOW_LABEL);
        o->labelfont(9);
        o->labelsize(32);
      }
      { Fl_Box* o = P1A1 = new Fl_Box(570, 445, 35, 35, "A");
        o->box(FL_PLASTIC_UP_BOX);
        o->labeltype(FL_SHADOW_LABEL);
        o->labelfont(9);
        o->labelsize(32);
      }
      { Fl_Box* o = P1A2 = new Fl_Box(535, 445, 35, 35, "A");
        o->box(FL_PLASTIC_UP_BOX);
        o->labeltype(FL_SHADOW_LABEL);
        o->labelfont(9);
        o->labelsize(32);
      }
      { Fl_Box* o = P1A3 = new Fl_Box(500, 445, 35, 35, "A");
        o->box(FL_PLASTIC_UP_BOX);
        o->labeltype(FL_SHADOW_LABEL);
        o->labelfont(9);
        o->labelsize(32);
      }
      { Fl_Box* o = P110 = new Fl_Box(460, 445, 40, 35, "10");
        o->box(FL_PLASTIC_UP_BOX);
        o->labeltype(FL_SHADOW_LABEL);
        o->labelfont(9);
        o->labelsize(32);
      }
      { Fl_Progress* o = Progress = new Fl_Progress(225, 450, 190, 25);
        o->box(FL_PLASTIC_DOWN_BOX);
        o->selection_color((Fl_Color)2);
        Fl_Group::current()->resizable(o);
      }
      o->end();
    }
    o->end();
  }
  return w;
}
