// generated by Fast Light User Interface Designer (fluid) version 1.0106

#ifndef mainwindow_h
#define mainwindow_h
#include <FL/Fl.H>
#include "desk.h"
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Button.H>
extern void cb_new(Fl_Button*, void*);
extern void cb_help(Fl_Button*, void*);
extern void cb_exit(Fl_Button*, void*);
extern void cb_hint(Fl_Button*, void*);
#include <FL/Fl_Browser.H>
extern Fl_Browser *ScoreBoard;
#include <FL/Fl_Output.H>
extern Fl_Output *MeOut;
extern Fl_Output *YouOut;
extern void cb_drop(Fl_Button*, void*);
extern void cb_get(Fl_Button*, void*);
#include <FL/Fl_Box.H>
extern Fl_Box *P0A0;
extern Fl_Box *P0A1;
extern Fl_Box *P0A2;
extern Fl_Box *P0A3;
extern Fl_Box *P010;
extern Fl_Box *P02;
extern Fl_Box *P12;
extern Fl_Box *P1A0;
extern Fl_Box *P1A1;
extern Fl_Box *P1A2;
extern Fl_Box *P1A3;
extern Fl_Box *P110;
#include <FL/Fl_Progress.H>
extern Fl_Progress *Progress;
Fl_Double_Window* make_window();
#endif
