8
Brief test of the books of the bible, what's in em and who wrote 'em.
3
This book deals with the journey of Israel from Mt. Sinai to the edge of
Canaan and the Israelites' preparation to enter the Land.
273
 Deuteronomy
 Numbers
 Kings
1
2
7
This book deals with the significant facts surrounding Israel's emergence as
a nation. Moses' great leadership is described as he accepted God's call to
return to Egypt in order to lead God's people to freedom.
273
 Genesis
 Numbers
 Exodus
1
3
1
First book of the bible written by moses to explain how everything began.
273
 Matthew
 Genesis
 Exodus
1
2
7
First book written after the death of moses, probably written by the
commander-in-chief throughout the entire time of conquest when Israel was
taking over the land.
273
 Joshua
 Samuel
 Ruth
1
1
7
Two books together covering a period of approximately 350 years, when kings
ruled over the land. These books form one book in the Hebrew Bible and are
considered prophetic literature.
273
 Psalms
 Chronicles
 Kings
1
3
7
This long poem deals with one of the deepest problems of man: How do we
explain sin and suffering, if there exists a God powerful enough to do
something about them?
273
 Job
 Psalms
 Chronicles
1
1
7
Book written by a tax-collector, called by Jesus to follow him early in his
public ministry, and hence was an eye-witness of most of the events he
describes.
273
 John
 Acts
 Matthew
1
3
3
This is basically a funeral song written by Jeremiah for the fallen city
of Jerusalem.
273
 Jeremiah
 Lamenations
 Amos
1
2
15
This book contains practical instructions for successful living, given by
God to supplement the teaching of the prophets, which was to call men to
repentance, and the work of the priests, which was to direct the worship
of the people. Mainly written by Solomon.
273
 Proverbs
 Psalms
 Solomon
1
1
0
