/*
 *  Source machine generated by GadToolsBox V2.0b
 *  which is (c) Copyright 1991-1993 Jaba Development
 *
 *  GUI Designed by : -- dante --
 */

#define GetString( g )      ((( struct StringInfo * )g->SpecialInfo )->Buffer  )
#define GetNumber( g )      ((( struct StringInfo * )g->SpecialInfo )->LongInt )

#define GD_main_soundsetup                     0
#define GD_main_screensetup                    1
#define GD_main_kbsetup                        2
#define GD_main_ok                             3
#define GD_main_cancel                         4
#define GD_main_mousesetup                     5

#define GDX_main_soundsetup                    0
#define GDX_main_screensetup                   1
#define GDX_main_kbsetup                       2
#define GDX_main_ok                            3
#define GDX_main_cancel                        4
#define GDX_main_mousesetup                    5

#define GD_sound_selecteddevice                0
#define GD_sound_ahisetup                      1
#define GD_sound_voices                        2
#define GD_sound_sfxvolume                     3
#define GD_sound_rvstereo                      4
#define GD_sound_ok                            5
#define GD_sound_cancel                        6

#define GDX_sound_selecteddevice               0
#define GDX_sound_ahisetup                     1
#define GDX_sound_voices                       2
#define GDX_sound_sfxvolume                    3
#define GDX_sound_rvstereo                     4
#define GDX_sound_ok                           5
#define GDX_sound_cancel                       6

#define GD_kb_listview                         0
#define GD_kb_ok                               1
#define GD_kb_cancel                           2
#define GD_kb_defaults                         3

#define GDX_kb_listview                        0
#define GDX_kb_ok                              1
#define GDX_kb_cancel                          2
#define GDX_kb_defaults                        3

#define GD_screen_mode                         0
#define GD_screen_modedesc                     1
#define GD_screen_dblbuffer                    2
#define GD_screen_directaccess                 3
#define GD_screen_ok                           4
#define GD_screen_cancel                       5

#define GDX_screen_mode                        0
#define GDX_screen_modedesc                    1
#define GDX_screen_dblbuffer                   2
#define GDX_screen_directaccess                3
#define GDX_screen_ok                          4
#define GDX_screen_cancel                      5

#define GD_mouse_scl                           0
#define GD_mouse_scm                           1
#define GD_mouse_scr                           2
#define GD_mouse_scl_text                      3
#define GD_mouse_scm_text                      4
#define GD_mouse_scr_text                      5
#define GD_mouse_dcl                           6
#define GD_mouse_dcm                           7
#define GD_mouse_dcr                           8
#define GD_mouse_dcl_text                      9
#define GD_mouse_dcm_text                      10
#define GD_mouse_dcr_text                      11
#define GD_mouse_ok                            12
#define GD_mouse_defaults                      13
#define GD_mouse_cancel                        14
#define GD_mouse_sensi                         15
#define GD_mouse_aimmode                       16
#define GD_mstext                              17
#define GD_mouse_sctext                        18
#define GD_dcltext                             19
#define GD_matext                              20
#define GD_mouse_invert                        21

#define GDX_mouse_scl                          0
#define GDX_mouse_scm                          1
#define GDX_mouse_scr                          2
#define GDX_mouse_scl_text                     3
#define GDX_mouse_scm_text                     4
#define GDX_mouse_scr_text                     5
#define GDX_mouse_dcl                          6
#define GDX_mouse_dcm                          7
#define GDX_mouse_dcr                          8
#define GDX_mouse_dcl_text                     9
#define GDX_mouse_dcm_text                     10
#define GDX_mouse_dcr_text                     11
#define GDX_mouse_ok                           12
#define GDX_mouse_defaults                     13
#define GDX_mouse_cancel                       14
#define GDX_mouse_sensi                        15
#define GDX_mouse_aimmode                      16
#define GDX_mstext                             17
#define GDX_mouse_sctext                       18
#define GDX_dcltext                            19
#define GDX_matext                             20
#define GDX_mouse_invert                       21

#define GD_mact_list                           0
#define GD_mact_abort                          1

#define GDX_mact_list                          0
#define GDX_mact_abort                         1

#define main_CNT 6
#define sound_CNT 7
#define keyboard_CNT 4
#define screen_CNT 6
#define mouse_CNT 22
#define macts_CNT 2

extern struct IntuitionBase *IntuitionBase;
extern struct Library       *GadToolsBase;

extern struct Screen        *Scr;
extern UBYTE                 *PubScreenName;
extern APTR                  VisualInfo;
extern struct Window        *mainWnd;
extern struct Window        *soundWnd;
extern struct Window        *keyboardWnd;
extern struct Window        *screenWnd;
extern struct Window        *mouseWnd;
extern struct Window        *mactsWnd;
extern struct Gadget        *mainGList;
extern struct Gadget        *soundGList;
extern struct Gadget        *keyboardGList;
extern struct Gadget        *screenGList;
extern struct Gadget        *mouseGList;
extern struct Gadget        *mactsGList;
extern struct Gadget        *mainGadgets[6];
extern struct Gadget        *soundGadgets[7];
extern struct Gadget        *keyboardGadgets[4];
extern struct Gadget        *screenGadgets[6];
extern struct Gadget        *mouseGadgets[22];
extern struct Gadget        *mactsGadgets[2];
extern UWORD                 mainLeft;
extern UWORD                 mainTop;
extern UWORD                 mainWidth;
extern UWORD                 mainHeight;
extern UWORD                 soundLeft;
extern UWORD                 soundTop;
extern UWORD                 soundWidth;
extern UWORD                 soundHeight;
extern UWORD                 keyboardLeft;
extern UWORD                 keyboardTop;
extern UWORD                 keyboardWidth;
extern UWORD                 keyboardHeight;
extern UWORD                 screenLeft;
extern UWORD                 screenTop;
extern UWORD                 screenWidth;
extern UWORD                 screenHeight;
extern UWORD                 mouseLeft;
extern UWORD                 mouseTop;
extern UWORD                 mouseWidth;
extern UWORD                 mouseHeight;
extern UWORD                 mactsLeft;
extern UWORD                 mactsTop;
extern UWORD                 mactsWidth;
extern UWORD                 mactsHeight;
extern UBYTE                *mainWdt;
extern UBYTE                *soundWdt;
extern UBYTE                *keyboardWdt;
extern UBYTE                *screenWdt;
extern UBYTE                *mouseWdt;
extern UBYTE                *mactsWdt;
extern struct TextAttr      *Font, Attr;
extern UWORD                 FontX, FontY;
extern UWORD                 OffX, OffY;
extern struct TextFont      *mainFont;
extern struct TextFont      *soundFont;
extern struct TextFont      *keyboardFont;
extern struct TextFont      *screenFont;
extern struct TextFont      *mouseFont;
extern struct TextFont      *mactsFont;
extern struct GfxBase       *GfxBase;
extern UBYTE                *sound_voices1Labels[];
extern UBYTE                *mouse_aimmode4Labels[];
extern UWORD                 mainGTypes[];
extern UWORD                 soundGTypes[];
extern UWORD                 keyboardGTypes[];
extern UWORD                 screenGTypes[];
extern UWORD                 mouseGTypes[];
extern UWORD                 mactsGTypes[];
extern struct NewGadget      mainNGad[];
extern struct NewGadget      soundNGad[];
extern struct NewGadget      keyboardNGad[];
extern struct NewGadget      screenNGad[];
extern struct NewGadget      mouseNGad[];
extern struct NewGadget      mactsNGad[];
extern ULONG                 mainGTags[];
extern ULONG                 soundGTags[];
extern ULONG                 keyboardGTags[];
extern ULONG                 screenGTags[];
extern ULONG                 mouseGTags[];
extern ULONG                 mactsGTags[];


extern int SetupScreen( void );
extern void CloseDownScreen( void );
extern void mainRender( void );
extern int OpenmainWindow( void );
extern void ClosemainWindow( void );
extern void soundRender( void );
extern int OpensoundWindow( void );
extern void ClosesoundWindow( void );
extern void keyboardRender( void );
extern int OpenkeyboardWindow( void );
extern void ClosekeyboardWindow( void );
extern void screenRender( void );
extern int OpenscreenWindow( void );
extern void ClosescreenWindow( void );
extern void mouseRender( void );
extern int OpenmouseWindow( void );
extern void ClosemouseWindow( void );
extern void mactsRender( void );
extern int OpenmactsWindow( void );
extern void ClosemactsWindow( void );
