78
Economics I Quiz Questions - College Softmore Level
1
Business firms try to maximize their normal profits
9
 True
 False
2
2
3
Industries in which economic profits are earned by the firms in the industry
will attract the entry of new firms into the industry.
9
 True
 False
2
1
3
If firms have sufficient time to enter and leave industries; the economic
profits of an industry will tend to disappear.
9
 True
 False
2
1
3
Business firms are really only free to produce whatever they want in any way
they wish if they do not want to maximize profits or to minimize losses.
9
 True
 False
2
1
3
To say that the demand for a resource is a derived demand means that it
depends upon the demands for the products the resource is used to produce.
9
 True
 False
2
1
3
Resources will tend to be used in those industries capable of earning normal
or economic profits.
9
 True
 False
2
1
3
Economic efficiency requires that a given output of a good or service be
produced in the least costly way.
9
 True
 False
2
1
3
If the market price of resource A increases, firms will tend to employ
smaller quantities of resource A.
9
 True
 False
2
1
3
Changes in the tastes of consumers are reflected in changes in consumer
demand for products.
9
 True
 False
2
1
3
The incentive which the price system provides to induce technological
improvement is the opportunity for economic profits.
9
 True
 False
2
1
3
In a capitalistic economy it is from the entrepreneur that the demand for
capital goods arises.
9
 True
 False
2
1
7
The tendency for individuals pursuing their own self-interest to bring about
results which are in the best interest of society as a whole is often called
"invisible hand."
9
 True
 False
2
1
3
The American economy cannot be called "capitalistic" because its operation
involves some "planning."
9
 True
 False
2
2
3
When the Federal government provides for a monetary system, it is
functioning to provide the economy with public goods and services.
9
 True
 False
2
2
3
An economy in which strong and effective competition is mantained will find
no need for programs designed to redistribute money.
9
 True
 False
2
2
3
Competitive product markets ensure an optimal allocation of an economy's
resources.
9
 True
 False
2
2
3
In a competitive product market and in the absence of spillover costs, the
supply curve or schedue reflects the costs of producing the product.
9
 True
 False
2
1
3
If demand and supply reflected al the benefits and costs of a product, the
equilibrium output of a competitive market woud be identical with its optimum.
9
 True
 False
2
1
1
The incusion of the spilover benefits would increase the demand for a product
9
 True
 False
2
1
7
The personal distibution of income describes the manner in which society's
total personal income is divided among wages and salaries, corporate profits,
proprietors income, interest and rents.
9
 True
 False
2
2
3
Limited liability refers to the fact that all members of a partnership are
liable for the debts incurred by one another.
9
 True
 False
2
1
3
A distribution of income which is based on the productivity of resources
usually results in considerable inequalit in the size of incomes.
9
 True
 False
2
1
3
In both relative and absolute terms, personal taxes have exceeded personal
saving in recent years.
9
 True
 False
2
1
3
Most of the personal saving in the American economy is done by those
households in the top 10% of its income receivers
9
 True
 False
2
1
3
Dissaving means that personal consumption expenditures exceed after-tax
income.
9
 True
 False
2
1
3
A "Durable good" is defined as a good which has an expected life of one
year or more.
9
 True
 False
2
1
1
A plant is defined as a group of firms under a single management.
9
 True
 False
2
2
3
An industry is a group of firms that produce the same or nearly the same
products.
9
 True
 False
2
1
1
The corporate form of organization is the least used by firms in the U.S.
9
 True
 False
2
2
3
The corporation in the U.S. today always has a tax advantage over other
legal forms of business organization.
9
 True
 False
2
2
3
Whether a business firm should incorporate or not depends chiefly upon the
amount of money capital it must have to finance the enterprise.
9
 True
 False
2
1
7
The wholesale and retail trade and the service industries contain a
relatively large number of firms but are not important sources of income
and employment in the American economy.
9
 True
 False
2
2
3
Corporations produce over one-half the total output produced by privately
owned business firms in the U.S.
9
 True
 False
2
1
3
Historical data show quite clearly that economic concentration has tended to
increase in the U.S. with the passage of time.
9
 True
 False
2
2
1
There are in the U.S. Approximately how many households (families)?
585
 63 million
 75 million
 80 million
 85 million
2
4
3
The functional distribution for the U.S. shows that the largest part of
personal income is ____
585
 wages and salaries
 proprietors income
 corporate profits
 interest and rents
2
1
3
Which of the folllowing is not a factor affecting the amount of money income
received by the individual household?
587
 The quantity of resources the household has available to supply
 busness firms
 the amount of saving done by the household
 the prices paid for various resources in the market
 the actual evel of emplloyment of the househods resources
2
2
1
The personal distribution of income affects ____
585
 the total output of the economy
 the number of peopllle who find employment in the economy
 the composition of the total output of the economy
 All of these
2
4
3
Expenditures for nondurable goods in recent years have amounted to approx.
what percentage of personal consumption expenditures?
585
 30 %
 40 %
 50 %
 60 %
2
2
1
Which of the following is a true statement?
587
 The durable goods & serv. parts ... vary more orver time than nondurable
 exp.
 expenditure for nondurable vary more
 expenditures for nondurable vary more ...
 expenditures for nondurable goods vary more ...
2
1
3
In recent years personal taxes have been approx. what percentage of total
income?
585
 16 %
 22 %
 24 %
 80 %
2
1
3
if we include self-employed farmers and professional people, there are
approx how many million business firms in the U.S.?
585
 5
 8
 16
 20
2
3
7
A group of 3 plants which is owned and operated by a single firm and which
consists of a farm growing wheat, a flour milling plant, and a plant which
bakes and sells bakery products is an example of ____
585
 a horizontal combination
 a vertical combination
 a conglomerate combination
 a corporation
2
2
1
Limited liablility is associated with ____
585
 only proprietorships
 only partnerships
 both proprietorships and partnerships
 only corporations
2
4
3
Which of the following forms of business organization can most effectively
raise money capital?
585
 Corporation
 partnership
 proprietorship
 vertical combination
2
1
1
Which of the following industry classes has the largest number of firms?
585
 Agriculture, forestry and fishing
 manufacturing
 wholesale and retail trade
 mining
2
1
3
Which of the following industry classes produces the largest percentage of
the national income?
585
 Agriculture, forestry, and fishing
 manufacturing
 wholesale and retail trade
 government
2
2
3
About what percentage of the national income of the United States is produced
by government.
585
 3 %
 5 %
 10 %
 12 %
2
4
3
The 100 largest manufacturing firms in the U.S. today own approximately what
percentage of the assets of all manufacturing firms?
585
 40 %
 45 %
 50 %
 more than 50 %
2
2
3
Transactions in the public sector of the economy are largely compulsory and
those in the private sector are voluntary
9
 True
 False
2
1
3
Government purchases of goods and services are called nonexhaustive and
government transfer payments are called exhaustive expenditures.
9
 True
 False
2
2
7
When a government levies taxes and uses the tax revenue to make transfer
payments it shifts resources from the production of private goods to the
production of social goods.
9
 True
 False
2
2
1
The level of Federal expenditures in 1984 was about $850 billion.
9
 True
 False
2
1
3
The chief source of revenue for the Federal government is the corporation
income tax.
9
 True
 False
2
2
7
Because the Federal personal income tax is a progressive tax, if a taxpayer
had a taxable income of $20,000 and his or her marginal tax rate was 35% the
taxpayer would be required to pay a total tax of less than $7000.
9
 True
 False
2
1
3
Personal income tax rates have been "indexed" since 1985 to prevent
inflation from pushing taxpayers into higher marginal tax brackets.
9
 True
 False
2
1
7
Because the marginal tax rate on all taxable corporate profits in excess of
$100,000 is 46%, beyond $100,000 the Federal corporate income tax is
proportional.
9
 True
 False
2
2
1
The Federal government levies sales taxes on tobacco and gasoline
9
 True
 False
2
2
3
There is a major loophole in the Federal tax system because personal income
tax rates are progressive
9
 True
 False
2
2
3
Total taxes collected by the Federal government are approximetely equal to
the amount of taxes collected by all state and local governments.
9
 True
 False
2
2
7
The chief difficulty in applying the benefits-received principle of taxation
is determining who receives the benefits of many of the goods and services
which government supplies.
9
 True
 False
2
1
1
A sales tax generally turns out to be a proportional tax
9
 True
 False
2
2
3
The state and federal taxes on gasoline are good examples of taxes levied on
the benefits-received principle.
9
 True
 False
2
1
3
Estimates of the overall structure of the American tax system depend on the
assumed incidence of taxes
9
 True
 False
2
1
3
A value-added tax is a tax on the difference between the value of goods sold
by a firm and the value of the goods it purchased from other firms.
9
 True
 False
2
1
7
Advocates of the "reindustrializing" the American economy have proposed
increasing the tax rate imposed by the federal government on corporate
income to force corporations to be more efficient.
9
 True
 False
2
2
7
A value-added tax, its poponents argue, would tend to reduce consumption
and increase saving in the economy and release resources for the production
of more investment goods.
9
 True
 False
2
1
3
Today all government expenditures equal approx. what percentage of the
American economy's total output
585
 10 %
 18 %
 23 %
 33 %
2
4
3
Which of the following is NOT one of the causes of the present size of
government expenditures in the U.S.
585
 Inflation
 Double taxation
 population growth
 egalitarianism
2
2
1
Which of the following would not be a government transfer expenditure?
585
 Contributions of employers to support the S.Security program
 social security payments to the aged
 unemployment compensation benefits
 payments to the widows of war veterans
2
1
3
Which of the following accounts for the largest percentage of all Federal
expenditures
585
 Income security
 National defense
 interest on the public debt
 veterans services
2
1
3
Which of the following is the largest source of the tax revenues of the
Federal government
585
 Sales and excise taxes
 property taxes
 payroll taxes
 personal income taxes
2
4
3
Tax evasion is estimated by the U.S. Treasury to cost the Federal gov.
each  year
585
 50 billion
 100 billion
 150 billion
 200 billion
2
2
3
When the income of a taxpayer increases and a tax is regressive, the amount
of the tax paid by the taxpayer ____
585
 Increases
 decreases
 remains unchanged
 may do any of the following
2
4
1
Which of the following tends to be a progressive tax in the U.S.
585
 income tax
 poperty tax
 sales tax
 payroll tax
2
1
1
Which of the following taxes can be least easily shifted
585
 personal income tax
 corporation income tax
 sales tax
 business property tax
2
1
1
The Pechman study of the American tax structure shows it to be
585
 very progressive
 slightly progressive
 slightly regressive
 very regressive
2
2
1
The advocates of "reindustrializing" the American economy argue that ____
585
 the production of consumer goods must be increased.
 the productivity of American workers must be improved.
 corporate income taxes should be increased.
 the production of investment goods needs to be reduced by a substatial amnt
2
2
3
Proponents of replacing the progressive Federal personal income tax with a
flat-rate tax contend it would ____
585
 redistribute the federal tax burden from the poor to the rich
 improve the incentives to work, invest, and take risks
 increase the built-in stability of the economy
 expand the progressivity of the American tax system
2
2
0
