
                             NIPPON SAFES INC.
                             °°°°°°°°°°°°°°°°°
                           Walk Through Solution
                           °°°°°°°°°°°°°°°°°°°°°
                     BY: The Holy Inquisition (T.H.I.)
                     °°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°
              THERE ARE ALSO MAPS AVAILABLE OF ALL LOCATIONS
              °°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°



DOUG NUTS (SMART)
°°°°°°°°°°°°°°°°°

OUTSIDE PRISON
°°°°°°°°°°°°°°
WALK LEFT TO LAST FOOD,EXAMINE TRASHCAN,PICKUP CAN,PICKUP TAB,WALK TO
HIGHWAY 3,TAKE THE PHONE APART(TAB),TALK TO TAXI DRIVER,ANSWER:CERTAINLY!.

TAXI CAB
°°°°°°°°
EXAMINE DOLL,TALK TO TAXI DRIVER,ASK:SUMO FAN,ANSWER:OF COURSE!,TALK TO TAXI
DRIVER.

SQUARE 3
°°°°°°°°
DOESN'T MATTER WHICH ANSWER,WALK TO HOT SUSHI.

HOT SUSHI
°°°°°°°°°
TALK TO MAX & KOS,SHOW THE LETTER,TALK TO MAX & KOS,ASK:MONASTARY,WALK TO
LANE.

LANE
°°°°
OPEN MAILBOX,PICKUP LETTER,PICKUP PACK,READ LETTER,OPEN DOOR(KEY),WALK TO
DOUG'S HOUSE.

DOUG'S HOUSE
°°°°°°°°°°°°
OPEN CHEST,PICKUP WRENCH,OPEN LARDER(RIGHT),DISMOUNT THE RADIO(WRENCH),GOT
MAGNET,WALK TO SQUARE 1.

SQUARE 1
°°°°°°°°
CRACK THE PARKING METER(WRENCH),GOT 100Y,TALK TO TAXI DRIVER,WALK TO
HIGHWAY,WALK TO SQUARE 1,EXAMINE BILL DISPENSER(DO THIS UNTIL YOU'VE GOT SIX
BILLS),READ BILLS,WALK TO HOT SUSHI.

HOT SUSHI
°°°°°°°°°
TALK TO MAX & KOS,ASK:SUMO,TALK TO BARMAN,ASK:BEER,BUY BEER(1000Y),OFFER
THE BEER,WALK TO SQUARE 3.

SQUARE 3
°°°°°°°°
BARTER THE WRENCH(HONEST CHAN'S(IF HE IS SHUT JUST WAIT)),ASK:BIG POT,WALK
TO SQUARE 2.

SQUARE 2
°°°°°°°°
TALK TO NEWSPAPER SELLER,ASK:KINZA,BUY TICKET(100Y),WALK TO METRO.

(IT'S NOT HARD TO GET TICKET SO I WILL SAY FROM NOW ON BUY TICKET)

METRO
°°°°°
INSERT TICKET(KINZA).

(SAME HERE I WILL JUST SAY WALK TO SQUARE(KINZA) FOR EXAMPLE)

KINZA STATION
°°°°°°°°°°°°°
EXAMINE POSTER,WALK TO SQUARE.

SQUARE
°°°°°°
TALK TO DINO FAGIOLI,WALK TO RESTAURANT(PARK).

RESTAURANT
°°°°°°°°°°
EXAMINE SIGN,TALK TO COOK,ASK:COMPETITION,SHOW GREEN BILL,WALK TO PARK
BENCH,SHOW ORANGE BILL,PICKUP COMIC,WALK TO SQUARE 2.

SQUARE 2
°°°°°°°°
BARTER THE COMIC(NEWSPAPER SELLER),GOT 100Y,PASSWORD QUESTION ASKED,THE
ANSWER IS ALWAYS 1732461,BUY TICKET(SUBU),WALK TO PACHINKO(SUBU).

PACHINKO
°°°°°°°°
EXAMINE SLOT,PLAY THE BALL,MOVE THE BALL(MAGNET),PUT BALLS IN BIG POT,COUNT
THE BALLS,EXCHANGE BALLS FOR CIGARS,WALK TO RESTAURANT(PARK).

RESTAURANT
°°°°°°°°°°
TALK TO COOK,ASK:COMPETITION,GOT VOUCHER,WALK TO SQUARE(KINZA).

SQUARE
°°°°°°
TALK TO DINO FAGIOLI,GOT TICKET,WALK TO SQUARE 1.

SQUARE 1
°°°°°°°°
OFFER TICKET.

OUTSIDE MONASTARY
°°°°°°°°°°°°°°°°°
TALK TO INTERCOM,ANSWER:ENTER ORDER,WALK TO LANE.

LANE
°°°°
OPEN MAILBOX,PICKUP PARCEL,EXAMINE PARCEL,WALK TO DOUG'S HOUSE.

DOUG'S HOUSE
°°°°°°°°°°°°
APPROACHED BY DONNA,WALK TO HOT SUSHI.

HOT SUSHI
°°°°°°°°°
TALK TO MAX & KOS,ASK:UNDER PRISON,WALK TO SQUARE 3.

SQUARE 3
°°°°°°°°
BARTER THE POT,GOT WRENCH,WALK TO SUBU STATION.

SUBU STATION
°°°°°°°°°°°°
AFTER GETTING OFF TRAIN WALK RIGHT TO TUNNEL,WALK RIGHT TO HATCH,OPEN
HATCH(WRENCH),WALK TO HATCH.

SEWERS
°°°°°°
PICKUP PICKAXE,WALK TO UNDER PRISON,MAKE A HOLE(PICKAXE),PUT THE PLASTIC
INTO THE HOLE(PARCEL),USE REMOTE CONTROL,GOT KEY,WALK TO DOUG'S HOUSE.

DOUG'S HOUSE
°°°°°°°°°°°°
APPROACHED BY DONNA,GOT LETTER OF INTRODUCTION,WALK TO OUTSIDE MONASTARY.

OUTSIDE MONASTARY
°°°°°°°°°°°°°°°°°
TALK TO INTERCOM,SAY:LETTER,WALK TO LIFT.

GARDEN OF GENTLE SLEEP
°°°°°°°°°°°°°°°°°°°°°°
PICKUP LEAF(STICK),REPEAT SIX TIMES(AS THERE ARE ONLY SIX LEAVES),WALK TO
MONASTARY.

ELDER
°°°°°
ASKS YOU QUESTIONS,ANSERS ARE:

1:SEVEN THOUSAND MILLION YEARS.
2:THE RED SAMURAI.
3:NO,LESS.

CELL 1
°°°°°°
PICKUP RICE,PICKUP MAT,WALK TO CELL 2,PICKUP SHEET,WALK TO CELL 3,PICKUP
POISON,WALK TO KITCHEN,PICKUP KNIFE,WALK TO COURTYARD.

COURTYARD
°°°°°°°°°
CUT THE ROPE(KNIFE),USE SHEET ON ROPE,POISON THE FISHES(POISON),PICKUP
FISHES,WALK TO KITCHEN,MAKE THE FISH GLUE,USE GLUE ON MAT,WALK TO GARDEN.

GARDEN OF GENTLE SLEEP
°°°°°°°°°°°°°°°°°°°°°°
DROP THE MAT,DROP THE BOWL(RICE),(WAIT UNTIL BIRDS LAND ON MAT),CATCH THE
BIRDS(SACK),(DO THIS FOR BOTH BIRDS),WALK TO BUDDHA HALL.

BUDDHA HALL
°°°°°°°°°°°
LIFT THE BUDDHA,PICK UP JADE BUDDHA,WALK TO COURTYARD,WALK UP BOTH RAMPS,
WALK PAST THE DOOR OF THE HUT AND DOUG WILL JUMP OFF.

                 -----------------------------------------

DONNA FATALE (SEXY)
°°°°°°°°°°°°°°°°°°°
OUSIDE PRISON
°°°°°°°°°°°°°
WALK LEFT TO FAST FOOD,PICKUP MUSTARD,WALK TO HIGHWAY 4,PICKUP SIGN,WALK TO
HIGHWAY 1,ASK FOR A LIFT(SIGN).

HIGHWAY
°°°°°°°
WALK TO LANE,PICKUP BOWL,WALK TO HOT SUSHI.

HOT SUSHI
°°°°°°°°°
TALK TO WEIRD GUY,TALK TO MAX & KOS,SAY:YOU'RE SWEET,GOT 500Y,WALK TO
OUTSIDE RESIDENCE.

OUTSIDE RESIDENCE
°°°°°°°°°°°°°°°°°
EXAMINE SIGN,TALK TO INTERCOM,ASK:STAFF,WALK TO HOT DOG(PARK).

HOT DOG
°°°°°°°
TALK TO HOT DOG VENDOR,ASK:TWO WITHOUT MUSTARD,BUY HOTDOGS(500Y),GOT 50Y,USE
MUSTARD ON HOTDOGS,WALK TO FOUNTAIN,PICKUP SAW ON WAY,FILL BOWL,WALK TO HOT
SUSHI,DELIVER HOTDOGS,GOT 50Y,WALK TO SQUARE 2.

SQUARE 2
°°°°°°°°
TALK TO GEISHA,ASK:TEA HOUSE,BUY TICKET(KINZA),WALK TO KINZA SQUARE.

KINZA SQUARE
°°°°°°°°°°°°
TALK TO GEISHA,ASK:HOW MUCH,EXAMINE POSTER,TALK TO DINO FAGIOLI,WALK TO
STORES.

STORES
°°°°°°
CHANGE THE PERFUME(BOWL),GOT 100Y + 100Y,WALK TO SQUARE 2.

SQUARE 2
°°°°°°°°
PICKUP MAGAZINE,READ THE MAGAZINE,BUY TICKET(TOZAIKU),WALK TO ETERNAL
REST(TOZAIKU).

ETERNAL REST
°°°°°°°°°°°°
TALK TO DOOR-KEEPER,ASK:LEAVE MESSAGE,EXAMINE PIGEON-HOLES,PHONE TO THE
HOTEL(PEN),SAY:STEALING YOU MOPED,WALK TO LIFT,KNOCK,(HAVE A GOOD LAUGH HERE
AT THE SOUNDS),WALK TO KINZA SQUARE.

KINZA SQUARE
°°°°°°°°°°°°
TALK TO DINO FAGIOLI,GOT WINNINGS,SUSCRIBE TO THE COURSE(WINNINGS),WALK TO
OUTSIDE RESIDENCE,TALK TO INTERCOM,SAY:DIPLOMA.

RESIDENCE
°°°°°°°°°
GOT KEY,WALK TO HALL,OPEN CABINET,EXAMINE SAFE,KNOCK,WALK TO MUSEUM,SAW THE
HAND(SAW),GOT HAND,WALK TO OUTSIDE RESIDENCE,OPEN RESIDENCE(KEY),WALK TO
HALL,OPEN SAFE(HAND),PICKUP AUTOGRAPH,READ THE AUTOGRAPH,WALK TO RESIDENCE,
TALK TO SECRETARY,WALK TO DOUG'S HOUSE,APPROACHED BY DOUG NUTS,WALK TO
SQUARE 2.

SQUARE 2
°°°°°°°°
PICKUP POSTER,PASSWORD QUESTION ASKED,ANSWER IS ALWAYS 1622,EXAMINE POSTER,
WALK TO STREET,EXAMINE SIGN,WALK TO SQUARE 2,BUY TICKET(SUBU),WALK TO LUCKY
LOOK(SUBU).

LUCKY LOOK
°°°°°°°°°°
TALK TO FIGARO THE BEAUTICIAN,WALK TO HALL(RESIDENCE),KNOCK,WALK TO DOUG'S
HOUSE.

DOUG'S HOUSE
°°°°°°°°°°°°
OPEN LARDER(RIGHT),EXAMINE COMPUTER,PICKUP CD-ROM,WALK TO STORES,CHANGE
CD-ROM,GOT SUSY'S CD,WALK TO TV TOWER(KINZA),INSERT THE COMPACT-DISC,WALK TO
HALL(RESIDENCE),SING.

EMPEROR'S ROOM
°°°°°°°°°°°°°°
OPEN RIGHT WARDOBE,PICKUP DOLL,OPEN LEFT WARDOBE,PICKUP BOTTLE,USE BOTTLE ON
DOLL,WALK TO WINDOW IN HALL,WALK TO DOUG'S HOUSE,APPROACHED BY DOUG,GOT
KEY(SHAPED LIKE A BOX),WALK TO RESIDENCE,USE KEY(BOX) ON PAINTING,PICKUP
KATANA,WALK TO EXIT.

                 ---------------------------------------


DINO FAGIOLI (SUCKER)
°°°°°°°°°°°°°°°°°°°°°
MUSEUM
°°°°°°
PICKUP FIRE EXTINGUISHER,PICKUP PANEL,PUSH BUTTONS SO THEY END UP LIKE THIS:

       RED  GREEN

       RED  RED

WALK TO CAVEAU.

CAVEAU
°°°°°°
PICKUP CASES,PICKUP ZOOP SOUP,PICKUP BOBO,PICKUP GIOCONDA,PICK THERMOMETER,
USE BOBO ON ZOOP SOUP,EAT THE BEANS,BREAK THE KUBO,PICKUP LIGHTER,USE
THERMOMETER ON LIGHTER,USE LIT LIGTER ON GIOCONDA,USE BURNING GIOCONDA ON
FIRE DETECTOR.

MUSEUM
°°°°°°
PICKUP SARCOPHAGI AND PLACE THEM IN THIS ORDER FROM LEFT TO RIGHT:

FANFANOPHREN THE THEBAN
HANDREOPTIS VI OF EGYPT
REGINA RAPHAELLA KARRAS
TUTANKRAXIS IL MAGNIFICO
CHEOPIPPO BAUDESES III

SQUARE 1
°°°°°°°°
APPROACHED BY SHADY TYPE,WALK TO HIGHWAY,WALK TO SQUARE 1,TALK TO TAXI
DRIVER,WALK TO HIGHWAY,WALK TO SQUARE 1,EXAMINE BILL DISPENSER(UNTIL YOU'VE
GOT ALL SIX BILLS),READ BILLS,WALK TO SQUARE 3.

SQUARE 3
°°°°°°°°
BARTER LIGHTER(HONEST CHAN'S),WALK TO RESTAURANT(PARK).

RESTAURANT
°°°°°°°°°°
SHOW GREEN BILL,WALK TO FOUNTAIN 1,EXAMINE FOUNTAIN,PICKUP COIN,GOT
100Y,WALK TO SQUARE 2,BUY TICKET(KINZA),WALK TO TV TOWER(KINZA).

TV TOWER
°°°°°°°°
OPEN DOOR(WRENCH),WALK TO ROOF,TALK TO SUICIDE,PICKUP HAT,PICKUP PARCEL,WALK
TO SQUARE(KINZA),TALKS TO DONNA,WALK TO SUMO ARENA,TALK TO SUMO MAN,WALK TO
SQUARE 2.

SQUARE 2.
°°°°°°°°°
BEG FOR ALMS(USE HAT ON MAN IN LIGHT GREY SUIT),GOT 100Y,PASSWORD QUESTION
ASKED,ANSWER IS ALWAYS 179,BUY TOICKET(SUBU),WALK TO SENTO BATHS
ENTRY(SUBU).

SENTO BATHS ENTRY
°°°°°°°°°°°°°°°°°
HIT THE GONG,WALK TO SENTO BATHS,TALK TO MR Y.,WALK TO SUMO ARENA(KINZA).

SUMO ARENA
°°°°°°°°°°
TALK TO SUMO MAN,ANY ANSWER WILL DO,WALK TO SQUARE,APPROACHED BY DOUG NUTS,
WALK TO SUMO ARENA,PICKUP TICKET,WALK TO SQUARE,APPROACHED BY DOUG NUTS,
GOT VOUCHER,WALK TO RESTAURANT(PARK),WALK TO SUMO ARENA,APPROACHED BY DONNA,
APPROACHED BY SECRET AGENT,WALK TO SQUARE 2.

SQUARE 2
°°°°°°°°
PICKUP NEWSPAPER,READ NEWSPAPER,WALK TO SQUARE 1,TALK TO INTERCOM,
ASK:VOLOUNTEERS,WALK TO RECEPTION.

RECEPTION
°°°°°°°°°
ASKED IQ TEST 1,ANSWERS ARE:

1:DINO FAGIOLI
2:EHM .. I DON'T KNOW. I WASN'T VERY GOOD AT GEOGRAPHY AT KINTERGARDEN ...
3:UHM ... I HAVE NO IDEA. I DON'T KNOW MR NAPOLEON ...
4:UHM ... I DON'T KNOW. MY CALENDER HAS STOPPED ...
5:UHM ... IT DEPENDS ON THE WEIGHING SCALES ...
6:ANSWERED AUTOMATICALLY.

ASKED IQ TEST 2,ANSWER ARE:

1:ONE OVER FOUR PI Y 0 BY Q1 Q2 OVER R SQUARED.
2:THER ARE NINE.
3:IN THE YEAR 1492.(MUST BE THE THIRD ANSWER FROM THE TOP)
4:FOUR THIRDS OF P R CUBE.
5:ANSWERED AUTOMATICALLY.

COMPUTER ROOM
°°°°°°°°°°°°°
OPEN FLOPPY DISK CONTAINER(REPEAT FOUR TIMES),PICKUP FLOPPY DISK(REPEAT
THREE TIMES),TILL YOU'VE GOT TWELVE FLOPPY DISKS,EXAMINE DISKS,INSERT ALL
EIGHT STIMUL DISKS INTO COMPUTER(YOU'VE GOT TO DO THIS BECAUSE LATER YOU
WON'T GET AN OBJECT BACK),PICKUP CABLE,PICKUP PANEL,CONNECT THE CABLE,INSERT
BLUE DISK(CPL),WALK TO RECEPTION.

RECEPTION
°°°°°°°°°
PICKUP FLOWER POT,OPEN BOTTOM DRAWER,PICKUP BAG,OPEN THE SACK(BAG),WALK TO
CHAIR ROOM.

CHAIR ROOM
°°°°°°°°°°
FILL THE POT(FLOWER POT),PICKUP GRID,PUSH THE SWITCH(ABOVE THE DOOR),WALK TO
REDUCER,WALK TO LAB.

LAB
°°°
SEED THE BEANS,WATER THE BEANS,PICKUP SUPERBEAN,EAT THE SUPERBEAN,OPEN DOOR,
WALK TO CHAIR ROOM.

CHAIR ROOM
°°°°°°°°°°
PUSH THE SWITCH(BY ROBOT),HIT THE ROBOT,PICKUP MAGNET,WALK TO RECEPTION,WALK
TO EXIT.


                       --------------------------------

FINAL PART
°°°°°°°°°°
I WON'T TELL YOU IT WILL ONLY SPOIL IT !!!!


                       --------------------------------


END NOTE
°°°°°°°°
TRY AND PLAY THIS GAME WITHOUT USING THIS SOLUTION UNLESS YOU GET COMPLETELY
BAFFLED,I KNOW I DID A COUPLE OF TIMES (THANKS TO MY WIFE LOU WHO SAID WHY
DON'T YOU TRY THIS YOU SILLY SOD !!!!)

   THANKS TO ASTROPATH FOR GIVING ME THIS BRILLIANT GAME TO PLAY.


                                 SIGNING OFF

                                    T.H.I.


