;Bomber_6+IMP_ver2
;Czyli marihuana+C2H5OH
;autor Grzegorz Przybylski


dl=423
	
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	DAT #1
	
start	SPL 6
	MOV 3 	@2
  ADD #dl 1
	JMP -2	#1
	DAT 1
	DAT 1	
	SPL 6
	MOV 3 	@2
	ADD #-dl 1
	JMP -2	#-3
	DAT 1
	DAT 1
	SPL 6
	MOV 3 	@2
	ADD #dl	1
	JMP -2	#2
	DAT 1
	DAT 1
	SPL 6
	MOV 3 	@2
	ADD #-dl 1
	JMP -2	#-4
	DAT 1
	DAT 1 
	SPL 6
	MOV 3 	@2
	ADD #dl	1
	JMP -2	#3
	DAT 1
	DAT 1
	SPL 6
	MOV 3 	@2
	ADD #-dl 1
	JMP -2	#-5
	DAT 1
	DAT 1
	SPL 6
	MOV 3 	@2
	ADD #dl	1
	JMP -2	#7
	DAT 1
	DAT 1
	SPL 6
	MOV 3 	@2
	ADD #-dl 1
	JMP -2	#-9
	DAT 1
	DAT 1
	SPL 6
	MOV 3 	@2
	ADD #dl	1
	JMP -2	#8
	DAT 1
	DAT 1
	SPL 6
	MOV 3 	@2
	ADD #-dl 1
	JMP -2	#-10
	DAT 1
	DAT 1
	SPL 6
	MOV 3 	@2
	ADD #dl	1
	JMP -2	#9
	DAT 1
	DAT 1
	SPL 6
	MOV 3 	@2
	ADD #-dl 1
	JMP -2	#-11
	DAT 1
	DAT 1
	SPL 6
	MOV 3 	@2
	ADD #dl	1
	JMP -2	#13
	DAT 1
	DAT 1
	SPL 6
	MOV 3 	@2
	ADD #-dl 1
	JMP -2	#-15
	DAT 1
	DAT 1
	SPL 6
	MOV 3 	@2
	ADD #dl	1
	JMP -2	#1
	DAT 1
	DAT 1	
	SPL 6
	MOV 3 	@2
	ADD #-dl 1
	JMP -2	#-3
	DAT 1
	DAT 1
	SPL 6
	MOV 3 	@2
	ADD #dl	1
	JMP -2	#2
	DAT 1
	DAT 1
	SPL 6
	MOV 3 	@2
	ADD #-dl 1
	JMP -2	#-4
	DAT 1
	DAT 1 
	SPL 6
	MOV 3 	@2
	ADD #dl	1
	JMP -2	#3
	DAT 1
	DAT 1
	SPL 6
	MOV 3 	@2
	ADD #-dl 1
	JMP -2	#-5
	DAT 1
	DAT 1
	SPL 6
	MOV 3 	@2
	ADD #dl	1
	JMP -2	#7
	DAT 1
	DAT 1
	SPL 6
	MOV 3 	@2
	ADD #-dl 1
	JMP -2	#-9
	DAT 1
	DAT 1
	SPL 6
	MOV 3 	@2
	ADD #dl	1
	JMP -2	#8
	DAT 1
	DAT 1
	SPL 6
	MOV 3 	@2
	ADD #-dl 1
	JMP -2	#-10
	DAT 1
	DAT 1
	SPL 6
	MOV 3 	@2
	ADD #dl	1
	JMP -2	#9
	DAT 1
	DAT 1
	SPL 6
	MOV 3 	@2
	ADD #-dl 1
	JMP -2	#-11
	DAT 1
	DAT 1
	SPL 6
	MOV 3 	@2
	ADD #dl	1
	JMP -2	#13
	DAT 1
	DAT 1
	SPL 6
	MOV 3 	@2
	ADD #-dl 1
	JMP -2	#-15
	DAT 1
	DAT 1
	SPL 6
	MOV 3 	@2
	ADD #dl	1
	JMP -2	#1
	DAT 1
	DAT 1	
	SPL 6
	MOV 3 	@2
	ADD #-dl 1
	JMP -2	#-3
	DAT 1
	DAT 1
	SPL 6
	MOV 3 	@2
	ADD #dl	1
	JMP -2	#2
	DAT 1
	DAT 1
	SPL 6
	MOV 3 	@2
	ADD #-dl 1
	JMP -2	#-4
	DAT 1
	DAT 1 
	SPL 6
	MOV 3 	@2
	ADD #dl	1
	JMP -2	#3
	DAT 1
	DAT 1
	SPL 6
	MOV 3 	@2
	ADD #-dl 1
	JMP -2	#-5
	DAT 1
	DAT 1
	SPL 6
	MOV 3 	@2
	ADD #dl	1
	JMP -2	#7
	DAT 1
	DAT 1
	SPL 6
	MOV 3 	@2
	ADD #-dl 1
	JMP -2	#-9
	DAT 1
	DAT 1
	SPL 6
	MOV 3 	@2
	ADD #dl	1
	JMP -2	#8
	DAT 1
	DAT 1
	SPL 6
	MOV 3 	@2
	ADD #-dl 1
	JMP -2	#-10
	DAT 1
	DAT 1
	SPL 6
	MOV 3 	@2
	ADD #dl	1
	JMP -2	#9
	DAT 1
	DAT 1
	SPL 6
	MOV 3 	@2
	ADD #-dl 1
	JMP -2	#-11
	DAT 1
	DAT 1
	SPL 6
	MOV 3 	@2
	ADD #dl	1
	JMP -2	#13
	DAT 1
	DAT 1
	SPL 6
	MOV 3 	@2
	ADD #-dl 1
	JMP -2	#-15
	DAT 1
	DAT 1
	SPL 6
	MOV 3 	@2
	ADD #dl	1
	JMP -2	#1
	DAT 1
	DAT 1	
	SPL 6
	MOV 3 	@2
	ADD #-dl 1
	JMP -2	#-3
	DAT 1
	DAT 1
	SPL 6
	MOV 3 	@2
	ADD #dl	1
	JMP -2	#2
	DAT 1
	DAT 1
	SPL 6
	MOV 3 	@2
	ADD #-dl 1
	JMP -2	#-4
	DAT 1
	DAT 1 
	SPL 6
	MOV 3 	@2
	ADD #dl	1
	JMP -2	#3
	DAT 1
	DAT 1
	SPL 6
	MOV 3 	@2
	ADD #-dl 1
	JMP -2	#-5
	DAT 1
	DAT 1
	SPL 6
	MOV 3 	@2
	ADD #dl	1
	JMP -2	#7
	DAT 1
	DAT 1
	SPL 6
	MOV 3 	@2
	ADD #-dl 1
	JMP -2	#-9
	DAT 1
	DAT 1
	SPL 6
	MOV 3 	@2
	ADD #dl	1
	JMP -2	#8
	DAT 1
	DAT 1
	SPL 6
	MOV 3 	@2
	ADD #-dl 1
	JMP -2	#-10
	DAT 1
	DAT 1
	SPL 6
	MOV 3 	@2
	ADD #dl	1
	JMP -2	#9
	DAT 1
	DAT 1
	SPL 6
	MOV 3 	@2
	ADD #-dl 1
	JMP -2	#-11
	DAT 1
	DAT 1
	SPL 6
	MOV 3 	@2
	ADD #dl	1
	JMP -2	#13
	DAT 1
	DAT 1
	SPL 6
	MOV 3 	@2
	ADD #-dl 1
	JMP -2	#-15
	DAT 1
	DAT 1
  SPL 6
	MOV 3 	@2
	ADD #dl	1
	JMP -2	#1
	DAT 1
	DAT 1	
	SPL 6
	MOV 3 	@2
	ADD #-dl 1
	JMP -2	#-3
	DAT 1
	DAT 1
	SPL 6
	MOV 3 	@2
	ADD #dl	1
	JMP -2	#2
	DAT 1
	DAT 1
	SPL 6
	MOV 3 	@2
	ADD #-dl 1
	JMP -2	#-4
	DAT 1
	DAT 1 
	SPL 6
	MOV 3 	@2
	ADD #dl	1
	JMP -2	#3
	DAT 1
	DAT 1
	SPL 6
	MOV 3 	@2
	ADD #-dl 1
	JMP -2	#-5
	DAT 1
	DAT 1
	SPL 6
	SPL 5	<1
	DJN -1  -500
	JMP -2  <-1
	DAT 1
	DAT 1
	MOV 0 1
	MOV 0 1
	MOV 0 1
