; Aleksander Dudek IVc
; wersja poprawiona przez Dominika Kozaczko.
; poprzednia nie kompilowala sie na skutek bledow w kompilatorze.

step equ 2667
inc  equ 25

start  spl koniec
       djn 0, #2
       spl 9
       mov 5, <1
       add #-inc,#-50+start
       jmp -2
       dat 1
       dat 1
       dat 1
       dat 1
       dat 1
       spl 9
       mov 5, <1
       add #-inc,#-48+start
       jmp -2
       dat 1
       dat 1
       dat 1
       dat 1
       dat 1
       spl 9
       mov 5, <1
       add #-inc,#-46+start
       jmp -2
       dat 1
       dat 1
       dat 1
       dat 1
       dat 1
       spl 9
       mov 5, <1
       add #-inc,#-44+start
       jmp -2
       dat 1
       dat 1
       dat 1
       dat 1
       dat 1
       spl 9
       mov 5, <1
       add #-inc,#-42+start
       jmp -2
       dat 1
       dat 1
       dat 1
       dat 1
       dat 1
       spl 9
       mov 5, <1
       add #-inc,#-40+start
       jmp -2
       dat 1
       dat 1
       dat 1
       dat 1
       dat 1
       spl 9
       mov 5, <1
       add #-inc,#-38+start
       jmp -2
       dat 1
       dat 1
       dat 1
       dat 1
       dat 1
       spl 9
       mov 5, <1
       add #-inc,#-36+start
       jmp -2
       dat 1
       dat 1
       dat 1
       dat 1
       dat 1
       spl 9
       mov 5, <1
       add #-inc,#-34+start
       jmp -2
       dat 1
       dat 1
       dat 1
       dat 1
       dat 1
       spl 9
       mov 5, <1
       add #-inc,#-32+start
       jmp -2
       dat 1
       dat 1
       dat 1
       dat 1
       dat 1
       spl 9
       mov 5, <1
       add #-inc,#-30+start
       jmp -2
       dat 1
       dat 1
       dat 1
       dat 1
       dat 1
       spl 9
       mov 5, <1
       add #-inc,#-28+start
       jmp -2
       dat 1
       dat 1
       dat 1
       dat 1
       dat 1
       spl 9
       mov 5, <1
       add #-inc,#-26+start
       jmp -2
       dat 1
       dat 1
       dat 1
       dat 1
       dat 1
       spl 9
       mov 5, <1
       add #-inc,#-24+start
       jmp -2
       dat 1
       dat 1
       dat 1
       dat 1
       dat 1
       spl 9
       mov 5, <1
       add #-inc,#-22+start
       jmp -2
       dat 1
       dat 1
       dat 1
       dat 1
       dat 1
       spl 9
       mov 5, <1
       add #-inc,#-20+start
       jmp -2
       dat 1
       dat 1
       dat 1
       dat 1
       dat 1
       spl 9
       mov 5, <1
       add #-inc,#-18+start
       jmp -2
       dat 1
       dat 1
       dat 1
       dat 1
       dat 1
       spl 9
       mov 5, <1
       add #-inc,#-16+start
       jmp -2
       dat 1
       dat 1
       dat 1
       dat 1
       dat 1
       spl 9
       mov 5, <1
       add #-inc,#-14+start
       jmp -2
       dat 1
       dat 1
       dat 1
       dat 1
       dat 1
       spl 9
       mov 5, <1
       add #-inc,#-12+start
       jmp -2
       dat 1
       dat 1
       dat 1
       dat 1
       dat 1
       spl 9
       mov 5, <1
       add #-inc,#-10+start
       jmp -2
       dat 1
       dat 1
       dat 1
       dat 1
       dat 1
       spl 9
       mov 5, <1
       add #-inc,#-8+start
       jmp -2
       dat 1
       dat 1
       dat 1
       dat 1
       dat 1
       spl 9
       mov 5, <1
       add #-inc,#-6+start
       jmp -2
       dat 1
       dat 1
       dat 1
       dat 1
       dat 1
       spl 9
       mov 5, <1
       add #-inc,#-4+start
       jmp -2
       dat 1
       dat 1
       dat 1
       dat 1
       dat 1
       spl 9
       mov 5, <1
       add #-inc,#-2+start
       jmp -2
       dat 1
       dat 1
       dat 1
       dat 1
       dat 1

       spl 9
       mov 5, <1
       add #inc,#50+koniec
       jmp -2
       dat 1
       dat 1
       dat 1
       dat 1
       dat 1
       spl 9
       mov 5, <1
       add #inc,#48+koniec
       jmp -2
       dat 1
       dat 1
       dat 1
       dat 1
       dat 1
       spl 9
       mov 5, <1
       add #inc,#46+koniec
       jmp -2
       dat 1
       dat 1
       dat 1
       dat 1
       dat 1
       spl 9
       mov 5, <1
       add #inc,#44+koniec
       jmp -2
       dat 1
       dat 1
       dat 1
       dat 1
       dat 1
       spl 9
       mov 5, <1
       add #inc,#42+koniec
       jmp -2
       dat 1
       dat 1
       dat 1
       dat 1
       dat 1
       spl 9
       mov 5, <1
       add #inc,#40+koniec
       jmp -2
       dat 1
       dat 1
       dat 1
       dat 1
       dat 1
       spl 9
       mov 5, <1
       add #inc,#38+koniec
       jmp -2
       dat 1
       dat 1
       dat 1
       dat 1
       dat 1
       spl 9
       mov 5, <1
       add #inc,#36+koniec
       jmp -2
       dat 1
       dat 1
       dat 1
       dat 1
       dat 1
       spl 9
       mov 5, <1
       add #inc,#34+koniec
       jmp -2
       dat 1
       dat 1
       dat 1
       dat 1
       dat 1
       spl 9
       mov 5, <1
       add #inc,#32+koniec
       jmp -2
       dat 1
       dat 1
       dat 1
       dat 1
       dat 1
       spl 9
       mov 5, <1
       add #inc,#30+koniec
       jmp -2
       dat 1
       dat 1
       dat 1
       dat 1
       dat 1
       spl 9
       mov 5, <1
       add #inc,#28+koniec
       jmp -2
       dat 1
       dat 1
       dat 1
       dat 1
       dat 1
       spl 9
       mov 5, <1
       add #inc,#26+koniec
       jmp -2
       dat 1
       dat 1
       dat 1
       dat 1
       dat 1
       spl 9
       mov 5, <1
       add #inc,#24+koniec
       jmp -2
       dat 1
       dat 1
       dat 1
       dat 1
       dat 1
       spl 9
       mov 5, <1
       add #inc,#22+koniec
       jmp -2
       dat 1
       dat 1
       dat 1
       dat 1
       dat 1
       spl 9
       mov 5, <1
       add #inc,#20+koniec
       jmp -2
       dat 1
       dat 1
       dat 1
       dat 1
       dat 1
       spl 9
       mov 5, <1
       add #inc,#18+koniec
       jmp -2
       dat 1
       dat 1
       dat 1
       dat 1
       dat 1
       spl 9
       mov 5, <1
       add #inc,#16+koniec
       jmp -2
       dat 1
       dat 1
       dat 1
       dat 1
       dat 1
       spl 9
       mov 5, <1
       add #inc,#14+koniec
       jmp -2
       dat 1
       dat 1
       dat 1
       dat 1
       dat 1
       spl 9
       mov 5, <1
       add #inc,#12+koniec
       jmp -2
       dat 1
       dat 1
       dat 1
       dat 1
       dat 1
       spl 9
       mov 5, <1
       add #inc,#10+koniec
       jmp -2
       dat 1
       dat 1
       dat 1
       dat 1
       dat 1
       spl 9
       mov 5, <1
       add #inc,#8+koniec
       jmp -2
       dat 1
       dat 1
       dat 1
       dat 1
       dat 1
       spl 9
       mov 5, <1
       add #inc,#6+koniec
       jmp -2
       dat 1
       dat 1
       dat 1
       dat 1
       dat 1
       spl 9
       mov 5, <1
       add #inc,#4+koniec
       jmp -2
       dat 1
       dat 1
       dat 1
       dat 1
       dat 1
       mov 5, <1
       add #inc,#2+koniec
       jmp -2
       dat 1
       dat 1
       dat 1
       dat 1
       dat 1

koniec  SPL 16
        SPL 8
        SPL 4
        SPL 2
        JMP step*7+imp
        JMP step*4+imp
        SPL 2
        JMP step*5+imp
        JMP imp+step
        SPL 4
        SPL 2
        JMP step*6+imp
        JMP step*2+imp
        SPL 2
        JMP step*3+imp
        JMP imp
        SPL 8
        SPL 4
        SPL 2
        JMP step*7+imp
        JMP step*4+imp
        SPL 2
        JMP step*5+imp
        JMP imp+step
        SPL 4
        SPL 2
        JMP step*6+imp
        JMP step*2+imp
        SPL 2
        JMP step*3+imp
        JMP imp
imp     MOV 0,step
