;IZI14_1;
;Krzysztof Izdebski;
;Rapackiego 17b/4;
;59-400 Jawor;


      dat 0
      dat 20
      mov -2  <1
start mov <-2  500
      djn -2  #11
      spl @-2
      add #510  -3
      add #11  -6
      add #11  -4
      djn -6  #3
      add #-5  1
      cmp #0  2
      mov -12  @-1
      add #5  1
      cmp #0  3
      mov -15  @-1
      djn -6  #94
      add #-470  -6
      add #-470  -4
      add #94  -3
      jmp -10
