;IZI 8.3;
;Krzysztof Izdebski;
;Rapackiego 17b/4;
;59-400 Jawor;


      dat 19
      add #-1    1
start mov <-2    500
      djn -2     #10
      spl @-2
      add #509   -3
      add #10    -6
      add #10    -4
      djn -7     #3
      add #-5    1
      mov 9      2
      add #5     1
      mov 6      4
      djn -4     #94
      add #470   -4
      add #-470  -3
      add #94    -3
      jmp -8
      dat 0

