;IZI 8bis;
;Krzysztof Izdebski;
;Rapackiego 17b/4;
;59-400 Jawor;



      dat 21
      add #-1    1
start mov <-2    500
      djn -2     #12
      spl @-2
      add #511   -3
      add #12    -6
      add #12    -4
      djn -7     #16
      add #-5    1
      cmp #0     2
      mov 9      @-1
      add #5     1
      cmp #0     4
      mov 6      @-1
      djn -6     #94
      add #470   -6
      add #-470  -4
      add #94    -3
      jmp -10
      dat 0

