;Yoda
;Mirek Kaim,
.WA91
start:	spl 7 -1
	mov #0 <-1
	jmp -1
	dat 0
	dat 0
	dat 0
	dat 0
	spl 7 -24
	mov #0 <-1
	jmp -1
	dat 0
	dat 0
	dat 0
	dat 0
	spl 7 -47
	mov #0 <-1
	jmp -1
	dat 0
	dat 0
	dat 0
	dat 0
	spl 7 -70
	mov #0 <-1
	jmp -1
	dat 0
	dat 0
	dat 0
	dat 0
	spl 7 -103
	mov #0 <-1
	jmp -1
	dat 0
	dat 0
	dat 0
	dat 0
	spl 7 -126
	mov #0 <-1
	jmp -1
	dat 0
	dat 0
	dat 0
	dat 0
	spl 7 -149
	mov #0 <-1
	jmp -1
	dat 0
	dat 0
	dat 0
	dat 0
	spl 7 -172
	mov #0 <-1
	jmp -1
	dat 0
	dat 0
	dat 0
	dat 0
	spl 7 -195
	mov #0 <-1
	jmp -1
	dat 0
	dat 0
	dat 0
	dat 0
	spl 7 -218
	mov #0 <-1
	jmp -1
	dat 0
	dat 0
	dat 0
	dat 0
	spl 7 -241
	mov #0 <-1
	jmp -1
	dat 0
	dat 0
	dat 0
	dat 0
	spl 7 -264
	mov #0 <-1
	jmp -1
	dat 0
	dat 0
	dat 0
	dat 0
	spl 7 -287
	mov #0 <-1
	jmp -1
	dat 0
	dat 0
	dat 0
	dat 0
	spl 7 -310
	mov #0 <-1
	jmp -1
	dat 0
	dat 0
	dat 0
	dat 0
	spl 7 -333
	mov #0 <-1
	jmp -1
	dat 0
	dat 0
	dat 0
	dat 0
	spl 7 -356
	mov #0 <-1
	jmp -1
	dat 0
	dat 0
	dat 0
	dat 0
	spl 7 -379
	mov #0 <-1
	jmp -1
	dat 0
	dat 0
	dat 0
	dat 0
	spl 7 -402
	mov #0 <-1
	jmp -1
	dat 0
	dat 0
	dat 0
	dat 0
	spl 7 -425
	mov #0 <-1
	jmp -1
	dat 0
	dat 0
	dat 0
	dat 0
	spl 7 -448
	mov #0 <-1
	jmp -1
	dat 0
	dat 0
	dat 0
	dat 0
	spl 7 -471
	mov #0 <-1
	jmp -1
	dat 0
	dat 0
	dat 0
	dat 0
	spl 7 -494
	mov #0 <-1
	jmp -1
	dat 0
	dat 0
	dat 0
	dat 0
	spl 7 -517
	mov #0 <-1
	jmp -1
	dat 0
	dat 0
	dat 0
	dat 0
	spl 7 -540
	mov #0 <-1
	jmp -1
	dat 0
	dat 0
	dat 0
	dat 0
	spl 7 -563
	mov #0 <-1
	jmp -1
	dat 0
	dat 0
	dat 0
	dat 0
	spl 7 -586
	mov #0 <-1
	jmp -1
	dat 0
	dat 0
	dat 0
	dat 0
	spl 7 -609
	mov #0 <-1
	jmp -1
	dat 0
	dat 0
	dat 0
	dat 0
	spl 7 -632
	mov #0 <-1
	jmp -1
	dat 0
	dat 0
	dat 0
	dat 0
	spl 7 -655
	mov #0 <-1
	jmp -1
	dat 0
	dat 0
	dat 0
	dat 0
	spl 7 -678
	mov #0 <-1
	jmp -1
	dat 0
	dat 0
	dat 0
	dat 0
	spl 7 -701
	mov #0 <-1
	jmp -1
	dat 0
	dat 0
	dat 0
	dat 0
	spl 7 -724
	mov #0 <-1
	jmp -1
	dat 0
	dat 0
	dat 0
	dat 0
	spl 7 -747
	mov #0 <-1
	jmp -1
	dat 0
	dat 0
	dat 0
	dat 0
	spl 7 -770
	mov #0 <-1
	jmp -1
	dat 0
	dat 0
	dat 0
	dat 0
	spl 7 -793
	mov #0 <-1
	jmp -1
	dat 0
	dat 0
	dat 0
	dat 0
	spl 7 -816
	mov #0 <-1
	jmp -1
	dat 0
	dat 0
	dat 0
	dat 0
	spl 7 -839
	mov #0 <-1
	jmp -1
	dat 0
	dat 0
	dat 0
	dat 0
	spl 7 -862
	mov #0 <-1
	jmp -1
	dat 0
	dat 0
	dat 0
	dat 0
	spl 7 -885
	mov #0 <-1
	jmp -1
	dat 0
	dat 0
	dat 0
	dat 0
	spl 7 -1008
	mov #0 <-1
	jmp -1
	dat 0
	dat 0
	dat 0
	dat 0
	spl 7 -1031
	mov #0 <-1
	jmp -1
	dat 0
	dat 0
	dat 0
	dat 0
	spl 7 -1054
	mov #0 <-1
	jmp -1
	dat 0
	dat 0
	dat 0
	dat 0
	spl 7 -1077
	mov #0 <-1
	jmp -1
	dat 0
	dat 0
	dat 0
	dat 0
	spl 7 -1100
	mov #0 <-1
	jmp -1
	dat 0
	dat 0
	dat 0
	dat 0
	spl 7 -1123
	mov #0 <-1
	jmp -1
	dat 0
	dat 0
	dat 0
	dat 0
	spl 7 -1146
	mov #0 <-1
	jmp -1
	dat 0
	dat 0
	dat 0
	dat 0
	spl 7 -1169
	mov #0 <-1
	jmp -1
	dat 0
	dat 0
	dat 0
	dat 0
	spl 7 -1192
	mov #0 <-1
	jmp -1
	dat 0
	dat 0
	dat 0
	dat 0
	spl 7 -1215
	mov #0 <-1
	jmp -1
	dat 0
	dat 0
	dat 0
	dat 0
	spl 7 -1238
	mov #0 <-1
	jmp -1
	dat 0
	dat 0
	dat 0
	dat 0
	spl 7 -1261
	mov #0 <-1
	jmp -1
	dat 0
	dat 0
	dat 0
	dat 0
	spl 7 -1284
	mov #0 <-1
	jmp -1
	dat 0
	dat 0
	dat 0
	dat 0
	spl 7 -1307
	mov #0 <-1
	jmp -1
	dat 0
	dat 0
	dat 0
	dat 0
	spl 7 -1330
	mov #0 <-1
	jmp -1
	dat 0
	dat 0
	dat 0
	dat 0
	spl 7 -1353
	mov #0 <-1
	jmp -1
	dat 0
	dat 0
	dat 0
	dat 0
	spl 7 -1376
	mov #0 <-1
	jmp -1
	dat 0
	dat 0
	dat 0
	dat 0
	spl 7 -1399
	mov #0 <-1
	jmp -1
	dat 0
	dat 0
	dat 0
	dat 0
	spl 7 -1422
	mov #0 <-1
	jmp -1
	dat 0
	dat 0
	dat 0
	dat 0
	spl 7 -1445
	mov #0 <-1
	jmp -1
	dat 0
	dat 0
	dat 0
	dat 0
	spl 7 -1468
	mov #0 <-1
	jmp -1
	dat 0
	dat 0
	dat 0
	dat 0
	spl 7 -1491
	mov #0 <-1
	jmp -1
	dat 0
	dat 0
	dat 0
	dat 0
	spl 7 -1513
	mov #0 <-1
	jmp -1
	dat 0
	dat 0
	dat 0
	dat 0
	spl 7 -1536
	mov #0 <-1
	jmp -1
	dat 0
	dat 0
	dat 0
	dat 0
	mov #0 <-1
	jmp -1
	dat 0
	dat 0
	dat 0
	dat 0
	end start
