# Makefile configuration section
# Boolean values must be either 'yes' or 'no'

# OpenGL support ? Speed up a lot the game, and allow some special effect
USE_OPENGL=yes

# Link with the SDL_mixer library ? If set to no, then no music
# nor sounds will be played.
USE_SDLMIXER=yes

# If USE_SDLMIXER=yes, compile with WAV sound support ?
# (USE_SOUND=no implies USE_MUSIC=no)
USE_SOUND=yes

# If USE_SDLMIXER=yes and USE_SOUND=yes, compile with OGG music support ?
USE_MUSIC=yes

# Compile with GDB debugging extensions, or with optimizations
DEBUG_MODE=yes

# zip compression support within ACC support
ACC_ZLIB_SUPPORT=yes

# generate a static or a dynamic library ?
STATIC_LIBRARY=no

# end of the Makefile configuration section
# #########################################

export
VERSION=0_7

CC=g++ -Werror
LINK=g++
MAKE=make

SRC= KDpp/Controller/Application.cpp                   \
     KDpp/Controller/Controller.cpp                    \
     KDpp/Controller/WidgetController.cpp              \
     KDpp/Controller/Event.cpp                         \
     KDpp/Controller/EventManager.cpp                  \
     KDpp/Controller/UserInterface/Button.cpp          \
     KDpp/Controller/UserInterface/Frame.cpp           \
     KDpp/Controller/UserInterface/Mouse.cpp           \
     KDpp/Controller/UserInterface/Widget.cpp          \
     KDpp/Controller/UserInterface/CheckBox.cpp        \
     KDpp/Controller/UserInterface/Keyboard.cpp        \
     KDpp/Controller/UserInterface/StaticText.cpp      \
     KDpp/Controller/UserInterface/EditField.cpp       \
     KDpp/Controller/UserInterface/KeyboardCursor.cpp  \
     KDpp/Controller/UserInterface/WidgetContainer.cpp \
     KDpp/Math/Vector.cpp                              \
     KDpp/Resources/ArchiveManager.cpp                 \
     KDpp/Resources/GlobalResourceSet.cpp              \
     KDpp/Resources/Resource.cpp                       \
     KDpp/Resources/ResourceManager.cpp                \
     KDpp/Resources/ResourceSet.cpp                    \
     KDpp/Resources/XMLResourceParser.cpp              \
     KDpp/Sound/Music.cpp                              \
     KDpp/Sound/Sound.cpp                              \
     KDpp/Sound/SoundSystem.cpp                        \
     KDpp/Tools/XMLParser.cpp                          \
     KDpp/Tools/FilePath.cpp                           \
     KDpp/Tools/Logfile.cpp                            \
     KDpp/Tools/Textfile.cpp                           \
     KDpp/Tools/XMLConfig.cpp                          \
     KDpp/Video/Color.cpp                              \
     KDpp/Video/DisplayableInstance.cpp                \
     KDpp/Video/DisplayableResource.cpp                \
     KDpp/Video/Display.cpp                            \
     KDpp/Video/Font.cpp                               \
     KDpp/Video/Image.cpp                              \
     KDpp/Video/ImageInstance.cpp                      \
     KDpp/Video/SdlImage.cpp                           \
     KDpp/Video/Sprite.cpp                             \
     KDpp/Video/SpriteInstance.cpp                     \
     KDpp/Video/SDL_rotozoom.cpp                       \
     KDpp/Video/XMLSpriteParser.cpp                    \
     KDpp/Video/Events/DisplayableEvent.cpp            \
     KDpp/Video/Events/FountainEvent.cpp               \
     KDpp/Video/Events/MovableEvent.cpp                \
     KDpp/Video/Events/SpriteEvent.cpp                 \
     KDpp/Video/Events/TextEvent.cpp


ifeq ($(USE_OPENGL),yes)
  SRC:=$(SRC) KDpp/Video/OglImage.cpp
endif

# libraries
LIBS:=$(shell sdl-config --libs)
LIBS:=$(LIBS) -lSDL_image -lSDL_ttf

ifeq ($(USE_EFENCE),yes)
  LIBS:=$(LIBS) -lefence
endif
ifeq ($(USE_OPENGL),yes)
  LIBS:=$(LIBS) -lGL
endif
ifeq ($(USE_SDLMIXER),yes)
  LIBS:=$(LIBS) -lSDL_mixer
endif

LIBS:=$(LIBS) $(shell xml2-config --libs) 

# compiler flags
CCFLAGS:=-Wall $(shell sdl-config --cflags) $(shell xml2-config --cflags)

ifeq ($(USE_OPENGL),no)
  CCFLAGS:=$(CCFLAGS) -DNO_OPENGL
endif
ifeq ($(USE_SDLMIXER),no)
  CCFLAGS:=$(CCFLAGS) -DNO_MUSIC -DNO_SOUND
else
ifeq ($(USE_MUSIC),no)
  CCFLAGS:=$(CCFLAGS) -DNO_MUSIC
endif
ifeq ($(USE_SOUND),no)
  CCFLAGS:=$(CCFLAGS) -DNO_SOUND -DNO_MUSIC
endif
endif
ifeq ($(DEBUG_MODE),yes)
  CCFLAGS:=$(CCFLAGS) -ggdb -DDEBUG -DDEBUG_SANITY_CHECK
endif
ifeq ($(DEBUG_MODE),no)
  CCFLAGS:=$(CCFLAGS) -O2 -DNDEBUG
endif
ifeq ($(DISPLAY_FPS),yes)
  CCFLAGS:=$(CCFLAGS) -DDISPLAY_FPS
endif

ifeq ($(ACC_ZLIB_SUPPORT),yes)
  CCFLAGS:=$(CCFLAGS) -DACC_ZLIB_SUPPORT
# We also need to link against zlib but libxml2 already includes it
endif

ifeq ($(STATIC_LIBRARY),yes)
  LCFLAGS:=$(LCFLAGS) -static
else
  LCFLAGS:=$(LCFLAGS) -shared -fpic
endif

DCFLAGS=-MM

OBJ:=$(SRC:%.cpp=%.o)
DEP:=$(OBJ:%.o=dep/%.d)

LIB_NAME=libkdpp.so

all: $(LIB_NAME)

FORCE:

dep: $(DEP)

$(DEP): %.d: FORCE
	@$(MAKE) -s --no-print-directory -f Makefile.dep $@

$(LIB_NAME): $(OBJ)
	$(LINK) $(LCFLAGS) $(LIBS) -o $@ $(OBJ)

$(OBJ): %.o: dep/%.d
$(OBJ): %.o: %.cpp
	$(CC) $(CCFLAGS) -o $@ -c $<

clean:
	find -name "*.o" -exec rm {} ";"
	rm -fR dep
	rm -f log.txt

doc: FORCE
	doxygen krystal.dox

distclean: clean
	rm -fR doc/html
