11
Martial Arts - Which is which?
99
The Malay unarmed fighting art, it is based on the movements of snakes and
tigers. It is said it came to a famous prince in a dream.
The only teachers of bersailat are found in the
Malay archipelago.
273
 Tai-Chi Chuan
 Bando
 Bersilat
1
3
103
This is a deadly combination of stick-fighting and black magic. The student
learns to concentrate his gaze on a certain vital spot on his opponent's
body while feinting and whirling one or two hardwood sticks.
This is a very difficult, very arcane and very
dangerous martial art.
273
 Philippine Arnis
 Aikido
 Plum Blossom Sword
1
1
227
This is the swordmanship you see in the samurai movies.  It was the chief
armed art used by the samurai (the bushi).
Kenjitsu is an extremely complex arsenal of combat
moves - some 1,700 movements are known. It has
evolved to a more peaceful sport known as Kendo.
273
 Bando
 Ninjitsu
 Kenjitsu
1
3
231
This was originally part of the samurai's arsenal, and was intended to
be used as a complement to swordmanship.  All the forms of this taught in
the west are sport forms.
Judo is primarily a sport and a method of physical
training, it has little relation to the realities
of actual combat.
273
 Kung Fu
 Shaolin
 Jujitsu and Judo
1
3
231
This martial art is primarialy a sport and not a "true" martial art at all.
It has been made famous in hollywood movies, but it originated from
Okinawa.
It can be used for self-defense, but the main
systems taught in the United States and Japan are
sport forms.
273
 Aikido
 Kung Fu
 Karate
1
3
231
A modern method developed by M. Uyeshiba in the 1920's. He had studied
Japanese sword fighting, as well as jujitso, and created his own personal
form for his own personal physical and spiritual development.
Aikido is unusual in that there is no definite and
rigorous format.  The movements depend on what the
opponent does, and according to flow and rhythm.
273
 Phillippine Aranis
 Tai-Chi Chuan
 Aikido
1
3
255
This deadly fighting art include basic techniques which has the expert
actually climbing the attacker, "like an eagle climbing a ladder."
It has been kept in relative secrecy in Burma for many centuries, and
would probably leave practicioners of the other fighting arts gaping - and
flat on their back.
The expert rushes like a boar, strikes like a bull
weaves like a cobra. He is alert as a deer,
confident as a monkey....
273
 Shaolin
 Bando
 Plum Blossom Sword
1
2
227
This fighting art is believed to be a big hoax. It's name is actually
a generic term for excercise.
In Chinese, the martial arts are called "wu-shu."
If you tell someone you are practicing Kung-Fu,
it could mean you're doing push ups, or leg lifts.
273
 Kung Fu
 Aikido
 Bando
1
1
231
A Korean fighting art which literally means "To-smash-with-the-feet-to-
destroy-with-the-hands." There is great emphasis on building the moral
character of the student.
It is strictly a "hard" unarmed fighting art
(there is no dance version). There is even a
series of blows to be used while on horseback.
273
 Karate
 Tae Kwon Do
 Kenjitsu
1
2
97
A Chineese method of swordfighting, mainly practiced by women.
It uses two short swords and small, swift
movements.
273
 Tai-Chi Chuan
 Bersilat
 Plum Blossom Sword
1
3
227
Japanese all-round armed and unarmed combat, with elements of disguise,
woodlore, camouflage, espionage, and poison.
It is said a Ninja can hide himself completely
in an open field, or curl to look like a rock, or
wedge himself into the rafters of a room.
273
 Plum Blossom Sword
 Kenjitsu
 Ninjitsu
1
3
227
The soft and graceful movements have names like "White Stork Spreads Wings,"
"Snake Creeps Down," "Owl at the Bottom of the Sea," and "Opening the Fan."
Chinese yin-yang shadow boxing. An exercise, a
sport, a meditation, a philosophy, a deadly
fighting art.
273
 Aikido
 Jujitso and Judo
 Tai-Chi Chuan
1
3
511
Every part of the world has its own fighting art, and each one is
probably invincible on its own turf. For some reason we all seem to have
some facination with secret ways of self-defense.  We love to theorize
whether Ali could have beat a sumo wrestler, or whether any certain
art of self defense is better than another.  Sometimes, though that
question just leads to arguments.  It may be best to say that, it's
not whether Karate is any better than Aikido, its just important that
they are all meant to better our physical and sometimes spiritual
fitness.
