0
Startling - hard to answer & hard to believe trivia
231
What object, believed by some to carry a 285-year old curse, remains locked
up in a coach house under lock and key at the rear of an ancient inn in
Yorkshire, England?
Called "The chair of death", cursed in 1702 by an
executed man named Bugsby. The chair was blamed
for 7 deaths in six years (some didn't believe it)
585
 A cursed sword, originally from a royal guard
 An ancient book from a mystical magician
 A hangmans chair
 A horses carriage, blamed for numerous deaths
2
3
0
