/*
 *  Source machine generated by GadToolsBox V2.0b
 *  which is (c) Copyright 1991-1993 Jaba Development
 *
 *  GUI Designed by : P.A.
 */

#include <exec/types.h>
#include <intuition/intuition.h>
#include <intuition/classes.h>
#include <intuition/classusr.h>
#include <intuition/imageclass.h>
#include <intuition/gadgetclass.h>
#include <libraries/gadtools.h>
#include <graphics/displayinfo.h>
#include <graphics/gfxbase.h>
#include <proto/exec.h>
#include <proto/intuition.h>
#include <proto/gadtools.h>
#include <proto/graphics.h>
#include <proto/utility.h>
#include <string.h>
#include "wadview.h"

struct Screen         *Scr = NULL;
UBYTE                 *PubScreenName = "Workbench";
APTR                   VisualInfo = NULL;
struct Window         *WadviewWnd = NULL;
struct Gadget         *WadviewGList = NULL;
struct IntuiMessage    WadviewMsg;
struct Gadget         *WadviewGadgets[1];
UWORD                  WadviewLeft = 122;
UWORD                  WadviewTop = 18;
UWORD                  WadviewWidth = 265;
UWORD                  WadviewHeight = 181;
UBYTE                 *WadviewWdt = (UBYTE *)"WadViewer";
struct TextAttr       *Font, Attr;
UWORD                  FontX, FontY;
UWORD                  OffX, OffY;

UWORD WadviewGTypes[] = {
	LISTVIEW_KIND
};

struct NewGadget WadviewNGad[] = {
	4, 2, 257, 176, (UBYTE *)"Main Listview", NULL, GD_lv, PLACETEXT_LEFT, NULL, (APTR)lvClicked
};

ULONG WadviewGTags[] = {
	(GTLV_ShowSelected), NULL, (TAG_DONE)
};

static UWORD ComputeX( UWORD value )
{
	return(( UWORD )((( FontX * value ) + 3 ) / 6 ));
}

static UWORD ComputeY( UWORD value )
{
	return(( UWORD )((( FontY * value ) + 4 ) / 8 ));
}

static void ComputeFont( UWORD width, UWORD height )
{
	Font = &Attr;
	Font->ta_Name = (STRPTR)Scr->RastPort.Font->tf_Message.mn_Node.ln_Name;
	Font->ta_YSize = FontY = Scr->RastPort.Font->tf_YSize;
	FontX = Scr->RastPort.Font->tf_XSize;

	OffX = Scr->WBorLeft;
	OffY = Scr->RastPort.TxHeight + Scr->WBorTop + 1;

	if ( width && height ) {
		if (( ComputeX( width ) + OffX + Scr->WBorRight ) > Scr->Width )
			goto UseTopaz;
		if (( ComputeY( height ) + OffY + Scr->WBorBottom ) > Scr->Height )
			goto UseTopaz;
	}
	return;

UseTopaz:
	Font->ta_Name = (STRPTR)"topaz.font";
	FontX = FontY = Font->ta_YSize = 8;
}

int SetupScreen( void )
{
	if ( ! ( Scr = LockPubScreen( PubScreenName )))
		return( 1L );

	ComputeFont( 0, 0 );

	if ( ! ( VisualInfo = GetVisualInfo( Scr, TAG_DONE )))
		return( 2L );

	return( 0L );
}

void CloseDownScreen( void )
{
	if ( VisualInfo ) {
		FreeVisualInfo( VisualInfo );
		VisualInfo = NULL;
	}

	if ( Scr        ) {
		UnlockPubScreen( NULL, Scr );
		Scr = NULL;
	}
}

int HandleWadviewIDCMP( void )
{
	struct IntuiMessage	*m;
	int			(*func)();
	BOOL			running = TRUE;

	while( m = GT_GetIMsg( WadviewWnd->UserPort )) {

		CopyMem(( char * )m, ( char * )&WadviewMsg, (long)sizeof( struct IntuiMessage ));

		GT_ReplyIMsg( m );

		switch ( WadviewMsg.Class ) {

			case	IDCMP_REFRESHWINDOW:
				GT_BeginRefresh( WadviewWnd );
				GT_EndRefresh( WadviewWnd, TRUE );
				break;

			case	IDCMP_CLOSEWINDOW:
				running = WadviewCloseWindow();
				break;

			case	IDCMP_VANILLAKEY:
				running = WadviewVanillaKey();
				break;

			case	IDCMP_RAWKEY:
				running = WadviewRawKey();
				break;

			case	IDCMP_GADGETUP:
			case	IDCMP_GADGETDOWN:
				func = ( void * )(( struct Gadget * )WadviewMsg.IAddress )->UserData;
				running = func();
				break;
		}
	}
	return( running );
}

int OpenWadviewWindow( void )
{
	struct NewGadget	ng;
	struct Gadget	*g;
	UWORD		lc, tc;
	UWORD		wleft = WadviewLeft, wtop = WadviewTop, ww, wh;

	ComputeFont( WadviewWidth, WadviewHeight );

	ww = ComputeX( WadviewWidth );
	wh = ComputeY( WadviewHeight );

	if (( wleft + ww + OffX + Scr->WBorRight ) > Scr->Width ) wleft = Scr->Width - ww;
	if (( wtop + wh + OffY + Scr->WBorBottom ) > Scr->Height ) wtop = Scr->Height - wh;

	if ( ! ( g = CreateContext( &WadviewGList )))
		return( 1L );

	for( lc = 0, tc = 0; lc < Wadview_CNT; lc++ ) {

		CopyMem((char * )&WadviewNGad[ lc ], (char * )&ng, (long)sizeof( struct NewGadget ));

		ng.ng_VisualInfo = VisualInfo;
		ng.ng_TextAttr   = Font;
		ng.ng_LeftEdge   = OffX + ComputeX( ng.ng_LeftEdge );
		ng.ng_TopEdge    = OffY + ComputeY( ng.ng_TopEdge );
		ng.ng_Width      = ComputeX( ng.ng_Width );
		ng.ng_Height     = ComputeY( ng.ng_Height);

		WadviewGadgets[ lc ] = g = CreateGadgetA((ULONG)WadviewGTypes[ lc ], g, &ng, ( struct TagItem * )&WadviewGTags[ tc ] );

		while( WadviewGTags[ tc ] ) tc += 2;
		tc++;

		if ( NOT g )
			return( 2L );
	}

	if ( ! ( WadviewWnd = OpenWindowTags( NULL,
				WA_Left,	wleft,
				WA_Top,		wtop,
				WA_Width,	ww + OffX + Scr->WBorRight,
				WA_Height,	wh + OffY + Scr->WBorBottom,
				WA_IDCMP,	LISTVIEWIDCMP|IDCMP_CLOSEWINDOW|IDCMP_RAWKEY|IDCMP_VANILLAKEY|IDCMP_REFRESHWINDOW,
				WA_Flags,	WFLG_DRAGBAR|WFLG_DEPTHGADGET|WFLG_CLOSEGADGET|WFLG_SMART_REFRESH|WFLG_ACTIVATE,
				WA_Gadgets,	WadviewGList,
				WA_Title,	WadviewWdt,
				WA_ScreenTitle,	"WadViewer",
				TAG_DONE )))
	return( 4L );

	GT_RefreshWindow( WadviewWnd, NULL );

	return( 0L );
}

void CloseWadviewWindow( void )
{
	if ( WadviewWnd        ) {
		CloseWindow( WadviewWnd );
		WadviewWnd = NULL;
	}

	if ( WadviewGList      ) {
		FreeGadgets( WadviewGList );
		WadviewGList = NULL;
	}
}

