/*
 *  Source machine generated by GadToolsBox V2.0b
 *  which is (c) Copyright 1991-1993 Jaba Development
 *
 *  GUI Designed by : P.A.
 */

#define GetString( g )      ((( struct StringInfo * )g->SpecialInfo )->Buffer  )
#define GetNumber( g )      ((( struct StringInfo * )g->SpecialInfo )->LongInt )

#define GD_lv                                  0

#define GDX_lv                                 0

#define Wadview_CNT 1

extern struct IntuitionBase *IntuitionBase;
extern struct Library       *GadToolsBase;

extern struct Screen        *Scr;
extern UBYTE                 *PubScreenName;
extern APTR                  VisualInfo;
extern struct Window        *WadviewWnd;
extern struct Gadget        *WadviewGList;
extern struct IntuiMessage   WadviewMsg;
extern struct Gadget        *WadviewGadgets[1];
extern UWORD                 WadviewLeft;
extern UWORD                 WadviewTop;
extern UWORD                 WadviewWidth;
extern UWORD                 WadviewHeight;
extern UBYTE                *WadviewWdt;
extern struct TextAttr      *Font, Attr;
extern UWORD                 FontX, FontY;
extern UWORD                 OffX, OffY;
extern UWORD                 WadviewGTypes[];
extern struct NewGadget      WadviewNGad[];
extern ULONG                 WadviewGTags[];

extern int lvClicked( void );

extern int SetupScreen( void );
extern void CloseDownScreen( void );
extern int HandleWadviewIDCMP( void );
extern int WadviewCloseWindow();
extern int WadviewVanillaKey();
extern int WadviewRawKey();
extern int OpenWadviewWindow( void );
extern void CloseWadviewWindow( void );
