.TH robot 6
.SH NAME
robot \- Robot Escape, quick-thinking maze game
.SH SYNOPSIS
.B robot
.SH DESCRIPTION
Robot Escape is a quick-thinking maze game. The player controls a
rolling ball trapped in a maze, which can turn left or right at
corners but cannot reverse direction. When the ball turns, it
throws a discus forward.

Each maze contains several robots. A robot can be destroyed by
hitting it with a discus. The level is complete when all robots
in the maze have been destroyed.

The ball is destroyed if it collides with a robot. A limited
number of balls are available, and the current supply can be seen
on the right-hand side of the screen. Extra balls are sometimes
given when new levels are started.

Each level has a time limit of 60 seconds.
.SH CONTROLS
To indicate the next direction you wish to turn in, press the
corresponding arrow key.
.PP
Space starts the game, pauses or unpauses, and dismisses messages.
Esc can be used to quit.
.SH OPTIONS
.B robot
does not respect any command-line options at this time.
.SH ENVIRONMENT
No environment variables are used directly by the
.B robot
program.
.SH FILES
.TP
.BI /usr/share/games/robot
The location where
.B robot
finds its data files (sound effects, graphics, music, and font).
.SH BUGS
If
.B robot
is unable to load its sounds and initialize an audio device, it refuses
to run, rather than simply running with sound disabled.
.SH ACKNOWLEDGEMENTS
The font used was made by Bitstream, Inc.; thanks to them for releasing
it under a suitable license.

Mersenne Twister random number code (used on all platforms except
OpenBSD) was written by Makoto Matsumoto, Takuji Nishimura, and Mutsuo
Saito.

Several of the sound effects are from Brian Raiter's
.B "Tile World"
game.
.SH AUTHOR
Code and graphics, except as noted above
.RS
Catatonic Porpoise (graue@oceanbase.org)
.RE
.PP
Music
.RS
MTails (mtails@zianet.com)
.RE

