.\" $Id: vis.3,v 0.0 1998/06/03 22:52:22 niels Exp $
.TH vis 3 ""
.
.SH NAME
\fBvis\fR - calculates the PVS (potential visible set) of a bsp-tree
.
.SH SYNOPSIS
\fB#include <qtools.h>\fR

\fB#include "vis.h"\fR

\fBbool vis(__memBase, int level, char *prtBuf);\fR
.
.SH DESCRIPTION
.
.SH RETURN VALUE
.
.SH NOTES
.
.SH SEE ALSO
.
.SH AUTHOR
.
