
                          **********************
                          *                    *
                          *    HOOK - SOLVE    *
                          *                    *
                          **********************

-----------------------------------------------------------------------------

THE SOLUTION TO HOOK FROM OCEAN.
-------------------------------

PART ONE.

YOU'RE AT THE PIRATE'S SQUARE.
GO DOWN MUGGERS ALLEY.
GO TO DR CHOP.(A BIT TO THE RIGHT!)
TAKE ROLLERBLINDER OFF THE WINDOW.
ASK DR CHOP HOW TO GET CLOTHES(HAT,PANTS ETC)
ASK DR CHOP HOW I EARN SOME EXTRA MONEY.
LET DR CHOP TAKE 2 TEETHES OFF YOU.(DO IT AGAIN!)
CHECK THE MAP BEFORE YOU GO OUT OF THERE.
GO TO JOLLY ROGERS PLACE.
ASK THE MANAGER ABOUT THE WAR.
THEN ASK HIM HOW TO GET THE HAT THEN LEAVE.
GO TO PIRATE'S SQUARE.
GO BEHIND PIRATE'S SQAURE.
TAKE WASHING LINE POLE.
TAKE ANCHOR.
LOOK AT JACKET.
GO TO PIRATE'S SQUARE.
GO TO DEAD MANS PIER.
TAKE ROPE.
USE ROPE WITH ANCHOR.
GO TO CROSSED SWORDS.
TAKE CUPS.
GO OUT OF THERE.
GO TO BAIT AND TACKLE.
TAKE CUP.
GO UPSTAIRS AND OUT.
NOW YOU'RE AT THE BALCONY,OVERSEEING PIRATE'S SQUARE.
THIS IS THE TRICKY PART IN HOOK,YOU HAVE TO SYNCRONIZE THIS OTHERWISE
IT IS MADE IN VAIN.
YOU HAVE TO USE THE ANCHOR TIED TO THE ROPE AT THE VERY TOP OF THE
CLOCK WHILE AT THE SAME TIME YOU'RE IN MOMENTUM OF SWINGING YOURSELF
TO THE OTHER BALCONY YOU HAVE TO TAKE THE PIRATE'S HAT,TRICKY INDEED.
NOW YOU USE THE DOOR,THE YOU'D BETTER FUCKING HURRY BACK TO BEHIND 
PIRATE'S SQAURE,SWINGING YOURSELF BACK,OUT OF BAIT AND TACKLE AND
BACK TO PIRATE'S SQUARE AND THEN TO BEHIND PIRATE'S SQUARE.
THIS HAS TO BE MADE REALLY FAST OTHERWIZE MRS SMEEDLE'S WILL MAKE
YOUR DAY.
AT BEHIND PIRATE'S SQUARE YOU TAKE THE JACKET USING THE WASHING POLE.
HOPE YOU MADE IT FAST ENOUGH OTHERWIZE YOU HAVE TO DO IT AGAIN.
EXAMINE JACKET.
GO BACK TO PIRATE'S SQUARE.
GO TO MUGGERS ALLEY.
GO TO JOLLY ROGER'S PLACE.
GO AND TALK TO FAKE JAKE(THE MAN THAT SITS NEAREST THE BAR!).
ASK FAKE JAKE IF HE NEEDS A DRINK.
GIVE THE BARTENDER THE 3 MUGS.(AGAIN AND AGAIN!)
GIVE THE BARTENDER THE 3 COINS.(AGAIN AND AGAIN!)
GIVE FAKE JAKE THE 3 MUGS FILLED WITH COCOA.
TAKE FAKE JAKE'S PANTS.
GO OUT TO MUGGERS ALLEY.
GO TO PIRATE'S SQUARE.
GO TO BEHIND PIRATE'S SQUARE.
USE ROLLERBLINDER.
GO TO PIRATE'S SQUARE.
GO TO MUGGERS ALLEY.
GO TO GOOD FORM PIER.
GO TO THE SHIP.
GO TO THE RIGHT AND TAKE THE COINS THAT ARE IN THE POTS.
GO BACK TO GOOD FORM PIER AND MUGGERS ALLEY,PIRATE'S SQUARE.
GO TO YE' PIRATE'S TAILOR.
ASK THE TAILOR FOR ANY METALDETECTORS,THEN GIVE THE MONEY TO HER.
GO OUT TO PIRATE'S SQUARE.
GO TO MUGGERS ALLEY.
GO TO GOOD FORM BEACH.
USE MAGNET ON "X" ON THE BEACH.
GO BACK TO MUGGERS ALLEY.
GO TO GOOD FORM PIER.
GO TO SHIP.
GO TO THE LEFT OF THE SHIP.

PART ONE DONE.

PART TWO.

YOU'RE AT THE BOTTOM OF THE SEA.
EXAMINE THE STEELPIECE.
EXAMINE THE BIG SHELL.
USE WASHING LINE POLE WITH THE ROPES.
USE THE BIG SHELL.
YOU'RE NOW AT THE LOOKOUT-POINT.
GO RIGHT INTO NEVERFOREST.
NOW YOU'RE INTO NEVERFOREST,JUST FOLLOW THE SIGNS IF YOU'RE LOST IT
WILL HELP YOU ALOT HERE.(THOUGH THEY ARE NOT TO BE TRUSTED FULLY!)
HERE'S ATLEAST HOW I MADE IT.
GO RIGHT.
GO RIGHT.
GO RIGHT.
GO UP.
GO RIGHT.
GO UP.
GO LEFT.
GO LEFT.
GO LEFT.
GO LEFT.
GO UP.
GO RIGHT.
GO RIGHT.
NOW YOU'VE MADE IT.(BY BEING TRAPPED!)
GO INTO THE TREE.

PART THREE.

NOW YOU'RE AT THE LOST BOY'S DINING AREA.
GO TO THE ROUND POND AND TALK TO TINGELING.
ASK HER EVERYTHING.
GO TO THE SLINGSHOT.
TALK TO ACE.
ASK HIM EVERYTHING.
GO TO DINING AREA.
GO TO THE LOST BOY'S WORKSHOP.
TAKE THE ARROW.
GO TO JOGGING AREA.
USE JOGGING EQUIPMENT.(ATLEAST THRICE!)
GO TO THE AVENGER.
TAKE THE NET.
EXAMINE THE NET.
GO BACK TO JOGGING AREA.
GO TO FOUR SEASONS.
TAKE THE DEAD WOOD.
USE THE DEAD WOOD WITH STRING.
TAKE THE FLOWER.
GO TO THE CHICKEN AND USE THE CONCHSHELL.
TAKE THE EGGS FAST.
GO TO THE JOGGING AREA.
GO TO THE LOST BOY'S WORKSHOP.
GIVE THE EGGS TO THE BOY.
GO TO THE DINING AREA.
GO TO THE ROUND POND.
GIVE FLOWER TO TINGELING.
TAKE BRANCH FROM THE TREE.
GO TO THE DINING AREA.
GO TO THE SLINGSHOT.
USE THE PIECE OF STRONG ELASTIC WITH SLINGSHOT.
USE THE BRANCH WITH THE STRING.
GO TO THE DINING AREA.
GO TO THE LOST BOY'S WORKSHOP.
USE BOW WITH PANPIPES.
TAKE PANPIPES.
GO TO DINING AREA.
GO TO SLINGSHOT.
GO TO CLIFFSIDE.(UPPER!)
USE YOURSELF WITH THE FAR CORNER OF THE FENCE.
GO BACK AND DO THIS THRICE!
THEN ASK THUDBUTT WHAT HE THOUGHT ABOUT THAT.
GO BACK TO SLINGSHOT AND USE SLINGSHOT WITH YOURSELF.
ASK THUDBUTT WHAT HIS HAPPY THOUGHT'S ARE.
GO TO SLINGSHOT.
GO TO DINING AREA.
TALK TO RUFIO.
SAY TO RUFIO "OH RUFIO!".
GO TO ROUND POND AND WALK TO THE MIDDLE OF THE SCREEN.
NOW YOU'RE INSIDE NEVERTREE.
TALK TO TINGELING.
EXAMINE THE BROWN PILE IN THE MIDDLE.
EXAMINE THE CHAIR TO THE RIGHT.
EXAMINE FIREPLACE.
NOW WAIT AND WATCH THE MOVIE.

PART FOUR.

NOW YOU'RE INTO THE WAR WITH HOOK,YOU'RE NOW FULLY PETER PAN.
BACK AT HOOK'S SHIP.
THIS PART IS EXACTLY THE SAME IDEA AS MONKEY ISLAND I,SLAGGING
THE MORE,THE MORE YOU GAIN.
THIS IS HOW I DID IT.
TELL HOOK "PETER PAN THE AVENGER!"
TELL HOOK "GOOD FORM JAMES"
TELL HOOK "TICK TOCK TICK HOOK'S AFRAID OF DEAD OLD CROC!"
TELL HOOK "YOU KIDNAPPED MY KIDS HOOK,YOU DESERVE TO DIE!"
TELL HOOK "PUT UP YOUR SWORDS IT'S HOOK OR ME THIS TIME!"
TELL HOOK "PETER PAN THE AVENGER!"

NOW YOU'VE MADE IT! JUST WATCH THE CREDITS AND HAVE FUN!

/ ELRIC IN 1992!
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

MANY THANX TO UNDERTAKER/SABBATH FOR HELPING ME OUT ON THIS.

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
