/* menus.h */

#include "weather.h"

#define IWIDTH 112
#define IHEIGHT 9

struct IntuiText ProjText[] =
{
	{ 2, 1, JAM1, CHECKWIDTH, 1, NULL, "New", NULL},
	{ 2, 1, JAM1, CHECKWIDTH, 1, NULL, "Open", NULL},
	{ 2, 1, JAM1, CHECKWIDTH, 1, NULL, "Save", NULL},
	{ 2, 1, JAM1, CHECKWIDTH, 1, NULL, "Save As...", NULL},
	{ 2, 1, JAM1, CHECKWIDTH, 1, NULL, "Print", NULL},
	{ 2, 1, JAM1, CHECKWIDTH, 1, NULL, "Setup", NULL},
	{ 2, 1, JAM1, CHECKWIDTH, 1, NULL, "About", NULL},
	{ 3, 1, JAM1, CHECKWIDTH, 1, NULL, "Quit", NULL}
};

struct MenuItem ProjItem[] =
{
	/* New */
	{ &ProjItem[1], 0, 0, IWIDTH, IHEIGHT,
	  ITEMTEXT | ITEMENABLED | HIGHCOMP, 0,
	  (APTR) &ProjText[0], NULL, NULL, NULL, MENUNULL },

	/* Open */
	{ &ProjItem[2], 0,11, IWIDTH, IHEIGHT,
	  COMMSEQ | ITEMTEXT | ITEMENABLED | HIGHCOMP, 0,
	  (APTR) &ProjText[1], NULL, 'O', NULL, MENUNULL },

	/* Save   *** NOT AVAILABLE YET *** */
	{ &ProjItem[3], 0,22, IWIDTH, IHEIGHT,
	  COMMSEQ | ITEMTEXT | HIGHCOMP, 0,
	  (APTR) &ProjText[2], NULL, 'S', NULL, MENUNULL },

	/* Save As... */
	{ &ProjItem[4], 0,33, IWIDTH, IHEIGHT,
	  ITEMTEXT | ITEMENABLED | HIGHCOMP, 0,
	  (APTR) &ProjText[3], NULL, NULL, NULL, MENUNULL },

	/* Print   *** NOT AVAILABLE YET *** */
	{ &ProjItem[5], 0,44, IWIDTH, IHEIGHT,
	  ITEMTEXT | HIGHCOMP, 0,
	  (APTR) &ProjText[4], NULL, NULL, NULL, MENUNULL },

	/* Defaults */
	{ &ProjItem[6], 0,55, IWIDTH, IHEIGHT,
	  ITEMTEXT | ITEMENABLED | HIGHCOMP, 0,
	  (APTR) &ProjText[5], NULL, NULL, NULL, MENUNULL },

	/* About */
	{ &ProjItem[7], 0,66, IWIDTH, IHEIGHT,
	  ITEMTEXT | ITEMENABLED | HIGHCOMP, 0,
	  (APTR) &ProjText[6], NULL, NULL, NULL, MENUNULL },

	/* Quit */
	{ NULL, 0,77, IWIDTH, IHEIGHT,
	  COMMSEQ | ITEMTEXT | ITEMENABLED | HIGHCOMP, 0,
	  (APTR) &ProjText[7], NULL, 'Q', NULL, MENUNULL }
};

/* Will be initialized elsewhere */
struct IntuiText AreaText[34];

#define AREAMENU_WIDTH 260

struct MenuItem AreaItem[] =
{
	{ &AreaItem[1], 0, 0, AREAMENU_WIDTH, IHEIGHT,
	  ITEMTEXT | ITEMENABLED | HIGHCOMP, 0,
	  (APTR) &AreaText[0], NULL, NULL, NULL, MENUNULL },

	{ &AreaItem[2], 0,11, AREAMENU_WIDTH, IHEIGHT,
	  ITEMTEXT | ITEMENABLED | HIGHCOMP, 0,
	  (APTR) &AreaText[1], NULL, NULL, NULL, MENUNULL },

	{ &AreaItem[3], 0,22, AREAMENU_WIDTH, IHEIGHT,
	  ITEMTEXT | ITEMENABLED | HIGHCOMP, 0,
	  (APTR) &AreaText[2], NULL, NULL, NULL, MENUNULL },

	{ &AreaItem[4], 0,33, AREAMENU_WIDTH, IHEIGHT,
	  ITEMTEXT | ITEMENABLED | HIGHCOMP, 0,
	  (APTR) &AreaText[3], NULL, NULL, NULL, MENUNULL },

	{ &AreaItem[5], 0,44, AREAMENU_WIDTH, IHEIGHT,
	  ITEMTEXT | ITEMENABLED | HIGHCOMP, 0,
	  (APTR) &AreaText[4], NULL, NULL, NULL, MENUNULL },

	{ &AreaItem[6], 0,55, AREAMENU_WIDTH, IHEIGHT,
	  ITEMTEXT | ITEMENABLED | HIGHCOMP, 0,
	  (APTR) &AreaText[5], NULL, NULL, NULL, MENUNULL },

	{ &AreaItem[7], 0,66, AREAMENU_WIDTH, IHEIGHT,
	  ITEMTEXT | ITEMENABLED | HIGHCOMP, 0,
	  (APTR) &AreaText[6], NULL, NULL, NULL, MENUNULL },

	{ &AreaItem[8], 0,77, AREAMENU_WIDTH, IHEIGHT,
	  ITEMTEXT | ITEMENABLED | HIGHCOMP, 0,
	  (APTR) &AreaText[7], NULL, NULL, NULL, MENUNULL },

	{ &AreaItem[9], 0,88, AREAMENU_WIDTH, IHEIGHT,
	  ITEMTEXT | ITEMENABLED | HIGHCOMP, 0,
	  (APTR) &AreaText[8], NULL, NULL, NULL, MENUNULL },

	{ &AreaItem[10], 0,99, AREAMENU_WIDTH, IHEIGHT,
	  ITEMTEXT | ITEMENABLED | HIGHCOMP, 0,
	  (APTR) &AreaText[9], NULL, NULL, NULL, MENUNULL },

	{ &AreaItem[11], 0,110, AREAMENU_WIDTH, IHEIGHT,
	  ITEMTEXT | ITEMENABLED | HIGHCOMP, 0,
	  (APTR) &AreaText[10], NULL, NULL, NULL, MENUNULL },

	{ &AreaItem[12], 0,121, AREAMENU_WIDTH, IHEIGHT,
	  ITEMTEXT | ITEMENABLED | HIGHCOMP, 0,
	  (APTR) &AreaText[11], NULL, NULL, NULL, MENUNULL },

	{ &AreaItem[13], 0,132, AREAMENU_WIDTH, IHEIGHT,
	  ITEMTEXT | ITEMENABLED | HIGHCOMP, 0,
	  (APTR) &AreaText[12], NULL, NULL, NULL, MENUNULL },

	{ &AreaItem[14], 0,143, AREAMENU_WIDTH, IHEIGHT,
	  ITEMTEXT | ITEMENABLED | HIGHCOMP, 0,
	  (APTR) &AreaText[13], NULL, NULL, NULL, MENUNULL },

	{ &AreaItem[15], 0,154, AREAMENU_WIDTH, IHEIGHT,
	  ITEMTEXT | ITEMENABLED | HIGHCOMP, 0,
	  (APTR) &AreaText[14], NULL, NULL, NULL, MENUNULL },

	{ &AreaItem[16], 0,165, AREAMENU_WIDTH, IHEIGHT,
	  ITEMTEXT | ITEMENABLED | HIGHCOMP, 0,
	  (APTR) &AreaText[15], NULL, NULL, NULL, MENUNULL },

	{ &AreaItem[17], 0,176, AREAMENU_WIDTH, IHEIGHT,
	  ITEMTEXT | ITEMENABLED | HIGHCOMP, 0,
	  (APTR) &AreaText[16], NULL, NULL, NULL, MENUNULL },

	{ &AreaItem[18], 0,187, AREAMENU_WIDTH, IHEIGHT,
	  ITEMTEXT | ITEMENABLED | HIGHCOMP, 0,
	  (APTR) &AreaText[17], NULL, NULL, NULL, MENUNULL },

	{ &AreaItem[19], AREAMENU_WIDTH + 16,0, AREAMENU_WIDTH, IHEIGHT,
	  ITEMTEXT | ITEMENABLED | HIGHCOMP, 0,
	  (APTR) &AreaText[18], NULL, NULL, NULL, MENUNULL },

	{ &AreaItem[20], AREAMENU_WIDTH + 16,11, AREAMENU_WIDTH, IHEIGHT,
	  ITEMTEXT | ITEMENABLED | HIGHCOMP, 0,
	  (APTR) &AreaText[19], NULL, NULL, NULL, MENUNULL },

	{ &AreaItem[21], AREAMENU_WIDTH + 16,22, AREAMENU_WIDTH, IHEIGHT,
	  ITEMTEXT | ITEMENABLED | HIGHCOMP, 0,
	  (APTR) &AreaText[20], NULL, NULL, NULL, MENUNULL },

	{ &AreaItem[22], AREAMENU_WIDTH + 16,33, AREAMENU_WIDTH, IHEIGHT,
	  ITEMTEXT | ITEMENABLED | HIGHCOMP, 0,
	  (APTR) &AreaText[21], NULL, NULL, NULL, MENUNULL },

	{ &AreaItem[23], AREAMENU_WIDTH + 16,44, AREAMENU_WIDTH, IHEIGHT,
	  ITEMTEXT | ITEMENABLED | HIGHCOMP, 0,
	  (APTR) &AreaText[22], NULL, NULL, NULL, MENUNULL },

	{ &AreaItem[24], AREAMENU_WIDTH + 16,55, AREAMENU_WIDTH, IHEIGHT,
	  ITEMTEXT | ITEMENABLED | HIGHCOMP, 0,
	  (APTR) &AreaText[23], NULL, NULL, NULL, MENUNULL },

	{ &AreaItem[25], AREAMENU_WIDTH + 16,66, AREAMENU_WIDTH, IHEIGHT,
	  ITEMTEXT | ITEMENABLED | HIGHCOMP, 0,
	  (APTR) &AreaText[24], NULL, NULL, NULL, MENUNULL },

	{ &AreaItem[26], AREAMENU_WIDTH + 16,77, AREAMENU_WIDTH, IHEIGHT,
	  ITEMTEXT | ITEMENABLED | HIGHCOMP, 0,
	  (APTR) &AreaText[25], NULL, NULL, NULL, MENUNULL },

	{ &AreaItem[27], AREAMENU_WIDTH + 16,88, AREAMENU_WIDTH, IHEIGHT,
	  ITEMTEXT | ITEMENABLED | HIGHCOMP, 0,
	  (APTR) &AreaText[26], NULL, NULL, NULL, MENUNULL },

	{ &AreaItem[28], AREAMENU_WIDTH + 16,99, AREAMENU_WIDTH, IHEIGHT,
	  ITEMTEXT | ITEMENABLED | HIGHCOMP, 0,
	  (APTR) &AreaText[27], NULL, NULL, NULL, MENUNULL },

	{ &AreaItem[29], AREAMENU_WIDTH + 16,110, AREAMENU_WIDTH, IHEIGHT,
	  ITEMTEXT | ITEMENABLED | HIGHCOMP, 0,
	  (APTR) &AreaText[28], NULL, NULL, NULL, MENUNULL },

	{ &AreaItem[30], AREAMENU_WIDTH + 16,121, AREAMENU_WIDTH, IHEIGHT,
	  ITEMTEXT | ITEMENABLED | HIGHCOMP, 0,
	  (APTR) &AreaText[29], NULL, NULL, NULL, MENUNULL },

	{ &AreaItem[31], AREAMENU_WIDTH + 16, 132, AREAMENU_WIDTH, IHEIGHT,
	  ITEMTEXT | ITEMENABLED | HIGHCOMP, 0,
	  (APTR) &AreaText[30], NULL, NULL, NULL, MENUNULL },

	{ &AreaItem[32], AREAMENU_WIDTH + 16, 143, AREAMENU_WIDTH, IHEIGHT,
	  ITEMTEXT | ITEMENABLED | HIGHCOMP, 0,
	  (APTR) &AreaText[31], NULL, NULL, NULL, MENUNULL },

	{ &AreaItem[33], AREAMENU_WIDTH + 16, 154, AREAMENU_WIDTH, IHEIGHT,
	  ITEMTEXT | ITEMENABLED | HIGHCOMP, 0,
	  (APTR) &AreaText[32], NULL, NULL, NULL, MENUNULL },

	{ NULL, AREAMENU_WIDTH + 16, 165, AREAMENU_WIDTH, IHEIGHT,
	  ITEMTEXT | ITEMENABLED | HIGHCOMP, 0,
	  (APTR) &AreaText[33], NULL, NULL, NULL, MENUNULL }
};

struct Menu Menus[] =
{
	{ &Menus[1],  0,  0, 63,  0, MENUENABLED, "Project", &ProjItem[0] },
	{ NULL     , 70,  0,103,  0, MENUENABLED, "Area (North)",&AreaItem[0] }
};

struct Menu *FirstMenu = &Menus[0];

struct IntuiText AboutText[] =
{
	{0, 1, JAM1, 20, 5, NULL, "Roleaid by Niilo Paasivirta",NULL},
	{0, 1, JAM1,  5, 4, NULL, "Wow!!", NULL},
	{0, 1, JAM1,  5, 4, NULL, "Great", NULL}
};
