SECRET DOCFILE!

 * WormTris has a special 'DOUBLE SCORE' feature, which can be executed
   as many times as you wish, or as you CAN. It's quite easy once you
   know it.

 * Try having 10 worms on a line, it's possible! You'll be rewarded with
   LOTS of points when you make such a TOTAL WORMAGE.

 * Advanced WormCombo-ing:

   The worm allows you to make LOTS of points, imagine this situation

      |    w|
      |    w|  drop a block at the spot marked '·'. the line carrying
      |    w|  the worms will vanish, dropping the worms in the resulting
      |·####|  shaft making a triple worm combo. this can also be pulled
      |#### |  of with more worms (more than 4 results in a ULTRA combo,
      |#### |  which generates lots of points).
      |#### |
      `-----'

 * Filesizes: Exe size:  88888 bytes
              Exe.info:   1777 bytes
              Doc size:  11111 bytes
              Doc.info:    888 bytes
              Data dir: 555555 bytes
             
        why I made the filesizes weird? I just thought it was funny :^)

Bye!
