#
# makefile for Ndebt: Manx Aztec C v5.0a
#
# use small code and data, 32 bit ints, Manx floating point
#
# CFLAGS to use Manx floating point
CFLAGS = -fm
Ndebt:  Ndebt.o
	ln Ndebt.o detach.ols -lm -lc

