48
Quality Costs Questions - for potential CQE & CQEIT Stdnts
1
The concept of quality cost budgeting
585
 Involves udgeting the individual elements
 Replaces the traditional profit and loss statement.
 Does not consider total quality costs.
 Considers the four categories of quality costs and their general trends
2
4
1
A goal of a quality cost report should be to
585
 Get the best product quality possible.
 Be able to satisfy MIL-Q-9858A.
 Integrate two financial reporting techniques.
 Indicate areas of excessive costs.
2
4
1
Quality cost trend analysis is facilitated by comparing quality costs to:
585
 Manufacturing costs over the same time period.
 Appropriate measurement bases.
 Cash flow reports.
 Q.C. department budget.
2
2
1
The basic objective of a quality cost program is to:
585
 Identify the source of quality failures.
 Determine the quality control department responsibilities.
 Utilize accounting department reports.
 Improve the profit posture of your company.
2
4
3
When one first analyzes quality cost data, he might generally expect to
find that, relative to total quality costs:
585
 Costs of prevention are high.
 Costs of appraisal are high.
 Costs of failure are high.
 All of these
2
3
1
The primary reason for collecting and analyzing quality costs is:
585
 To satisfy requirements of MIL-Q-9858A.
 To see that quality costs are close to industry averages.
 To achieve optimum balance of prevention, appraisal, and failure costs.
 To identify the source of trouble.
2
3
1
Quality cost data would not normally be obtained from which of the following
585
 Labor reports
 Capital expenditure reports
 Salary budget reports
 Scrap reports
2
2
1
Sources of quality cost data do not normally include:
585
 Scrap reports.
 Labor reports.
 Salary budget reports.
 Capital expenditure reports.
2
4
1
The modern approach to quality cost is to:
585
 Concentrate on external failures.
 Consider the four cost segments and their general trends.
 Reduce expenditures on each segment individually.
 Make annual budget cuts where cost elements show major variances.
2
2
1
The modern concept of budgeting quality costs is to:
585
 Budget each of the four segments: prevention, appraisal & int/ext failures
 Concentrate on external failures. Since they deal with customers.
 Establish budget for reducing the total of the quality costs.
 Reduce expenditures on each segment.
2
3
1
Typically, total quality costs involve:
585
 All costs incurred by the quality department.
 Some costs incurred by production.
 Some costs incurred by production engineering.
 All of these.
2
4
3
When analyzing quality costs, a helpful method for singling out the highest
cost contributors is:
585
 A series of interviews with the line foreman.
 The application of the Pareto theory.
 An audit of budget variances.
 The application of break-even and profit volume analysis.
2
2
3
When looking for existing sources of internal failure cost data, which of
the following is usually the best source available:
585
 Operating budgets.
 Salemen's field reports.
 Labor and material cost documents.
 Purchase orders.
2
3
1
Of the following, which are typically appraisal costs
585
 Vendor surveys and vendor faults
 Quality planning and quality reports
 Drawing control centers and material dispositions.
 Quality audits and final inspection.
2
4
1
Which of the following cost elements is normally a prevention cost
585
 Receiving inspection.
 Outside endorsements or approvals.
 Design of quality measurement equipment.
 All of these.
2
3
1
Quality costs are best classified as:
585
 Cost of inspection, test, quality engineering, quality admin. & equipment
 Direct, inderect and overhead.
 Cost of prevention, cost of appraisal and cost of failure.
 None of these.
2
3
3
Operating quality costs can be related to different volume bases. An
example of volume base that could be used would be:
585
 Direct labor cost.
 Standard manufacturing cost.
 Processing & sales cost.
 All of these.
2
4
1
When operating a quality cost system, excessive costs can be identified when:
585
 Appraisal costs exceed failure costs.
 Appraisal and failure costs are equal.
 Total quality costs exceed 4% of manufacturing costs.
 There is no fixed rule-management experience must be used.
2
4
3
When looking for existing sources of external failure cost data, Which of
the following is usually the best source available:
585
 Customer corrective action requests.
 Salemen's field reports.
 Returned material reports.
 Purchase orders.
2
3
3
Outside endorsements or approvals, such as Underwriters' Laboratories fees,
are usually considered which of the following quality costs:
585
 External failure.
 Appraisal.
 Prevention.
 Internal failure.
2
2
1
A good quality cost reporting system will:
585
 Lead to operating at the lowest possible cost.
 Supplement the company's financial reporting system.
 Get the best product quality possible.
 Indicate areas of excessive quality costs.
2
4
1
Which of the following cost elements is a prevention cost
585
 Quality planning
 Process quality control.
 Design of quality measurment equipment.
 All of these.
2
4
1
A good quality cost reporting system will:
585
 Lead to operating at the lowest possible cost.
 Supplement the company's financial reporting system.
 Get the best product quality possible.
 Indicate areas of excessive quality costs.
2
4
3
When analyzing monthly quality cost trends on failure reports of many
types of consumer goods, you must be most alert to the effects of
585
 Changes in marketing management personnel
 Secular trends in the data
 Seasonal variations in the data
 Cyclical variations within the data
2
3
7
When analyzing quality cost data during the initial stages of
management's emphasis on quality control and corrective action as
part of a product improvement program, one normally expects to see
585
 Increased prevention costs and decreased appraisal costs
 Decreased internal failure costs
 Increased appraisal costs with little change in prevention costs
 Increased external failure costs
2
3
1
The basic objective of a quality cost program is to
585
 Improve the profit posture of your company
 Interface with the accounting department
 Identify the source of quality failures
 Identify the quality control department costs
2
1
3
Which of the following cost elements is usually considered an
appraisal cost
585
 Screening rejected lots
 Receiving inspection
 Surveying suppliers
 Preparing inspection plans
2
2
7
One of the best analytical methods for identifying those failure costs
that should be attacked first for the greatest return on the invested
prevention dollar is to
585
 Perform an internal financial audit
 Study the budget variance report
 Apply the Gompertz curve technique
 Apply the Pareto principle
2
4
7
In planning the staffing for your new quality control dept, you use
which of the following as the best justification for estimating the
number of people required
585
 A total salary budget as a given percent of sales dollars
 The number of people in the engineering department
 The quality objectives that have been set by top management
 None of these
2
3
3
Costs incurred in field testing for acceptance at the customer's site,
prior to releasing a product for customer acceptance, is considered
585
 Prevention cost
 Appraisal cost
 Failure cost
 None of these
2
2
7
The percentages of total quality cost are distributed as follows:
Prevention 10%,  Appraisal 25%,  Internal failure 40%, and External
failure 25%. We can conclude
585
 We should invest more money in prevention
 The amount spent for appraisal seems about right
 Expenditures for failures is excessive
 Nothing
2
4
1
An adequate quality budget should be
585
 About 10% of direct production costs
 Estimated from past quality costs
 About 2% of sales
 Based on total quality cost trend
2
4
3
The quality cost of writing operating instructions and operating
procedures for inspection and testing should be charged to
585
 Appraisal costs
 Internal failure costs
 Prevention costs
 External failure costs
2
3
3
Quality costs should not be reported against which one of the
following measurement bases
585
 Direct labor
 Sales
 Net profit
 Unit volume of production
2
3
1
Included as "Prevention quality cost" would be
585
 Salaries of personnel engaged in design of measurement & control equip.
 Capital equipment purchased
 Training costs of instructing personnel to achive production standards
 Sorting nonconforming material which may delay/stop production
2
1
1
Quality cost data
585
 Must be maintained when the end product is for the government
 Must be mailed to the contracting officer on request
 Is often an effective means of identifying quality problem areas
 All of these
2
3
3
Quality cost systems provide for defect prevention.  Which of the
following elements is primary to defect prevention
585
 Corrective action
 Data collection
 Cost analysis
 Training
2
1
1
In life cycle costing, the term "Life" refers to whose viewpoint
585
 Producer's
 User's
 Contractor's
 Quality control
2
2
3
Which of the following cost indices is likely to have the greatest
appeal to top management as an indicator of relative cost
585
 Quality cost per unit of product
 Quality cost per hour of direct production labor
 Quality cost per unit of processing cost
 Quality cost per unit of sales
2
4
3
Review of purchase orders for quality requirements falls into which
of the following quality cost segments
585
 Prevention
 Appraisal
 Internal failures
 External failures
2
1
1
Failure costs include costs due to
585
 Quality control engineering
 Inspection set-up for tests
 Certification of special-process suppliers
 Supplier analysis of non-conforming hardware
2
4
1
Quality cost trend analysis is facilitated by comparing quality cost to
585
 Manufacturing costs over the same time period
 Cash flow reports
 Appropriate measurement bases
 QC Department budget
2
3
1
Which of the following is least likely to be reported as a failure-related cot
585
 Sorting lots rejected by a sampling procedure
 Downtime caused by late delivery of a purchased part rej at supplier
 Repair of field failures
 Retesting of a repaired product
2
2
1
The basic objective of a quality cost program is to
585
 Identify the source of quality failures
 Interface with the accounting department
 Improve the profit of your company
 Identify quality control department costs
2
3
1
Cost of calibrating test and inspection equipment would be included in
585
 Prevention cost
 Appraisal cost
 Failure cost
 Material-procurement cost
2
2
7
In some instances, the ordinary cost-balance formula in not valid and
cannot be applied because of the presence of vital intangibles. Such an
intangible involves
585
 Safety of human beings
 Compliance with legislation
 Apparatus for collecting of revenue
 Credit to marketing as new sales for warranty replacements
2
1
7
If the prevention costs are increased to pay for engineering work in
quality control, and this results in a reduction in the number of
product defects, this yields a reduction in
585
 Appraisal costs
 Operating costs
 Quality costs
 Failure costs
2
4
1
Market based cost standards are guided by
585
 What others spend
 What we ought to spend
 Marketing budget
 Quality analysis forecast
2
1
3
Which of the following activities is not normally charged as a
preventive cost
585
 Quality training
 Design and development of quality measurement equipment
 Quality planning
 Laboratory acceptance testing
2
4
0
