15
Quality Audit Questions - for Quality Auditors & Engineers
1
Design reviews
585
 Should be formal, scheduled, and documented
 Should be held when there are design problems
 Should be held informally between engineering & management
 Should involve a maximum of four people in order to be manageable
2
1
1
The minimum number of personnel required to perform an audit is
585
 One
 Two
 Three
 Five
2
1
3
The number of personnel and the experience and qualifications of
personnel assigned to an audit is dependent on
585
 The scope of the audit
 The time available to perform the audit
 The subject of the audit
 All of these, including the cost of performing the audit
2
4
1
The true independence of the audit function is evidenced in
585
 The lines of the organization chart
 The quality and objectivity of the audit
 The number of significant findings reported
 All of these
2
2
1
Audits shall be scheduled such that
585
 All vendors are examined annually
 Activities are examined according to their importance
 All major projects are examined after completion
 All major projects are examined just before completion
2
2
7
A process audit is the evaluation of a manufacturing or test operation
against documented instructions and standards to measure ____ to these
standards and the effectiveness of the instructions.
585
 Conformance
 Results
 Deviations
 All of these
2
1
7
An audit designed to evaluate the effectiveness of the quality assurance
program by examining the knowledge of, compliance to, and adequacy of
current production methods is known as a(n)
585
 Process audit
 Self-audit
 Compliance audit
 Internal audit
2
1
1
Quality systems audits are used to verify that
585
 The performance and conduct of employees meet standards
 The measurements being taken on a product are valid
 The QA program conforms with established requirements
 Inspections are being performed by qualified personnel
2
3
3
The supplier's Quality Assurance manual should be reviewed before an
audit by
585
 The lead auditor
 The auditors conducting the audit
 The auditee
 All of these
2
2
1
The Quality Assurance Manual should be reviewed for
585
 Calibration records
 Compliance to purchase order or contract requirements
 Inclusion of purchase ordering data
 All of these
2
2
1
Which is the most suitable location for an audit interview to be conducted
585
 Where the activities under discussion are performed
 Anywhere during a tour of the plant
 At a private location or office
 In the Quality Assurance manager's office
2
3
1
What characteristic should the auditor not show during an interview
585
 Empathy
 Sympathy
 Humility
 Objectivity
2
2
7
Upon arrival at the auditee's premises, a meeting between the auditee and
the audit team should take place. Who from the auditee's organization is
not considered a key attendee at this entry interview
585
 Manager(s) of the area(s) to be audited
 Quality assurance manager
 Production manager
 Chief executive officer of the firm
2
4
1
Flowcharting of activities and systems are most helpful in detecting
585
 Inappropriate use of resources
 Deficient organizational structures
 Holes or gaps in control systems
 Improper use of statistical methods
2
3
3
In performing all types of audits, auditors must keep in mind that their
observations are the result of
585
 Opinions on the part of the auditor
 Bias on the part of the auditee
 Sampling of a population
 Information from a hostile environment
2
3
3
In the planning of a manufacturing program, the greatest quality effort
should be put logically into
585
 Test and inspection of product
 Non-destructive testing equipment
 Nonconformance to specifications
 Preventing substandard quality from occurring
2
4
0
