49
Western Humanities II 1400-1900 AD - College Junior Level
3
Great Italian Humanist, Had an encounter with a true love named Laura. Who
became the insparation for most of his poems. Wrote Canzoniere, Secretum.
585
 Francisco Petrarch
 Giovanni Occaccio
 Giovanni Boccaccio
 Michel de Montaigne
2
1
7
Essayist and Philosopher, notable for his tolerance in a bigoted age.
Studied Law, became a counselor with the parliment. Also served two terms
as a mayor of Bordaux. Wrote Essays (assai) and Cannibals.
585
 Michel de Montaigne
 Baldassare Castiglione
 William Shakespeare
 Francesco Petrarch
2
1
7
Widely talented, trained as a goldsmith, studied archeology. Invented
linear perspective. Designed the Pazzi Chapel, Florence Cathedral and
Ospedale deli Innocenti.
585
 Filippo Brunelleschi
 Donato di Niccolo Bardi
 Tommaso Guidi (Masaccio)
 Andrea Mantegna
2
1
3
Diplomat, soldier, and humanist scholar. Embodied the idear of the well
rounded courtier in The Book of the Courtier.
585
 Baldassare Castiglione
 Michel de Montaigne
 Niccolo Machiavelli
 Johannes Ockeghem
2
1
3
Wrote The Prince, based on political theories of classical history and his
own observation of the "political animal".
585
 Baldassare Castiglione
 Michel de Montaigne
 Niccolo Machiavelli
 Giovanni Boccaccio
2
2
3
Sculpt the statue called St.Mark, showing realism and commanding authority.
Free of its restrictive environment, builds on the legacy of Polykleitos.
585
 Donato di Niccolo Bardi (Donatello)
 Leonardo da Vinci
 Michelangelo Buonarroti
 None of these
2
1
1
Painted the Adoration of the Magi.
585
 Leonardo da Vinci
 Piero Della Francesca
 Andrea Mantegna
 Lorenzo Ghiberti
2
1
3
Famous for the Gates of Paradise, which contains the Story of Jacob and Esau
in one of its panels.
585
 Lorenzo Ghiberti
 Michel de Montaigne
 Michelangelo Buonarroti
 Leonardo da Vinci
2
1
3
Painted the Sistine Chapel Ceiling, also famous for his 13 foot statue of
David.
585
 Michelangelo Buonarroti
 Leonardo da Vinci
 Lorenzo Ghiberti
 Gentile Da Fabriano
2
1
1
Painted The Adoration of the Magi (tempra on wood panel).
585
 Gentile Da Fabriano
 Donato di Niccolo Bardi (Donatello)
 Tommaso Guidi (Masaccio)
 None of these
2
1
3
Painted The Holy Trinity with the Virgin and St John, as well as The
Tribute Money.
585
 Tommaso Guidi (Masaccio)
 Donato di Niccolo Bardi (Donatello)
 Filippo Brunelleschi
 Lorenzo Ghiberti
2
1
3
Indifference to or Rejection or exclusion of religion and religious
considerations.
585
 Secularism
 Humanism
 Neoplatonism
 None of these
2
1
3
The belief that man is born good and wise and that life is meant to be
enjoyed - belief in human perfectability.
585
 Secularism
 Humanism
 Neoplatonism
 None of these
2
2
1
A group of workers, or Union.
585
 Guilds
 Fresco
 House
 Intercession
2
1
1
The Pope who commissioned Michaelangelo to paint the sistine chapel.
585
 Pope Mark
 Pope Julius II
 Pope Medici
 Pope Ceasar III
2
2
1
The monestary built by Gargantua & Ponocrates for the pure of heart.
585
 Theleme
 Palladio
 Sistine Chapel
 Castiglione
2
1
1
A distinctive melody that serves as the basis for a musical composition.
585
 Monophony
 Theme
 Polyphony
 Motet
2
2
1
Describes music consisting of a single melodic line (without harmony)
585
 Theme
 Monophony
 Polyphony
 A cappella
2
2
3
Describes music in which two or more melodies are played simultaneously
(same as counterpoint) characteristic of baroque music.
585
 Theme
 Polyphony
 Motet
 Cantata
2
2
3
A short choral composition, using religious text, for four voices in
polyphony.
585
 Theme
 Motet
 A Cappella
 None of these
2
2
1
Choral music without instrumental accompaniment
585
 Theme
 A Cappella
 Monophony
 None of these
2
2
1
Opposition of church law, a crime punishable by death or the rack.
585
 Heresy
 Theocracy
 Inquisition
 None of these
2
1
3
A principle where the church is the ruling body of a nation, country, or
entity. The consituants follow 'Church law'.
585
 Theocracy
 Inquisition
 Secularism
 None of These
2
1
3
A system (usually for painting) where people and objects tend to dissolve
into the background. Less defined, blurred around the edges.
585
 Linear Perspective
 Aerial Perspective
 Foreshortening
 None of these
2
2
1
Giving spatial depth to picture.
585
 Linear Perspective
 Aerial Perspective
 Foreshortening
 Planar expansion
2
1
1
The teacher of Gargantua. Also was his partner in creating Theleme
585
 Ponocrates
 Panagora
 Gattamelata
 Botticelli
2
1
3
Architect of the COLONNADE OF ST. PETER'S BASILICA (Series of outdoor columns
with statues on top).
585
 Tintoretto
 El Greco
 Bernini
 Caravaggio
2
3
3
Architect of BALDACCHINO, ST. PETER'S BASILICA (dark curving columns inside
in a square).
585
 El Greco
 Rembrandt van Rijn
 Bernini
 Albrecht Durer
2
3
3
Painted THE RAPE OF THE DAUGHTERS OF LEUCIPPUS (2 men on horses picking up 2
naked women)
585
 Rembrandt van Rijn
 Peter Paul Rubens
 Nicholas Poussin
 Tintoretto
2
2
3
Painted INTERIOR OF A COURTYARD (man smoking long pipe with a woman and girl
next/near by).
585
 Pieter De Hooch
 Caravaggio
 Mansart and LeBrun
 Christopher Wren
2
1
3
Painted LANDSCAPE WITH THE BURIAL OF PHOCION (distance view with 2 men
carrying a white robed body on a stretcher).
585
 Nicholas Poussin
 Peter Paul Rubens
 Mansart and LeBrun
 Rembrandt van Rijn
2
1
1
Architects of the Palace of VERSAILLES (Gorgeous palace has hall of mirrors)
585
 Mansart and LeBrun
 Bernini and Christopher Wren
 Mansart and Bernini
 Christopher and LeBrun
2
1
3
Architect of ST. PAUL'S CATHEDRAL (cross shaped from top, has two stories of
columns from the front with a clock on the right bell tower).
585
 Christopher Wren
 Mansart and LeBrun
 Bernini
 Albrecht Durer
2
1
3
A papal certificate that reduces the temporal punishment for sin, on earth
and in purgatory, after the sin has been forgiven.
585
 Penance
 Intercession
 Salvation by faith
 Indulgence
2
4
3
The use of varying degrees of shading to suggest the play of reflected light
on a curved or uneven surface.
585
 Soliloquy
 Chiaroscuro
 Intercession
 None of these
2
2
3
A speech made by dramatic character in isolation and intended to convey his
or her inner reflections.
585
 Penance
 Index
 Soliloquy
 None of these
2
3
3
A polyphonic multimovement composition for solo voices, chorus and orchestra,
usually for performance in a church.
585
 Basso continuo
 Cantata
 Fugue
 Madrigal
2
2
7
A single bass line of chords, usually played by the harpsichord or cello,
that exists to support and unify the melodies being woven above it (also
called "figured bass").
585
 Madrigal
 Basso continuo
 Concerto grosso
 Opera
2
2
3
a song, using a text in the vernacular language, for several voices in
polyphony.
585
 Cantata
 Fugue
 Madrigal
 Opera
2
3
7
a polyphonic composition, generally for two to four voices (vocal or instr.)
in which the same themes are passed from voice to voice or instrument to
instrument to instrument - very popular with baroque composers.
585
 Concerto grosso
 Fugue
 Concerto
 Oratorio
2
2
3
A piece of music for one or more solo instruments and orchestra, usually with
three contrasting movements.
585
 Concerto grosso
 Concerto
 Opera
 Mandrigal
2
2
7
An orchestral composition in which the instruments are divided into two
contrasting bodies: a large (ripieno, or grosso) and a small (concertino)
ensemble.
585
 Concerto grosso
 Oratorio
 Basso continuo
 None of these
2
1
3
Painted THE FOUR HORSEMEN OF THE EPOCALYPSE (black and white woodcut of four
horsemen, an angel and some people being stampeded).
585
 Michelangelo
 Tintoretto
 Albrecht Durer
 Peter Paul Rubens
2
3
1
Painted THE FOUR APOSTLES (actually 2 panels with 2 apostles in each)
585
 Michelangelo
 Nicholas Poussin
 Caravaggio
 Albrecht Durer
2
4
1
Painted THE LAST JUDGEMENT (dozens of men floating as if in an aerial world).
585
 Michelangelo
 Albrecht Durer
 Bernini
 Nicholas Poussin
2
1
7
Painted THE BURIAL OF COUNT ORGAZ (dome shaped picture, has christ and angels
at the top and the pope, priests, counts around an armoured body who is being
moved by the pope and a cardinal).
585
 El Greco
 Peter Paul Rubens
 Nicholas Poussin
 Caravaggio
2
1
3
Painted THE CONVERSION OF ST. PAUL (has a man lying of the ground with his
arms up next to a horse. theres a man behind the head of the horse).
585
 Peter Paul Rubens
 Caravaggio
 Rembrandt van Rijn
 Pieter De Hooch
2
2
3
Painted THE BLINDING OF SAMSON (has a man being held down by some soldiers
in the dark - almost looks like a cave)
585
 Bernini
 Leonardo da Vinci
 Tintoretto
 Rembrandt van Rijn
2
4
3
Painted THE DESCENT FROM THE CROSS (has jesus being brought down from the
cross in the late evening by some poor looking people).
585
 Peter Paul Rubens
 Rembrandt van Rijn
 Albrecht Durer
 Caravaggio
2
2
3
Painted THE RETURN OF THE PRODIGAL SON (has a young bald man kneeling before
his bearded father with some wise men nearby).
585
 El Greco
 Pieter De Hooch
 Rembrandt van Rijn
 Peter Paul Rubens
2
3
16383
 
HUMANITIES II - Western Humanities from 1400-1900 AD
 
This is a brief test of the major accomplishments, and developments of
the Italian Renaissance (1375-1500), The northern reformation and
expansion (1430-1600), The age of genius (1475-1600), The new synthesis
of the the seventeenth century, The decline of the aristocracy
(1700-1798), and of course the romantic temper (1789-1848).
 
This is not a complete test of all possible questions you may encounter
in a Humanities II class, but rather a small sample of the most likely
questions (based on this authors opinion) that you may be confronted
with in a final exam of this subject.
 
