#include "adv.t"
#include "adv-mods.t"
#include "std.t"
#include "verbs.t"
#include "classes.t"
#include "funcs.t"
#include "fight.t"
#include "objects.t"
#include "help.t"

/* things semi-stable */
#include "house.t"
#include "thief.t"
#include "puzzle.t"
#include "bank.t"
#include "alice.t"
#include "carousel.t"
#include "dam.t"
#include "river.t"
#include "volcano.t"
#include "temple.t"
#include "maze.t"
