59
Final exam for a BASIC ELECTRONICS circuits & principles course.
1
The transistor is a _____ controlling device.
585
 voltage
 current
 power
 impedance
2
2
1
The nucleus of an atom contains _____ and _____.
585
 protons, electrons
 electrons, neutrons
 protons, neutrons
 photons, neutrons
2
3
3
Atoms are electrically neutral when they have the same number of _____
and _____.
585
 protons, electrons
 electrons, neutrons
 protons, neutrons
 photons, neutrons
2
1
1
A material through which electrons can pass readily is called a(an)______.
585
 insulator
 field
 vacuum
 conductor
2
4
1
_____ poles of a magnet repel and ______ poles of a magnet attract.
585
 like, unlike
 like, like
 unlike, unlike
 unlike, like
2
1
1
A difference in potential is measured in units called _____.
585
 amperes
 coulombs
 joules
 volts
2
4
1
A car battery converts ____ energy to ____ energy.
585
 light, electrical
 mechanical, electrical
 chemical, mechanical
 chemical, electrical
2
4
3
Maximum current is induced in a wire when it moves at an angle of _____ to
the magnetic lines of force.
585
 0 degrees
 30 degrees
 45 degrees
 90 degrees
2
4
1
If the period of a sine wave is 25usec, the frequency is _____.
585
 25 kHz
 25 mHz
 4 kHz
 40 kHz
2
4
1
The power in a circuit may be found by ________.
585
 E x I
 E / I
 E / R
 I x R
2
4
3
A resistor with the following colors: yellow, purple, and green (from left
to right) has a value of _______.
585
 470 K
 4.7 Meg
 570 K
 47 Meg
2
2
1
The incorrect equation is _______.
585
 E = I x R
 I = E / R
 R = E / I
 E = I / R
2
4
1
As the resistance in a circuit is increased the current in a circuit _____.
73
 increases
 decreases
 remains the same
2
2
3
A resistor whose colors are brown, red, yellow, and silver may have a
maximum value of _______.
585
 144 K
 132 K
 126 K
 13.2 K
2
2
3
With a current of 2 amperes through a resistance of 12 ohms, the power
dissipated is ________.
585
 24 watts
 3 watts
 48 watts
 288 watts
2
3
3
When 12 volts are applied to a circuit whose resistance is 6K ohms the
current will be ______.
585
 2 amperes
 0.2 amperes
 20 ma
 2 ma
2
4
1
When 3 uamps flows through an 18 Kohm resistor the voltage drop will be ____.
585
 54 volts
 54 millivolts
 54 microvolts
 6 millivolts
2
2
3
When a current of 20 ma is due to a voltage of 40 volts, the resistance in
the circuit is ______.
585
 20 K
 2 K
 200 ohms
 20 ohms
2
2
3
A 12 K resistor in series with a 6 K resistor results in a total resistance
of ______.
585
 18 K
 9 K
 6 K
 4 K
2
1
3
The total resistance of a circuit containing a 240-ohm resistor in parallel
with an 80-ohm resistor is _____.
585
 320 ohms
 160 ohms
 60 ohms
 40 ohms
2
3
1
Three 15 K resistors in parallel result in a resistance of ____.
585
 45 K
 30 K
 15 K
 5 K
2
4
15
There are three paths for current at a junction, (paths A, B, and C). If path
A supplies 5 ma to the junction, and path B has a current of 8 ma leaving
the junction, then path C has a current of ____ ma (entering, leaving) the
junction.
585
 13 ma leaving
 13 ma entering
 3 ma leaving
 3 ma entering
2
4
3
A device that offers more impedance to current in one direction than in the
other direction is a(an) ______.
585
 transistor
 diode
 inductor
 capacitor
2
2
1
A variable resistor is called a ______.
585
 varactor
 variometer
 potentiometer
 varistor
2
3
1
As the temperature in a resistor is increased, its resistance _____.
585
 increases
 decreases
 remains the same
 none of the above
2
1
3
The resistance of a wire may be increased by (increasing, decreasing) its
length and (increasing, decreasing) its cross-sectional area.
585
 increasing, increasing
 increasing, decreasing
 decreasing, increasing
 decreasing, decreasing
2
2
3
In order to exist in a stable orbit in a given shell an electron must have
a certain _____ level.
585
 energy
 valance
 potential
 conduction
2
1
3
The device whose atomic arrangement falls into the cubic lattice system is
the ____.
585
 conductor
 semiconductor
 insulator
 inductor
2
2
3
The sharing of an electron by adjacent atoms of a semiconductor is known as
____ bonding.
585
 covalent
 valence
 nuclear
 atomic
2
1
1
A crystal without impurities is known as a(n) ______ crystal.
585
 face-centered
 body-centered
 ionic
 intrinsic
2
4
1
N-type germanium is formed by doping it with a ______ material.
585
 pentavalent
 tetravalent
 crystalline
 ionic
2
1
3
When the positive terminal of a battery is connected to the N-type region of
a PN junction it is said to be ______.
585
 inverted
 forward-biased
 reverse-biased
 diffused
2
3
3
The process by which an a-c signal is converted into pulsating direct current
is known as _____.
585
 amplification
 rectification
 inversion
 conversion
2
2
1
A constantly changing current in a wire results in a(n) _____.
585
 counter emf
 inductance
 conductance
 voltage
2
1
3
The property of a circuit that tends to oppose a change in current is called
 _______.
585
 capacitance
 resistance
 conductance
 inductance
2
4
3
The value of an inductor may be increasing by (increasing, decreasing) the
number of turns and (increasing, decreasing) the coil diameter.
585
 decreasing, decreasing
 decreasing, increasing
 increasing, decreasing
 increasing, increasing
2
4
1
In an inductive circuit the current _____ the voltage by _____ degrees.
585
 leads, 90
 leads, 180
 lags, 90
 lags, 180
2
3
3
The total inductance of a circuit containing a 6-mh inductor in series with
a 3-mh inductor is ______.
585
 18 mh
 9 mh
 3 mh
 2 mh
2
2
3
The parallel combination of a 36-uh inductor and a 12-uh inductor is
equivalent to a _____ inductor.
585
 48-uh
 24-uh
 9-uh
 6-uh
2
3
7
The inductive reactance of a circuit may be increased by (increasing,
decreasing) its inductance and (increasing, decreasing) the frequency of
the applied voltage.
585
 increasing, increasing
 increasing, decreasing
 decreasing, increasing
 decreasing, decreasing
2
1
1
A device that allows only low frequencies to pass is known as a _____.
585
 high-pass filter
 bandpass filter
 low-pass filter
 none of the above
2
3
3
If 20 volts are applied to the primary of a transformer having a turns ratio
of 5:1, the voltage in the secondary will be _____.
585
 100 V
 20 V
 4 V
 1 V
2
3
3
In a step-up transformer the voltage is (stepped-up, stepped-down) and the
current is (stepped-up, stepped-down).
585
 stepped-up, stepped-up
 stepped-up, stepped-down
 stepped-down, stepped-up
 stepped-down, stepped-down
2
2
3
The impedance of a circuit containing a 6-ohm resistor in series with an
8-ohm inductive reactance is ______.
585
 100 ohms
 48 ohms
 14 ohms
 10 ohms
2
4
3
In an RL circuit the time required for the current to reach 63 percent of
its maximum value is known as the ______.
585
 critical time
 time constant
 time factor
 time vector
2
2
3
When a square wave is applied to a LR circuit the waveform across the inductor
is _____.
585
 integrated
 differentiated
 truncated
 inebriated
2
2
1
A device that opposes a change in voltage in a circuit is called a(n) ______.
585
 resistor
 capacitor
 inductor
 transistor
2
2
3
A 48-mfd capacitor and a 16-mfd capacitor are connected in parallel, the total
capacitance is _____.
585
 64 mfd
 32 mfd
 24 mfd
 12 mfd
2
1
3
Capcitance may be decreased by (decreasing, increasing) the plate area and
(decreasing, increasing) the distance between the plates.
585
 decreasing, decreasing
 decreasing, increasing
 increasing, decreasing
 increasing, increasing
2
2
7
The capacitive reactance in a circuit may be increased by (increasing,
decreasing) the capacitance in the circuit and (increasing, decreasing) the
frequency applied to the circuit.
585
 increasing, increasing
 increasing, decreasing
 decreasing, increasing
 decreasing, decreasing
2
4
3
A 20-mfd capacitor in series with a 100 K resistor results in a time
constant of ______.
585
 20 seconds
 5 seconds
 2 seconds
 0.5 seconds
2
3
1
In an RC circuit the current (leads, lags) the voltage by ____ degrees.
585
 leads, 90
 leads, 180
 lags, 90
 lags, 180
2
1
1
The voltage across the capacitor in an RC circuit is _____.
585
 integrated
 differentiated
 desegregated
 obliterated
2
1
3
The ratio used to determine the shape of a waveform across a component is
known as ______.
585
 L-to-R
 R-to-C
 TC-to-f
 TC-to-P
2
4
3
In an LRC circuit the total reactance is equal to the ______ X  and  X
                                                              L       C
585
 sum of
 difference between
 product of
 ratio between
2
2
3
In a series-resonant LCR circuit X   is _______   X   .
                                  L                C
585
 greater than
 equal to
 less than
 in phase with
2
2
1
In a series LCR circuit power will be consumed in __________.
585
 L and C only
 L only
 C only
 R only
2
4
1
The Q of a resonant circuit is the ratio of ________.
1755
 X  to  X
  L      C
 X  to  R
  L
 X  to  X
  C      L
 R  to  X
         C
2
2
1
The impedance of a series resonant circuit is ________.
729
 maximum
 equal to X
           L
 equal to X
           C
 minimum
2
4
1
The impedance of a parallel circuit is ________.
729
 maximum
 equal to X
           L
 equal to X
           C
 minimum
2
1
0
