/*pragma libcall krsnakebase KsRegisterServer 1e 0*/
/*pragma libcall krsnakebase KsRemoveServer 24 001*/
#pragma libcall krsnakebase KsRegisterClient 2a 0
#pragma libcall krsnakebase KsRemoveClient 30 001
/*pragma libcall krsnakebase KsNotifyClients 36 01803*/
#pragma libcall krsnakebase KsWaitForEvent 3c 001
#pragma libcall krsnakebase KsReadEvent 42 01803
#pragma libcall krsnakebase KsGetClientSig 48 001
#pragma libcall krsnakebase KsReadKRSNAkePrefs 4e 0
#pragma libcall krsnakebase KsWriteKRSNAkePrefs 54 001
#pragma libcall krsnakebase KsReadSoundObject 5a 001
#pragma libcall krsnakebase KsPlaySoundObject 60 001
#pragma libcall krsnakebase KsDeleteSoundObject 66 001
/*pragma libcall krsnakebase KsShowInterface 6c 001*/
/*pragma libcall krsnakebase KsHideInterface 72 001*/
#pragma libcall krsnakebase KsNotifyServer 78 0802
/*pragma libcall krsnakebase KsGetNotifySig 7e 001*/
/*pragma libcall krsnakebase KsGetNotifyEvent 84 01803*/
