37
Metrology Questions - from various Quality Books/Magazines
1
Wear allowance on a Go plug gage permits gages to be
585
 Slightly smaller in diameter than the low limit of spec
 Slightly larger in diameter than the low limit of spec
 Right on the low limit of spec
 Slightly larger in diameter than the high limit of spec
2
2
3
Measurement gaging is preferable to go-no-go gaging in a quality
characteristic because
585
 It is more scientific
 It provides the most information per piece inspected
 It requires greater skills
 It requires a larger sample than gaging does
2
2
7
Which of the following nondestructive testing methods is best for rapid
inspection of 1/2 in. diameter carbon steel rod one foot long for surface
cracks
585
 Radiography
 Ultrasonic
 Magnetic particle
 Liquid penetrant
2
3
3
To measure an angle on a work piece, the most accurate method would
involve the use of
585
 A sine-bar
 A set of plastic triangles
 A bevel protractor
 None of these
2
1
15
What type of gaging instrument would you use to determine the fractional
part of an inch that can be read by multiplying the denominator of the
finest subdivision on the scale by the total nr of divisions on the second
scale
585
 Vernier
 Micrometer
 Comparator
 Demonimeter
2
1
1
A device used to measure viscosity or consistency is
585
 Viscosimeter
 Farinograph
 Consistometer
 All of these
2
4
1
The smallest size a 3 inch micrometer can measure is
585
 3 in.
 2 In.
 1 In.
 2.5 In.
2
2
1
Test and inspection equipment should be
585
 Replaced periodically
 Covered when not in use
 Calibrated periodically
 As sophisticated as possible
2
3
1
The metric system
585
 Is based upon the circumference of the earth's equator
 Originated in England
 Is better than the inch-pound system
 Is legal in the United States
2
4
1
Accuracy is
585
 Getting consistent results repeatedly
 Reading to four decimals
 Using the best measuring device available
 Getting an unbiased true value
2
4
1
Measurement error
585
 Is the fault of the inspector
 Can be determined
 Is usually of no consequence
 Can be eliminated by frequent calibrations of the measuring device
2
2
1
Precision is
585
 Getting consistent results repeatedly
 Reading to four or more decimals
 Distinguishing small deviations from the standard value
 Extreme care in the analysis of data
2
1
3
True testing variability can be obtained in a destructive testing
situation under one of these conditions
585
 Enough samples have been tested
 It cannot be obtained
 All samples are taken closely together
 The same person and instruments are used
2
2
3
Which trigometric functions finds the most use in ordinary angular
measurement
585
 Sine
 Cosine
 Tangent
 Cotangent
2
1
1
Sensitivity is
585
 Extreme care in data analysis
 Ability to distinguish differences in the response variability
 Getting the true result
 Using the best measuring device
2
2
1
100 percent inspection is
585
 Used to sort items
 At best only 60 percent effective
 Assures a satisfactory outgoing quality level
 Is theoretically unsound but is and excellent practice
2
1
1
The intentional difference in the sizes of mating parts is the
585
 Specification
 Clearance
 Natural tolerance
 Satisfactory functioning
2
2
3
The ultimate standard for U.S. units of measurements, used to verify
all masters, is
585
 The official meter
 The imperial yard
 The length of a light wave
 The geiger counter
2
3
3
In comparing the philosophies of "tight tolerances loosely enforced"
and realistic tolerances rigidly enforced", we can conclude that
585
 The first one is preferred
 The second one is preferred
 Neither is really practical
 Both have a place in any production operation
2
2
1
The permissible variation in a dimension is the
585
 Clearance
 Allowance
 Tolerance
 Measurement
2
3
1
Sensitivity in experimentation is
585
 Getting the true result
 Extreme care in data analysis
 Using the best measuring device
 Ability to destinguish differences in the response variable
2
4
3
The principal use of V-Blocks is, holding in fixed relation to the
surface plate
585
 Angular pieces
 Cylindrical pieces
 Spherical parts
 Measuring tools
2
2
3
The vernier makes measurement readings as fine as thousandths of
an inch possible by
585
 Magnifying the graduations
 Providing more widely spaced graduations
 Visually subdividing the smallest divisions on a scale
 Providing more closely spaced graduations
2
3
1
Dial indicator inaccuracies are stated in terms of
585
 Percentage of full scale range
 Dial indicator divisions
 Percent reliability
 None of these
2
1
3
Which of the following is most important to consider when calibrating
a piece of equipment
585
 Calibration sticker
 Maintenance history card
 Wheatstone bridge
 Standard used
2
4
1
A gage that checks a single dimension (and tolerance) is
585
 A micrometer
 A vernier
 A varigage
 A plug gage
2
4
3
A tracer type surface finish instrument, such as a profilemeter, should
not be used to measure
585
 Roughness measurement on gear teeth
 Depth of scratches on a metal surface
 Roughness measurement on mild steel plate
 Surface condition of a tapered hole
2
2
3
Several types of good instruments are usually equipped with a mirror behind
the dial-pointer to reduce which of the following measurement errors
585
 Interpolation rounding
 Parallax
 Nonlinearity in lower scale regions
 Wrong scale reading
2
2
1
Pneumatic gaging has one major advantage over electronic gaging and that is
585
 Cost
 Higher amplification
 The elimination of metal to metal contact
 Increased accuracy
2
3
1
When using an inside or outside caliper, care must be taken to get the proper
585
 Slip
 Depth
 Grip
 Feel
2
4
1
Specifying a tolerance by +0.0000 -0.0001 is known as
585
 Limit dimensioning
 Manufacturing limits
 Unilateral tolerancing
 Bilateral tolerancing
2
3
3
The distinguishing feature of the optical comparator is that adjustments
for measurement are observed on a
585
 Screen
 Reticle coordinator
 Dial indicator
 Rotating stage
2
1
1
Color can be described as
585
 Photometric
 Two dimnsional
 Three dimensional
 One dimensional
2
3
1
Fixed gages
585
 Measure one or more dimensions
 Measure only one dimension
 Are all made of tool steel
 Are a fast method of checking parts
2
4
3
The reliability of a measuring instrument is linked to the U.S. National
standards by
585
 Traceability
 Confirmation
 Unification
 Capability
2
1
1
Gages that tell how much a dimension varies from specification are called
585
 Accurators
 Depth gages
 Indicating gages
 Tolerators
2
3
1
The finest reading possible with a vernier micrometer in inches is
585
 Hundred-thousandths
 Ten-thousandths
 Micro-tenths
 Thousandths
2
2
3
The method whereby several sizes of gage blocks can be conveniently combined
to total a desired dimension is called
585
 Magnetism
 Interlocking
 Wringing
 Stacking
2
3
0
