#ifndef WW_STRINGS_H
#define WW_STRINGS_H


/****************************************************************************/


/* This file was created automatically by CatComp.
 * Do NOT edit by hand!
 */


#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif

#ifdef CATCOMP_ARRAY
#undef CATCOMP_NUMBERS
#undef CATCOMP_STRINGS
#define CATCOMP_NUMBERS
#define CATCOMP_STRINGS
#endif

#ifdef CATCOMP_BLOCK
#undef CATCOMP_STRINGS
#define CATCOMP_STRINGS
#endif


/****************************************************************************/


#ifdef CATCOMP_NUMBERS

#define MSG_MENU_PROJECT 0
#define MSG_MENU_NEW 1
#define MSG_KEY_NEW 2
#define MSG_MENU_OPEN 3
#define MSG_KEY_OPEN 4
#define MSG_MENU_SAVE1 5
#define MSG_KEY_SAVE 6
#define MSG_MENU_SAVEAS 7
#define MSG_KEY_SAVEAS 8
#define MSG_MENU_PRINT 9
#define MSG_KEY_PRINT 10
#define MSG_MENU_PRINTAS 11
#define MSG_MENU_HIDE 12
#define MSG_MENU_REVEAL 13
#define MSG_MENU_CLOSE 14
#define MSG_MENU_ABOUT 15
#define MSG_KEY_ABOUT 16
#define MSG_MENU_EXIT 17
#define MSG_MENU_QUIT 18
#define MSG_KEY_QUIT 19
#define MSG_MENU_EDIT 20
#define MSG_MENU_CUT 21
#define MSG_KEY_CUT 22
#define MSG_MENU_COPY 23
#define MSG_KEY_COPY 24
#define MSG_MENU_PASTE 25
#define MSG_KEY_PASTE 26
#define MSG_MENU_ERASE 27
#define MSG_KEY_ERASE 28
#define MSG_MENU_UNDO 29
#define MSG_KEY_UNDO 30
#define MSG_MENU_REDO 31
#define MSG_MENU_MACROS 32
#define MSG_MENU_STARTLEARNING 33
#define MSG_MENU_STOPLEARNING 34
#define MSG_MENU_ASSIGNMACRO 35
#define MSG_MENU_LOAD 36
#define MSG_MENU_SAVE2 37
#define MSG_MENU_SETTINGS 38
#define MSG_MENU_CREATEICONS 39
#define MSG_KEY_CREATEICONS 40
#define MSG_MENU_LOADSETTINGS 41
#define MSG_MENU_SAVESETTINGS 42
#define MSG_MENU_SAVESETTINGSAS 43
#define MSG_MENU_USER 44
#define MSG_MENU_HELP 45
#define MSG_MENU_ICONIFY 46
#define MSG_MENU_MANUAL 47
#define MSG_KEY_MANUAL 48
#define MSG_MENU_POINTER 49
#define MSG_MENU_REVERT 50
#define MSG_KEY_REVERT 51
#define MSG_MENU_TITLEBAR 52
#define MSG_MENU_TOOLS 53
#define MSG_MENU_VIEW 54
#define MSG_CANTLOCK_NAMED 55
#define MSG_CANTLOCK_DEFAULT 56
#define MSG_MENU_PROJECTDELETE 57
#define MSG_SHORTCUT_PROJECTDELETE 58
#define MSG_MENU_QUITWB 59
#define MSG_MENU_EDITDELETE 60
#define MSG_MENU_INSERT 61
#define MSG_MENU_APPEND 62
#define MSG_MENU_CLEARHS 63
#define MSG_SHORTCUT_POINTER 64
#define MSG_SHORTCUT_TITLEBAR 65
#define MSG_MENU_ANIMATIONS 66
#define MSG_SHORTCUT_ANIMATIONS 67
#define MSG_MENU_ENGRAVEDSQUARES 68
#define MSG_MENU_CREATURES 69
#define MSG_MENU_OBJECTS 70
#define MSG_MENU_FRUITS 71
#define MSG_MENU_ABOUTWW 72
#define MSG_NONE 73
#define MSG_GAMEPAD1 74
#define MSG_GAMEPAD2 75
#define MSG_GAMEPAD3 76
#define MSG_GAMEPAD4 77
#define MSG_JOYSTICK1 78
#define MSG_JOYSTICK2 79
#define MSG_JOYSTICK3 80
#define MSG_JOYSTICK4 81
#define MSG_LEFTKYBD 82
#define MSG_RIGHTKYBD 83
#define MSG_EASY 84
#define MSG_NORMAL 85
#define MSG_HARD 86
#define MSG_DESC_AFFIXER 87
#define MSG_DESC_AMMO 88
#define MSG_DESC_ARMOUR 89
#define MSG_DESC_AUTOJUMP 90
#define MSG_DESC_BONUS 91
#define MSG_DESC_BRAKES 92
#define MSG_DESC_CUTTER 93
#define MSG_DESC_CYCLONE 94
#define MSG_DESC_ENCLOSER 95
#define MSG_DESC_GLOW 96
#define MSG_DESC_GRABBER 97
#define MSG_DESC_GROWER 98
#define MSG_DESC_ICE 99
#define MSG_DESC_LIGHTNING 100
#define MSG_DESC_MINIBOMB 101
#define MSG_DESC_MINIHEALER 102
#define MSG_DESC_MINIPULSE 103
#define MSG_DESC_MISSILE 104
#define MSG_DESC_MULTIPLIER 105
#define MSG_DESC_POWER 106
#define MSG_DESC_PROTECTOR 107
#define MSG_DESC_PUSHER 108
#define MSG_DESC_REMNANTS 109
#define MSG_DESC_SIDESHOT 110
#define MSG_DESC_SLAYER 111
#define MSG_DESC_SLOWER 112
#define MSG_DESC_SUPERBOMB 113
#define MSG_DESC_SUPERHEALER 114
#define MSG_DESC_SUPERPULSE 115
#define MSG_DESC_SWITCHER 116
#define MSG_DESC_TREASURE 117
#define MSG_DESC_UMBRELLA 118
#define MSG_TRANSLATOR 119
#define MSG_COMPILEDFOR 120
#define MSG_RUNNINGON 121
#define MSG_PRIORITY 122
#define MSG_PROCESSNUMBER 123
#define MSG_ANT 124
#define MSG_BEAR 125
#define MSG_BIRD 126
#define MSG_BULL 127
#define MSG_BUTTERFLY 128
#define MSG_CAMEL 129
#define MSG_CHICKEN 130
#define MSG_CLOUD 131
#define MSG_CYCLONE 132
#define MSG_DOG 133
#define MSG_EEL 134
#define MSG_ELEPHANT 135
#define MSG_FISH 136
#define MSG_FRAGMENT 137
#define MSG_FROG 138
#define MSG_GIRAFFE 139
#define MSG_GOOSE 140
#define MSG_HORSE 141
#define MSG_KANGAROO 142
#define MSG_KOALA 143
#define MSG_LEMMING 144
#define MSG_MISSILE 145
#define MSG_MONKEY 146
#define MSG_MOUSE 147
#define MSG_OCTOPUS 148
#define MSG_ORB 149
#define MSG_OTTER 150
#define MSG_PANDA 151
#define MSG_RABBIT 152
#define MSG_RAIN 153
#define MSG_RHINOCEROS 154
#define MSG_SALAMANDER 155
#define MSG_SNAIL 156
#define MSG_SNAKE 157
#define MSG_SPIDER 158
#define MSG_SQUID 159
#define MSG_TURTLE 160
#define MSG_ZEBRA 161
#define MSG_CONGRATULATIONS 162
#define MSG_HAIL_ABOUT 163
#define MSG_HAIL_CREATURES 164
#define MSG_HAIL_FRUITS 165
#define MSG_HAIL_OBJECTS 166
#define MSG_POINTS 167
#define MSG_APPLE 168
#define MSG_ORANGE 169
#define MSG_CARROT 170
#define MSG_LEMON 171
#define MSG_RADISH 172
#define MSG_PINEAPPLE 173
#define MSG_LIME 174
#define MSG_PASSIONFRUIT 175
#define MSG_WATERMELON 176
#define MSG_COCONUT 177
#define MSG_PEAR 178
#define MSG_CORN 179
#define MSG_BLACKBERRY 180
#define MSG_BLUEBERRY 181
#define MSG_STRAWBERRY 182
#define MSG_CELERY 183
#define MSG_TURNIP 184
#define MSG_KIWIFRUIT 185
#define MSG_MANGO 186
#define MSG_LETTUCE 187
#define MSG_DELETELSET 188
#define MSG_DELETED 189
#define MSG_CANTDELETE 190
#define MSG_OPENLSET 191
#define MSG_LOADING 192
#define MSG_OPENED 193
#define MSG_CANTOPEN 194
#define MSG_SAVELSET 195
#define MSG_SAVING 196
#define MSG_SAVED 197
#define MSG_CANTSAVE 198
#define MSG_PAUSED 199
#define MSG_UNPAUSED 200
#define MSG_LOADINGFX 201
#define MSG_LOADINGMUSIC 202
#define MSG_NOPORT 203
#define MSG_NOMEMORY 204
#define MSG_NOCHANNELS 205
#define MSG_INSTRUCTIONS 206
#define MSG_INTRODUCING 207
#define MSG_POINTS2 208
#define MSG_NEWDONE 209
#define MSG_NOWORMS 210
#define MSG_MODIFIED 211
#define MSG_CONTINUECANCEL 212
#define MSG_ALL 213
#define MSG_STICKYON 214
#define MSG_STICKYOFF 215
#define MSG_STARTGAME 216
#define MSG_LEVELEDITOR 217
#define MSG_FX 218
#define MSG_MUSIC 219
#define MSG_SHUFFLE 220
#define MSG_DIFFICULTY 221
#define MSG_WORM1 222
#define MSG_WORM2 223
#define MSG_WORM3 224
#define MSG_WORM4 225
#define MSG_SINGLE 226
#define MSG_TRIPLE 227
#define MSG_QUINTUPLE 228
#define MSG_SEPTUPLE 229
#define MSG_GAMEOVER 230
#define MSG_GREEN 231
#define MSG_RED 232
#define MSG_BLUE 233
#define MSG_YELLOW 234
#define MSG_LEVEL 235
#define MSG_BONUSLEVEL 236
#define MSG_TIMEEXPIRED 237
#define MSG_FAST 238
#define MSG_NORMAL2 239
#define MSG_SLOW 240
#define MSG_STOPPED 241
#define MSG_BONUS_ORBS 242
#define MSG_BONUS_BANANAS 243
#define MSG_BONUS_RAIN 244
#define MSG_BONUS_OBJECTS 245
#define MSG_BONUS_BUTTERFLIES 246
#define MSG_BONUS_RABBITS 247
#define MSG_LEVELBONUS 248
#define MSG_NUMBERBONUS 249
#define MSG_TIMEBONUS 250
#define MSG_DIMBONUS 251
#define MSG_GLOWBONUS 252
#define MSG_OPENLSET2 253
#define MSG_SAVELSET2 254
#define MSG_HIGHSCORES 255
#define MSG_WORMCONTROLS 256
#define MSG_SHUFFLE2 257
#define MSG_ENGRAVED2 258
#define MSG_DIFFICULTY2 259
#define MSG_SOUND 260
#define MSG_FX2 261
#define MSG_MUSIC2 262
#define MSG_LANGUAGE 263
#define MSG_ENG 264
#define MSG_GER 265
#define MSG_ITA 266
#define MSG_STARTGAME2 267
#define MSG_SCORE 268
#define MSG_LEVEL2 269
#define MSG_NAME 270
#define MSG_TIME 271
#define MSG_DATE 272
#define MSG_CREATURES 273
#define MSG_OBJECTS 274
#define MSG_FRUITS 275
#define MSG_MANUAL 276
#define MSG_ABOUT 277
#define MSG_GREENWORM 278
#define MSG_REDWORM 279
#define MSG_BLUEWORM 280
#define MSG_YELLOWWORM 281
#define MSG_RESOLUTION 282
#define MSG_POINTS3 283
#define MSG_OK 284
#define MSG_INSTRUCTIONS2 285
#define MSG_INSTRUCTIONS3 286
#define MSG_INSTRUCTIONS4 287
#define MSG_SPA 288
#define MSG_INSTRUCTIONS5 289
#define MSG_INSTRUCTIONS6 290
#define MSG_INSTRUCTIONS7 291
#define MSG_DESC_BACKWARDS 292
#define MSG_DESC_FORWARDS 293
#define MSG_INSTRUCTIONS8 294
#define MSG_GRE 295
#define MSG_DESC_TAMER 296
#define MSG_DESC_GRENADE 297
#define MSG_BONUS_ENCLOSE 298
#define MSG_BONUS_CHERRIES 299
#define MSG_BONUS_PATH 300
#define MSG_CONTINUE 301
#define MSG_LEVELEDITOR2 302
#define MSG_SYSTEM_INFORMATION 303
#define MSG_MENU_QUITTITLE 304
#define MSG_MENU_PREVIOUS 305
#define MSG_MENU_NEXT 306
#define MSG_BONUS_DOGS 307
#define MSG_BONUS_SNAKES 308
#define MSG_BONUS_BULLS 309
#define MSG_BY 310
#define MSG_TRANSLATOR1 311
#define MSG_TRANSLATOR2 312
#define MSG_S_M_R 313
#define MSG_RECOVERABLE 314
#define MSG_FATAL 315
#define MSG_APPDESC 316
#define MSG_SOUND2 317
#define MSG_LEVELEDITOR3 318
#define MSG_INSTRUCTIONS9 319
#define MSG_INSTRUCTIONS10 320
#define MSG_INSTRUCTIONS11 321
#define MSG_INSTRUCTIONS12 322
#define MSG_MENU_HELP2 323
#define MSG_SOFTDRINK 324
#define MSG_PIZZA 325
#define MSG_FRIES 326
#define MSG_ICECREAM 327
#define MSG_HAMBURGER 328
#define MSG_MODIFIEDSCORES 329
#define MSG_MENU_UPDATE 330
#define MSG_KEY_UPDATE 331
#define MSG_UPDATE_YES 332
#define MSG_UPDATE_NO 333
#define MSG_POL 334
#define MSG_ISOMETRIC 335
#define MSG_PORCUPINE 336
#define MSG_WHATSCREEN 337
#define MSG_CUSTOMWB 338
#define MSG_PUBSCREEN 339
#define MSG_TERMITE 340
#define MSG_BONUS_JUMP 341
#define MSG_DESC_AUTOTURN 342
#define MSG_VERYHARD 343
#define MSG_OPTIONS 344
#define MSG_BAT 345
#define MSG_AUTOSAVE 346
#define MSG_STARTGAME3 347
#define MSG_MANUAL2 348
#define MSG_ABOUT2 349
#define MSG_OK2 350
#define MSG_3DWORMS 351
#define MSG_RUS 352
#define MSG_MULTIPLIER 353

#endif /* CATCOMP_NUMBERS */


/****************************************************************************/


#ifdef CATCOMP_STRINGS

#define MSG_MENU_PROJECT_STR "Project"
#define MSG_MENU_NEW_STR "New"
#define MSG_KEY_NEW_STR "N"
#define MSG_MENU_OPEN_STR "Open..."
#define MSG_KEY_OPEN_STR "O"
#define MSG_MENU_SAVE1_STR "Save"
#define MSG_KEY_SAVE_STR "S"
#define MSG_MENU_SAVEAS_STR "Save As..."
#define MSG_KEY_SAVEAS_STR "A"
#define MSG_MENU_PRINT_STR "Print"
#define MSG_KEY_PRINT_STR "P"
#define MSG_MENU_PRINTAS_STR "Print As..."
#define MSG_MENU_HIDE_STR "Hide"
#define MSG_MENU_REVEAL_STR "Reveal..."
#define MSG_MENU_CLOSE_STR "Close"
#define MSG_MENU_ABOUT_STR "About..."
#define MSG_KEY_ABOUT_STR "?"
#define MSG_MENU_EXIT_STR "Exit"
#define MSG_MENU_QUIT_STR "Quit..."
#define MSG_KEY_QUIT_STR "Q"
#define MSG_MENU_EDIT_STR "Edit"
#define MSG_MENU_CUT_STR "Cut"
#define MSG_KEY_CUT_STR "X"
#define MSG_MENU_COPY_STR "Copy"
#define MSG_KEY_COPY_STR "C"
#define MSG_MENU_PASTE_STR "Paste"
#define MSG_KEY_PASTE_STR "V"
#define MSG_MENU_ERASE_STR "Erase"
#define MSG_KEY_ERASE_STR "E"
#define MSG_MENU_UNDO_STR "Undo"
#define MSG_KEY_UNDO_STR "Z"
#define MSG_MENU_REDO_STR "Redo"
#define MSG_MENU_MACROS_STR "Macros"
#define MSG_MENU_STARTLEARNING_STR "Start Learning"
#define MSG_MENU_STOPLEARNING_STR "Stop Learning"
#define MSG_MENU_ASSIGNMACRO_STR "Assign Macro..."
#define MSG_MENU_LOAD_STR "Load..."
#define MSG_MENU_SAVE2_STR "Save..."
#define MSG_MENU_SETTINGS_STR "Settings"
#define MSG_MENU_CREATEICONS_STR "Create Icons?"
#define MSG_KEY_CREATEICONS_STR "I"
#define MSG_MENU_LOADSETTINGS_STR "Load Settings..."
#define MSG_MENU_SAVESETTINGS_STR "Save Settings"
#define MSG_MENU_SAVESETTINGSAS_STR "Save Settings As..."
#define MSG_MENU_USER_STR "User"
#define MSG_MENU_HELP_STR "Help"
#define MSG_MENU_ICONIFY_STR "Iconify"
#define MSG_MENU_MANUAL_STR "Manual..."
#define MSG_KEY_MANUAL_STR "M"
#define MSG_MENU_POINTER_STR "Pointer?"
#define MSG_MENU_REVERT_STR "Revert"
#define MSG_KEY_REVERT_STR "R"
#define MSG_MENU_TITLEBAR_STR "Titlebar?"
#define MSG_MENU_TOOLS_STR "Tools"
#define MSG_MENU_VIEW_STR "View"
#define MSG_CANTLOCK_NAMED_STR "Can't lock public screen \"%s\"!"
#define MSG_CANTLOCK_DEFAULT_STR "Can't lock default public screen!"
#define MSG_MENU_PROJECTDELETE_STR "Delete..."
#define MSG_SHORTCUT_PROJECTDELETE_STR "D"
#define MSG_MENU_QUITWB_STR "Quit Worm Wars"
#define MSG_MENU_EDITDELETE_STR "Delete"
#define MSG_MENU_INSERT_STR "Insert"
#define MSG_MENU_APPEND_STR "Append"
#define MSG_MENU_CLEARHS_STR "Clear high scores"
#define MSG_SHORTCUT_POINTER_STR "P"
#define MSG_SHORTCUT_TITLEBAR_STR "B"
#define MSG_MENU_ANIMATIONS_STR "Animations?"
#define MSG_SHORTCUT_ANIMATIONS_STR "T"
#define MSG_MENU_ENGRAVEDSQUARES_STR "Engraved squares?"
#define MSG_MENU_CREATURES_STR "Creatures..."
#define MSG_MENU_OBJECTS_STR "Objects..."
#define MSG_MENU_FRUITS_STR "Fruits..."
#define MSG_MENU_ABOUTWW_STR "About Worm Wars..."
#define MSG_NONE_STR "None"
#define MSG_GAMEPAD1_STR "Gamepad 1"
#define MSG_GAMEPAD2_STR "Gamepad 2"
#define MSG_GAMEPAD3_STR "Gamepad 3"
#define MSG_GAMEPAD4_STR "Gamepad 4"
#define MSG_JOYSTICK1_STR "Joystick 1"
#define MSG_JOYSTICK2_STR "Joystick 2"
#define MSG_JOYSTICK3_STR "Joystick 3"
#define MSG_JOYSTICK4_STR "Joystick 4"
#define MSG_LEFTKYBD_STR "Lt. Kybd"
#define MSG_RIGHTKYBD_STR "Rt. Kybd"
#define MSG_EASY_STR "Easy"
#define MSG_NORMAL_STR "Normal"
#define MSG_HARD_STR "Hard"
#define MSG_DESC_AFFIXER_STR "AFFIXER: Stops protectors rotating."
#define MSG_DESC_AMMO_STR "AMMO: 5 bullets."
#define MSG_DESC_ARMOUR_STR "ARMOUR: Immune to most damage."
#define MSG_DESC_AUTOJUMP_STR "AUTOJUMP: Automagically jump."
#define MSG_DESC_BONUS_STR "BONUS: Awards the next number."
#define MSG_DESC_BRAKES_STR "BRAKES: Allows stopping."
#define MSG_DESC_CUTTER_STR "CUTTER: Cuts a tunnel through tail."
#define MSG_DESC_CYCLONE_STR "CYCLONE: Unleashes a cyclone."
#define MSG_DESC_ENCLOSER_STR "ENCLOSER: Rectangular enclosure."
#define MSG_DESC_GLOW_STR "GLOW: Leaves a glowing tail."
#define MSG_DESC_GRABBER_STR "GRABBER: Grabs all objects."
#define MSG_DESC_GROWER_STR "GROWER: Enlarges silver, gold, etc."
#define MSG_DESC_ICE_STR "ICE: Freezes enemies."
#define MSG_DESC_LIGHTNING_STR "LIGHTNING: Flashes around tail."
#define MSG_DESC_MINIBOMB_STR "MINI BOMB: A minor explosion."
#define MSG_DESC_MINIHEALER_STR "MINI HEALER: 5 lives."
#define MSG_DESC_MINIPULSE_STR "MINI PULSE: A minor fragment burst."
#define MSG_DESC_MISSILE_STR "MISSILE: Launches a guided missile."
#define MSG_DESC_MULTIPLIER_STR "MULTIPLIER: Double points."
#define MSG_DESC_POWER_STR "POWERUP: Thicker bullets."
#define MSG_DESC_PROTECTOR_STR "PROTECTOR: An orbiting companion."
#define MSG_DESC_PUSHER_STR "PUSHER: Lets you push things."
#define MSG_DESC_REMNANTS_STR "REMNANTS: Bullets leave a trail."
#define MSG_DESC_SIDESHOT_STR "SIDESHOT: Shoot sideways."
#define MSG_DESC_SLAYER_STR "SLAYER: Smart bomb."
#define MSG_DESC_SLOWER_STR "SLOWER: Slows creatures down."
#define MSG_DESC_SUPERBOMB_STR "SUPER BOMB: A major explosion."
#define MSG_DESC_SUPERHEALER_STR "SUPER HEALER: 10 lives."
#define MSG_DESC_SUPERPULSE_STR "SUPER PULSE: A major fragment burst."
#define MSG_DESC_SWITCHER_STR "SWITCHER: Changes tail colours."
#define MSG_DESC_TREASURE_STR "TREASURE: Treasure level."
#define MSG_DESC_UMBRELLA_STR "UMBRELLA: Skips 2-3 levels."
#define MSG_TRANSLATOR_STR "English translation by James Jacobs"
#define MSG_COMPILEDFOR_STR "Compiled for:"
#define MSG_RUNNINGON_STR "Running on:"
#define MSG_PRIORITY_STR "Priority:"
#define MSG_PROCESSNUMBER_STR "Process number:"
#define MSG_ANT_STR "Ant"
#define MSG_BEAR_STR "Bear"
#define MSG_BIRD_STR "Bird"
#define MSG_BULL_STR "Bull"
#define MSG_BUTTERFLY_STR "Butterfly"
#define MSG_CAMEL_STR "Camel"
#define MSG_CHICKEN_STR "Chicken"
#define MSG_CLOUD_STR "Cloud"
#define MSG_CYCLONE_STR "Cyclone"
#define MSG_DOG_STR "Dog"
#define MSG_EEL_STR "Eel"
#define MSG_ELEPHANT_STR "Elephant"
#define MSG_FISH_STR "Fish"
#define MSG_FRAGMENT_STR "Fragment"
#define MSG_FROG_STR "Frog"
#define MSG_GIRAFFE_STR "Giraffe"
#define MSG_GOOSE_STR "Goose"
#define MSG_HORSE_STR "Horse"
#define MSG_KANGAROO_STR "Kangaroo"
#define MSG_KOALA_STR "Koala"
#define MSG_LEMMING_STR "Lemming"
#define MSG_MISSILE_STR "Missile"
#define MSG_MONKEY_STR "Monkey"
#define MSG_MOUSE_STR "Mouse"
#define MSG_OCTOPUS_STR "Octopus"
#define MSG_ORB_STR "Orb"
#define MSG_OTTER_STR "Otter"
#define MSG_PANDA_STR "Panda"
#define MSG_RABBIT_STR "Rabbit"
#define MSG_RAIN_STR "Rain"
#define MSG_RHINOCEROS_STR "Rhinoceros"
#define MSG_SALAMANDER_STR "Salamander"
#define MSG_SNAIL_STR "Snail"
#define MSG_SNAKE_STR "Snake"
#define MSG_SPIDER_STR "Spider"
#define MSG_SQUID_STR "Squid"
#define MSG_TURTLE_STR "Turtle"
#define MSG_ZEBRA_STR "Zebra"
#define MSG_CONGRATULATIONS_STR "CONGRATULATIONS!"
#define MSG_HAIL_ABOUT_STR "About Worm Wars"
#define MSG_HAIL_CREATURES_STR "Creatures"
#define MSG_HAIL_FRUITS_STR "Fruits"
#define MSG_HAIL_OBJECTS_STR "Objects"
#define MSG_POINTS_STR "Pts"
#define MSG_APPLE_STR "Apple"
#define MSG_ORANGE_STR "Orange"
#define MSG_CARROT_STR "Carrot"
#define MSG_LEMON_STR "Lemon"
#define MSG_RADISH_STR "Radish"
#define MSG_PINEAPPLE_STR "Pineapple"
#define MSG_LIME_STR "Lime"
#define MSG_PASSIONFRUIT_STR "Passionfruit"
#define MSG_WATERMELON_STR "Watermelon"
#define MSG_COCONUT_STR "Coconut"
#define MSG_PEAR_STR "Pear"
#define MSG_CORN_STR "Corn"
#define MSG_BLACKBERRY_STR "Blackberry"
#define MSG_BLUEBERRY_STR "Blueberry"
#define MSG_STRAWBERRY_STR "Strawberry"
#define MSG_CELERY_STR "Celery"
#define MSG_TURNIP_STR "Turnip"
#define MSG_KIWIFRUIT_STR "Kiwifruit"
#define MSG_MANGO_STR "Mango"
#define MSG_LETTUCE_STR "Lettuce"
#define MSG_DELETELSET_STR "Delete Levelset"
#define MSG_DELETED_STR "Deleted %s."
#define MSG_CANTDELETE_STR "Can't delete %s!"
#define MSG_OPENLSET_STR "Load levelset..."
#define MSG_LOADING_STR "Loading %s..."
#define MSG_OPENED_STR "Opened %s (%d levels)."
#define MSG_CANTOPEN_STR "Can't open %s!"
#define MSG_SAVELSET_STR "Save levelset..."
#define MSG_SAVING_STR "Saving %s..."
#define MSG_SAVED_STR "Saved %s (%d levels)."
#define MSG_CANTSAVE_STR "Can't save %s!"
#define MSG_PAUSED_STR "Paused...press P to unpause"
#define MSG_UNPAUSED_STR "Unpaused"
#define MSG_LOADINGFX_STR "Loading sound effects..."
#define MSG_LOADINGMUSIC_STR "Loading music..."
#define MSG_NOPORT_STR "No port for sound effects!"
#define MSG_NOMEMORY_STR "No memory for sound effects!"
#define MSG_NOCHANNELS_STR "Can't allocate all channels!"
#define MSG_INSTRUCTIONS_STR "Collect or shoot numbers 1-9 to clear level."
#define MSG_INTRODUCING_STR "Introducing:"
#define MSG_POINTS2_STR "points"
#define MSG_NEWDONE_STR "New done."
#define MSG_NOWORMS_STR "No worms active!"
#define MSG_MODIFIED_STR "Level data has been modified."
#define MSG_CONTINUECANCEL_STR "Continue|Cancel"
#define MSG_ALL_STR "All"
#define MSG_STICKYON_STR "Sticky mode on"
#define MSG_STICKYOFF_STR "Sticky mode off"
#define MSG_STARTGAME_STR "Start Game (ENTER)"
#define MSG_LEVELEDITOR_STR "Level Editor"
#define MSG_FX_STR "Sound Effects"
#define MSG_MUSIC_STR "Music"
#define MSG_SHUFFLE_STR "_Shuffle Levels?"
#define MSG_DIFFICULTY_STR "_Difficulty:"
#define MSG_WORM1_STR "Worm _1:"
#define MSG_WORM2_STR "Worm _2:"
#define MSG_WORM3_STR "Worm _3:"
#define MSG_WORM4_STR "Worm _4:"
#define MSG_SINGLE_STR "Single"
#define MSG_TRIPLE_STR "Triple"
#define MSG_QUINTUPLE_STR "Quint."
#define MSG_SEPTUPLE_STR "Sept."
#define MSG_GAMEOVER_STR "Game over!"
#define MSG_GREEN_STR "(Green)"
#define MSG_RED_STR "(Red)"
#define MSG_BLUE_STR "(Blue)"
#define MSG_YELLOW_STR "(Yellow)"
#define MSG_LEVEL_STR "Level %d of %d"
#define MSG_BONUSLEVEL_STR "Bonus Level"
#define MSG_TIMEEXPIRED_STR "Time expired!"
#define MSG_FAST_STR "Fast"
#define MSG_NORMAL2_STR "Normal"
#define MSG_SLOW_STR "Slow"
#define MSG_STOPPED_STR "Stopped"
#define MSG_BONUS_ORBS_STR "Capture the Orbs"
#define MSG_BONUS_BANANAS_STR "Eat the Bananas"
#define MSG_BONUS_RAIN_STR "Drink the Rain"
#define MSG_BONUS_OBJECTS_STR "Grab the Objects"
#define MSG_BONUS_BUTTERFLIES_STR "Touch the Butterflies"
#define MSG_BONUS_RABBITS_STR "Hunt the Rabbits"
#define MSG_LEVELBONUS_STR "Level Bonus"
#define MSG_NUMBERBONUS_STR "Number Bonus"
#define MSG_TIMEBONUS_STR "Time Bonus"
#define MSG_DIMBONUS_STR "Dim Bonus"
#define MSG_GLOWBONUS_STR "Glow Bonus"
#define MSG_OPENLSET2_STR "&Load levelset..."
#define MSG_SAVELSET2_STR "&Save levelset..."
#define MSG_HIGHSCORES_STR "High Score Table"
#define MSG_WORMCONTROLS_STR "Worm Controls"
#define MSG_SHUFFLE2_STR "Shuffle le&vels?"
#define MSG_ENGRAVED2_STR "Engraved s&quares?"
#define MSG_DIFFICULTY2_STR "Difficulty"
#define MSG_SOUND_STR "Sound"
#define MSG_FX2_STR "E&ffects?"
#define MSG_MUSIC2_STR "&Music?"
#define MSG_LANGUAGE_STR "Language"
#define MSG_ENG_STR "English"
#define MSG_GER_STR "German"
#define MSG_ITA_STR "Italian"
#define MSG_STARTGAME2_STR "Start &Game"
#define MSG_SCORE_STR "Score"
#define MSG_LEVEL2_STR "Level"
#define MSG_NAME_STR "Name"
#define MSG_TIME_STR "Time"
#define MSG_DATE_STR "Date"
#define MSG_CREATURES_STR "&Creatures..."
#define MSG_OBJECTS_STR "&Objects..."
#define MSG_FRUITS_STR "F&ruits..."
#define MSG_MANUAL_STR "Ma&nual..."
#define MSG_ABOUT_STR "&About..."
#define MSG_GREENWORM_STR "Green Worm"
#define MSG_REDWORM_STR "Red Worm"
#define MSG_BLUEWORM_STR "Blue Worm"
#define MSG_YELLOWWORM_STR "Yellow Worm"
#define MSG_RESOLUTION_STR "Resolution"
#define MSG_POINTS3_STR "Points"
#define MSG_OK_STR "&OK"
#define MSG_INSTRUCTIONS2_STR "Make square enclosures to kill creatures."
#define MSG_INSTRUCTIONS3_STR "Jump further when moving faster."
#define MSG_INSTRUCTIONS4_STR "Some obstacles can be shot."
#define MSG_SPA_STR "Spanish"
#define MSG_INSTRUCTIONS5_STR "These are teleports."
#define MSG_INSTRUCTIONS6_STR "Extra life every 1,000 points."
#define MSG_INSTRUCTIONS7_STR "Monkeys throw bananas; catch them for points."
#define MSG_DESC_BACKWARDS_STR "BACKWARDS: Shoot diagonally backwards."
#define MSG_DESC_FORWARDS_STR "FORWARDS: Shoot diagonally forwards."
#define MSG_INSTRUCTIONS8_STR "Go under clouds to catch rain."
#define MSG_GRE_STR "Greek"
#define MSG_DESC_TAMER_STR "TAMER: Changes evil creatures to good."
#define MSG_DESC_GRENADE_STR "GRENADE: Super bomb when shooting."
#define MSG_BONUS_ENCLOSE_STR "Make Enclosures"
#define MSG_BONUS_CHERRIES_STR "Eat the Cherries"
#define MSG_BONUS_PATH_STR "Follow the Path"
#define MSG_CONTINUE_STR "Continue?"
#define MSG_LEVELEDITOR2_STR "Level &Editor"
#define MSG_SYSTEM_INFORMATION_STR "&System information..."
#define MSG_MENU_QUITTITLE_STR "Quit to title screen (Space)"
#define MSG_MENU_PREVIOUS_STR "Previous level (Del)"
#define MSG_MENU_NEXT_STR "Next level (Help)"
#define MSG_BONUS_DOGS_STR "Flee the Dogs"
#define MSG_BONUS_SNAKES_STR "Survive the Snakes"
#define MSG_BONUS_BULLS_STR "Enrage the Bulls"
#define MSG_BY_STR "By"
#define MSG_TRANSLATOR1_STR "English translation by"
#define MSG_TRANSLATOR2_STR "James Jacobs"
#define MSG_S_M_R_STR "Screen Mode Requester"
#define MSG_RECOVERABLE_STR "Recoverable Error"
#define MSG_FATAL_STR "Fatal Error"
#define MSG_APPDESC_STR "Arcade game"
#define MSG_SOUND2_STR "Sound:"
#define MSG_LEVELEDITOR3_STR "Level Editor (Spacebar)"
#define MSG_INSTRUCTIONS9_STR "You can also make diagonal enclosures."
#define MSG_INSTRUCTIONS10_STR "Prefer your own colour for more points."
#define MSG_INSTRUCTIONS11_STR "Fragments bounce off metal."
#define MSG_INSTRUCTIONS12_STR "Worms can't turn while traversing frost."
#define MSG_MENU_HELP2_STR "Help"
#define MSG_SOFTDRINK_STR "Soft drink"
#define MSG_PIZZA_STR "Pizza"
#define MSG_FRIES_STR "Fries"
#define MSG_ICECREAM_STR "Ice cream"
#define MSG_HAMBURGER_STR "Hamburger"
#define MSG_MODIFIEDSCORES_STR "High scores have been modified."
#define MSG_MENU_UPDATE_STR "Check for updates..."
#define MSG_KEY_UPDATE_STR "U"
#define MSG_UPDATE_YES_STR "is available"
#define MSG_UPDATE_NO_STR "You are up to date."
#define MSG_POL_STR "Polish"
#define MSG_ISOMETRIC_STR "Isometric?"
#define MSG_PORCUPINE_STR "Porcupine"
#define MSG_WHATSCREEN_STR "What screen do you want to run the game on?"
#define MSG_CUSTOMWB_STR "Custom screen|Workbench screen"
#define MSG_PUBSCREEN_STR "Public screen name:"
#define MSG_TERMITE_STR "Termite"
#define MSG_BONUS_JUMP_STR "Jump the Walls"
#define MSG_DESC_AUTOTURN_STR "AUTOTURN: Automagically turn."
#define MSG_VERYHARD_STR "Very Hard"
#define MSG_OPTIONS_STR "Options"
#define MSG_BAT_STR "Bat"
#define MSG_AUTOSAVE_STR "Autosave levelset?"
#define MSG_STARTGAME3_STR "Start Game"
#define MSG_MANUAL2_STR "Manual..."
#define MSG_ABOUT2_STR "About..."
#define MSG_OK2_STR "OK"
#define MSG_3DWORMS_STR "&3D worms?"
#define MSG_RUS_STR "Russian"
#define MSG_MULTIPLIER_STR "×"

#endif /* CATCOMP_STRINGS */


/****************************************************************************/


#ifdef CATCOMP_ARRAY

struct CatCompArrayType
{
    LONG   cca_ID;
    STRPTR cca_Str;
};

static const struct CatCompArrayType CatCompArray[] =
{
    {MSG_MENU_PROJECT,(STRPTR)MSG_MENU_PROJECT_STR},
    {MSG_MENU_NEW,(STRPTR)MSG_MENU_NEW_STR},
    {MSG_KEY_NEW,(STRPTR)MSG_KEY_NEW_STR},
    {MSG_MENU_OPEN,(STRPTR)MSG_MENU_OPEN_STR},
    {MSG_KEY_OPEN,(STRPTR)MSG_KEY_OPEN_STR},
    {MSG_MENU_SAVE1,(STRPTR)MSG_MENU_SAVE1_STR},
    {MSG_KEY_SAVE,(STRPTR)MSG_KEY_SAVE_STR},
    {MSG_MENU_SAVEAS,(STRPTR)MSG_MENU_SAVEAS_STR},
    {MSG_KEY_SAVEAS,(STRPTR)MSG_KEY_SAVEAS_STR},
    {MSG_MENU_PRINT,(STRPTR)MSG_MENU_PRINT_STR},
    {MSG_KEY_PRINT,(STRPTR)MSG_KEY_PRINT_STR},
    {MSG_MENU_PRINTAS,(STRPTR)MSG_MENU_PRINTAS_STR},
    {MSG_MENU_HIDE,(STRPTR)MSG_MENU_HIDE_STR},
    {MSG_MENU_REVEAL,(STRPTR)MSG_MENU_REVEAL_STR},
    {MSG_MENU_CLOSE,(STRPTR)MSG_MENU_CLOSE_STR},
    {MSG_MENU_ABOUT,(STRPTR)MSG_MENU_ABOUT_STR},
    {MSG_KEY_ABOUT,(STRPTR)MSG_KEY_ABOUT_STR},
    {MSG_MENU_EXIT,(STRPTR)MSG_MENU_EXIT_STR},
    {MSG_MENU_QUIT,(STRPTR)MSG_MENU_QUIT_STR},
    {MSG_KEY_QUIT,(STRPTR)MSG_KEY_QUIT_STR},
    {MSG_MENU_EDIT,(STRPTR)MSG_MENU_EDIT_STR},
    {MSG_MENU_CUT,(STRPTR)MSG_MENU_CUT_STR},
    {MSG_KEY_CUT,(STRPTR)MSG_KEY_CUT_STR},
    {MSG_MENU_COPY,(STRPTR)MSG_MENU_COPY_STR},
    {MSG_KEY_COPY,(STRPTR)MSG_KEY_COPY_STR},
    {MSG_MENU_PASTE,(STRPTR)MSG_MENU_PASTE_STR},
    {MSG_KEY_PASTE,(STRPTR)MSG_KEY_PASTE_STR},
    {MSG_MENU_ERASE,(STRPTR)MSG_MENU_ERASE_STR},
    {MSG_KEY_ERASE,(STRPTR)MSG_KEY_ERASE_STR},
    {MSG_MENU_UNDO,(STRPTR)MSG_MENU_UNDO_STR},
    {MSG_KEY_UNDO,(STRPTR)MSG_KEY_UNDO_STR},
    {MSG_MENU_REDO,(STRPTR)MSG_MENU_REDO_STR},
    {MSG_MENU_MACROS,(STRPTR)MSG_MENU_MACROS_STR},
    {MSG_MENU_STARTLEARNING,(STRPTR)MSG_MENU_STARTLEARNING_STR},
    {MSG_MENU_STOPLEARNING,(STRPTR)MSG_MENU_STOPLEARNING_STR},
    {MSG_MENU_ASSIGNMACRO,(STRPTR)MSG_MENU_ASSIGNMACRO_STR},
    {MSG_MENU_LOAD,(STRPTR)MSG_MENU_LOAD_STR},
    {MSG_MENU_SAVE2,(STRPTR)MSG_MENU_SAVE2_STR},
    {MSG_MENU_SETTINGS,(STRPTR)MSG_MENU_SETTINGS_STR},
    {MSG_MENU_CREATEICONS,(STRPTR)MSG_MENU_CREATEICONS_STR},
    {MSG_KEY_CREATEICONS,(STRPTR)MSG_KEY_CREATEICONS_STR},
    {MSG_MENU_LOADSETTINGS,(STRPTR)MSG_MENU_LOADSETTINGS_STR},
    {MSG_MENU_SAVESETTINGS,(STRPTR)MSG_MENU_SAVESETTINGS_STR},
    {MSG_MENU_SAVESETTINGSAS,(STRPTR)MSG_MENU_SAVESETTINGSAS_STR},
    {MSG_MENU_USER,(STRPTR)MSG_MENU_USER_STR},
    {MSG_MENU_HELP,(STRPTR)MSG_MENU_HELP_STR},
    {MSG_MENU_ICONIFY,(STRPTR)MSG_MENU_ICONIFY_STR},
    {MSG_MENU_MANUAL,(STRPTR)MSG_MENU_MANUAL_STR},
    {MSG_KEY_MANUAL,(STRPTR)MSG_KEY_MANUAL_STR},
    {MSG_MENU_POINTER,(STRPTR)MSG_MENU_POINTER_STR},
    {MSG_MENU_REVERT,(STRPTR)MSG_MENU_REVERT_STR},
    {MSG_KEY_REVERT,(STRPTR)MSG_KEY_REVERT_STR},
    {MSG_MENU_TITLEBAR,(STRPTR)MSG_MENU_TITLEBAR_STR},
    {MSG_MENU_TOOLS,(STRPTR)MSG_MENU_TOOLS_STR},
    {MSG_MENU_VIEW,(STRPTR)MSG_MENU_VIEW_STR},
    {MSG_CANTLOCK_NAMED,(STRPTR)MSG_CANTLOCK_NAMED_STR},
    {MSG_CANTLOCK_DEFAULT,(STRPTR)MSG_CANTLOCK_DEFAULT_STR},
    {MSG_MENU_PROJECTDELETE,(STRPTR)MSG_MENU_PROJECTDELETE_STR},
    {MSG_SHORTCUT_PROJECTDELETE,(STRPTR)MSG_SHORTCUT_PROJECTDELETE_STR},
    {MSG_MENU_QUITWB,(STRPTR)MSG_MENU_QUITWB_STR},
    {MSG_MENU_EDITDELETE,(STRPTR)MSG_MENU_EDITDELETE_STR},
    {MSG_MENU_INSERT,(STRPTR)MSG_MENU_INSERT_STR},
    {MSG_MENU_APPEND,(STRPTR)MSG_MENU_APPEND_STR},
    {MSG_MENU_CLEARHS,(STRPTR)MSG_MENU_CLEARHS_STR},
    {MSG_SHORTCUT_POINTER,(STRPTR)MSG_SHORTCUT_POINTER_STR},
    {MSG_SHORTCUT_TITLEBAR,(STRPTR)MSG_SHORTCUT_TITLEBAR_STR},
    {MSG_MENU_ANIMATIONS,(STRPTR)MSG_MENU_ANIMATIONS_STR},
    {MSG_SHORTCUT_ANIMATIONS,(STRPTR)MSG_SHORTCUT_ANIMATIONS_STR},
    {MSG_MENU_ENGRAVEDSQUARES,(STRPTR)MSG_MENU_ENGRAVEDSQUARES_STR},
    {MSG_MENU_CREATURES,(STRPTR)MSG_MENU_CREATURES_STR},
    {MSG_MENU_OBJECTS,(STRPTR)MSG_MENU_OBJECTS_STR},
    {MSG_MENU_FRUITS,(STRPTR)MSG_MENU_FRUITS_STR},
    {MSG_MENU_ABOUTWW,(STRPTR)MSG_MENU_ABOUTWW_STR},
    {MSG_NONE,(STRPTR)MSG_NONE_STR},
    {MSG_GAMEPAD1,(STRPTR)MSG_GAMEPAD1_STR},
    {MSG_GAMEPAD2,(STRPTR)MSG_GAMEPAD2_STR},
    {MSG_GAMEPAD3,(STRPTR)MSG_GAMEPAD3_STR},
    {MSG_GAMEPAD4,(STRPTR)MSG_GAMEPAD4_STR},
    {MSG_JOYSTICK1,(STRPTR)MSG_JOYSTICK1_STR},
    {MSG_JOYSTICK2,(STRPTR)MSG_JOYSTICK2_STR},
    {MSG_JOYSTICK3,(STRPTR)MSG_JOYSTICK3_STR},
    {MSG_JOYSTICK4,(STRPTR)MSG_JOYSTICK4_STR},
    {MSG_LEFTKYBD,(STRPTR)MSG_LEFTKYBD_STR},
    {MSG_RIGHTKYBD,(STRPTR)MSG_RIGHTKYBD_STR},
    {MSG_EASY,(STRPTR)MSG_EASY_STR},
    {MSG_NORMAL,(STRPTR)MSG_NORMAL_STR},
    {MSG_HARD,(STRPTR)MSG_HARD_STR},
    {MSG_DESC_AFFIXER,(STRPTR)MSG_DESC_AFFIXER_STR},
    {MSG_DESC_AMMO,(STRPTR)MSG_DESC_AMMO_STR},
    {MSG_DESC_ARMOUR,(STRPTR)MSG_DESC_ARMOUR_STR},
    {MSG_DESC_AUTOJUMP,(STRPTR)MSG_DESC_AUTOJUMP_STR},
    {MSG_DESC_BONUS,(STRPTR)MSG_DESC_BONUS_STR},
    {MSG_DESC_BRAKES,(STRPTR)MSG_DESC_BRAKES_STR},
    {MSG_DESC_CUTTER,(STRPTR)MSG_DESC_CUTTER_STR},
    {MSG_DESC_CYCLONE,(STRPTR)MSG_DESC_CYCLONE_STR},
    {MSG_DESC_ENCLOSER,(STRPTR)MSG_DESC_ENCLOSER_STR},
    {MSG_DESC_GLOW,(STRPTR)MSG_DESC_GLOW_STR},
    {MSG_DESC_GRABBER,(STRPTR)MSG_DESC_GRABBER_STR},
    {MSG_DESC_GROWER,(STRPTR)MSG_DESC_GROWER_STR},
    {MSG_DESC_ICE,(STRPTR)MSG_DESC_ICE_STR},
    {MSG_DESC_LIGHTNING,(STRPTR)MSG_DESC_LIGHTNING_STR},
    {MSG_DESC_MINIBOMB,(STRPTR)MSG_DESC_MINIBOMB_STR},
    {MSG_DESC_MINIHEALER,(STRPTR)MSG_DESC_MINIHEALER_STR},
    {MSG_DESC_MINIPULSE,(STRPTR)MSG_DESC_MINIPULSE_STR},
    {MSG_DESC_MISSILE,(STRPTR)MSG_DESC_MISSILE_STR},
    {MSG_DESC_MULTIPLIER,(STRPTR)MSG_DESC_MULTIPLIER_STR},
    {MSG_DESC_POWER,(STRPTR)MSG_DESC_POWER_STR},
    {MSG_DESC_PROTECTOR,(STRPTR)MSG_DESC_PROTECTOR_STR},
    {MSG_DESC_PUSHER,(STRPTR)MSG_DESC_PUSHER_STR},
    {MSG_DESC_REMNANTS,(STRPTR)MSG_DESC_REMNANTS_STR},
    {MSG_DESC_SIDESHOT,(STRPTR)MSG_DESC_SIDESHOT_STR},
    {MSG_DESC_SLAYER,(STRPTR)MSG_DESC_SLAYER_STR},
    {MSG_DESC_SLOWER,(STRPTR)MSG_DESC_SLOWER_STR},
    {MSG_DESC_SUPERBOMB,(STRPTR)MSG_DESC_SUPERBOMB_STR},
    {MSG_DESC_SUPERHEALER,(STRPTR)MSG_DESC_SUPERHEALER_STR},
    {MSG_DESC_SUPERPULSE,(STRPTR)MSG_DESC_SUPERPULSE_STR},
    {MSG_DESC_SWITCHER,(STRPTR)MSG_DESC_SWITCHER_STR},
    {MSG_DESC_TREASURE,(STRPTR)MSG_DESC_TREASURE_STR},
    {MSG_DESC_UMBRELLA,(STRPTR)MSG_DESC_UMBRELLA_STR},
    {MSG_TRANSLATOR,(STRPTR)MSG_TRANSLATOR_STR},
    {MSG_COMPILEDFOR,(STRPTR)MSG_COMPILEDFOR_STR},
    {MSG_RUNNINGON,(STRPTR)MSG_RUNNINGON_STR},
    {MSG_PRIORITY,(STRPTR)MSG_PRIORITY_STR},
    {MSG_PROCESSNUMBER,(STRPTR)MSG_PROCESSNUMBER_STR},
    {MSG_ANT,(STRPTR)MSG_ANT_STR},
    {MSG_BEAR,(STRPTR)MSG_BEAR_STR},
    {MSG_BIRD,(STRPTR)MSG_BIRD_STR},
    {MSG_BULL,(STRPTR)MSG_BULL_STR},
    {MSG_BUTTERFLY,(STRPTR)MSG_BUTTERFLY_STR},
    {MSG_CAMEL,(STRPTR)MSG_CAMEL_STR},
    {MSG_CHICKEN,(STRPTR)MSG_CHICKEN_STR},
    {MSG_CLOUD,(STRPTR)MSG_CLOUD_STR},
    {MSG_CYCLONE,(STRPTR)MSG_CYCLONE_STR},
    {MSG_DOG,(STRPTR)MSG_DOG_STR},
    {MSG_EEL,(STRPTR)MSG_EEL_STR},
    {MSG_ELEPHANT,(STRPTR)MSG_ELEPHANT_STR},
    {MSG_FISH,(STRPTR)MSG_FISH_STR},
    {MSG_FRAGMENT,(STRPTR)MSG_FRAGMENT_STR},
    {MSG_FROG,(STRPTR)MSG_FROG_STR},
    {MSG_GIRAFFE,(STRPTR)MSG_GIRAFFE_STR},
    {MSG_GOOSE,(STRPTR)MSG_GOOSE_STR},
    {MSG_HORSE,(STRPTR)MSG_HORSE_STR},
    {MSG_KANGAROO,(STRPTR)MSG_KANGAROO_STR},
    {MSG_KOALA,(STRPTR)MSG_KOALA_STR},
    {MSG_LEMMING,(STRPTR)MSG_LEMMING_STR},
    {MSG_MISSILE,(STRPTR)MSG_MISSILE_STR},
    {MSG_MONKEY,(STRPTR)MSG_MONKEY_STR},
    {MSG_MOUSE,(STRPTR)MSG_MOUSE_STR},
    {MSG_OCTOPUS,(STRPTR)MSG_OCTOPUS_STR},
    {MSG_ORB,(STRPTR)MSG_ORB_STR},
    {MSG_OTTER,(STRPTR)MSG_OTTER_STR},
    {MSG_PANDA,(STRPTR)MSG_PANDA_STR},
    {MSG_RABBIT,(STRPTR)MSG_RABBIT_STR},
    {MSG_RAIN,(STRPTR)MSG_RAIN_STR},
    {MSG_RHINOCEROS,(STRPTR)MSG_RHINOCEROS_STR},
    {MSG_SALAMANDER,(STRPTR)MSG_SALAMANDER_STR},
    {MSG_SNAIL,(STRPTR)MSG_SNAIL_STR},
    {MSG_SNAKE,(STRPTR)MSG_SNAKE_STR},
    {MSG_SPIDER,(STRPTR)MSG_SPIDER_STR},
    {MSG_SQUID,(STRPTR)MSG_SQUID_STR},
    {MSG_TURTLE,(STRPTR)MSG_TURTLE_STR},
    {MSG_ZEBRA,(STRPTR)MSG_ZEBRA_STR},
    {MSG_CONGRATULATIONS,(STRPTR)MSG_CONGRATULATIONS_STR},
    {MSG_HAIL_ABOUT,(STRPTR)MSG_HAIL_ABOUT_STR},
    {MSG_HAIL_CREATURES,(STRPTR)MSG_HAIL_CREATURES_STR},
    {MSG_HAIL_FRUITS,(STRPTR)MSG_HAIL_FRUITS_STR},
    {MSG_HAIL_OBJECTS,(STRPTR)MSG_HAIL_OBJECTS_STR},
    {MSG_POINTS,(STRPTR)MSG_POINTS_STR},
    {MSG_APPLE,(STRPTR)MSG_APPLE_STR},
    {MSG_ORANGE,(STRPTR)MSG_ORANGE_STR},
    {MSG_CARROT,(STRPTR)MSG_CARROT_STR},
    {MSG_LEMON,(STRPTR)MSG_LEMON_STR},
    {MSG_RADISH,(STRPTR)MSG_RADISH_STR},
    {MSG_PINEAPPLE,(STRPTR)MSG_PINEAPPLE_STR},
    {MSG_LIME,(STRPTR)MSG_LIME_STR},
    {MSG_PASSIONFRUIT,(STRPTR)MSG_PASSIONFRUIT_STR},
    {MSG_WATERMELON,(STRPTR)MSG_WATERMELON_STR},
    {MSG_COCONUT,(STRPTR)MSG_COCONUT_STR},
    {MSG_PEAR,(STRPTR)MSG_PEAR_STR},
    {MSG_CORN,(STRPTR)MSG_CORN_STR},
    {MSG_BLACKBERRY,(STRPTR)MSG_BLACKBERRY_STR},
    {MSG_BLUEBERRY,(STRPTR)MSG_BLUEBERRY_STR},
    {MSG_STRAWBERRY,(STRPTR)MSG_STRAWBERRY_STR},
    {MSG_CELERY,(STRPTR)MSG_CELERY_STR},
    {MSG_TURNIP,(STRPTR)MSG_TURNIP_STR},
    {MSG_KIWIFRUIT,(STRPTR)MSG_KIWIFRUIT_STR},
    {MSG_MANGO,(STRPTR)MSG_MANGO_STR},
    {MSG_LETTUCE,(STRPTR)MSG_LETTUCE_STR},
    {MSG_DELETELSET,(STRPTR)MSG_DELETELSET_STR},
    {MSG_DELETED,(STRPTR)MSG_DELETED_STR},
    {MSG_CANTDELETE,(STRPTR)MSG_CANTDELETE_STR},
    {MSG_OPENLSET,(STRPTR)MSG_OPENLSET_STR},
    {MSG_LOADING,(STRPTR)MSG_LOADING_STR},
    {MSG_OPENED,(STRPTR)MSG_OPENED_STR},
    {MSG_CANTOPEN,(STRPTR)MSG_CANTOPEN_STR},
    {MSG_SAVELSET,(STRPTR)MSG_SAVELSET_STR},
    {MSG_SAVING,(STRPTR)MSG_SAVING_STR},
    {MSG_SAVED,(STRPTR)MSG_SAVED_STR},
    {MSG_CANTSAVE,(STRPTR)MSG_CANTSAVE_STR},
    {MSG_PAUSED,(STRPTR)MSG_PAUSED_STR},
    {MSG_UNPAUSED,(STRPTR)MSG_UNPAUSED_STR},
    {MSG_LOADINGFX,(STRPTR)MSG_LOADINGFX_STR},
    {MSG_LOADINGMUSIC,(STRPTR)MSG_LOADINGMUSIC_STR},
    {MSG_NOPORT,(STRPTR)MSG_NOPORT_STR},
    {MSG_NOMEMORY,(STRPTR)MSG_NOMEMORY_STR},
    {MSG_NOCHANNELS,(STRPTR)MSG_NOCHANNELS_STR},
    {MSG_INSTRUCTIONS,(STRPTR)MSG_INSTRUCTIONS_STR},
    {MSG_INTRODUCING,(STRPTR)MSG_INTRODUCING_STR},
    {MSG_POINTS2,(STRPTR)MSG_POINTS2_STR},
    {MSG_NEWDONE,(STRPTR)MSG_NEWDONE_STR},
    {MSG_NOWORMS,(STRPTR)MSG_NOWORMS_STR},
    {MSG_MODIFIED,(STRPTR)MSG_MODIFIED_STR},
    {MSG_CONTINUECANCEL,(STRPTR)MSG_CONTINUECANCEL_STR},
    {MSG_ALL,(STRPTR)MSG_ALL_STR},
    {MSG_STICKYON,(STRPTR)MSG_STICKYON_STR},
    {MSG_STICKYOFF,(STRPTR)MSG_STICKYOFF_STR},
    {MSG_STARTGAME,(STRPTR)MSG_STARTGAME_STR},
    {MSG_LEVELEDITOR,(STRPTR)MSG_LEVELEDITOR_STR},
    {MSG_FX,(STRPTR)MSG_FX_STR},
    {MSG_MUSIC,(STRPTR)MSG_MUSIC_STR},
    {MSG_SHUFFLE,(STRPTR)MSG_SHUFFLE_STR},
    {MSG_DIFFICULTY,(STRPTR)MSG_DIFFICULTY_STR},
    {MSG_WORM1,(STRPTR)MSG_WORM1_STR},
    {MSG_WORM2,(STRPTR)MSG_WORM2_STR},
    {MSG_WORM3,(STRPTR)MSG_WORM3_STR},
    {MSG_WORM4,(STRPTR)MSG_WORM4_STR},
    {MSG_SINGLE,(STRPTR)MSG_SINGLE_STR},
    {MSG_TRIPLE,(STRPTR)MSG_TRIPLE_STR},
    {MSG_QUINTUPLE,(STRPTR)MSG_QUINTUPLE_STR},
    {MSG_SEPTUPLE,(STRPTR)MSG_SEPTUPLE_STR},
    {MSG_GAMEOVER,(STRPTR)MSG_GAMEOVER_STR},
    {MSG_GREEN,(STRPTR)MSG_GREEN_STR},
    {MSG_RED,(STRPTR)MSG_RED_STR},
    {MSG_BLUE,(STRPTR)MSG_BLUE_STR},
    {MSG_YELLOW,(STRPTR)MSG_YELLOW_STR},
    {MSG_LEVEL,(STRPTR)MSG_LEVEL_STR},
    {MSG_BONUSLEVEL,(STRPTR)MSG_BONUSLEVEL_STR},
    {MSG_TIMEEXPIRED,(STRPTR)MSG_TIMEEXPIRED_STR},
    {MSG_FAST,(STRPTR)MSG_FAST_STR},
    {MSG_NORMAL2,(STRPTR)MSG_NORMAL2_STR},
    {MSG_SLOW,(STRPTR)MSG_SLOW_STR},
    {MSG_STOPPED,(STRPTR)MSG_STOPPED_STR},
    {MSG_BONUS_ORBS,(STRPTR)MSG_BONUS_ORBS_STR},
    {MSG_BONUS_BANANAS,(STRPTR)MSG_BONUS_BANANAS_STR},
    {MSG_BONUS_RAIN,(STRPTR)MSG_BONUS_RAIN_STR},
    {MSG_BONUS_OBJECTS,(STRPTR)MSG_BONUS_OBJECTS_STR},
    {MSG_BONUS_BUTTERFLIES,(STRPTR)MSG_BONUS_BUTTERFLIES_STR},
    {MSG_BONUS_RABBITS,(STRPTR)MSG_BONUS_RABBITS_STR},
    {MSG_LEVELBONUS,(STRPTR)MSG_LEVELBONUS_STR},
    {MSG_NUMBERBONUS,(STRPTR)MSG_NUMBERBONUS_STR},
    {MSG_TIMEBONUS,(STRPTR)MSG_TIMEBONUS_STR},
    {MSG_DIMBONUS,(STRPTR)MSG_DIMBONUS_STR},
    {MSG_GLOWBONUS,(STRPTR)MSG_GLOWBONUS_STR},
    {MSG_OPENLSET2,(STRPTR)MSG_OPENLSET2_STR},
    {MSG_SAVELSET2,(STRPTR)MSG_SAVELSET2_STR},
    {MSG_HIGHSCORES,(STRPTR)MSG_HIGHSCORES_STR},
    {MSG_WORMCONTROLS,(STRPTR)MSG_WORMCONTROLS_STR},
    {MSG_SHUFFLE2,(STRPTR)MSG_SHUFFLE2_STR},
    {MSG_ENGRAVED2,(STRPTR)MSG_ENGRAVED2_STR},
    {MSG_DIFFICULTY2,(STRPTR)MSG_DIFFICULTY2_STR},
    {MSG_SOUND,(STRPTR)MSG_SOUND_STR},
    {MSG_FX2,(STRPTR)MSG_FX2_STR},
    {MSG_MUSIC2,(STRPTR)MSG_MUSIC2_STR},
    {MSG_LANGUAGE,(STRPTR)MSG_LANGUAGE_STR},
    {MSG_ENG,(STRPTR)MSG_ENG_STR},
    {MSG_GER,(STRPTR)MSG_GER_STR},
    {MSG_ITA,(STRPTR)MSG_ITA_STR},
    {MSG_STARTGAME2,(STRPTR)MSG_STARTGAME2_STR},
    {MSG_SCORE,(STRPTR)MSG_SCORE_STR},
    {MSG_LEVEL2,(STRPTR)MSG_LEVEL2_STR},
    {MSG_NAME,(STRPTR)MSG_NAME_STR},
    {MSG_TIME,(STRPTR)MSG_TIME_STR},
    {MSG_DATE,(STRPTR)MSG_DATE_STR},
    {MSG_CREATURES,(STRPTR)MSG_CREATURES_STR},
    {MSG_OBJECTS,(STRPTR)MSG_OBJECTS_STR},
    {MSG_FRUITS,(STRPTR)MSG_FRUITS_STR},
    {MSG_MANUAL,(STRPTR)MSG_MANUAL_STR},
    {MSG_ABOUT,(STRPTR)MSG_ABOUT_STR},
    {MSG_GREENWORM,(STRPTR)MSG_GREENWORM_STR},
    {MSG_REDWORM,(STRPTR)MSG_REDWORM_STR},
    {MSG_BLUEWORM,(STRPTR)MSG_BLUEWORM_STR},
    {MSG_YELLOWWORM,(STRPTR)MSG_YELLOWWORM_STR},
    {MSG_RESOLUTION,(STRPTR)MSG_RESOLUTION_STR},
    {MSG_POINTS3,(STRPTR)MSG_POINTS3_STR},
    {MSG_OK,(STRPTR)MSG_OK_STR},
    {MSG_INSTRUCTIONS2,(STRPTR)MSG_INSTRUCTIONS2_STR},
    {MSG_INSTRUCTIONS3,(STRPTR)MSG_INSTRUCTIONS3_STR},
    {MSG_INSTRUCTIONS4,(STRPTR)MSG_INSTRUCTIONS4_STR},
    {MSG_SPA,(STRPTR)MSG_SPA_STR},
    {MSG_INSTRUCTIONS5,(STRPTR)MSG_INSTRUCTIONS5_STR},
    {MSG_INSTRUCTIONS6,(STRPTR)MSG_INSTRUCTIONS6_STR},
    {MSG_INSTRUCTIONS7,(STRPTR)MSG_INSTRUCTIONS7_STR},
    {MSG_DESC_BACKWARDS,(STRPTR)MSG_DESC_BACKWARDS_STR},
    {MSG_DESC_FORWARDS,(STRPTR)MSG_DESC_FORWARDS_STR},
    {MSG_INSTRUCTIONS8,(STRPTR)MSG_INSTRUCTIONS8_STR},
    {MSG_GRE,(STRPTR)MSG_GRE_STR},
    {MSG_DESC_TAMER,(STRPTR)MSG_DESC_TAMER_STR},
    {MSG_DESC_GRENADE,(STRPTR)MSG_DESC_GRENADE_STR},
    {MSG_BONUS_ENCLOSE,(STRPTR)MSG_BONUS_ENCLOSE_STR},
    {MSG_BONUS_CHERRIES,(STRPTR)MSG_BONUS_CHERRIES_STR},
    {MSG_BONUS_PATH,(STRPTR)MSG_BONUS_PATH_STR},
    {MSG_CONTINUE,(STRPTR)MSG_CONTINUE_STR},
    {MSG_LEVELEDITOR2,(STRPTR)MSG_LEVELEDITOR2_STR},
    {MSG_SYSTEM_INFORMATION,(STRPTR)MSG_SYSTEM_INFORMATION_STR},
    {MSG_MENU_QUITTITLE,(STRPTR)MSG_MENU_QUITTITLE_STR},
    {MSG_MENU_PREVIOUS,(STRPTR)MSG_MENU_PREVIOUS_STR},
    {MSG_MENU_NEXT,(STRPTR)MSG_MENU_NEXT_STR},
    {MSG_BONUS_DOGS,(STRPTR)MSG_BONUS_DOGS_STR},
    {MSG_BONUS_SNAKES,(STRPTR)MSG_BONUS_SNAKES_STR},
    {MSG_BONUS_BULLS,(STRPTR)MSG_BONUS_BULLS_STR},
    {MSG_BY,(STRPTR)MSG_BY_STR},
    {MSG_TRANSLATOR1,(STRPTR)MSG_TRANSLATOR1_STR},
    {MSG_TRANSLATOR2,(STRPTR)MSG_TRANSLATOR2_STR},
    {MSG_S_M_R,(STRPTR)MSG_S_M_R_STR},
    {MSG_RECOVERABLE,(STRPTR)MSG_RECOVERABLE_STR},
    {MSG_FATAL,(STRPTR)MSG_FATAL_STR},
    {MSG_APPDESC,(STRPTR)MSG_APPDESC_STR},
    {MSG_SOUND2,(STRPTR)MSG_SOUND2_STR},
    {MSG_LEVELEDITOR3,(STRPTR)MSG_LEVELEDITOR3_STR},
    {MSG_INSTRUCTIONS9,(STRPTR)MSG_INSTRUCTIONS9_STR},
    {MSG_INSTRUCTIONS10,(STRPTR)MSG_INSTRUCTIONS10_STR},
    {MSG_INSTRUCTIONS11,(STRPTR)MSG_INSTRUCTIONS11_STR},
    {MSG_INSTRUCTIONS12,(STRPTR)MSG_INSTRUCTIONS12_STR},
    {MSG_MENU_HELP2,(STRPTR)MSG_MENU_HELP2_STR},
    {MSG_SOFTDRINK,(STRPTR)MSG_SOFTDRINK_STR},
    {MSG_PIZZA,(STRPTR)MSG_PIZZA_STR},
    {MSG_FRIES,(STRPTR)MSG_FRIES_STR},
    {MSG_ICECREAM,(STRPTR)MSG_ICECREAM_STR},
    {MSG_HAMBURGER,(STRPTR)MSG_HAMBURGER_STR},
    {MSG_MODIFIEDSCORES,(STRPTR)MSG_MODIFIEDSCORES_STR},
    {MSG_MENU_UPDATE,(STRPTR)MSG_MENU_UPDATE_STR},
    {MSG_KEY_UPDATE,(STRPTR)MSG_KEY_UPDATE_STR},
    {MSG_UPDATE_YES,(STRPTR)MSG_UPDATE_YES_STR},
    {MSG_UPDATE_NO,(STRPTR)MSG_UPDATE_NO_STR},
    {MSG_POL,(STRPTR)MSG_POL_STR},
    {MSG_ISOMETRIC,(STRPTR)MSG_ISOMETRIC_STR},
    {MSG_PORCUPINE,(STRPTR)MSG_PORCUPINE_STR},
    {MSG_WHATSCREEN,(STRPTR)MSG_WHATSCREEN_STR},
    {MSG_CUSTOMWB,(STRPTR)MSG_CUSTOMWB_STR},
    {MSG_PUBSCREEN,(STRPTR)MSG_PUBSCREEN_STR},
    {MSG_TERMITE,(STRPTR)MSG_TERMITE_STR},
    {MSG_BONUS_JUMP,(STRPTR)MSG_BONUS_JUMP_STR},
    {MSG_DESC_AUTOTURN,(STRPTR)MSG_DESC_AUTOTURN_STR},
    {MSG_VERYHARD,(STRPTR)MSG_VERYHARD_STR},
    {MSG_OPTIONS,(STRPTR)MSG_OPTIONS_STR},
    {MSG_BAT,(STRPTR)MSG_BAT_STR},
    {MSG_AUTOSAVE,(STRPTR)MSG_AUTOSAVE_STR},
    {MSG_STARTGAME3,(STRPTR)MSG_STARTGAME3_STR},
    {MSG_MANUAL2,(STRPTR)MSG_MANUAL2_STR},
    {MSG_ABOUT2,(STRPTR)MSG_ABOUT2_STR},
    {MSG_OK2,(STRPTR)MSG_OK2_STR},
    {MSG_3DWORMS,(STRPTR)MSG_3DWORMS_STR},
    {MSG_RUS,(STRPTR)MSG_RUS_STR},
    {MSG_MULTIPLIER,(STRPTR)MSG_MULTIPLIER_STR},
};

#endif /* CATCOMP_ARRAY */


/****************************************************************************/


struct LocaleInfo
{
    APTR li_LocaleBase;
    APTR li_Catalog;
};



#endif /* WW_STRINGS_H */
