



HIDIHI!


HERE IS THE 100% SOLUTION OF ECO QUEST 
**************************************

BY THE MEGA MIGHTY MWB

WALK TO ADAMS FATHER
LOOK AT THE BIRD IN THE BOX
TAKE THE BOTTLE OF DETERGENT
TAKE THE CLEAN RAG.
USE DETERGENT WITH THE RAG ON THE BIRD (OUT OF YOUR INVENTORY).
NOW SOME ANIMATION
GIVE THE RAT HIS WATER BOTTLE (CLOSE TO THE CAGE).
SOME "DANCES WITH RAT" IS TO BE SEEN.
WALK TO THE STAIR AT THE LEFT.(OKEY,THERES ONLY ONE CHAIR!)
OPEN THE ENVELOPE..AND SEE YOUR MEMBERSHIPCARD.
PICKUP THE TORN ENVELOPE AND THROW IT IN THE RECYCLING BOX.
TAKE THE REUSABLE BAG (NEX TO THE BOX).
PICK UP THE EMPTY SODA CAN AND THROW IN IN THE BOX TOO.
LOOK AT THE MONITOR TWICE (2X!).
AND SEE THAT PIC OF KINGS QUEST 5!!.
LOOK AT THE BLACKBOARD AT THE WALL AND MAKE A NOTE OF THE PICTURE.
THROW THE FLASK OF FERTILIZER SOLUTION INTO THE AQUARIUM.
(FROM YOUR INVENTORY).
THAN WALK TO THEW DOOR AND OPEN IT BY PRESSING THE "E" KEY.
(IF YOU GOT A CRACKED VERSION.(HA HA)
LOOK AT THE BOARD AND TALK TO THE DOLPHIN FOR THREE TIMES !!.
TALK AND LOOK AT HIM TILL YOU FIND OUT HE WILL EAT SOMETHING.
THAN TAKE A MACKEREL OUT OF THE BASKET.
THROW IT TO THE DOLPHIN ONLY WHEN HE LOOKS HUNGRY!
FEED HIM TILL HE IS READY FOR COMPANY.
GET IN THE POOL.
THE DOLPHIN WILL BE PLEASED.
AFTER A WHILE THE DOLPHIN INVITES ADAM TO CLIMB HIS BACK.
AFTER SOME SWIMMING HE WANTS TO PLAY ANOTHER GAME.
SO CLIMB OUT OF THE POOL.
AND KEEP THROWING THE FRISBEE UNTILL THE DOLPHIN GETS TALKING.
PULL THE HANDLE NEXT TO THE POOL TO OPEN THE DOOR TO OPEN SEE.
*** DAYS PASS ***
OPEN THE DOOR.
TAKE THE DIVING EQUIPMENT AND THE TRANSMITTER FROM THE CLOSET.
LOOK AT THE BOATS.
GET THROUGH THE DOOR.
AND GET INTO THE WATER ... BUT FIRST EMPTY YOUR POCKETS.
THAN PUT ON FINS,GLOVES,AND MASK.
SWIM  EAST....NORTH...NORTH.
AT THE SHIP TAKE THE EMPTY GLASS JAR (AT THE LEFT SIDE).
TO THE LEFT YOU CANOT SWIM YET SO TAKE SOME CARBAGE AWAY.
THAN SWIM ONE SCREEN LEFT AND THE DOLPHINE JOIN YOU TO DIVE.
SWIM DOWN...RIGHT...DOWN...DOWN(A BIT AT THE LEFTSCREEN!!)
HERE YOU ARE AT "ELURIA".
DO SOME CLEANING HERE AGAIN.
TAKE STEEL CAGE.
SWIM TO THE BUILDING AT THE RIGHT.
TAKE THE BRONZE CONCH SHELL.
SWIM BACK OUT OF THE BUILDING.
SWIM TO THE POSEIDON STATUE.
USE THE SHELL ON THE LEFT STATUE.
PUT THE SHELL INTO THE CUPPED HANDS OF THE SERVANT.
THAN TAKE THE BRONZE TRIDENT.
THAN SWIM BACK INTO THE BUILDING AT THE RIGHT.
USE THE TRIDENT ON THE WALL AT THE RIGHT.
(STICK IT IN THE THREE EYES)
NOW YOU SEE THE FISH LIKE ORACLE.
TALK TO THE FISH.
NOW YOU MUST FINISH A PUZZLE.
WHEN FINISHED THE PUZLE YOU ARE GIVEN THREE RIDDLES.
JUST CLICK THE ANSWERES ON THE PUZZLE.
1 WHOSE MARCH OF PROGRESS DOOMS US ALL? (MAN)
2 WHAT GLIDES LIKE A BIRD,BUT DOESNOT FLY? (FISH)
3 WHAT REACHES OUT TO THOSE IN NEED? (HEART).
SWIM OUT OF THE BUILDING.
*** ANIMATION ***
GO TO THE BUILDING WITH THE PILARS.
TALK TO THE GOLDEN MASK.
THAN TURN ALL THE PILARS AT THE LEFT..
AS THEY LOOK LIKE THE ONES ON THE RIGHT.
THE ROOM WILL SHAKES WHEN ALL IS DONE CORRECTLY.
TALK TO THE MASKED SENATOR.
SWIM OUTSIDE THE BUILDING.
SWIM ONE SCREEN TO THE LEFT.
DO SOME CLEANING HERE IN FRONT OF THE LARGE STATUE.
USE SOME SOLUTION ON THE LARGE STATUE.
IT SEEMS TO BE STATUE OF CELTUS.
TALK TO THE CRAB.
TAKE THE SHELL (JUST WHERE THE CRAP WAS STANDING)
SWIM TO THE RIGT SCREEN.
SWIM UP (A BIT AT THE LEFT STAYING).
TAKE THE CLEAN COTTON RAG.
DO SOME CLEANING HERE.
SWIM ONE SCREEN DOWN AND ENTER THE BUILDING OF THE SENATOR.
IT WAS THE PILAR-BUILDING REMEMBER?
ABOUT 255 POINTS WE'VE GOT NOW?
TALK TO THE SENATOR.
USE THE RAG TO CLEAN THE SHELL IN YOUR INVENTORY.
GIVE THE OIL-CLEANED SHELL TO THE SENATOR.
SWIM OUT
*** ANIMATION ***
SWIM UP CLOSE TO THE UPPER LEFT SCREEN.
TALK TO THE UNDER MIDDLE HOUSE.
GIVE THE GUARD YOUR BADGE.
HELP THE FISH IN THE PLASTIC BAG.(2X)
*** ANIMATION ***
CLEAN UP THE PLASTIC BAG.
LEAVE THAT HOUSE AND ENTER THE HOUSE AT THE LEFT.
TALK TO THE FISH AND HEAR ABOUT THE PLANTS HE EAT.
PUT THE SEA URCHIMS ON THE ALGAE-COVERED LEAVES OF THE CORAL.
*** ANIMATION ***
SWIM TO THE SECOND HOUSE AT THE RIGHT.(MIDDLE ROW)
TALK TO THE FISH.
USE THE SHELL WITH THE SHARP EDGE ON THE SIX PLASTIC RINGS.
*** ANIMATION *** RECIEVE THE FISH-BONE TWEEEZERS
CLEAN UP THE RINGS.
(ITS A GREAT TRASHCAN/BAG AINT IT?)
SWIM UP ONE MORE HOUSE TO ENTER.
CLEANUP THE BALOON.
GET THE BLOCKAGE OFF THE THROAT OF THE TURTLE.
USE THE FISH-BONE TWEEZERS TO GET THE BALLOON OUT OF HIS THROAT.
*** ANIMATION ***
RECIEVE THE FOUR METAL SCREWS.
CLEANUP THE BALOON.
SWIM OUT.
ENTER THE MIDDLE HOUSE.(THE MANATEE GUARD)
TALK TO HIM.
*** ANIMATION ***
WHEN YOU SEE THE FISHERMAN TALK TO HIM.
USE THE CAGE ON THE PROPELLERS.
USE THE FOUR SCREWS ON THE CAGE.
*** ANIMATION ***
TAKE! THE WATERPUMP.
CLEANUP THE BOTTLE.
ENTER THE MOST LEFT (UPPER) HOUSE.
PICK UP THE BLEACH BOTTLE.
USE THE WATERPUMP AT THE WINDOW.
*** ANIMATION ***
RECIEVE THE LIONFISH SPINE.
*** ANIMATION ***
GET THE MASK
*** ANIMATION ***
USE THE TRIDENT TO GET TO THE ORACLE.
GIVE THE MASK TO THE ORACLE.
*** ANIMATION ***
RECIEVE THE PROPHECY.
SWIM OUT.
ONE SCREEN SOUTH.ONE SCREEN EAST.
DO SOME CLEANING.
TAKE THE MIRROR.
LOOK INTO THE EAR OF THE HEAD.
SWIM EAST.
SWIM UP THROUGH THE HOLE.
OPEN THE CHEST.
LOOK AT THE SKELETON AND SEE THE KEY.
PULL THE PIKE TIP.(2X)
THE KEY WILL DROP INTO THE WATER NOW.
SWIM SOUTH.
TRY TO CATCH THE KEY.
THE KEY WILL BE SWOLLOWED BY A FISH.
FOLLOW THE FISH ONE SCREEN EAST.
IN THAT SCEEN YOU SEE A CABLE.
PULL THE CABLE SO YOU CAN SEE WHERE THE OCTOPUS IS LOCATED.
PUT THE EMPTY JAR AT THE OCTOPUS IN THE MIDDLE OF THE SCREEN.
SWIM EAST.
TAKE THE FISHING LURE.
SWIM EAST AND LET THE KEYSTEELING FISH GET TO THE WEST.
SWIM WEST.
TAKE THE OPENED JAR.
SWIM WEST.
SEE THE "BURP" WHERE THE FISH WAS EATEN.
LOOK AT THE ANEMONE.
GIVE THE FISH LURE TO THE ANEMONE.
NOW TAKE THE KEY.
SWIM WEST.
PUT THE JAR ON THE EAR OF THE BIG HEAD.
CATCH THE FLASHLIGHT FISH.
SWIM EAST TWICE.
USE THE MIRROR ON THE OCTOPUS.
PULL THE CABLE.
SWIM EAST.
USE THE TRIDENT ON THE CORNER OF THE TANK (NEXT TO THE TOILET).
TAKE THE TOILET FLOAT.
SWIM TO THE SUBMARINE.
OPEN THE PANEL IN THE VEHICLE.
TAKE THE HACHSAW AND TAKE THE HAMMER.(IT SCRUMBLES!)
SWIM EAST TWICE.INTO THE CAVE.
USE THE JAR WITH THE FLASHLIGHT-FISH ON THE CAVE.
USE YOUR HAND ON THE WALL.(A BIT UP-EAST)
DO THAT SEVERAL TIMES.
WRITTEN BY MWB. PLK47899.2504CD.DENHAAG.HOLLAND.
LOOK AT THE GREENISH SUBSTANCE.
USE THE HAND ICON SOMR MORE TIMES AT THE WALLL.
YOU MUST REMOVE ALL THE STONES.
AFTER SOME WORK YOU CAN DISCOVER A METAL BOX IN FRONT OF THE GREENISH CAVE.
USE THE KEY ON THE BOX.
USE THE OILY RAG ON THE BOX.
USE THE KEY AGAIN.
TAKE THE CLOTHES.(AND USE'M)
SWIM INTO THE GREENISH CAVE.
SWIM BACK.
SWIM TWO TIMES WEST.
SWIM ONE SCREEN UP AND SEE THE NET OF BONES.
USE THE SHARP SHEL ON THE FISH TO FREE HIM BACK.
SWIM DOWN SWIM EAST TWICE.
TAKE THE PROTECTIVE SUIT OUT OF THE BOX AGAIN.
ENTER THE GREENISH CAVE.
USE THE FLOAT ON THE CABLE IN YOUR INVENTORY.
USE THE RADIO (TRANSMITTER) WITH THE CABLE.
USE THE CABLE ON THE BARREL.
*** ANIMATION ***
SWIM NORTH AND SEE A MODERN HARPOON VESSEL.
USE TRIDENT ON THE DOOR.
*** ANIMATION ***
YOU WILL SWIM RIGHT INTO THE NYLON NET.
USE THE SHARP SHELL ON THE NYLON NET.
YOUR FRIEND WILL BE CAPTURED BY THE FLESH-EATER.
SWIM BACK TO THE HARPOON VESSEL.(1X SOUTH...EAST...INTO THE CAVE...
INFRONT OF THE GREEN CAVE TO THE EAST.THAN ON SCREEN UP)
USE THE TRIDENT ON THE DOOR.
SWIM INTO THE BOAT.
SWIM NORTH.
FOLLOW THE TAUT CABLE UP TO THE NORTH.
SEE THE SHOT WHALE.
TALK TO HIM.
SWIM BACK.
SWIM INTO HIS MOUTH.(USE THE HANDICON ON HIS MOUTH!!)
USE THE SAW ON THE HARPOON SHAFT.
SWIM OUT OF THE MOUTH.
USE HANDICON ON THE WHALE TO GET CLOSER.
PULL OUT THE SHAFT WITH THE CABLE.
USE DEMETYER'S PRECIUOS MEDICINE ON THE WOUND.
ABOUT 583 POINTS COLLECTED?
*** ANIMATION ***
SWIM INTO FLESH-EATER'S HOLE (NEXT TO THE HARPOONER).
INHERE FREE THE DOLPHINE WITH THE SHARP SHELL.
*** ANIMATION ***
OUTSIDE THE CAVE DO SOME HELP FOR THE WHALE BY STICKING THE MANTA WITH
THE TINY LIONFISH SPINE.TWICE?
THE WHALE WILL KNOCK DOWN THE FLASH-EATER NOW.
*** "END"ANIMATION ***
IT'S A PITY I ONLY GOT 638 POINTS..BUT I WAS IN A HURRY.
COLLECT THE LOST POINTS YOURSELF AND BE HAPPY!!!!!!!!!!!


ALL DONE BY    M.W.B./DEBOND...PLK47899- 2504CD- DENHAAG- HOLLAND.
















