           
                   HERE IS THE BLOODY SOLUTION OF...........


                   P O L I C E   Q U E S T  III  !!!
                   *********************************

                   PLAYED AND TYPED BY M.W.B.!!!!!!!
                   *********************************


THIS IS YOUR FIRST DAY.
***********************

FIRST YOU STEP OUT OF THE LIFT BY YOURSELF
ENTER THE CORRIDOR TO THE LEFT AND ENTER THE DOOR AT THE LEFT.
WALK TO THE RIGHT DESK.
REMOVE THE FORM FROM THE BASKET
READ THE NOTE.
LEAVE,AND GO TO THE BRIEFINGROOM ONE SCREEN TO THE RIGHT.
ENTER THE ROOM.
TALK TO OFFICER MORALES.
GO TO THE FRONT OF THE ROOM,
AND TAKE THE CLIPBOARD AT THE LEFTSIDE OF THE PODIUM.
CONDUCT THE BRIEFING.
GO BACK TO YOUR OFFICE.
TALK TO MORALES TILL SHE LEAVES.
SELECT SUSTAINED ON THE FORM.
GO TO THE ELEVATOR PRESS "1" TO THE FIRST FLOOR.
GO TO THE LOCKERROOM.
HERE YOU GET A MESSAGE TO MAKE A PHONECALL.
YOU MUST GO TO ASPEN FALL.
GO TO THE LOCKERROOM AGAIN TO YOUR LOCKER AT THE MIDDLE ROW IN THE MIDDLE.
ENTER YOUR CODE "776".
TAKE THE NIGHTSTICK,FLASHLIGT AND THE NOTEBOOK.
NOW LEAVE THE BUILDING.
WE SUPPOSE TO HAVE ABOUT 13 POINTS.
ENTER THE BLACK AND WHITE CAR AND GO TO ASPEN FALLS.
14.08 HOURS
WHEN YOU GET THERE LEAVE THE CAR.
TALK TO THE LADY WITH THE CHILD.
SHE WILL TEL YOU ABOUT A STRANGE MAN.
WALK ONE SCREEN TO THE RIGHT AND YOU SEE HIM DANCING LIKE A FOOL.
CLICK WITH THE HAND ICON ON HIM.
HE WILL GRAP YOUR BADGE AND THROW IT INTO THE RIVER.
AFTER A WHILE HE'LL JUMP INTO THE WATER HIMSELF.
SEARCH HIS CLOTHES NOW.
YOU'LL FIND A KEY IN'M.
THROUGH THE KEYS INTO THE RIVER TOO.
THE MAN WILL COME OUT OF THE WATER TO KILL YOU.
BUT BEFORE HE CAN DO YOU'VE TO GET YOUR KNIGHT STICK FROM YOUR INVENTORY.
JUST BEFORE HE GETS OUT OF THE WATER YOU MUST CLICK THE STICK ON HIM!
NOW HE'LL FALL DOWN,AND CUFF HIM.
SEARCH HIM.
WALK TO YOUR CAR AND PUT HIM IN THE PASSENGERS SEAT.
ENTER THE CAR YOURSELF AND DRIVE TO THE JAIL.
THE JAIL IS AT THE BACK OF THE POLICE STATION.
WHEN YOU GET THERE PUT YOUR GUN IN ONE OF THE LOCKERS NEXT TO THE LEFT WALL.
ENTER THE JAIL AND WALK TO THE BOOKING WINDOW.
TAKE THE NUT'S KNIFE AND PUT IT INTO THE PROPERTY DRAWER.
AND PUT THE NUT'S DRIVER'S LICENCE THEREIN TOO.
CLICK THE HAND ICON ON THE SALLY PORT DOOR AND ENTER THE CORRECT SECTION NR.
IT IS SUPPOSED TO BE 12025.
THE MAN WILL BE LOCKED UP.
YOU GET YOUR HANDCUFFS BACK FROM THE JAILER.
HE WILL TELL YOU WHERE TO GO FOR MEETING MORALES.
IT IS AT FREEWAY 41!
DON'T FORGET TO GET YOUR GUN BACK BEFORE DRIVING TO MORALES.
TALK TO OFFICER MORALES AND THAN TO THE WOMAN IN THE RED CAR.
TALK TO MORALES AGAIN.
(EH BY THE WAY THIS BLOODY TEXT WAS DONE BY .. 
M.W.B.  PLK47899 - 2504 CD - DENHAAG - HOLLAND.)
NOW A DECISION DIALOG BOX APPEARS AT YOUR SCREEN.
SELECT THE SIGNATURE BOX.
TALK AGAIN TO THE WOMAN.
AFTER THAT ENTER YOUR CAR AGAIN.
DRIVE ON THE FREEWAY FOR PERSONS WICH DRIVE TOO FAST TOO SLOW OR
WICH ARE DRUNK.
WHEN YOU SEE A SUSPICIOUS VEHICLE JUST DRIVE A BIT BEHIND THAT CAR.
PUT ON YOUR SIRENE AND WAIT TILL THE CAR PULLS OVER.
WATCH THE TIME IN THE LEFT SIDE OF YOUR SCREEN.
WALK TO THE CAR AT THE RIGHT SIDE!
TALK TO THE DRIVER AND GET HIS LICENCE.
GET BACK TO YOUR OWN CAR AND INSERT THE LICENSE INTO THE CAR COMPUTER.
ENTER PLATE ID AND LICENSE NUMBER TO IDENTIFY THE CAR AND DRIVER.
DON'T PULL OVER THE UNDERCOVER COP - A TIP IS:...LOOK FOR HIS EXEMPT PLATE!.
THE LAST CAR HAS A DRUNK DRIVER.
STOP HIM ALSO.
PUT THE HANDCUFFS ON.
TAKE THIS ONE TO THE JAIL.
PUT YOUR GUN IN THE LOCKER.
ENTER THE JAIL.
REMOVE HIS HANDCUFFS.
PUT HIS PROPERTYS IN THE DRAWER.
GIVE HIM A BREATHTEST.
ENTER THE PROPER OFFENCE CODE.
IT IS ....23152....
WATCH WHAT HAPPENES NOW WITH SONNY'S WIFE IN THE MEANTIME!
YOU HAVE TO MAKE A FAST DISPATCH CALL NOW IN YOUR OFFICE.
YOU HAVE TO GO TO OAK TREE MALL.
GET YOUR GUN BACK.
ENTER YOUR CAR AND DRIVE ON.
WHEN YOU ARRIVE THERE,YOU SEE TWO NURSES CARRYING MARIE INTO THE AMBULANCE.
GET INTO THE AMBULANCE.
IN THE HOSPITAL LISTEN TO THE DOCTOR.
TAKE A LOOK AT YOUR WIFE.
EXIT THE ROOM.
YOU ARE TAKEN BACK TO THE SCENE.
TALK TO THE JOURNALIST AND YOU GET A CARD.
NOW BUT YOUR BATERIES INTO THE FLASHLIGHT.
EXAMINE THE CAR OF MARIE AT THE RIGHT DOOR.
YOU'LL FIND A BRONZE STAR.
LOOK AT THE BACKSIDE OF IT.
YOU SEE THE NUMBER ....09987.... 
ENTER YOUR CAR.
YOU ARE AUTOMATICALLLY DRIVEN HOME.

THE SECOND DAY.
***************


THE NEXT MORNING YOU ARE WAKEN BY THE PHONE BY YOUR CAPTAIN.
TAKE THE MUSICBOX FROM THE TOPSHELF OF YOUR CLOSET.
LEAVE YOUR BEDROOM.
ENTER YOUR CAR,AND GO TO THE OFFICE.(BY ITSELF)
GO TO THE HOMICIDE OFFICE,AT THE OPPOSITE OF YOUR OWN OFFICE.
THAT WAS ON THE SECOND FLOOR REMEMBER?
THE CAPTAIN TELLS YOU THAT MARIES CASE HAS THE NUMBER....199144....

NOTE THE DATE(03-30-91)AND THE TIME(17.30 HOURS)

YOU GET ANOTHER NUMBER LIKE....199137....IT IS CLIFFORD JONES.
NOTE THE DATE(03-23-90)AND THE TIME(17.30HOURS)

HERE YOU GET YOUR NEW PARTNER MORALES AS WELL.
CLICK ON THE COMPUTER WITH YOUR ACCESCARD.
NOW YOU SEE A BLUE SCREEN.

ENTER THE NUMBER....09987....IN THE SERIAL CODE.
NOW YOU GET A NUMBER OF THE MURDER VICTIM....199124....
PUT THIS NUMMBER IN THE VIEWCASE.
NOW YOU SEE THE PERSONS FILE.

ENTER THE NUMBER OF SAMUEL BRITT....199124....
NOTE THE DATE(03-09-90)AND THE TIME(17.15 HOURS)

NOW TALK TO EARL.
LOOK IN YOUR INVENTORY AT THE JOURNALIST CARD .
YOU SEE THE NUMBER....555-0707....
MAKE A PHONECALL WITH THAT NUMBER.
BOOK THE BRONZE STAR AND THE GOLD CHAIN AS EVIDENCE FOR CASE NUMBER...199144..
IN THE EVIDENCE BOOKING ROOM BESIDES THE JAIL ENTRANCE.
YOU NOW GO TO THE HOSPITAL TO VISIT MARIE.
SHE IS IN ROOM .. 307 ..
IN THE HOSPITAL WALK TO THE FLOWERSTAND.
PAY FOR THE FLOWERS BY CLICKING IN YOUR INVENTORY ON YOUR PURSE.
(HOW MUST YOU PAY OTHERWISE ASSHOLE!)
WALK TO THE ELEVATORS AND YOU ARE TAKEN TO MARIES'ROOM.
GIVE HER THE ROSE.
GIVE HER THE MUSICBOX.
KISS HER.(WOULDN'T YOU DO THAT YOUR SELF BASTARDS?)
LEAVE THE HOSPITAL.
YOU'LL GO HOME AGAIN.
WHEN YOU AWAKE YOU GET TO THE OFFICE. 
  
THE THIRD DAY.
***************


AT THE OFFICE GO TO THE HOMICIDE OFFICE.(THATS YOURS NOW!)
TAKE THE NOTE FROM THE BASKET.
DRIVE TO THE ADDRESS YOU FOUND...325 SOUTH SECOND STREET(OLD INDUSTRIE PARK).
LEAVE THE OFFICE AND TAKE THE WHITE CAR.
YOUR PARTNER WILL FOLLOW YOU TOO.
WE GOT 148 POINTS NOW.(YOU TOO?)
WALK UP THE STAIRS OVER TO THE PILE OF PAPERS BEHIND THE SHOPPING CART.
IDENTIFY YOURSELF BY SELECTING YOUR WALLET FROM THE INVENTORY,
AND CLICK IT ON THE PERSON LYING THERE
CLICK WITH YOUR HANDCUFFS ON THE SHOPPINGCART.
THE LADY WILL FOLLOW YOU NOW TO THE POLICE STATION.
AT THE POLICE STATION:...TALK TO HER,TAKE THE LUNCH FROM THE DESK BEHIND YOU.
GIVE THE LUNCH TO THE LADY.
USE YOUR COMPUTER AND SELECT "T O O L S ".
SELECT "DRAWING COMPOSITE".
KEEP WORKING WITH THE COMPOSITION AS LONG AS THE LADY SAYS "OK" ON ALL.
THAN SELECT "S E A R C H ".
THE COMPUTER WILL COME UP WITH SOME CHARACTERS.
THE LADY WILL GIVE YOU A POSSITIVE IDENTIFICATION.
TURN COMPUTER OFF.
TALK TO THE LADY.
TAKE HER BACK "HOME".
DON'T FORGET TO GET BACK YOUR HANDCUFFS.
THEN YOU GO HOME.


DAY FOUR
*********



GO TO YOUR OFFICE.
LOOK ON THE BASKET ON YOUR DESK.
TAKE THE SUBPOENA AND READ IT.
TAKE THE ELEVATOR TO THE THIRD FLOOR.
TAKE THE TRACKING DEVICE FROM THE DESK.
GO TO THE BLACK POLICE CAR.
OPEN THE GLOVE COMPARTMENT,AND TAKE THE CALIBRATION CHART.
DRIVE THE WHITE UNMARKED CAR TO THE COURTHOUSE.
ENTER THE COURTHOUSE.
CLICK THE TALK ICON ON THE ATTORNEYS TO ANSWER ALL THE QUESTIONS.
GIVE THE CALIBRATION CHART TO THE PROSECUTING ATTORNEYS WHEN ASKED FOR.
YOU HAVE WON THE CASE!
LEAVE THE COURTHOUSE.
OFFICER MORALES WANTS TO MAKE ANOTHER PHONECALL.
IN THAT TIME TAKE THE KEYES FROM HER PURSE.
GO TO ZAK'S SHOP AT THE LEFT SIDE OF THE STREET.
LET ZAK MAKE A COPY OF THE KEY.
PAY FOR IT.
MAKRE A QUICK RETURN TO THE CAR BEFORE MORALES GETS BACK.
RETURN THE KEYS TO THE PURSE.
AFTER A WHILE YOU GET A MESSAGE BY RADIO.
DRIVE TO THE SCENE OF THE CRIME.
IT IS LOCATED AT WEST ROSE NR 300.
WHEN GOT THERE GET OUT OF THE CAR.
THE TIME IS NOW 17.16 HOURS.
WHILE MORALES TAKES THE PHOTOS OF THE VICTUM,YOU OPEN THE TRUNK OF YOUR CAR.
GET THE CASE AND TAKE EVERYTHING YOU SEE IN THERE.
THAN GO THE THE DEAD BODY.
GET THE VICTIM'S LICENCE.
READ THE NUMBER ON THE BACKSIDE...980453...
CLICK THE NOTEBOOK ON THE DRIVERS LICENCE.
CLICK THE TOOTHPICK ON THE VICTIM'S FINGER NAILS.
OPEN THE VICTIM'S SHIRT AND CLICK THE NOTE BOOK ON THE PENTAGRAM.
WALK TO THE DAMAGED CAR AND CLICK THE EYE ICON ON THE BACKSIDE.
CLICK THE SCRAPER OF YOUR INVENTORY ON THE GOLD PAINT.
WALK BACK TO YOUR CAR AND PUT EVERYTHING BACK IN THE TRUNK.
ENTER YOUR CAR AND DRIVE TO THE OFFICE.
WE HAVE ABOUT 222 POINTS!
ENTER THE STATION AND GO TO THE HOMICIDE OFFICE AT FLOOR 2.
LOOK IN THE BASKET AND READ THE MESSAGE.
TURN ON THE COMPUTER.
CLICK ON "HOMICIDE".
SELECT NEW FILE.
BOOK YOUR EVIDENCE UNDER THE NEW NUMBER YOU JUST CREATED...199145...
TURN OFF COMPUTER.
NOW GO TO THE EVIDENCE ROOM.
THAT WAS OUTSIDE THE BUILDING.
ENTER THE DOOR TO THE EVIDENCE ROOM.
PUT THE SKIN AND HAIR SAMPLES FROM YOUR INVENTORY INTO THE DESK.
AND ENTER THE CASENUMBER...199145...
LEAVE THE EVIDENCE ROOM.
DON'T FORGET YOUR GUN FROM THE LOCKER.
DRIVE TO THE HOSPITAL IN THE UNMARKED CAR.
TIME IS NOW 19.08 HOURS.
ENTER THE HOSPITAL.
WALK TO THE ELEVATORS AND ENTER.
IN MARIE'S ROOM YOU 'LL MET THE DOCTOR.
LOOK AT THE CHART AT THE FOOT OF HER BED AND READ IT.
LOOK AT MARIE AND NOTICE THE DIFFERENCE BETWEEN THE AMOUNT OF THE DR.
AND THE IV BOTTLE.
PRESS THE CALL BUTTON ABOVE MARIE'S HEAD.
NPW TALK TO THE NURSE AND THE DOCTOR.
THE DOCTOR WILL CHANGE THE IV DOSIS.
GIVE HER A KISS NOW.
LEAVE THE HOSPITAL AND DRIVE HOME AT 22.00 HOURS.
THERE'R ABOUT 249 POINTS NOW!

DAY FIVE
********

FIRST YOU DRIVE TO THE STATION AND GO TO THE HOMMICIDE OFFICE.
READ THE MEMO ON THE BULLETIN BOARD IN THE ROOM AT THE LEFT.
TURN ON YOUR PC.
ENTER THE NR 199145 OF THE CASE.
TURNOFF PC.
NOW MAKE A DISPATCH CALL.
TURN ON PC.
SELECT TOOLS.
SELECT CITY MAP.
SELECT PLOT CRIMES.
ENTER THE LOCATIONS AT:
280 WEST PALM.
392 S.6TH.
341 E.ROSE.
376 W.ROSE.
NOW SELECT CHECK PATTERN.
AND CONNECT THE FOUR POINTS BY CLICKING THE RIGHT MOUSEBUTTON.
NOW YOU'LL SEE AN INCOMPLETE PENTAGRAM.
YOU HAVE TO SEARCH THE FIFTH LOCATION BETWEEN...
EIGHT AND NINTH STREETS ON PALM.
(IF YOU DON'T REMEMBER THE LOCATIONS...
LOOK AT THE MURDERED GUY IN THE TRASHCAN THERE WAS A STAR ON HIS CHEST!)
IT'LL TAKE SOME TIME TO GET THE RIGHT PLACES.
BUT THE COMPUTER WILL TELL YOU WHEN YOU ARE RIGHT.
BY CHECKING THE PATTERN!
TURN OFF COMPUTER BY QUITING.
GO TO THE PSYCHOLOGIS ACROSS THE HALL OF THE BRIEFING ROOM.
TAKE THE FILE FROM THE DESK.
YOU'READ IT AND REPLACE IT.
GO TO YOUR CAR NOW.
WE SUPPOSE TO HAVE ABOUT 269 POINTS.
ENTER THE WHITE CAR.
YOU'LL GET RESPONS TO GO TO 200 EAST PALM.
(YOU GOT IT ON YOUR COMPUTER EARLIER...
EH BY THE WAY ... SOME THANX MUST GO TO GWH FOR DRAWING THE PENTAGRAM)
WHEN ARRIVED...LOOK AT THE CAR SOME TIMES.
THEN GET THE SCRAPER AND AN ENVELOPE OUT OF YOUR TRUNK.
USE THE SCRAPER ON THE CAR.
YOU'LL PUT IT IN THE ENVELOPE.
PLANT THE TRACK DEVICE ON THE CAR.
NOW ENTER THE SALOON.(OLD NUGGET)
WHEN THE SECOND POOLPLAYER ARRIVES,CLICK THE EYE ICON ON HIM.
TALK TO HIM.
SUDDENLY HI WILL SHOOT AT YOU,AND RUN AWAY.
GET INTO YOUR CAR AND FOLLOW HIM BY USING THE TRACKER.
GO AS QUICKLY AS YOU CAN TO THE HIGHWAY,ITS ACROSS THE MAP.
YOU'LL FIND A CAR OVERTURNED.
GET OUT OF THE CAR.
GET THE FLARES OF YOUR INVENTORY,AND PUT'M ON THE ROAD.
LOOK AT THE VEHICLE.
TAKE THE KEYS FROM IGNITION.
OPEN THE VEHICLE'S TRUNK WITH THE IGNITION KEYS.
AND NOTE THERE ARE MANY COCAINE PACKETS.
CLICK THE HAND ICON ON THE COCAINE PACKETS AND MORALES WILL TAKE'M.
POINTS ARE NOW ABOUT 304!
PUT BACK THE SCRAPER AND THE EMPTY ENVELOPES IN THE TRUNK.
ENTER YOUR CAR AND RETURN TO THE POLICE STATION.
TIME IS NOW 14.36.
MORALES WILL LEAVE NOW.
GO TO YOUR OFFICE.
AND USE THE DUPLICATED KEY OF MORALES ON HER DESK.
JUST DO THIS QUICK,COZ MORALES WILL COME IN.
YOU WILL SEE IN HER DRAWER A NOTE WITH A NUMBER ON ... 386.
CLOSE THE DRAWER.
READ THE NOTE ON YOUR DESK.(YOU HAVE TO GO TO THE HOSPITAL)
AND GO TO THE ELEVATOR.
GO TO THE EVIDENCE BOOKINGROOM.
GET THE ENVELOPE WITH THE WHITE PAINT AND BOOK IT,
GIVE NUMBER ... 199145.
LEAVE THE ROOM AND ENTER THE WHITE CAR.
MORALES APPEARS AGAIN AS ALWAYS.
IT WILL BE 15.10 HOURS.
AT THE HOSPITAL,GO TO MARIES ROOM.
KISS HER AND LEAVE THE HOSPITAL.
THAN YOU ARE TO BE DRIVING HOME AT 22.00 HOURS.

DAY SIX
*********

GO TO THE POLICE STATION.(WHERE ELSE?)
ENTER YOUR OFFICE,AND TALK TO YOUR CAPTAIN.
THAN GO TO THE LOCKER ROOM ON THE FIRST FLOOR.
ENTER THE TOILET,AND PICKUP TWO PLY TOILET PAPER.
USE THE PAPER ON THE TOILET AND FLUSH IT.
LEAVE THE TOILET.
TALK TO THE CLEANING MAN IN THE CORRIDOR.
WHEN THE MAN IS GOING TO CLEAN IT.
WALK INTO THE LADIES ROOM.
SEARCH MORALES' LOCKER.
OPEN IT WITH THE COMBINATION WHICH WAS FOUND IN HER DESK..386.
CLICK YOUR NOTEBOOK ON THE ENVELOPES.
CLOSE THE LOCKER AND RETURN TO YOUR OFFICE.
TALK NOW TO THE CAPTAIN ABOUT YOUR DISCOVERY.
THEN YOU HAVE TO GO TO THE CORONER.
ENTER THE BUILDING.
INSIDE GET THE MANILLA ENVELOPE,AND OPEN IT.
YOU'LL GET THREE THINGS.
GO TO THE BODIES AND READ THE TEXT ON THE BIG TOE.
THE CORNER WILL GIVE YOU THE CLIPPING.
"500 WEST PEACH".
THAN GO BACK TO YOUR CAR.
GO TO THE HOSPITAL AND GIVE MARIE THE LOCKET.
(SHE'LL OPEN HER EYES NOW!)
DO SOME TALKING AND KISS HER.
LEAVE THE HOSPITAL AND GET BACK IN YOUR CAR.
IN THE CAR YOU GET RESPONS FOR 500 WEST PEACH AVE.
THERE SEEMS TO BE A HOUSE BURNING.
WHEN ARRIVED THERE,GET THE SCRAPER AND SOME ENVELOPES.
TALK TO THE FIRE CHIEF AND WHEN HE GIVES HIS OKEY,ENTER THE HOUSE.
PICKUP THE PHOTO.
LOOK AT THE PHOTO AND NOTICE THE ADRESS.
"522 WEST PALM".
ENTER THE ALTAR ROOM.
USE THE SCRAPER AND ENVELOPE TO GET SOME BLOOD AND HAIR.
PUT THE SCRAPER AND ENVELOPES IN THE TRUNK.
RETURN TO YOUR CAR AND GO TO THE MALL.(AUTOMATICALLY)
MORALES WANTS TO MAKE A PHONECALL THERE.
ENTER THERE THE RECRUITING OFFICE.
AFTER SOME SHIT TALKING OF THE OFFICER,SHOW HIM YOUR WALLET.
THAN SHOW HIM THE PICTURE YOU FOUND IN THE HOUSE.
HE IS TO MAKE A PRINTOUT.
TAKE THE PRINTOUT AND READ IT.
GET BACK TO THE POLICE STATION.
ENTER THE PSYCHOLOGICAL'S ROOM.
TALK TO HIM AND SHOW HIM THE MILITARY RECORD (PRINTOUT)
OF MICHAEL BAINS.
AFTER THAT,RETURN TO YOUR CAR.
IT IS NOW 16.33 HOURS.
GO TO 522 WEST PALM
YOU KNOCK THE DOOR,BUT NO ONE GIVE YOU RESPONS.
GO TO THE COURT ROOM TO GET A SEARCH WARENT.
ENTER THE BUILDING.
TALK TO THE COURT REPORTER,
AND GIVE HER THE NEWS CLIPPING OF YOUR INVENORY.
SHOW HER THE PHOTO TOO.
SHE WILL GIVE YOU NOW THE SEARCH WARRENT YOU NEEDED.
372 POINTS ARE GIVEN.
LEAVE,AND GO BACK TO 522 WEST PALM.(THE CRACK HOUSE)
HERE ARRIVED,YOU TRY TO SERVE THE WARRENT.
BUT NOBODY IS ANSWERING YET!.
GO BACK TO THE POLICE STATION.
GO TO THE EVIDENCE ROOM AND BOOK THE PHOTO,
THE SAMPLE BLOOD AND HAIR,THE CULTBOOK AND THE CULTRING.
USE NUMBER 199145.
THEN GO TO THE COURTHOUSE.
ENTER THE BUILDING.
TALK TO THE JUDGE AGAIN.
AND ASK FOR A BACKUP HELP.SHE WILL GRANT YOUR REQUEST.
GO TO THE CRACK HOUSE AGAIN.(522 WEST PALM)
EXIT THE CAR AND DRAW YOUR WEAPON.
WALK TO THE DOOR.
THE RAM WILL CRACK THEW DOOR.
THEN ENTER THE HOUSE.
KILL THE FIRST GUY YOU SEE.
CUFF THE OTHER PERSON.
LIFT THE CUSHION OF THE SOFA.
TAKE THE REMOTE CONTROL.
USE IT ON THE TV AND CLICK THE EIGHT BUTTON.
THAT WILL OPEN A SECRET DOOR.
GET YOUR GUN WHEN YOU ENTER THE ROOM.
SHOOT TO KILL THE FIRST PERSON.
MORALES WILL GET IN NOW.
AND SIT BACK NOW AND SEE WHAT HAPPENS!!!!!!!!!
THATS THE BLOODY END OF POLICE QUEST THREEEEEEEEEEEEEEEEEEEEE!!
YOU'LL SEE US (MWB-SHI-GWH!) IN JUST ANOTHER SOLUTION.





MWB....PLK47899 - 2504 CD - DENHAAG - HOLLAND.














 
 
 
 
 


























.
