#!/bin/sh
#
# starts the Armagetron master server from the installation directory

echo $$ > $HOME/.armagetron/armagetron-masterstarter.pid

INSTALL=/usr/local/games/armagetron

if [ ! -r $HOME/.armagetron ] ; then
   mkdir $HOME/.armagetron
fi

if [  "x$1" = "x-h" ] ; then
    echo -e "\n\nTo uninstall Armagetron, type armagetron --uninstal."
fi

if [  "x$1" = "x--uninstall" ] ; then
    $INSTALL/uninstall
else
    while true; do
		echo "$INSTALL/bin/master --datadir $INSTALL --configdir /etc/armagetron --userdatadir $HOME/.armagetron $* 2>&1 & jobs -p > $HOME/.armagetron/armagetron-master.pid ; wait; echo terminated" | bash -i 2>&1
    done
#    $INSTALL/bin/master --datadir $INSTALL --logdir $HOME/.armagetron $*
fi



