qboolean Amplifier_IsPlayerRunning();
void Amplifier_Execute_f();
void Amplifier_Prev_f();
void Amplifier_Play_f();
void Amplifier_Pause_f();
void Amplifier_Stop_f();
void Amplifier_Next_f();
void Amplifier_FadeOut_f();
void Amplifier_FastForward_f();
void Amplifier_Rewind_f();
int Amplifier_GetStatus();
qboolean Amplifier_OnChange_mp3_volume(cvar_t *var, char *s);
void Amplifier_Repeat_f();
void Amplifier_Shuffle_f();
void Amplifier_ToggleRepeat_f();
void Amplifier_ToggleShuffle_f();
char *Amplifier_Macro_MP3Info();
qboolean Amplifier_GetOutputtime(int *elapsed, int *total);
qboolean Amplifier_GetToggleState(int *shuffle, int *repeat);
void Amplifier_GetPlaylist_Info(int *current, int *length);
void Amplifier_PrintPlaylist_f();
void Amplifier_PlayTrackNum_f();
void Amplifier_SongInfo_f();
void Amplifier_LoadPlaylist_f();
char *Amplifier_Menu_SongtTitle();
