qboolean ANR_IsPlayerRunning();
void ANR_Execute_f();
void ANR_Prev_f();
void ANR_Play_f();
void ANR_Pause_f();
void ANR_Stop_f();
void ANR_Next_f();
void ANR_FadeOut_f();
void ANR_FastForward_f();
void ANR_Rewind_f();
int ANR_GetStatus();
qboolean ANR_OnChange_mp3_volume(cvar_t *var, char *s);
void ANR_Repeat_f();
void ANR_Shuffle_f();
void ANR_ToggleRepeat_f();
void ANR_ToggleShuffle_f();
char *ANR_Macro_MP3Info();
qboolean ANR_GetOutputtime(int *elapsed, int *total);
qboolean ANR_GetToggleState(int *shuffle, int *repeat);
void ANR_GetPlaylist_Info(int *current, int *length);
void ANR_PrintPlaylist_f();
void ANR_PlayTrackNum_f();
void ANR_SongInfo_f();
void ANR_LoadPlaylist_f();
char *ANR_Menu_SongtTitle();
