         
               WAR IN MIDDLE EARTH (a quick solution to the game)

THE METHOD DETAILED IN THIS LISTING, TO COMPLETING THE GAME, SHOULD ONLY BE
VIEWED AS THE QUICKEST WAY, AND THEREFORE WILL VARY GREATLY FROM THE WAY 
THE GAME WAS ORIGINALLY MEANT TO BE PLAYED.


1) THE FIRST STEP TO BE TAKEN IS TO SEND THE RING BEARER TO SOME SAFE
LOCATION AWAY FROM THE CLUTCHES OF THE NAZGULS. I HAVE FOUND THAT SENDING
THE RING BEARER TO THE WEST IS PROBABLY THE SAFEST PLACE.

2) NOTHING MUCH CAN BE DONE AT THIS STAGE UNTIL SAURONS ARMY IS ON THE
MOVE. ONCE YOU GAIN CONTROL OF THE FORCES OF GOOD THE FIRST MOVES THAT MUST
BE MADE ARE THOSE CONCERNING THE ROHIRRIM, DISPLAYED AS HORSE ICONS. SEND
ALL OF THE ROHIRRIM TO EDORAS,THIS WILL GIVE YOU A LARGE ARMY WHICH WILL BE
NEEDED TO DEFEND AGAINST MASSIVE ATTACKS FROM ORCS AND URUK-HAI. SHOULD
EDORAS FALL TO THE FORCES OF SAURON THEN HIS VICTORY WILL BE ASSURED AND THE
GAME WILL END IN YOUR DEFEAT.

3) FROM THIS POINT ON IT WOULD BE ADVISABLE TO SAVE THE GAME FREQUENTLY AS
ONE WRONG MOVE, OR A BATTLE THAT GOES WRONG WILL ENSURE VICTORY FOR SAURON.

4) SEND ALL OF THE FORCES OF GOOD (EXCEPT THE ROHIRRIM) TO MT.DOOM OR
BARAD-DUR, REMEMBERING THAT MORE AND MORE FORCES WILL BECOME AVAILABLE TO
YOU AS THE GAME PROGRESSES. YOU WILL FIND THAT THE FORCES OF GOOD WILL FIND
THEIR OWN WAY THERE AND IN THERE OWN TIME,THIS WILL PROBABLY MEAN THAT LARGE
LOSSES MAY BE SUSTAINED BY YOU AS YOUR FORCES MAY APPEAR TO BE SPREAD PRETTY
THINLY. MEANWHILE IN MORDOR SAURONS ARMY SHOULD BE SPREADING ACROSS THE
MAP,THIS MEANS THAT IF TOU ARE CAREFUL YOU CAN AVOID CONFRONTATIONS AND
REACH MORDOR IN PRETTY MUCH ONE PIECE.

5) IF THINGS HAVE GONE ACCORDING TO PLAN THE 10,000 ORCS ENCOUNTERED AT THE
MORANNON GATES SHOULD HAVE BEEN OVERCOME BY THE FORCES OF GOOD CONTINUALLY
ARRIVING THERE,IF HOWEVER LARGE FORCES OF ORCS ARE STILL PRESENT IT MAY BE
WORTH TRYING TO GO OVER THE MOUNTAINS.ONCE SUFFICIENT FORCES HAVE ENTERED
MORDOR IT ONLY BECOMES NECESSARY TO OVERCOME THE 5000 ORCS AT MT.DOOM. IF
AFTER MT.DOOM IS CAPTURED AND YOU STILL HAVE LARGE FORCES AVAILABLE YOU CAN
TRY OVER RUNNING BARAD-DUR, BUT I FOUND SURROUNDING IT MUCH EASIER AS THE
GAME AT THIS POINT IS ALMOST COMPLETE.

6) TO FINISH THE GAME ALL THAT IS NOW REQUIRED IS TO GET THE RING TO
MT.DOOM. THE QUICKEST WAY TO DO THIS IS TO SEND THE RINGBEARER TO THE
NEAREST ENCAMPMENT OF ORCS,POOR FRODO GETS KILLED AND A NAZGUL IS SUMMONED
TO RETURN THE RING TO SAURON.NAZGULS DON'T SLEEP SO THE JOURNEY TO BARAD-DUR
WILL NOT TAKE VERY LONG, THE ONLY THING THAT YOU MUST ENSURE TO DO IS TO
INTERCEPT THE NAZGUL WITH THE FORCES THAT ARE SURROUNDING BARAD-DUR. ONCE
YOU ARE IN POSSESSION OF THE RING TAKE IT TO THE NOW ORC FREE MT.DOOM.
AND THAT IS ALL THAT IS NEEDED TO END THE GAME ON A WINNING NOTE!


     A FEW NOTES ON THE PROTECTION CODES IN THE GAME!

THE GAME I WAS PLAYING WAS CRACKED BY THORAX WHICH STILL CONTAINS PROTECTION
CODES. THESE CODES FOR SOME REASON SEEM TO BE LINKED TO MOVEMENTS OF THE
RINGBEARER, AS THEY ONLY SEEM TO APPEAR AFTER YOU CONTROL THIS CHARACTER.
THE CODES COME IN THE FORM OF A LETTER/NUMBER COMBINATION AND ARE LINKED TO
CO-ORDINATES OF TOWNS ON THE MAP.
NO MAP HAS SO FAR TURNED UP SO ALL THAT CAN BE DONE IS TO GUESS AT THE
CODE.HOWEVER I WAS LUCKY ENOUGH TO GUESS ONE OF THEM CORRECTLY SND IT MAY BE
HELPFUL ENOUGH TO LEAST MAKE AN APPROXIMATE GUESS AT SOME OF THE OTHER
LOCATIONS.
THE ONE THAT IS KNOWN FOR SURE IS BELEGOST C-3

  HOPEFULLY THE GAME WILL WORK AS EASILY FOR YOU AS IT DID FOR ME,AND A SET
OF DOCS. FOR THE CODES WILL ARRIVE SHORTLY, AND THE GAME CAN BE PLAYED IN THE
MANNER IT WAS MEANT TO BE PLAYED.

  BEST OF LUCK FROM VULCAN
                    ------
