AR				=	ar
CC				=	ppc-morphos-gcc
#CC			=	ppc-morphos-gcc4
#CXX			=	ppc-morphos-g++
#CXX			=	ppc-morphos-g++4
CHMOD			=	chmod
RANLIB		=	ranlib
RM				=	rm -f
STRIP			=	strip

#------------------------------------------------------------------------------#

VERSION		=	1.5.77

#------------------------------------------------------------------------------#

CFLAGS		=	-g -O2 -Wall `sdl-config --cflags` -D_VER=\"$(VERSION)\"


LDFLAGS		=	`sdl-config --libs` -lSDL_image -lSDL_mixer

#------------------------------------------------------------------------------#

SRC			=	game.c \
					game.h \
					main.c


OBJ			=	$(patsubst %.c,%.o, $(filter %c, $(SRC)))


BIN			=	Game

#------------------------------------------------------------------------------#

all:			$(BIN)


$(BIN):		$(OBJ)
			$(CC) $(OBJ) -o $@.db $(LDFLAGS)
			$(STRIP) --strip-unneeded --remove-section=.comment $@.db -o $@
			$(CHMOD) u+x $@


%.o:			%.c
			$(CXX) $(CFLAGS) -c $< -o $@

#------------------------------------------------------------------------------#

clean:
		$(RM) $(BIN) $(BIN).db $(OBJ)
