        Willkommen zu aMalone

aMalone ist eine übersetzung des
jungen Brettspiels 'abalone', daß
schon zu den klassischen Spielen
gehört. Das Spiel erfordert sowohl
taktischen wie auch strategischen
Fähigkeiten. Trotzdem, sind die
Spielregeln einfach.
Das Hauptmenü und die Submenüs
bezeichnen:

A. aMalone spielen
B. Stellung aufsetzen
C. Hilfe
D. Ende

A1. Neues Spiel
A2. Partie laden
A3. Partie speichern
A4. Zug zurück
A5. Halbzug zurück
A6. Halbzug vorwärts
A7. Zum ersten Halbzug
A8. Zum letzten Halbzug
A9. Hauptmenü

B1. Schwarz begint
B2. Weiß begint
B3. Lehres Brett
B4. Beginaufstellung
B5. Hauptmenü

Die Schwierigkeit kann mann einstellen
zwischen 1 und 9. Klicke die Pfeile
an für eine höhere oder niedrige
Schwierigkeit. Die Zahl gleicht die
Suchtiefe der Halbzügen, worauf der
Komputer seinen Zug basiert. Ein
Halbzug ist ein Zug von Schwarz oder
Weiß.

Beide Spieler können Mensch oder
Komputer sein. Klicke den Spieler an
zum Wechseln zwischen Mensch und
Komputer, und umgekehrt.

Das Lämpchen zeigt den Spieler am Zug.

Ein Zug gibt mann wie folgt ein:
1. zeige die Kopfkugel an, und drücke
   die linke Maustaste ein.
2. zeige die Endkugel an, und lasse
   die linke Maustaste los.
3. zeige das Feld an wo die Kopfkugel
   (oder Endkugel) hingehen soll,
   und klicke nochmals auf die linke
   Maustaste.

                    Viel Spaß !
