                THE LAST NINJA 3 QUICK-SOLLUTION - BY *RAT*
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

 
OK... LET'S START:
 

IF YOU WANT TO HAVE A BETTER BUSHIDO , ATTACK THE ENEMIES WITH THE SAME 
WEAPONS THEY USE OR WITHOUT WEAPON.

LEVEL 1:

THE FIRST THING TO DO IS TO COLLECT ALL THINGS IN LEVEL 1.
IF YOU HAVE EVERYTHING , BUILD A CLIMBING-GLOVE OUT OF THE CLAWS AND THE
GLOVE YOU FOUND . NOW CLIMB UP THE ROCKFACE AND OFF WE GO.
TAKE THE LAMP AND GO BACK TO THE ROCKFACE. THERE YOU FILL UP THE LAMP WITH
THE STUFF INSIDE THE BARRELS . -> BACK UP. WHEN YOU ARRIVE AT THE ROCK,
YOU USE YOUR SELFMADE BOMB TO DROP IT . GET DOWNSIDE INTO THIS ROOM
AGAIN AND (WALK NEAR THE WALL) TAKE THE SCRIPT.
WITH THIS YOU CAN LEAVE LEVEL ONE AND ENTER
 
LEVEL 2:

GET THE BELLOWS. YOU ALSO FIND A BOAT (?) AND GIVE THIS A TOUCH . IT LEAVES 
THE SCREEN AND APPAERS IN THE NEXT ROOM AGAIN . IF YOU ENTER THIS ROOM ,
PUSH YOUR STICK UP IN THE CORNER . AT THE END OF THE PATH PRESS FIRE AND 
WHEN YOU LANDED ON THE BOAT , AT ONCE AGAIN . IN THE FOLLOWING MAZE YOU
FIND YOUR SCROLL. AFTER THE MAZE CLIMB DOWN THE FLOWER (ATTETION) .
GO TO THE NEXT SCREEN AND C U IN 
 
LEVEL 3:

GET THE SCROLL AND -ON THE BRIDGE- THE LOCKER FOR THE WATER-FLEW-OUT.
THIS WORKS AS FOLLOW : STAND IN FRONT OF THE RIGHT CORNER OF THE FENCE.
NOW PUSH YOUR STICK DOWN-LEFT AND JUMP IN THE RIGHT MOMENT. NOW WALK TO THE 
NEXT SCREEN AND TAKE THE THING . STOP THE WATER AND ---> GO TO
 
LEVEL 4:

WALK ON . CLIMB UP THE 2ND HOLDS AND FIND UP THERE A MOUTH-SAFE .
NOW YOU CAN GET INTO THE GAS-ROOM AND TAKE THE POWDER.
GET THE KEYSTONES AND THE SCROLL . WHEN YOU ARRIVE AT THE FIRE , USE THE 
BELLOWS AND AND AFTER THAT , THROW IN THE KEYSTONE. THE RESULT IS A KEY .
WITH THIS KEY YOU CAN UNLOCK THE DOOR AND CONTINUE IN
 
LEVEL 5:

<TrY To MaNaGe HaViNg ThE FuLl BuShIdO ArRiViNg HeRe>

YOU FIND THE SCROLL ON YOUR WAY . IF YOU ARE STANDING IN FRONT OF KUNOTOKI,
USE THE SCROLL. HE BEGINS TO THROW. REFLECT HIS THROWS PRESSING BUTTON
AND LEFT-UP. IF THIS ISN'T ENOUGH ,THROW YOUR WEAPONS.
 
THAT'S ALL . I HOPE YOU COULD MAKE IT WITH THIS .
 
OK , DUDES , L8ER ON .
 
...RAT



Call The Association!
      (206)-384-2591
