AR			= ar
CC			= g++
RANLIB	= ranlib
RM			= rm

CFLAGS	= -g -O2 -Wall `sdl-config --cflags` -I../gengine -I../effect/ -I../plan -I../option -I/usr/include/lua

OBJ		= DemoInput.o DemoMode.o GameInput.o PosterState.o PosterScroller.o demo-script.o
BIN		= libstate.a

all: $(BIN)

$(BIN):	$(OBJ)
		$(AR) cru $(BIN) $(OBJ)
		$(RANLIB) $(BIN)

%.o:	%.cpp
		$(CC) $(CFLAGS) -c $<

clean:
		$(RM) -f $(OBJ) $(BIN)
