17
Intro to General Psychology - College Freshman Level
1
The goals of phychology are to
585
 Develop effective methods of psychotherapy
 Describe, understand, predict and control behavior
 Explain the functioning of the human mind
 Compare, analyze, and control human behavior
2
2
1
Psychology is best defined as the
585
 Empirical study of the mind
 Study of individual differences in human behavior
 Scientific study of the behavior of organisms
 Study of the relationship between mind and body
2
3
1
Skinner's contribution to behaviorism lies in his insistence that
1609
 Behavior is shaped and maintained by its consequences
 Behavior is only partially conscious
 The whole is more than the sum of its parts
 Non-biological motives such as self-actualization are the primary
determinants of behavior
2
1
3
A psychologist observes the behavior of organisms in the wild and keeps
careful records of the observed behavior. The method being used is
585
 Clinical observation
 Naturalistic observation
 Free observation
 Survey method
2
2
1
Pavlov's contribution to behaviorism lies in his discovery of
585
 The conditional response
 Self-observation
 Unconscious motivation
 Concscious experience
2
1
3
The conditions which a researcher wishes to prevent from affecting the
experiment are called
585
 Constants
 Dependent variables
 Extraneous variables
 Independent variables
2
3
3
In a study of effects of alcohol on driving ability, the control group
should be given
585
 A high dosage of alcohol
 One-half the dosage given the experimental group
 A driving test before and after drinking alcohol
 No alcohol at all
2
4
3
Which of the following would most likely be investigated by use of a case
study
1609
 The extent of marijuana usage in the general population
 The effects of caffeine on memory
 A rare psychological problem such as multiple personality
 The correlation between hours of sleep per night and the grade point
average of college students
2
3
1
A representative sample is an essential element of the
585
 Survey method
 Psychoanalytic method
 Natural experiment or case study
 Clinical method
2
1
1
The most basic perceptual organization is
585
 Shape constancy
 Depth perception
 Figure-ground
 Size constancy
2
3
3
Which of the following is the correct sequence of events for the motivational
process
585
 Reinforcement-need-behavioral response
 Need-drive-behavioral response
 Drive-behavioral response-need
 Behavioral response-drive-need
2
2
1
biological drives tend to maintain bodily equilibrium in a process called
585
 Need reduction
 Homeostasis
 Thermostasis
 Set point
2
2
1
in general, performance is best at ____ levels of arousal
585
 Low
 Moderate
 High
 Extremely high
2
2
1
At the top of Maslow's hierarchy of needs is
585
 Love
 Belonging
 Self-esteem
 Self-actualization
2
4
3
Which theory of an emotion hold that we see a bear, feel fear, become aroused
and run
585
 The commonsense theory
 The Cannnon-Bard theory
 The James-Lange theory
 Cognitive theory
2
1
1
The most universal and easily interpreted facial expression of emotion is
585
 A frown
 Baring of the teeth
 A smile
 Tears
2
3
3
An individual who refuses to believe a family member has died is using the
defense mechanism of
585
 Denial
 Suppression
 Avoidance
 Fantasy
2
1
1
The simplest conflict to resolve is usually a _____
585
 External
 Approach-approach
 Avoidance-avoidance
 Personal
2
2
0
