99
Self-Assesment test: What is your intimacy quotient?
225
Do you have more than your share of colds?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
2
225
Do you believe that emotions have very little to do with physical ills?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
2
225
Do you often have indigestion?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
2
225
Do you frequently worry about your health?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
2
225
Would a nutritionist be appalled by your diet?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
2
225
Do you usually watch sports rather than participate in them?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
2
225
Do you often feel depressed or in a bad mood?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
2
225
Are you irritable when things go wrong?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
2
225
Were you happier in the past than you are right now?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
2
227
Do you believe it possible that a person's character can be read or his future
foretold by means of astrology, I Ching, tarot cards, or some other means?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
2
225
Do you worry about the future?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
2
227
Do you try to hold in your anger as long as possible and then sometimes
explode in a rage?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
2
225
Do people you care about often make you feel jealous?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
2
227
If your intimate partner were unfaithful one time, would you be unable to
forgive and forget?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
2
225
Do you have difficulty making important decisions?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
2
225
Would you abandon a goal rather than to take risks to reach it?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
2
225
When you go on a vacation, do you take some work along?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
2
225
Do you usually wear clothes that are dark or neutral in color?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
2
227
Do you usually do what you feel like doing, regardless of social pressures
or criticism?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
1
225
Does a beautiful speaking voice turn you on?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
1
227
Do you always take an interest in where you are and what's happening around
you?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
1
225
Do you find most odors interesting rather than offensive?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
1
225
Do you enjoy trying new and different foods?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
1
225
Do you like to touch and be touched?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
1
225
Are you easily amused?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
1
225
Do you often do things spontaneously or impulsively?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
1
227
Can you sit still through a long committee meeting or lecture without
twiddling your thumbs or wriggling in your chair?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
1
227
Can you usually fall asleep and stay asleep without the use of sleeping pills
or tranquilizers?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
1
225
Are you a moderate drinker rather than either a heavy drinker or a teetotaler?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
1
225
Do you smoke at all or very little?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
1
225
Can you put yourself in another person's place or experience his emotions?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
1
227
Are you seriously concerned about social problems even when they don't affect
you personally?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
1
225
Do you think that most people can be trusted?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
1
227
Can you talk to a celebrity or a stranger as easily as you can talk to your
neighbors?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
1
227
Do you get along well with salesclerks, waiters, service-station attendants
and cabdrivers?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
1
225
Can you easily discuss sex in mixed company without feeling uncomfortable?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
1
225
Can you express appreciation for a gift or a favor without feeling uneasy?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
1
227
When you feel affection for someone, can you express it physically as well as
verbally?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
1
225
Do you sometimes feel that you have extrasensory perception?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
1
225
Do you like yourself?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
1
225
Do you like others of your own sex?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
1
225
Do you enjoy an evening alone?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
1
227
Do you vary your schedule to avoid doing the same things at the same times
each day?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
1
225
Is love more important to you than money or status?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
1
225
Do you place a higher premium on kindness than on truthfulness?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
1
225
Do you think it is possible to be too rational?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
1
227
Have you attended or would like to attend a sensitivity or encounter-group
session?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
1
225
Do you discourage friends from dropping in unannounced?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
2
225
Would you feel it a sign of weakness to seek help for a sexual problem?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
2
225
Are you upset when a homosexual seems attracted to you?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
2
225
Do you have difficulty communicating with someone of the opposite sex?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
2
227
Do you believe that men who write poetry are less masculine than men who drive
trucks?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
2
227
Do most women prefer men with well developed muscles than men with well
developed emotions?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
2
225
Are you generally indifferent to the kind of place in which you live?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
2
227
Do you consider it a waste of money to buy flowers for yourself or for
others?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
2
227
When you see an art object you like, do you pass it up if the cost would mean
cutting back on your food budget?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
2
227
Do you think it pretentious and extravagant to have an elegant dinner when
alone or with members of your immediate family?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
2
225
Are you often bored?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
2
225
Do sundays depress you?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
2
225
Do you frequently feel nervous?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
2
225
Do you dislike the work you do to earn a living?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
2
225
Do you think a carefree hippie lifestyle would have no delights for you?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
2
225
Do you watch TV selectively rather than simply to kill time?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
1
225
Have you read any good books recently?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
1
225
Do you often daydream?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
1
225
Do you like to fondle pets?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
1
225
Do you like many different forms and styles of art?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
1
225
Do you enjoy watching an attractive person of the opposite sex?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
1
227
Can you describe how your date or mate looked the last time you went out
together?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
1
225
Do you find it easy to talk to new acquaintances?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
1
225
Do you communicate with others through touch as well as through words?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
1
225
Do you enjoy pleasing members of your family?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
1
225
Do you avoid joining clubs or organizations?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
2
227
Do you worry more about how you present yourself to prospective dates than
about how you treat them?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
2
225
Are you afraid that if people knew you too well they wouldn't like you?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
2
225
Do you fall in love at first sight?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
2
227
Do you always fall in love with someone who reminds you of your parents of the
opposite sex?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
2
225
Do you think love is all you presently need to be happy?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
2
227
Do you feel a sense of rejection if a person you love tries to preserve his
or her independence?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
2
225
Can you accept your loved one's anger and still believe in his or her love?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
1
225
Can you express your innermost thoughts and feelings to the person you love?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
1
227
Do you talk over disagreements with your partner rather than silently worry
about them?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
1
227
Can you easily accept the fact that your partner has loved others before
you and not worry about how you compare with them?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
1
225
Can you accept a partner's disinterest in sex without feeling rejected?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
1
227
Can you accept occasional sessions of unsatisfactory sex without blaming
yourself or your partner?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
1
225
Should unmarried adolescents be denied contraceptives?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
2
227
Do you believe that even for adults in private, there are some sexual acts
that should remain illegal?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
2
227
Do you think that hippie communes and Israeli kibbutzim have nothing useful
to teach the average american?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
2
225
Should a couple put up with unhappy marriage for the sake of their children?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
2
225
Do you think that mate swappers necessarily have unhappy marriages?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
2
225
Should older men and women be content not to have sex?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
2
225
Do you believe that pornography contributes to sex crimes?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
2
227
Is sexual abstinence beneficial to a person's health, strength, wisdom,
or character?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
2
225
Can a truly loving wife or husband sometimes be sexually unreceptive?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
1
227
Can intercourse during a women's menstrual period be as appealing or as
appropriate as at any other time?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
1
227
Should a women concentrate on her own sensual pleasure during intercourse
rather than to pretend enjoyment to increase her partner's pleasure?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
1
225
Can a man's effort to bring his partner to orgasm reduce his own pleasure?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
1
225
Should fun and sensual pleasure be the principal goals in sexual relations?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
1
225
Is pressure to perform well a common cause of sexual incapacity?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
1
227
Is sexual intercourse for you an uninhibited act rather than a demonstration
of your sexual ability?
Turn verbose OFF for this test, this is a self
evaluation you should be honest on all your responses
for an accurate evaluation
65
 Yes
 No
0
1
12287
Score:
0  - 30 %  You have a shell like a tortoise and draw your head at the first
           sign of psychological danger.
30 - 60 %  You're about average, you have potential. You have some barriers
           but have had enough experience to take some chances.
60 - 90 %  You possess the self-confidence and sense of security not only
           to run the risks of intimacy but to enjoy it. This could be a
           little discomforting to another person who doesn't have your
           capacity or potential for close relationships.
90 - 100%  You're either an intimate superman or are worried too much about
           giving the right answers, which puts you back in the less than
           30 percent category.
Source: 'Go to health' book by communications research machines, inc.
