27
Quality Motivation Concepts - for potential CQE students
3
When considering human motivation in solving quality problems, it is MOST
important to recognize that
585
 Individuals have wants.
 Individuals have different levels of needs.
 Individual motivation is of little concern to quality problem solving.
 Individuals have basic needs.
2
2
1
The effective supervisor
585
 Sometimes does a job himself because he can do it better than others.
 Sees his role as one of making people happy.
 Has objectives of growth and increased profit by working through people.
 Leaves personnel development to the Personnel Department.
2
3
1
The application of human factors analysis in a plant production environment
585
 Identifies reasons why errors are made.
 Is a practical example of using psychological techniques on workers.
 Is identified with a formal quality motivation program.
 Relates attitudes and prejudices among plant personnel.
2
1
1
An essential element of a quality motivation progam is
585
 The establishment of attainable goals
 The establishment of failure costs.
 A stable environment.
 The generation of a minimum level of defects.
2
1
3
In a visual inspection situation, one of the best ways to minimize
deterioration of the quality level is to
585
 Re-train the inspector frequently.
 Add variety to the task.
 Have a program of frequent eye exams.
 Have a standard to compare against a part of the operation.
2
4
7
The Quality Engineer should be concerned with the human factors of a new
piece of in-house manufacturing equipment as well as it's operational
effects because it
585
 May speed the line to the point a visual operator inspection is impossible
 May require the operator undivided attention at the controls
 May remove an operator formerly devoting some time to inspection.
 All of these.
2
4
7
The famous Western Electric Hawthorne plant study provided which of the
working clinical evidence regarding the factors that can increase work
group productivity
587
 Attention and recognition is as, or more important than working
 conditions
 Productivity did not change significantly under any test conditions
 Informal group pressures set a production "goal"
 People with higher capablilities are bored with routine jobs
2
1
3
When giving instructions to those who will perform a task, the communication
process is completed
585
 When the worker goes to his work station to do his task
 When the person giving the instruction has finished talking
 When the worker acknowledges the instructions by how they will perform it
 When the worker says that he understands the instructions
2
3
7
McGregor's Theory X manager is typified as one who operates from the
following basic assumption about people working for him (select the
one best answer)
585
 Performance can be improved through tolerance and trust
 People have a basic need to produce
 Status is more important than money
 People are lazy and are motivated by reward and punishment
2
4
3
When installing a new system for collecting failure data in a manufacturing
plant, the following approach is recommended
713
 Have production write their own procedure
 Use a procedure from another company
 Enlist the collaboration of all affected departments in drafting
 and applying
 None of these
2
3
7
Having designed a test fixture to performance requirements, the design
should be carefully evaluated by the quality engineer to insure that it has
included
585
 Low cost components
 Printout capability
 Human motor coordination factors
 Computer inputs
2
3
15
In order to instill the quality control employee with the desire
to perform to his utmost and optimum ability, which of the following
recognition for sustaining motivation has been found effective
for most people
585
 Recognition by issuance of monetary award
 Verbal recognition publicly
 Public recognition, plus non-monetary award.
 Private verbal recognition.
2
3
1
Human factors engineering concepts introduced to your final inspection area
585
 Are not valuable until the test equipment has been set up and operating
 Should be incorp. during the design and planning stage of the area
 Will result in schedule slippage wherever incorporated
 Will result in reduced inspector efficiency, but greater accuracy
2
2
3
One human management approach, often called the "carrot and the stick"
approach is best typified by which of the following theories
585
 Herzberg's "Hygiene Theory"
 Maslow's "Hierarchy of Motivation"
 Skinner's "Reinforcement of Behavior Theory"
 McGregor's "Theory 'X' "
2
4
1
The technology for predicting human reliablility in production processes
585
 Is inevitably correlated with monetary rewards
 Is represented by the many motivation programs in effect
 Is still in the development stages
 Is based on the determination of the workmanship error rate
2
3
3
Which of the following tasks has been shown to have the most incentive
or motivational value to the quality engineer
585
 Attend defect control meetings
 Document action taken on special problems
 Investigate product quality problems
 Initiate corrective action to solve nonroutine problems
2
3
3
In scanning type inspection task, inspection accuracy is likely to be
greater if
585
 The product moves toward the inspector rather than laterally past him
 The inspector searces the product, area by area, for all types of defects
 The magnification is increased
 The product is scanned while stationary rather than while it is moving
2
4
3
Studies have shown that the most effective communications method for
transferring information is
585
 Oral only
 Written only
 Combined written and oral
 Bulletin board
2
3
1
Quality motivation in industry should be directed at
585
 Manufacturing management
 Procurement, Engineering and Quality
 The working force
 All of these
2
4
7
A thorough analysis of the cause and effect of plant quality problems
usually indicates that a major percentage of the basic factors affecting
poor quality performance are
585
 Operator controllable
 Management controllable
 Union controllable
 Customer controllable
2
2
1
Methods for predicting human reliability in production processes are
585
 Represented by the many motivation programs in effect
 Inevitably correlated with monetary rewards
 Still in the developmental stages
 Based on the complexity of the process
2
3
3
One of the most important techniques in making a training program
effective is to
603
 Concentrate only on developing knowledge and skills needed to do a good
 job
 Transmit all of the information that is even remotely related to the
 function
 Set individual goals instead of group goals
 Give people meaningful measures of performance
2
4
3
During the design review stage for new equipment, you recommend that a
human factors use test be performed under one of the following conditions
585
 On a production model, if possible
 Not combined with engineering tests on the same equipment
 It demonstrate capability of workers to do all functions of equipment
 All of these
2
3
1
The primary visual consideration in designing an inspection workspace is
585
 The environmental color decor because of psychological effect
 The size and shape of the inspection table or bench
 The illumination and how it is provided
 The traffic flow in or near the inspection station
2
3
3
A successful quality circle program should produce all of the following
benefits except
585
 Improved worker moral
 Decreased need for management efforts to maintain quality
 Improved communication between managers and quality circle members
 Cost savings from participative problem solving
2
2
3
Which one of these human management approaches has led to the practice
of job enrichment
585
 Skinner
 Maslow
 Herzberg's "Hygiene Theory"
 McGregor
2
3
1
Extensive research into the results of quality motivation has shown that
587
 The supervisor's attitude toward his people is of little long term
 consequence
 Motivation is too nebulous to be correlated with results
 Motivation is increased when employees set their own goals
 Motivation is increased when management sets challenging goals for them
2
3
1
Select the non-hygienic motivator, as defined by Herzberg
585
 Salary increases
 Longer vacations
 Sales bonuses
 Performance recognition
2
4
0
