19
Stress analysis self-test, meant to evaluate your level of stress
33
I get annoyed when I have to wait
Use: -quiet- Why mode!!!
65
 True
 False
0
1
33
I tend to worry about how things will turn out
Use: -quiet- Why mode!!!
65
 True
 False
0
1
33
I think my appearance is OK
Use: -quiet- Why mode!!!
65
 True
 False
0
2
33
Getting to the top is always worth the effort
Use:  -quiet- Why mode!!!
65
 True
 False
0
1
33
When I have problems, I work them out right away
Use: -quiet- Why mode!!!
65
 True
 False
0
2
33
This stage of life is rewarding
Use: -quiet- Why mode!!!
65
 True
 False
0
2
33
There seems to be a lot of tension around me on the job
Use: -quiet- Why mode!!!
65
 True
 False
0
1
33
Today is more important than either yesterday or tomorrow
Use: -quiet- Why mode!!!
65
 True
 False
0
2
33
I have more than two alcoholic drinks per day
Use: -quiet- Why mode!!!
65
 True
 False
0
1
33
There is a lot of stress in my work
Use: -quiet- Why mode!!!
65
 True
 False
0
1
33
Things seem to be over my head
Use: -quiet- Why mode!!!
65
 True
 False
0
1
33
I have had a lot of tragedy and disappointment over the last year
Use: -quiet- Why mode!!!
65
 True
 False
0
1
33
I wish than I were younger than I am
Use: -quiet- Why mode!!!
65
 True
 False
0
1
33
Each day I take a walk or spend time out of doors for fun
Use: -quiet- Why mode!!!
65
 True
 False
0
2
33
I have a trusted person with whom I can discuss my problems
Use:  -quiet- Why mode!!!
65
 True
 False
0
2
33
My present job is a great source of satisfaction for me
Use: -quiet- Why mode!!!
65
 True
 False
0
2
33
When I feel stressed, I can still breathe normally
Use:  -quiet- Why mode!!!
65
 True
 False
0
2
33
I have the authority to carry out my responsibilities
Use:  -quiet- Why mode!!!
65
 True
 False
0
2
33
Things I am trying to do get disrupted or sidetracked
Use:  -quiet- Why mode!!!
65
 True
 False
0
1
33
I fit well with the people around me
Use:   -quiet- Why mode!!!
65
 True
 False
0
2
6842
***  STRESS TEST INTERPRETATION  ***
FOR A GRADE % OF:          YOUR LEVEL OF STRESS IS:
------------------  ------------------------------------------
 0%  to  30%               Low level of stress
 31% to  65%               Moderate level of stress
 66% to 100%               HIGH level of stress (calm down!)
NOTE: In this test there is no right or wrong answers, the questions and
      answers are just used to help you self-evaluate your level of stress.
