# AR = shar -c -v -d
AR = echo

all	:
		(cd util;	make all);
		(cd adlcomp;	make all);
		(cd adlrun;	make all);
		(cd samples;	make all);
		(cd misc;	make all);

install :
		(cd util;	make all);
		(cd adlcomp;	make install);
		(cd adlrun;	make install);
		(cd misc;	make install);

shar	:
		(cd util;	make shar);
		(cd adlcomp;	make shar);
		(cd adlrun;	make shar);
		(cd samples;	make shar);
		(cd include;	make shar);
		(cd misc;	make shar);
		${AR}	README		COPYRIGHT	PORTING		\
			Makefile	man		adlcomp		\
			adlrun		misc		util		\
			include		samples		samples/aard	\
			samples/mpu	samples/demos	man/*	\
		> adl.shar

touch	:
		(cd util;	make -t);
		(cd adlcomp;	make -t);
		(cd adlrun;	make -t);
		(cd samples;	make touch);
		(cd misc;	make -t);

clean	:
		(cd util;	make clean);
		(cd adlcomp;	make clean);
		(cd adlrun;	make clean);
		(cd samples;	make clean);
		(cd include;	make clean);
		(cd misc;	make clean);
		rm -f adl.shar
