#ifndef _THEGOONIES_CONSTANTS
#define _THEGOONIES_CONSTANTS

#define PLAYER_MAX_ENERGY		64
#define PLAYER_MAX_EXPERIENCE	16
#define PLAYER_CRITICAL_ENERGY	8
#define PLAYER_SPEED			(1.5f)
#define SKULL_SPEED				(2.0f)
#define SKELETON_SPEED			(2.25f)
#define BONE_SPEED				(2.5f)
#define BAT_SPEED				(1.5f)

#define YELLOW_FRATELLI_SPEED	(1.75f)
#define BLUE_FRATELLI_SPEED		(2.00f)
#define GREEN_FRATELLI_SPEED	(2.5f)
#define RED_FRATELLI_SPEED		(2.25f)
#define GREY_FRATELLI_SPEED		(1.5f)
#define WHITE_FRATELLI_SPEED	(1.75f)
#define BULLET_SPEED			(4.0f)
#define MUSICALNOTE_SPEED		(4.0f)

#endif

