.TH MISHIGAME 6
.SH NAME
mishigame \- tetris\-like game
.SH SYNOPSIS
.B mishigame [options]
.SH DESCRIPTION
Mishigame is tetris\-like game. It uses SDL to comunicate with graphics
hardware, keyboard, and other services.
.SH OPTIONS
.TP
.B \--fullscreen
Enables fullscreen mode.
.TP
.B \--speed
Sets speed of the game. `1' is the lowest speed and `4' is the highest speed.
.TP
.B \--help
Displays list of command line options.
.TP
.B \--version
Displays version number.
.TP
.B \--copy
Displays copyright notice.
.SH FILES
.B ~/.mishigame
Personal config file.
.SH HOMEPAGE
http://mishigame.sourceforge.net
.SH AUTHOR
Marcel ©ebek <sebek64@post.cz>
