.\"     Title: bi2cf
.\"    Author: Florian Dietrich <n8flo@yahoo.de>
.\" Generator: DocBook XSL Stylesheets v1.71.0 <http://docbook.sf.net/>
.\"      Date: Jan 30 2003
.\"    Manual: 
.\"    Source: 
.\"
.TH "BI2CF" "6" "Jan 30 2003" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
bi2cf \- a map conversion tool for Crimson Fields
.SH "SYNOPSIS"
.HP 6
\fBbi2cf\fR \fImapname\fR [\-p\ 1|2] [\-f\ b|1|2|h] [\-l] [\-t\ \fImapname\fR] [\-i\ \fImapinfo\fR] [\-o\ \fIoutfile\fR] [\-d\ \fImapdir\fR] [\-O\ \fIdestdir\fR] [\-q]
.HP 6
\fBbi2cf\fR {\-h | \-v}
.SH "DESCRIPTION"
.PP
\fBbi2cf\fR
is a map conversion tool for Crimson Fields. It takes the data files of maps from Battle Isle, Battle Isle Data Disk 1 or 2, or History Line 1914\-1918 and converts them into map sources usable with the
\fBcfed\fR(6)
map compiler for Crimson Fields.
\fBbi2cf\fR
can handle both uncompressed maps and levels crunched with TPWM.
.PP
For some units and tiles there are no corresponding counterparts in Crimson Fields. These cases are mapped to similar ones if available. As a result some maps will not be as balanced as the originals, others may be unwinnable, and still others may even fail to compile. If this happens the map in question needs to be adjusted manually.
.SH "OPTIONS"
.PP
\fB\-d\fR \fImapdir\fR
.RS 3n
Set the location of the Battle Isle map files.
.RE
.PP
\fB\-f\fR b|1|2|h
.RS 3n
Force map type to Battle Isle / BI Data Disk 1 / BI Data Disk 2 / History Line, respectively. Use this option when map format autodetection does not work correctly. Maps from BI Data Disk 1 will always be detected as standard Battle Isle maps, so you have to use
\fB\-f 1\fR
in that case.
.RE
.PP
\fB\-h\fR
.RS 3n
Print a usage message on standard output and exit.
.RE
.PP
\fB\-i\fR \fImapinfo\fR
.RS 3n
Set map info message.
.RE
.PP
\fB\-l\fR
.RS 3n
Skip last row and column of the map. This is necessary for maps from the PC version of Battle Isle.
.RE
.PP
\fB\-o\fR \fIoutfile\fR
.RS 3n
Write map to file
\fIoutfile\fR. Default file name is
\fImapname.src\fR.
.RE
.PP
\fB\-O\fR \fIdestdir\fR
.RS 3n
Set target directory for the converted map. This setting is ignored if a map name was given using the
\fB\-t\fR
option.
.RE
.PP
\fB\-p\fR 1|2
.RS 3n
Set default number of players for this map.
.RE
.PP
\fB\-q\fR
.RS 3n
Run quietly. Don't print processing information on standard output.
.RE
.PP
\fB\-t\fR \fImapname\fR
.RS 3n
Set title and file name for the converted map. Default is
\fImaptype\-mapname\fR.
.RE
.PP
\fB\-v\fR
.RS 3n
Print version information on standard output and exit.
.RE
.SH "SEE ALSO"
.PP

\fBcfed\fR(6),
\fBcrimson\fR(6)
.SH "COPYRIGHT"
.PP
Copyright \(co 2002 Florian Dietrich
.PP
This software is distributed under the terms of the
[1]\&\fIGNU General Public License\fR
(GPL).
.SH "AUTHOR"
.PP
Florian Dietrich <\&n8flo@yahoo.de\&>
.sp -1n
.IP "" 3n
Author.
.SH "REFERENCES"
.TP 3
1.\ GNU General Public License
\%http://www.gnu.org/copyleft/gpl.html
