.TH "Matchball" "6" "0.28" "Marco Kraus" "Games"
.SH "intro"
Matchball SDl ist just a litte (addictive) puzzlegame, written in C++ with the Simple DirectMedia Layer by Marco Kraus.
.SH "game"
The goal is to remove all balls.
You can remove balls when you click them,
and the ball is connected to (at least) another ball,
with the same color. Then more balls with the 
same color are connected then more point you will get.

The points are calculated in square: n^2

If you can clear the complete field, you will
get 500 Points bonus.

Future plans are to give some time bonus points.
.SH "future, bugs, todo"
See the matchball manuals
.SH "Credits"
Marco Kraus <marco@libsdl.de> 
(mainauthor,maintainer and all other things not listed here)

Felix Luebbe <felix@sunbeambbs.de> 
(win32 port, sound, betatesting, much more)

Fred Benkler <fred@sunbeambbs.de> 
(backgrounds)

Felix Stolle <phoenix@purebytes.de>
(some FX, crystal ball theme)

Linny Erdmann <sky@skylein.de>
(smiley ball theme)

Steffi Schmidt <kira@linuxterm.de>
(some FX, betatesting)

Marius Andra
(some codeideas)

Free Software Foundation
(free truetype fonts)
