5
Basic College Algebra Theory
101
Identify the following subsets of Real Numbers
    { 1, 2, 3, 4, ... }
Whole numbers are similar but include zero,
Integers include zero and negative numbers.
585
 Whole Numbers
 Natural Numbers
 Rational Numbers
 Integers
2
2
229
Identify the following Subset of Real Numbers
  { ..., -3, -2, -1, 0, 1, 2, 3, ... }
Natural numbers begin with the number 1 and count
upward, Whole numbers are similar to natural
numbers but include 0.
585
 Rational Numbers
 Natural Numbers
 Integers
 Whole Numbers
2
3
97
Which of the following is NOT a valid property of Quotients
In this example the ac/ca = 1 which is not the
same as a/b.
4095
 a     c
--- = ---  if and only if ad = bc
 b     d
 ac     a
---- = ---
 ca     b
 a     c     ad  -  bc
--- - --- = -----------
 b     d        bd
 a     c     ad  +  bc
--- + --- = -----------
 b     d        bd
2
2
225
Which of the following is NOT a valid property of Exponents
A correct example of this would be:
   2     2        2
  a  +  a   =   2a
1755
  m       n      m+n
 a   x   a  =   a
   m n     mn
 (a )  =  a
  n    n    2n
 a  + a  = a
     m     m m
 (ab)  =  a b
2
3
109
If a is a nonzero real number, then
        0
       a  =  ?
The only exception to this is if a = 0, then
the answer would be undefined.
585
 Minus one  (-1)
 Zero (0)
 One (1)
 Infinite
2
3
39
The following algebraic rule is more commonly known as:
                          2     2
    ( x + y )( x - y ) = x  -  y
This is a useful rule to remember
585
 Cube of a Binomial
 Difference of Two Squares
 Square of a Binomial
 A Polynomial in x
2
2
0
