14
Identify standard forms of Calculus II differentials
229
Identify the correct differential:
      du = ?
        du
  du = ---- dx
        dx
1809
 a du
 du + dv
 du
---- dx
 dx
1
3
37
Identify the correct differential:
       d(au) =  ?
    d(au) = a du
1815
  du
 ---- dx
  dx
 a du
 du
----
 dx
1
2
165
Identify the correct differential:
  d(u + v) = ?
THE SUM RULE
d(u+v) = du + dv
275
  u
 a  ln a du
 du + dv
 cos u du
1
2
237
Identify the correct differential:
           n
        d(u ) = ?
THE POWER RULE FOR POSITIVE INTEGER POWERS OF X
     n      n-1
  d(u ) = nu   du
1843
    n
  nu  du
    n-1
  nu   du
   du
  ---- dx
   dx
1
2
237
Identify the correct differential:
      u
   d(e ) = ?
   u
  e  is indestuctible! It can not be changed by
     differentiation.
787
    u
   e  du
  du + de
    u
  ln  du
1
1
229
Identify the correct differential:
  d(ln u) = ?
Derivative of       d          1  du
Natural Log :      --- ln u = --- ---
                   dx          u  dx
1843
   u
  e du
   u
  a  ln a du
  du
 ----
  u
1
3
237
Identify the correct differential:
         u
      d(a ) = ?
When a constant is raised to a variable power:
   u     u
d(a ) = a  ln a du
883
      u
     a  ln a du
     du
    ----
     u
     u
    e  du
1
1
69
Identify the correct differential:
    d(sin u) = ?
d(sin u) = cos u du
547
     2
  sec u du
 -cos u du
 cos u du
1
3
69
Identify the correct differential:
  d(cos u) = ?
 d(cos u) = - sin u du
273
 sin u du
 - sin u du
 sin u cos u du
1
2
69
Identify the correct differential:
  d( ln |sec u|) = ?
d(ln|sec u|) = tan u
785
 tan u
 cot u
    2
-csc u du
1
1
37
Identify the correct differential:
  d( ln |sin u|) = ?
d(ln|sin u|) = cot u
275
     2
  sec  u du
 cos u
 cot u
1
3
101
Identify the correct differential:
  d(tan u) = ?
              2
d(tan u) = sec u du
563
    2
 sec  u du
    2
 csc  u du
 sec u tan u du
1
1
101
Identify the correct differential:
  d(cot u) = ?
                 2
 d(cot u) = - csc u du
563
       2
    sec  u du
       2
  - csc  u du
  sec u tan u du
1
2
37
Identify the correct differential:
  d(sec u) = ?
d(sec u) = sec u tan u du
273
 - csc u cot u du
 sec u tan u du
 tan u + sin u du
1
2
37
Identify the correct differential:
  d(csc u) = ?
d(csc u) = -csc u cot u du
273
 - csc u cot u du
 sec u tan u du
 cos u - sin u du
1
1
0
