:LOOP|
GOTO LOOP|

:TOUCH|
[ "Analysis Software Version 1.1"|
[ "Awaiting Information..."|

HAVEITEM MailPackage @RES|
IF @RES DOANALYSIS|
GOTO LOOP|

:DOANALYSIS|
[ "Working..."|
[ "  Working..."|
[ "    Working..."|
[|
[ "Analysis Complete"|
[ "Please Take Results"|
TAKEITEM MailPackage @RES|
ADDITEM ResultsOfAnalysis|
GLOSET 0 2|
[ "%n:  Oh my goodness!  I need to"|
[ "get this to James immediately!"|
GOTO LOOP|


