SubWindow, mainwindow = WindowObject,
    MUIA_Window_Title, "Connect 4",
    MUIA_Window_ID   , MAKE_ID('C','O','N','4'),
    MUIA_Window_Width , MUIV_Window_Width_Screen(50),
    MUIA_Window_Height, MUIV_Window_Height_Screen(50),
    MUIA_Window_ScreenTitle, "Connect 4",
    MUIA_Window_Menustrip, strip = MUI_MakeObject(MUIO_MenustripNM, connect4menu, 0),

    WindowContents,
        VGroup,
            Child, HGroup,
                Child, RectangleObject,
                    MUIA_HorizWeight, 50,
                End,
                Child, redlamp = LampObject,
                          MUIA_Lamp_Type, MUIV_Lamp_Type_Huge,    // red player goes first
                          MUIA_Lamp_Red,   0xffffffff,
                          MUIA_Lamp_Green, 0,                     // Red
                          MUIA_Lamp_Blue,  0,
                End,
                Child, ply1name = TextObject,
                          MUIA_Text_Contents, default_player_name[0],
                          MUIA_Frame, MUIV_Frame_Text,
                          MUIA_Background, MUII_TextBack,
                End,
                Child, TextObject,
                          MUIA_Text_Contents, " vs ",
                          MUIA_Text_SetMax, TRUE,
                End,
                Child, ply2name = TextObject,
                          MUIA_Text_Contents, default_player_name[1],
                          MUIA_Frame, MUIV_Frame_Text,
                          MUIA_Background, MUII_TextBack,
                End,
                Child, yellowlamp = LampObject,
                          MUIA_Lamp_Type, MUIV_Lamp_Type_Huge,
                          MUIA_Lamp_Red,   0xffffffff,
                          MUIA_Lamp_Green, 0xffffffff,            // Yellow
                          MUIA_Lamp_Blue,  0,
                End,
                Child, RectangleObject,
                    MUIA_HorizWeight, 50,
                End,
            End,
            Child, board = NewObject(gameboardmcc->mcc_Class, NULL,
                    MUIA_FixWidth,              gb_width,
                    MUIA_FixHeight,             gb_height,
                    MUIA_Bitmap_Width,          gb_width,
                    MUIA_Bitmap_Height,         gb_height,
                    MUIA_Bitmap_SourceColors,   gb_colours,
                    MUIA_Bitmap_Precision,      PRECISION_IMAGE,
                    MUIA_Bitmap_UseFriend,      TRUE,
                    MUIA_Bodychunk_Depth,       gb_colourdepth,
                    MUIA_Bodychunk_Compression, gb_compression,
                    MUIA_Bodychunk_Body,        gb_body,
            End,
            /*Child, HGroup,
                Child, Label2("Status"),
                Child, TextObject,
                    MUIA_Text_Contents, "",
                    MUIA_Frame, MUIV_Frame_Text,
                    MUIA_Background, MUII_TextBack,
                    MUIA_HorizWeight, 300,
                End,
                Child, RectangleObject, End,
                Child, Label2("Lag"),
                Child, LampObject,
                    MUIA_Lamp_Type, MUIV_Lamp_Type_Medium,
                    MUIA_Lamp_Red,   0x00000000,
                    MUIA_Lamp_Green, 0xffffffff,            // Green
                    MUIA_Lamp_Blue,  0,
                End,
                Child, LampObject,
                    MUIA_Lamp_Type, MUIV_Lamp_Type_Medium,
                    MUIA_Lamp_Red,   0x00000000,
                    MUIA_Lamp_Green, 0xffffffff,            // Green
                    MUIA_Lamp_Blue,  0,
                End,
                Child, LampObject,
                    MUIA_Lamp_Type, MUIV_Lamp_Type_Medium,
                    MUIA_Lamp_Red,   0xffffffff,
                    MUIA_Lamp_Green, 0xffffffff,            // Yellow
                    MUIA_Lamp_Blue,  0,
                End,
                Child, LampObject,
                    MUIA_Lamp_Type, MUIV_Lamp_Type_Medium,
                    MUIA_Lamp_Red,   0xffffffff,
                    MUIA_Lamp_Green, 0xffffffff,            // Yellow
                    MUIA_Lamp_Blue,  0,
                End,
                Child, LampObject,
                    MUIA_Lamp_Type, MUIV_Lamp_Type_Medium,
                    MUIA_Lamp_Red,   0xffffffff,
                    MUIA_Lamp_Green, 0x00000000,            // Red
                    MUIA_Lamp_Blue,  0,
                End,
            End,*/
        End,
End,

