SubWindow, newgamewin = WindowObject,
    MUIA_Window_Title,  "New Game",
    MUIA_Window_ID,     MAKE_ID('N','E','W','G'),
    MUIA_Window_Width,  MUIV_Window_Width_Default,
    MUIA_Window_Height, MUIV_Window_Height_Default,
    MUIA_Window_ScreenTitle, "Connect 4",
    MUIA_Window_CloseGadget, FALSE,

    WindowContents, VGroup,
        Child, HGroup,
            Child, LampObject,
                MUIA_Lamp_Type, MUIV_Lamp_Type_Huge,    
                MUIA_Lamp_Red,   0xffffffff,
                MUIA_Lamp_Green, 0,                     // Red
                MUIA_Lamp_Blue,  0,
            End,
            Child, name1 = StringObject,
                MUIA_String_Contents, default_player_name[0],
                MUIA_Frame, MUIV_Frame_String,
                MUIA_String_MaxLen, NAME_LEN,
                MUIA_CycleChain, 1,
                MUIA_String_AdvanceOnCR, TRUE,
            End,
            Child, pop1 = PopobjectObject,
                MUIA_Popstring_Button, PopButton(MUII_PopUp),
                MUIA_Popobject_Object, poplistview1=ListviewObject,
                    MUIA_FixWidth, 300,
                    MUIA_Frame, MUIV_Frame_InputList,
                    MUIA_Listview_List, poplist1=ListObject,
                        MUIA_List_Format, "BAR,BAR,WEIGHT=200",
                        MUIA_List_Title, TRUE, // Enable multicolumn title support
                        MUIA_Listview_ScrollerPos, MUIV_Listview_ScrollerPos_Right,
                        MUIA_List_DisplayHook,     &PAB_display_hook,
                        MUIA_List_ConstructHook,   &PAB_constructor_hook,
                        MUIA_List_DestructHook,    &PAB_destructor_hook,
                        MUIA_List_CompareHook,     &PAB_compare_hook,
                    End,
                End,
            End,
        End,
        Child, HGroup,
            Child, LampObject,
                MUIA_Lamp_Type, MUIV_Lamp_Type_Huge,
                MUIA_Lamp_Red,   0xffffffff,
                MUIA_Lamp_Green, 0xffffffff,         // Yellow
                MUIA_Lamp_Blue,  0,
            End,
            Child, name2 = StringObject,
                MUIA_String_Contents, default_player_name[1],
                MUIA_Frame, MUIV_Frame_String,
                MUIA_String_MaxLen, NAME_LEN,
                MUIA_CycleChain, 1,
                MUIA_String_AdvanceOnCR, TRUE,
            End,
            Child, pop2 = PopobjectObject,
                MUIA_Popstring_Button, PopButton(MUII_PopUp),
                MUIA_Popobject_Object, poplistview2=ListviewObject,
                    MUIA_FixWidth, 300,
                    MUIA_Frame, MUIV_Frame_InputList,
                    MUIA_Listview_List, poplist2=ListObject,
                        MUIA_List_Format, "BAR,BAR,WEIGHT=200",
                        MUIA_List_Title, TRUE, // Enable multicolumn title support
                        MUIA_Listview_ScrollerPos, MUIV_Listview_ScrollerPos_Right,
                        MUIA_List_DisplayHook,     &PAB_display_hook,
                        MUIA_List_ConstructHook,   &PAB_constructor_hook,
                        MUIA_List_DestructHook,    &PAB_destructor_hook,
                        MUIA_List_CompareHook,     &PAB_compare_hook,
                    End,
                End,
            End,
        End,
        Child, HGroup,
            Child, RectangleObject, End,
            Child, startbutton = TextObject,
                      MUIA_Text_Contents, MUIX_C"Start",
                      MUIA_Frame, MUIV_Frame_Button,
                      MUIA_InputMode, MUIV_InputMode_RelVerify,
                      MUIA_Background, MUII_ButtonBack,
                      MUIA_CycleChain, 1,
            End,
            Child, RectangleObject, End,
        End,
    End,
End,

