SubWindow, settingswin = WindowObject,
    MUIA_Window_Title, "Connect 4 settings",
    MUIA_Window_ID   , MAKE_ID('S','E','T','T'),
    MUIA_Window_Width , MUIV_Window_Width_Default,
    MUIA_Window_Height, MUIV_Window_Height_Default,
    MUIA_Window_ScreenTitle, "Connect 4",

    WindowContents,
         RegisterGroup(Page_titles),
             MUIA_Register_Frame, TRUE,

             Child, VGroup,
                  Child, HGroup, MUIA_Background, MUII_BACKGROUND,
                     Child, RectangleObject, End,
                     Child, addbutton = TextObject,
                               MUIA_Text_Contents, MUIX_C"Add",
                               MUIA_Frame, MUIV_Frame_Button,
                               MUIA_InputMode, MUIV_InputMode_RelVerify,
                               MUIA_Background, MUII_ButtonBack,
                               MUIA_CycleChain, 1,
                     End,
                     Child, deletebutton = TextObject,
                               MUIA_Text_Contents, MUIX_C"Delete",
                               MUIA_Frame, MUIV_Frame_Button,
                               MUIA_InputMode, MUIV_InputMode_RelVerify,
                               MUIA_Background, MUII_ButtonBack,
                               MUIA_CycleChain, 1,
                     End,
                     Child, clearbutton = TextObject,
                               MUIA_Text_Contents, MUIX_C"Clear list",
                               MUIA_Frame, MUIV_Frame_Button,
                               MUIA_InputMode, MUIV_InputMode_RelVerify,
                               MUIA_Background, MUII_ButtonBack,
                               MUIA_CycleChain, 1,
                     End,
                     Child, RectangleObject, End,
                  End,
                  Child, HGroup,
                     Child, playerlistview = ListviewObject,
                         MUIA_Listview_ScrollerPos, MUIV_Listview_ScrollerPos_Right,
                         MUIA_Listview_List, playerlist=ListObject,
                             InputListFrame,
                             MUIA_List_Format, "BAR,BAR,WEIGHT=200",
                             MUIA_List_Title, TRUE, // Enable multicolumn title support
                             MUIA_List_DisplayHook,   &PAB_display_hook,
                             MUIA_List_ConstructHook, &PAB_constructor_hook,
                             MUIA_List_DestructHook,  &PAB_destructor_hook,
                             MUIA_List_CompareHook,   &PAB_compare_hook,
                         End,
                     End,
                  End,
             End,

             Child, VGroup,
                 Child, RectangleObject, End,
                 Child, HGroup,
                     Child, RectangleObject, End,
                     Child, VGroup,
                         Child, HGroup,
                             Child, TextObject,
                                 MUIA_Text_Contents, "Accept games requests ",
                                 MUIA_Text_SetMax, TRUE,
                             End,
                             Child, netacceptcycle = CycleObject,
                                 MUIA_Cycle_Entries, cycle_acceptnet_strings,
                             End,
                         End,
                         Child, RectangleObject, End,
                         Child, ColGroup(2),
                              Child, Label2("Port:"),
                                 Child, netport = StringObject,
                                     MUIA_String_Format, MUIV_String_Format_Left,
                                     MUIA_String_Accept, "0123456789",
                                     MUIA_String_Integer, 5000, // Default port value
                                     MUIA_String_MaxLen, PORT_LEN,
                                     MUIA_Frame, MUIV_Frame_String,
                                     MUIA_CycleChain, 1,
                                     MUIA_String_AdvanceOnCR, TRUE,
                                 End,
                              Child, Label2("User name:"),
                                 Child, netname = StringObject,
                                     MUIA_String_Format, MUIV_String_Format_Left,
                                     MUIA_String_MaxLen, NAME_LEN,
                                     MUIA_Frame, MUIV_Frame_String,
                                     MUIA_CycleChain, 1,
                                     MUIA_String_AdvanceOnCR, TRUE,
                                 End,
                         End,
                     End,
                     Child, RectangleObject, End,
                 End,
                 Child, RectangleObject, End,
             End,
         End,
End,

