LOCKCONTROLS|
WALKTO 566 167 3|
[ "Howarth: I hope they got everything"|
[ "ready to leave."|
WALKTO 566 155 3|
FACE W|
[ "Howarth: This...is the last of it."|
LABELJUMP 2 KILL|
[ "Howarth: Oh, Sarah.  How I wish you"|
[ "were still here..."|
FACE N|
PAUSE 1|
[ "Howarth: You were so headstrong, so"|
[ "determined.  It's just that..."|
FACE E|
PAUSE 1|
[ "Howarth: Just that..."|
FACE S|
LOADLEVEL LEVEL253.LEVEL|
