LOCKCONTROLS|
WALKTO 179 138 4|
[ "Whoa!  Right out of a science-fiction book!"|
WALKTO 159 138 4|
[ "Like some kind of molecular"|
[ "transporter of something..."|
FACE N|
[ "What's this..."|
WALKTO 159 100 4|
LABELJUMP 1 KILL|
FACE S|
PAUSE 2|
[ "HOLY COW!  It IS a transporter!"|
[ "All the test information's on here!"|
[ "Even Sir Howarth signed it!"|
WALKTO 232 127 5|
FACE S|
[ "I've got to tell my buddies about this!"|
LOADLEVEL LEVEL77.LEVEL|
