SOUND "Sounds/Birds.iff" 8345 %0101|
GLOGET 6 @RES|
IF @RES SKIPSPEECH|
FRAMEANIM 37|
[ "Mike: Oh, it's simply GORGEOUS out!"|
SOUND "Sounds/Birds.iff" 8345 %0101|
LOCKCONTROLS|
FACE W|
WAIT 20|
FACE N|
WAIT 20|
FACE E|
WAIT 20|
FACE S|
WAIT 20|
UNLOCKCONTROLS|
[ "Mike: I think I'll spend some time out"|
[ "here.  Take a relaxing stroll about the yard,"|
[ "then get back in and study."|
GLOSET 6 -1|
:SKIPSPEECH|
IDLE|
