:LOOP|
RND @DIR 3|
WALK @DIR 3 12|
GOTO LOOP|
:TOUCH|
[ "Hi there, young man!  You seem"|
[ "like a nice young boy...not like one"|
[ "of those rioters out there."|
[|
[ "Mike: Rioters?  You mean..."|
[ "Lady: They're tearing the colony"|
[ "apart out of fear.  But don't worry..."|
[|
[ "Lady: We're safe in here.  Ooh!"|
[ "Those NASTY NASTY PEOPLE! They'll"|
[ "get what they deserve."|
GOTO LOOP|
