SET @MLOOP 0|
GLOGET 2 @RES|
IF @RES = 1 OTHERLOOP|
:LOOP|
FACE 0|
GOTO LOOP|
:OTHERLOOP|
FACE 0|
MATH @MLOOP + 1|
IF @MLOOP < 20 OTHERLOOP|
:TOUCH|
[ "Obey the law."|
[|
[ "Mike: (Don't tell him I don't"|
[ "KNOW the law here!)"|
GLOGET 2 @RES|
IF @RES = 1 FIGHT|
GOTO LOOP|
:FIGHT|
[ "Guard: Really?  Maybe you came in on that"|
[ "'transporter' everyone's babbling about!"|
[ "Maybe YOU were the one who pushed the"|
[ "button and destroyed our planet!!!"|
[ "Guard: Take this!"|
ATTACK 50|
