Official documentation to the game SpaceStone

Init Screen
Choose the amount of player you desire by moving your joystick
up and down. When satisfied, press fire to exit.

Status Screen
This screen is probably the most frequently visited of all the 
screens. On this screen you can see how many ships you have left, 
how big your lasers are etc. It is also on this screen you
make use of any experience points you may possess. To do this you
simply move your joystick until the skill/part you want to increase
is highlighted, and then press fire. Before you do this you may also
want to know how many experience points it is going to cost to perform
this particular increase, just look to the right on the screen!

Money - how many credits you have.
Loan - how big your loan to the local galaxy mob is.
Ships - how many more ships you may loose before it is game over for you.
Hull - how much damage your ship takes before going to 'Kingdom Come'.
Max Hull - the Hull of your ship can never increase beyond this number.
Repair Speed - how fast you and your companions repair your ship.
Laser - how much damage your lasers do/how big lasers you have fitted.
Charge Speed - how frequently laser beams may be fired. Actually it is 
	the time it takes for your lasers to charge before another shot.
Xp - how many experience point you have. Use these to increase your
	other abilities. 
Engine - this is really the capacity of your hyperspace engine. To work
	it needs antimatter, and the bigger and better the engine, the
	less antimatter it requires to take you to other solar systems.
	The engine moves your ship in and out of a parallell universe,
	commonly known as hyperspace, where time and space are different
	from what we are used to. Seemingly endless distances may be
	travelled in only a few seconds, thanks to hyperspace.
Antimatter - for every molecule of real visible matter, there exists 
	an antagonist, called antimatter. If matter and antimatter should
	ever meet, vast amounts of energy would be the result and nothing
	else! This phenomena has been exploited by scientists to create
	the hyperspace engine, which uses antimatter as fuel.
	Warning: Make sure you never run out of it, or you are stuck!
	As a safety your ship is also equipped with a small antimatter 
	producing unit, which produces one unit of antimatter every turn.
Solar System - shows the name of the solar system you currently are in.
Enter Solar System - shows the bodys of the system and other ships that
	may be in this same system.
Use Hyperdrive - takes you to a map of the galaxy where you may travel
	to other solar systems.
End Turn - end your turn. Maybe you are waiting for your ship to be 
	repaired, or antimatter to be produced?


Solar System Screen
Move your ship over any planet you want to visit. When and where you may
land on the surface, a box surrounding the planet will be visible.
Now just press fire to land on the planet.
If you want to return to the status screen from this screen, just press
fire when you have not highlighted a box.
The big planet on the left of every solar system screen is in fact not
a planet, but a sun. Do not try to land on it...

Hyperspace Engine Screen
Move your joystick to localize in what system you are now. Then move
the crooshair to a system you want to visit, check the name of it, 
the amount of antimatter needed to go there and the amount of antimatter
that you have available. If you have enough antimatter, and you choose
to go to this new system, press fire. Otherwise go back to your current
system, (antimatter needed equals zero) and press fire. This way you
will return to the status screen.

Market Planets
On these planets you may pay back your loan, gamble for credits or 
antimatter or just buy new and bigger ships...

Fighting Planets
Many planets are inhabited by nasty aliens trying to get rid of you as
soon as you show up. They will try to kill you, so you better fight back!
Just remember, you lasers will fire in the direction you are flying so
never be still! Also, on the bottom of the screen is five indicators
showing how much longer before you may fire. You can only fire when all
five indicators are lit.
When your ship has lost 75 per cent of its hull or more, it will start 
to flash violently.
Now you must really be carefull or "you're gonna' get your ass kicked" .
If you touch or fly into any of your enemies, instant death awaits you!
If you manage to exterminate all the aliens, you loot the planet, 
of course, and you will be notified of what you found.


/Nexus 950615
