7 July 1996, Linkoping, Sweden

Looking through my good old code library I stumbled upon this
game that I put together last summer and then hadn't had
any time to continue on. So I though I might as well spread
it to those of you who still use the A1200.
After some hours of bug-deletion I put together this far 
from final version (at least considering what I inteded from
the start!). Although I know quite a few bugs still left 
I hope someone will find it worth a few minutes of play...

So have a nice few minutes! And I will NOT be held responsible 
for any damage this game might cause to Your computer! 
It has been developed and tested on a non-expanded A1200, only!

By the way, this is a 100% assembler game, compiled with the
one and only, AsmOne by Promax.

/Torbjorn Nilsson, aka Nexus of Magic Design

E-mail:   nexus@lysator.liu.se
Homepage: http://www.lysator.liu.se/~celeborn/_magic.html

