// generated by Fast Light User Interface Designer (fluid) version 1.00

#include <FL/Fl.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Menu_Bar.H>
#include <FL/Fl_Slider.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Ask.H>
#include <FL/fl_draw.H>

extern Fl_Slider *y_slider;
extern Fl_Slider *x_silder;
extern Fl_Menu_Bar *main_menu;
Fl_Double_Window* make_gamewin();
extern Fl_Slider *y_slider;
extern Fl_Slider *x_silder;
extern Fl_Menu_Bar *main_menu;
extern Fl_Menu_Item menu_main_menu[];
