4
From KIDS Discover magazine
1
Where are the pyramids found?
585
Iraq
India
Eqypt
Africa
2
3
1
What was buried in the pyramid?
585
Camels
Pharoahs
Scientists
Mommys
2
2
1
Pyramids were constructed from:
585
sand & clay
limestone & granite
pebbles & concrete
brick & steel
2
2
1
The longest river in the world is the:
585
Amazon
Tile
Mississippi
Nile
2
4
1
Eqypt is in the
585
Arctic circle
Rain forest
Desert
Mountains
2
3
0
