; $VER: AFind.install 1.61 (17.12.96)
; Install script for AFind (Workbench 2.0 or higher)
;
(COMPLETE 0)
;(USER 2) ;Nur für den Test.
(SET #ApplicationName "Spy_vs_Spy")
(SET #ApplicationDir "sys:")
;(SET #ApplicationDir "ram:") ;Nur für den Test.
(SET #ArchiveDir "df0:")
(SET #ArchiveDir "/") ;Wenn das Skript auf der OriginalDisk in einem
                      ;Install ordner liegt.
;=============================================================================
; German strings

(IF (= @language "deutsch")
(
(SET default_lang 2)

(SET #bad-kick "Sie benötigen Workbench 2.0 oder größer")
(SET #bad-installer
(CAT "Achtung! Es ist eine alte Version des Programmes 'Installer' "
     "auf Ihrem Amiga!\n\nDie Installation benötigt mindestens Installer 42.9.\n\n"
     "Bitte überprüfen Sie Ihre Konfiguration!\n"
     "Wenn Sie fortfahren, wird eine Vollinstallation vorgenommen, das heißt\n"
     "es werden alle Kataloge,Anleitungen und die OS2.0+ Version installiert.\n"
     "%s ist auch dann voll einsatzfähig!"
))

(SET #App-InstallMsg
(CAT "\n\%s Installationsskript.\n"
        "Diese Skript installiert %s auf Ihrer Amiga Festplatte.\n\n"
        "%s-Install © 1997 Guido Mersmann\n"
        "All Rechte reserviert."
))

(SET #App-Where
(CAT "Wo möchten Sie %s installieren ?\n"
        "(Ein Verzeichnis wird angelegt)"
))
(SET #App-WhereSource
(CAT "Wo befindet sich 'Spy Vs Spy'!"
))

(SET #App-Exit "\n%s installiert !!")


))

;=============================================================================
; English strings

(IF (<> @language "deutsch")
(
(SET default_lang 4)

(SET #bad-kick "You must have at least Workbench 2.0+")
(SET #bad-installer
(CAT "You have an old version of the program 'Installer' "
     "on your Amiga!\n\nThe installation procedure needs at least Installer 42.9.\n\n"
     "Please check your configuration!\n\n"
     "If you proceed the whole archive will be installed.\n"
     "%s will work without any restrictions!"
))

(SET #App-InstallMsg
(CAT "\n\%s installation script.\n"
        "This script installs %s on your Amiga-Harddisk.\n\n"
        "%s-Install © 1997 Guido Mersmann\n"
        "All rights reserved."
))

(SET #App-Where
(CAT "Where would you like to install %s ?\n"
        "(A drawer will be created)"
))
(SET #App-WhereSource
(CAT "Where is your 'Spy Vs Spy'!\n"
))


(SET #App-Exit "\n%s installed !!")


))
;----------------------------------------------------------------------------
;----------------------------------------------------------------------------
;	Copy_File (Name) (Newname)
;----------------------------------------------------------------------------
;----------------------------------------------------------------------------
(PROCEDURE P_CopyFile #Dummy #NewName

(if (<> (exists (TACKON #ArchiveDir #Dummy) (noreq)) 0) 
(
                   (COPYFILES
	(SOURCE (TACKON #ArchiveDir #Dummy))
	(DEST #ApplicationDir)
	(NEWNAME #NewName)
	(HELP @copyfiles-help)
	(OPTIONAL <force>)
	(ALL)
	(INFOS)
                   )
)
) ;If
) ;PROCEDURE

;----------------------------------------------------------------------------
;----------------------------------------------------------------------------
;	GetApplicationDir
;----------------------------------------------------------------------------
;----------------------------------------------------------------------------
(PROCEDURE P_GetApplicationDir #Dummy

(SET #ApplicationDir
        (TACKON
                (ASKDIR
                        (PROMPT (#App-Where #ApplicationName))
                        (HELP @askdir-help)
                        (default #Dummy)
                )
                #ApplicationName
        )
)
) ;PROCEDURE
;----------------------------------------------------------------------------
;----------------------------------------------------------------------------
;	P_CopyArchiveIcon
;----------------------------------------------------------------------------
;----------------------------------------------------------------------------
(PROCEDURE P_CopyArchiveIcon
                   (COPYFILES
	(SOURCE (CAT (CAT (TACKON #ArchiveDir "/") #ApplicationName) ".info"))
	(DEST (TACKON #ApplicationDir "/"))
	(HELP @copyfiles-help)
                   )
) ;PROCEDURE
;----------------------------------------------------------------------------
;----------------------------------------------------------------------------
;	P_Rename
;----------------------------------------------------------------------------
;----------------------------------------------------------------------------
(PROCEDURE P_Rename #Dummy #Dummy2
(if (= (exists (TACKON #ApplicationDir #Dummy)) 2)
        (rename (TACKON #ApplicationDir #Dummy) (TACKON #ApplicationDir #Dummy2))
)
) ;PROCEDURE
;----------------------------------------------------------------------------
;----------------------------------------------------------------------------
;	GetSourceDir
;----------------------------------------------------------------------------
;----------------------------------------------------------------------------
(PROCEDURE P_GetSourceDir #Dummy

(SET #ArchiveDir
                (ASKDIR
                        (PROMPT (#App-WhereSource #ApplicationName))
                        (HELP @askdir-help)
                        (default #Dummy)
                )
)
) ;PROCEDURE
;----------------------------------------------------------------------------
;----------------------------------------------------------------------------
;	MAIN
;----------------------------------------------------------------------------
;----------------------------------------------------------------------------
(message (#App-installmsg #ApplicationName #ApplicationName #ApplicationName #ApplicationName))
(welcome)

 (SET #ApplicationDir (P_GetApplicationDir #ApplicationDir))
; (SET #ArchiveDir (P_GetSourceDir #ArchiveDir))

 (MAKEDIR #ApplicationDir)
 (SET #ArchiveDir (Tackon #ArchiveDir "d/"))

 (P_CopyFile "spy1prg" "0")
(COMPLETE 50)
 (P_CopyFile "PICT.PI1" "1")
(COMPLETE 60)
 (P_CopyFile "PICU.PI1" "2")
(COMPLETE 70)
 (P_CopyFile "PICZ.PI1" "3")
(COMPLETE 80)
 (P_CopyFile "PICS.PI1" "4")
(COMPLETE 90)
 (P_CopyFile "PICY.PI1" "5")
(SET #ArchiveDir "")
 (P_CopyFile "Data" "Spy_vs_Spy")
 (P_CopyFile "Spy_vs_Spyinfo" "Spy_vs_Spy.info")


; (SET #Dummy
; (CAT "SpyConvert " (Tackon #ApplicationDir "Spy_Vs_Spy")
; ))
; (RUN #Dummy)
(COMPLETE 100)

;(exit #App-exit)
