|                                    | |                              |
C                                    | |                              C
Y                                    | |                              Y
A            ___          _     |\   | |  _  ___   ______             A
N           / _/ /\  /\  / \    | \  | | | | \_ \  \____/             N
I          / /   \ \/ / / O \   |  \ | | | |   \ \ ______             I
D          \ \    \  / / ___ \  |   \| | | |   / / \____/             D
E           \ \   / / / /   \ \ | |\   | | |  / /  ______             E
|            \/   \/  \/     \/ | | \  | |_|  \/   \____/             |
*                               | |  \ |                              *
|                               | |   \|  [RaT]                       |
C                               | |                                   C
Y                              _| |_                                  Y
A                              \   /                                  A
N                               \ /                                   N
I                                V                                    I
D                                                                     D
E                          P R E S E N T :                            E
|                                                                     |
*                                                                     *
                         -------------------- 
                         HEART OF CHINA SOLVE 
                         -------------------- 

 IN HONGKONG :  
 ------------- 

 JAKE MASTERS (JM) GOES TO TOWN. HIS FIRST TRIP LEADS TO THE PUB.
 AFTER A TALK TO THE KEEPER HO (1 1 1 1) , 2 DIRTY GUYS ARE
 THREATENING HIM (1 2). IN A TALK HE MANAGES TO PERSUADE THE CHINESE
 CHI TO GET WITH HIM ON A RESCUE-TRIP (1 3 3 OR 3 3 2).
 CHI FAERS GOING BY PLANE. SO JM LEAVES THE PUB, TAKES THE PAPER AND
 CONSTRUCTS A LITTLE PLANE OUT OF IT, THAT HE PRESENTS CHI.
 CHI HAS THE IDEA TO GET HERBS AT THE CHEMIST'S SHOP.
 WU DOESN'T REACT WHEN JM TALKS TO HIM. CHI MANAGES TO PERSUADE THE
 CHEMIST. THE CHEMIST NEEDS "GULL-GUANO".
 JM AND CHI GO TO THE DOCK. CHI GIVES A PRUNE TO THE GULL.
 THE GULL SHITS AND JM PUTS THE SHIT INTO HIS POCKET.
 AGAIN AT THE CHEMIST WU.
 JM TALKS TO HIM AND PUTS THE GUANO INTO THE MORTAR. 
 HE GETS THE HERBS AND A FAKED PASSPORT AND A MAP.JM AND CHI
 VISIT LOMAX BEFORE THE JOURNEY. AT TH AIRPORT JM DECIDES TO DON'T
 SHOW THE TICKET-COLLECTOR HIS PASSPORT. INSIDE THE PLANE JM TAKES
 THE CROWBAR, THE ROPE AND THE ANCHOR.


 IN CHENG DU :
 -------------

 AFTER ARRIVAL A FARMER APPEARS WHICH TALKS TO CHI (3 2 3). CHI
 CHNAGES HIS CLOTHES AGAINST THE FARMER'S. JM TRIES TO CATCH THE COW
 WITH THE ROPE. AFTER SEVERAL USELESS TRIES HE GIVES THE ROPE TO CHI
 WHICH HAS LESS PROBLEMS. WITH THE CAUGHT COW THE BOTH GO TO THE
 CASTLE. THERE THEY WATCH A FARMER WHICH IS ALLOWED TO ENTER THE
 CASTLE WITH HIS COW. OF COURSE, CHI TRIES THE SAME TRICK.
 JM GIVES HIM THE ANCHOR THAT CHI CONNECTS WITH THE ROPE. ARRIVED
 INSIDE, CHI PUTS ON HIS NINJA-CLOTHES AT ONCE. AT FIRST HE EXPLORES
 THE DOOR-KEEPER'S HOME AND TAKES THE KEYS. THEN CHI SNEAKS INTO
 THE PALACE AND LISTENS TO A TALK LI DENG'S. IN THE BIG HALL HE
 FINDS KATE AND TELLS HER TO GET HELP AS FAST AS POSSIBLE.
 BACK IN THE ENTRY-HALL CHI GOES INTO THE DINING-ROOM AND TAKES THE
 BOTTLE.HE GOES ON TO THE KITCHEN AND NARCOTIZES THE DOG WITH THE
 WINE. HE TAKES THE BOTH FRIED CHICKENS. THEN HE ENTERS THE COOKS
 ROOM. FROM THERE HE GETS THE KNIFE. HE OPENS THE DOOR AND DISCOVERS
 A SECOND ENTRY TO THE BIG HALL. AFTER EXPLORING THE PALACE CHI
 WALKS TO THE CASTLE-WALL. HE THROWS THE ANCHOR OVER THE WALL AND
 PULLS JM OVER IT. TO HIDE FROM THE GUARDIANS, THE BOTH SNEAK BACK
 INTO THE DOOR-KEEPER'S HOME. WHEN THE DANGER IS OVER , THE BOTH RUN
 INTO THE PALACE. WHEN THE GUARDIANS HAVE LEFT THE ROOM ,JM AND CHI
 GO INTO THE DINING-ROOM. THERE JM THROWS DOWN THE LAMP AND LIGHTS
 A FIRE. THROUGH KITCHEN AND BEDROOM THEY ARRIVE IN THE BIG HALL.
 JM LOCKS THE DOOR AND SHOTS THE SNAKES. UNFORTUNATELY HE CAN'T STOP
 THE SNAKES BEFORE BITING KATE. JM CARRIES KATE ON HIS ARMS AND
 ESCAPES TO THE BALCONY. THERE CHI CONNECTS THE ROPE WITH THE
 BALUSTRADE AND THE THREE ESCAPE TO THE TANK-GARAGE. IN THE TANK JM
 USES THE KEY AND PUSHES THE STARTER. IT FOLLOWS THE FIRST ACTION-
 SEQUENCE. IN THE PLANE JM GIVES THE HERBS TO CHI.


 IN KATHMANDU 
 ------------ 

 JM LEAVES THE PLANE AND TALKS TO CHI ABOUT THE SITUATION. JM GOES
 GETTING HELP, CHI WALKS BACK TO THE PLANE. THERE HE TAKES A TENT-
 ROOF AND A BLANKET AND PUTS IT AROUND KATE. HE GIVES HER HIS
 NINJA-MEDICINE AND THE GUANO-HERBS. JM TALKS TO AMA (2 2 3) AND
 AFTER THAT HE LOOKS AROUND IN THE VILLAGE. IN THE POST-OFFICE HE
 POSTS A TELEGRAM TO LOMAX. THEN HE VISITS THE RESTAURANT AND
 TALKS TO THE KEEPER (2 3). THE KEEPER SENDS HIM TO SARDAR (2).
 NOW JM GOES TO THE LAMA. AFTER A SHORT TALK TO A YOUNG MONK HE
 IS ALLOWED TO ENTER. THE FIRST TALK TO THE WISE MAN IS RESULTLESS.
 JM GOES TO THE LOCAL DICTATOR. AFTER A WRONG REMARK HE FLIES
 INTO THE PRISON. CHI RUNS TO AMA AND SHE RESCUES JM. JM HAS A 
 SHORT TALK TO KATE AND AFTER THAT HE HAS A TRIP TO THE SCRAP YARD
 WHERE HE MEETS A BOY. THE BOY OFFERS AFTER A SHORT TALK A TUBE
 WHICH IS FULL OF PETROL FOR A SWAP. CHI BUILDS FROM THE CIGAR-
 BOX, THE EATING-STICKS AND FOUR COINS A PLAY-CAR; FOR THIS HE  GETS
 THE PETROL-TUBE. NOW HE GOES BACK TO THE LAMA AND RECEIVES SOME
 NEWS. IN THE RESTAURANT HE MANAGES TO PERSUADE SARDAR TO HELP (1 3).
 JM GIVES HIN HIS WEAPON AS A PRESENT AND THE REVOLUTION STARTS.
 THE GAME CONTINUES IN TURKEY.


 IN ISTANBUL
 ----------- 

 ON THE RUNWAY JM GETS NO PETROL FROM THE SELLER. ON THE WAY TO  
 TOWN KATE AND JM NOTICE A LITTLE BOY SELLING ORANGES. JM FINDS IN
 A SIDE-ROAD THE OFFICERS' CLUB AND HAS FROM THERE A LITTLE CALL TO
 LOMAX AFTER THAT JAKE IS CAUGHT FROM THE SULTAN'S CREW. KATE SWAPS
 HER BROOCH AT THE SELLER AND GAMBLES FOR MORE MONEY. AFTER THAT
 SHE SHE GOES TO THE ORANGE-SELLER AND OVERTHROWS HIS CART. SHE
 SAYS SORRY AND GETS A FLOWER FROM HER YOUNG FAN. NOW SHE BUYS A
 CAMEL FOR 200. SHE GOES BACK TO THE SHOP AND BUYS A SAW. NOW SHE
 RIDES ON CAMEL-BACK TO THE PALACE. IN A SIDE-ROAD SHE MEETS A
 WOMAN A GIVES HER THE FLOWER. KATE RESCUES JM AND THEY ESCAPE TO
 THE TOWN-GATE. THERE KATE GIVES THE CAMEL TO THE BOY AND JM
 WHISPERS SOME WORDS OF EXCUSING (3 2).
 ARRIVED AT THE AIRPORT THEY SEE BURSTING THEIR PLANE INTO FLAMES.
 THEY ESCAPE TO THE STATION AND BUY A TICKET FOR THE ORIENT-EXPRESS.


 IN THE TRAIN
 ------------ 

 JM'S   SCENE : (1 1 3 3)
 KATE'S SCENE : (2 1 3)

 IT FOLLOWS THE HAPPY... 

          :+:END:+:
                                     DONE BY RAT/CYANiDE

