[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]
[]                   A Solve To Spellbreaker                  []
[][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][][]

This is not a help file; it is a solve. Furthermore this solve
will not always follow a word for word format. This is because
the game changes with every boot up and in some places every time
you get into a room.

There are many places in this solve where you will have to put
things in your zipper or take them out. Again I must stress that
this is NOT a word for word solution.

In order to finish the game you must recover 13 cubes. Each of
these 13 cubes take you to different rooms when you use the
blorple spell on them. All the cubes look alike except for the
last one you get. To tell them apart you must put them in a magic
box which you aquire soon in the game. Once you put them in the
box, the box depicts an animal. The animal for each cube is
different and this is how you disern them. The following is a
list of the cubes and where they take you.

Cube                                                         Room
-----------------------------------------------------------------
Moles                                                Packed Earth
Rabbits                                                 Soft Room
Dolphins                                               Water Room
Eagles                                                   Air Room
Worms                                                   Bone Room
Spiders                                                  Web Room
Fireflies                                              Light Room
Butterflies                                         Changing Room
Owls                                                 Nothing Room
Grues                                                   Dark Room
Salamanders                                             Fire Room
Unicorns                                               Magic Room
Turtles                                                 Sand Room

Onto the solve.....

Z.Z.Z.S.GET ALL.LEARN LESOCH.G.G.LEARN BLORPLE.S.LESOCH (UNTIL IT
WORKS).GET CUBE.BLORPLE CUBE

PACKED EARTH
------------
FROTZ KNIFE.E.S.GET ZIPPER.OPEN ZIPPER.BLORPLE CUBE
PACKED EARTH
------------
D.D.Z (UNTIL ROC CATCHES YOU).Z(UNTIL ROC TAKES YOU TO HER
NEST).GET SCROLL.GNUSTO CASKLY.LEARN BLORPLE.BLORPLE CUBE.S.GET
SCROLL.GNUSTO THROCK.GET SCROLL FROM ZIPPER.U.Z(UNTIL LARGE
BOULDERS ARE ABOUT TO FALL).GIRGOL.U(UNTIL YOU REACH TOP OF
MOUNTAIN).GET COIN.W(IN THE HERMETS HOUSE).LEARN CASKLY.CASKLY
HUT (UNTIL IT WORKS).GET CUBE.LEARN BLORPLE.BLORPLE CUBE

SOFT ROOM
---------
S.GET WEED.G.PUT CUBE IN ZIPPER.LEARN BLORPLE.BLORPLE
CUBE

PACKED EARTH
------------
W.W.N.PLANT WEED.LEARN THROCK.THROCK WEED.D.GET ALL.U.S.
GNUSTO ESPNIS.OPEN BOX.GET CUBE.LEARN BLORPLE.BLORPLE CUBE

WATER ROOM
----------
LEARN BLORPLE.PUT ALL IN ZIPPER.GET FISH.GET KNIFE.CLOSE
ZIPPER.S.DROP FISH.GET CUBE.GET BOTTLE.BLORPLE CUBE

WATER ROOM
----------
IN THE MANNER DESCRIBED ABOVE GET THE MOLE CUBE.LEARN BLORPLE.
BLORPLE CUBE

PACKED EARTH
------------
OPEN BOTTLE.GET SCROLL.GNUSTO LISKON.LEARN LISKON.E.N.LISKON
SERPENT.N.N. (THE FOLLOWING SEQUENCE YOU MAY HAVE TO DO SEVERAL
TIMES UNTIL IT WORKS CORRECTLY) LEARN MALYON.LEARN ESPNIS.MALYON
IDOL.Z.ESPNIS IDOL.Z.Z.Z.(IF IT WORKED CORRECTLY THEN CONTINUE).
CLIMB IDOL.GET CUBE.LEARN BLORPLE.BLORPLE CUBE

AIR ROOM
--------
LEARN BLORPLE.N.GET SCROLL.GNUSTO TINSOT.BLORPLE CUBE

AIR ROOM
--------
W.E.OFFER 300.OFFER 400.OFFER 500.DROP RED CARPET.GET BLUE
CARPET.W.LEARN BLORPLE.(FIND DOLPHIN CUBE) BLORPLE CUBE

WATER ROOM
----------
N.LEARN TINSOT.G.G.G.G.PUT ALL IN ZIPPER BUT KNIFE.CLOSE
ZIPPER.TINSOT OUTFLOW PIPE.TINSOT OUTFLOW PIPE(SOMETIMES THE
SPELL DOESN'T WORK SO DO IT UNTIL IT DOES TWICE).Z.Z.Z.REZROV
DOOR.TINSOT WATER (UNTIL IT WORKS).GET ON ICE FLOW.U.GET
CUBE.E.N.REZROV CABINET.GET MOULDY BOOK.LEARN CASKLY.CASKLY
MOULDY BOOK (UNTIL IT WORKS).GNUSTO SNAVIG.S.W.U.DROP CARPET.SIT
ON CARPET.U.W (UNTIL YOU ARE AT THE ABOVE THE MOUNTAINS).N (UNTIL
YOU ARE ABOVE THE NEST).LEARN BLORPLE.D.GET OFF CARPET.GET
ALL.BLORPLE CUBE

WEB ROOM
--------
S.SHOW CUBE TO BELBOZ.ANSWER HIS QUESTION CORRECTLY.(FIND DOLPHIN
CUBE).LEARN BLORPLE.BLORPLE CUBE

WATER ROOM
----------
LEARN BLORPLE.LEARN SNAVIG.PUT ALL IN ZIPPER BUT KNIFE.CLOSE
ZIPPER.S.GET CUBE.SNAVIG GROUPER.D.Z(UNTIL YOU ARE YOURSELF
AGAIN).GET ALL.U.BLORPLE CUBE

LIGHT ROOM
----------
W.Z(UNTIL FRAGMENT APPEARS).LEARN TINSOT.TINSOT FRAGMENT(UNTIL IT
WORKS).GET FRAGMENT.(GET DOLPHIN CUBE)LEARN BLORPLE.BLORPLE CUBE

WATER ROOM
----------
N.LEARN LISKON.PUT ALL IN ZIPPER BUT KNIFE.CLOSE ZIPPER.LISKON
SELF (UNTIL IT WORKS).ENTER OUTFLOW PIPE.W.GET CUBE.W.U.LEARN
BLORPLE.BLORPLE CUBE

CHANGING ROOM
-------------
N.GET ROSE.LEARN BLORPLE.BLORPLE CUBE

CHANGING ROOM
-------------
W.PUT ROSE IN CARVING.GET ROSE.N.TOUCH ROSE TO W RUNE.W.TOUCH
ROSE TO NE RUNE.NE.TOUCH ROSE TO NW RUNE.NW.REZROV ALABASTER.W
GET CUBE.LEARN BLORPLE.BLORPLE CUBE

NOTHING ROOM
------------
S.DROP FRAGMENT.CLIMB ROCK.ROCK, GO S.ROCK, GO N.G.ROCK, GO SW
ROCK, GO S.ROCK, GO E.G.G.(THE NEXT MOVE DEPENDS ON WHICH
DIRECTION THE OTHER ROCK MOVED LAST, IF HE WENT N THEN: ROCK, GO
E. IF HE WENT W THEN: ROCK, GO S).CLIMB OTHER ROCK.GET CUBE.LEARN
BLORPLE.BLORPLE CUBE

DARK ROOM
---------
D.DROP KNIFE.LEARN SNAVIG.LEARN BLORPLE.PUT ALL IN ZIPPER.CLOSE
ZIPPER.D.SNAVIG GRUE.ENTER POOL.CLIMB PILLAR.GET CUBE.Z(UNTIL YOU
ARE YOURSELF AGAIN).BLORPLE CUBE

FIRE ROOM
---------
PUT CUBE IN BOX.GET CUBE FROM BOX.N.THROW BOW ON OUTCROPPING
LEARN BLORPLE.BLORPLE CUBE
FIRE ROOM
---------
W.GET ALL.(FIND OWL CUBE).LEARN BLORPLE.BLORPLE CUBE

NOTHING ROOM
------------
E.SAVE GAME.(THE NEXT ROOM YOU ENTER CHANGES EVERY TIME YOU ENTER
IT).LEARN JINDAK.G.G.G.G.LEARN BLORPLE.REZROV DOOR.N.GET X2,X7
JINDAK.(IF BOTH PILES ARE EQUAL THEN PUT BOTH BACK AND JINDAK
AGAIN THEN SEE WHICH PILE GLOWS MORE BRIGHTLY, IF THE FIRST ONE
GLOWS MORE BRIGHTLY THEN GET X2 CUBE AND BLORPLE IT.IF IT WAS THE
SECOND ONE THAN GET X7 AND BLORPLE IT).(IF THE PILES ARE OF
DIFFERENT BRIGHTNESS THEN REMEMBER WHICH ONE WAS BRIGHTER, IF THE
FIRST PILE GLOWED BRIGHTER THAT MEANS THE LOWER NUMBERED CUBE IS
THE RIGHT ONE IF THE SECOND PILE GLOWED BRIGHTER THAT MEANS THE
HIGHER NUMBERED CUBE IS THE RIGHT ONE).GET X3,X8.JINDAK.(IF EQUAL
THAN USE THE HIGHER OR LOWER NUMBERED CUBE AS DESCRIBED ABOVE).IF
NOT EQUAL THEN GET X4,X9.REPEAT PREVIOUS IF EQUAL, IF NOT EQUAL
THEN RESTORE AND TRY AGAIN. YOU MAY HAVE TO DO THIS SEVERL TIMES.

SAND ROOM
---------
D.UNLOCK CABINET WITH KEY.OPEN CABINET.GET SCROLL.LEARN BLORPLE
G.G.G.G.G.G.PUT BOOK IN CABINET.CLOSE CABINET.LOCK CABINET WITH
KEY.REZROV DOOR.BLORPLE (THE X CUBE YOU GOT TO THE SAND ROOM
WITH)

SAND ROOM
---------
DROP ALL BUT BURIN,SCROLL,BOX,ZIPPER.(FIND UNICORN CUBE).PUT CUBE
IN BOX.GET ALL CUBES.PUT ALL CUBES IN ZIPPER.GET ALL CUBES.PUT
ALL CUBES IN ZIPPER.(UNTIL ALL CUBE BUT THE UNICORN CUBE ARE IN
THE ZIPPER).U.GET SACK.OPEN SACK.COPY GIRGOL ON VELLUM SCROLL
EMPTY ZIPPER INTO SACK.GET FLIMSY SCROLL.PUT FLIMSY SCROLL IN
ZIPPER.CLOSE ZIPPER.DROP ZIPPER.GET BOX.GET CUBE FROM BOX.BLORPLE
CUBE

MAGIC ROOM
----------
E.Z.HOLD CUBE.Z(UNTIL THE SHADOWY FIGURE IS ABOUT TO JUMP INTO
THE HYPERCUBE).GIRGOL.GET CUBE FROM HYPERCUBE.PUT SACK IN
HYPERCUBE!

THERE YOU HAVE IT! 600 OUT OF 600....THERE MAY BE FLAWS IN THE
SOLUTION BECAUSE I AM DOING THIS STRICTLY FROM MEMORY.

-Davros-
