                       WITNESS (Infocom)

NOTE: This file contains two different solves.


        T H E   W I T N E S S !  (TUTORIAL (C) 1983 BY DOOBIE PRODS.)

"THE WITNESS" IS A PRETTY STRAIGHT-FORWARD LITTLE MYSTERY. IT'S NOT AS
COMPLICATED OR INVOLVED AS DEADLINE, YET ITS ATMOSPHERE AND DETAIL MORE
THAN COMPENSATES FOR ITS QUICK SOLVABILITY.

ACTUALLY, "THE WITNESS" CAN BE SOLVED BY NEVER HAVING TO LEAVE THE SITE OF
THE MURDER! HOWEVER, A LOT OF THE FUN FUN AND INTERESTING NUANCES OF THIS
GAME CAN BE MISSED BY FOLLOWING THIS QUICK-FINISH, SO BEFORE I REVEAL IT
STEP-BY-STEP, I'LL GIVE YOU A FEW "THINGS TO TRY". THIS IS FOR ALL THOSE
TRUE ADVENTURERS WHO MIGHT JUST BE LOOKING FOR A LITTLE NUDGE IN THE
RIGHT DIRECTION.

THE GAME IS SUPPOSED TO BE PRETTY AUTOMATIC FOR THE FIRST PART, SO
UNLESS YOU'RE WANDERING ABOUT OUTSIDE THE HOUSE FOR MAPPING PURPOSES,
START THE GAME BY DOING THE FOLLOWING:

N,N, "RING THE BELL"

LINDER'S BUTLER, PHONG, WILL ANSWER THE DOOR. YOU CAN NOW DO ANYTHING FOR
ONE MOVE, THEN PHONG WILL SHOW YOU INTO THE LIVING ROOM, WHERE YOU WILL MEET
LINDER AND HIS DAUGHTER, MONICA.

IT MIGHT HELP HERE TO ASK MR. LINDER AND MONICA ABOUT ALL THE OTHER CHAR-
ACTERS IN THE GAME (THIS IS A MUST IN ALL INFOCOM MYSTERIES!). DO THIS
BY SAYING "ASK LINDER ABOUT (MONICA OR MRS. LINDER OR PHONG, ETC.).

AFTER A BIT (10-12 MINUTES), LINDER WILL TAKE YOU INTO HIS OFFICE. HERE
YOU SHOULD "SIT IN THE WOODEN CHAIR" WHEN HE ASKS YOU TO. HE WILL THEN FILL
YOU IN ON THE BACKSTORY OF THE GAME AND WILL SHOW YOU A NOTE, WHICH YOU
MIGHT BE POLITE ENOUGH TO READ.
 

NOW, IF YOU SIT THERE AND WAIT, MONICA WILL ENTER AROUND 8:35 AND STICK 
AROUND FOR A MOMENT TALKING TO HER FATHER BEFORE HEADING OFF TO GO
TO THE MOVIES. IF YOU WAIT UNTIL AROUND 9:03, LINDER WILL HEAR THE
DOORBELL; PUSH THE BUTLER'S BUTTON TO SIGNAL PHONG; THEN DIE FROM A
BULLET SHOT THROUGH THE OFFICE WINDOW.

BEFORE LINDER IS KILLED, YOU MIGHT WANT TO TRY THE FOLLOWING AND SEE
WHAT HAPPENS (OR DOESN'T...):

   1. TRY PUSHING THE BUTLER'S BUTTON AND SEE WHAT LINDER DOES.

   2. EXAMINE THE WINDOW AND ASK LINDER ABOUT WHAT YOU FIND THERE.

   3. EXAMINE THE CLOCK AND TRY OPENING IT.

   4. TRY STANDING UP AFTER YOU'VE FIRST SAT DOWN IN THE CHAIR.
      THEN WAIT UNTIL 9:03 (I'D SAVE THE GAME FIRST!).


AFTER THE MURDER OCCURS, TRY THE FOLLOWING:

   1. EXAMINE THE WINDOW AND ANALYZE WHAT YOU FIND THERE.

   2. EXAMINE THE KEYHOLE IN THE CLOCK.

   3. TRY PUSHING THE BUTLER'S BUTTON RIGHT AFTER THE MURDER. THEN TRY
      PUSHING IT AGAIN AFTER MONICA GETS HOME (AROUND 11:00).

   4. IF YOU "SEARCH PHONG", YOU WILL FIND THE KEYS YOU NEED TO UNLOCK
      ALL THE LOCKED DOORS IN THE HOUSE.

   5. GO INTO PHONG'S ROOM AND EXAMINE THE BOOK HE'S READING. HE'S USING
      A VERY INTERESTING BOOKMARK. SHOW THIS TO PHONG AND MONICA AND THE
      TIED-UP STILES (HE'S IN THE LIVING ROOM.

   6. FOR FUN, TRY CALLING THE RESTAURANT'S PHONE # THAT'S ON THE
      MATCHBOOK (ADELINE 1308).

   7. ANALYZE THE FOOTPRINTS YOU FIND IN THE MUD OUTSIDE THE OFFICE
      PORCH.. THEN COMPARE THE PLASTER CAST DUFFY MAKES TO STILES'
      SHOES AND ALSO TO THE MUDDY BOOTS YOU FIND ON THE PLATFORM BY THE
      FRONT DOOR. ALSO, SHOW THE MUDDY BOOTS TO PHONG.

   8. SHOW STILES THE: MATCHBOOK; THE NOTE LINDER GAVE YOU; AND
      THE MUDDY HANDGUN (YOU FIND THIS OUTSIDE BY THE OFFICE PATH.)

   9. BEFORE MONICA GETS HOME (11:00), UNLOCK AND OPEN THE WORKSHOP
      DOOR (IN THE GARAGE) THEN GO INSIDE THE WORKSHOP AND "WAIT FOR
      MONICA'. WATCH WHAT SHE DOES WHEN SHE DRIVES IN AND ENTERS.

  10. OF COURSE, ASK EVERYBODY ABOUT EVERYBODY ELSE; SHOW EVERYTHING
      OF INTEREST TO EVERYONE; AND TRY ACCUSING PHONG, MONICA AND STILES.

NOW, FOR THOSE OF YOU LOOKING FOR A QUICK FINISH, HERE'S THE STEP-BY-STEP:

(BREAK OUT IF YOU DON'T WANT THE ANSWER )

SOLUTION:

N,N, "RING BELL", (DO ANYTHING FOR ONE MOVE, SUCH AS 'I'), (PHONG WILL LEAD
YOU INTO THE LIVING ROOM), "ASK MONICA ABOUT HER MOTHER", "WAIT", (LINDER 
WILL SOON TAKE YOU TO HIS OFFICE), "SIT IN THE WOODEN CHAIR', 'WAIT UNTIL 
9:04' (ANSWER YES WHENEVER IT ASKS IF YOU WANT TO KEEP WAITING), (LINDER WILL
BE SHOT AND KILLED), "GET UP", "HIDE BEHIND THE LOUNGE", "WAIT UNTIL
12:05" (ANSWER YES EVERYTIME IT ASKS), (SOMEWHERE AROUND MIDNIGHT, MONICA
WILL COME BACK INTO THE OFFICE, GO OVER TO THE CLOCK, UNLOCK IT AND REMOVE
SOMETHING), "STAND UP", "ACCUSE MONICA", "WAIT FOR DUFFY", "ARREST MONICA".

THE PROGRAM WILL THEN OFFER YOU A SYNOPSIS OF THE ACTUAL EVENTS.

===========================================================================
==========================================================================

            WITNESS


THIS WALKTHRU WILL HELP YOU TO FINISH "WITNESS."  THIS GAME IS A MUCH SIMPLER
ONE THAN "DEADLINE," SO I HOPE YOU WON'T BE DISAPPOINTED WHEN YOU SEE HOW 
EASY IT IS TO SOLVE THIS MYSTERY.

OKAY, YOU START SOUTH OF THE HOUSE, WHERE YOU JUST PICKED UP A MATCHBOOK. 
<BY THE WAY, NONE OF THE STUFF THAT CAME WITH THE GAME IS REALLY NECESSARY 
TO SOLVING THE CASE>.  GO NORTH TWICE TO THE FRONT DOOR AND RING THE BELL.  
PHONG WILL LET YOU IN.  THEN JUST TRY TO GO EAST, AND PHONG WILL LEAD YOU TO 
THE LIVING ROOM, WHERE MONICA AND MR. LINDER ARE.
NOW, WAIT <GET USED TO DOING THAT, BECAUSE THERE'S A LOT OF WAITING IN THIS
ONE>, AND LINDER WILL EVENTUALLY TAKE YOU TO HIS OFFICE.  SIT DOWN IN THE
WOODEN CHAIR, AND LINDER WILL HAND YOU A NOTE.  READ IT, AS IT WILL HELP 
WASTE SOME TIME.  NOW, JUST DO ANYTHING <BUT STAY SEATED!> TO MAKE TIME PASS.  
SHOW THE MATCHBOOK TO LINDER FOR AN INTERESTING REACTION, IF YOU LIKE.  IN 
ANY CASE, YOU JUST HAVE TO KEEP WAITING.

EVENTUALLY, MONICA WILL COME IN BRIEFLY TO ANNOUNCE SHE'S GOING TO THE MOVIES. 
THIS IS NOT WHAT YOU'RE WAITING FOR, HOWEVER! SO, KEEP ON WAITING, AND
FINALLY, THE MURDER WILL OCCUR. LINDER WILL BE SHOT WHILE YOU SIT THERE, AND
YOU CAN'T STOP IT FROM HAPPENING.  READ THE DESCRIPTION CAREFULLY AT THE 
MOMENT THE SHOT IS FIRED. THERE'S SOMETHING ODD ABOUT IT. IN FACT, THE WHOLE
THING IS A SETUP.

THE FIRST THING TO DO IS STAND UP, THEN PUSH THE BUTTON. INSTEAD OF RINGING 
TO SUMMON THE BUTLER, IT CAUSES A STRANGE CLICK TO BE HEARD FROM THE CLOCK. 
AT THIS POINT, PHONG WILL ENTER THE ROOM. TELL HIM YOU WANT THE KEYS, AND 
HE'LL HAND THEM OVER TO YOU.  NOW, EXAMINE THE CLOCK.  KEYHOLE SEEMS A LITTLE 
STRANGE, DOESN'T IT?  THE DOORBELL RINGS WHILE YOU'RE DOING THIS, SO AS PHONG
GOES TO ANSWER THE DOOR, EXAMINE THE KEYHOLE.

I'LL BET YOU'RE GETTING SOME IDEAS ALREADY!  HOWEVER, YOU'LL NEED TO HAVE
THE POWDER ANALYZED, AND DUFFY HASN'T ARRIVED YET, SO WAIT AROUND UNTIL HE
DOES.  THEN GET THE POWDER ANALZYED <YOU CAN IGNORE STILES, HE'S ONLY A RED
HERRING>.  WHILE THAT'S BEING DONE, EXAMINE THE WINDOW <YOU CAN'T OPEN THE
CLOCK YET, IT'S THE ONE KEY YOU DON'T HAVE>. THE GREEN WIRE SEEMS SUSPICIOUS,
SO GET IT FOR FUTURE REFERENCE. NOW, GO WEST INTO THE HALLWAY, THEN
NORTH TWICE, AND OPEN THE BUTLER'S DOOR.

GO WEST INTO THE ROOM, AND READ THE MYSTERY BOOK <BY THE WAY, YOU CAN DROP
THE TELEGRAM AND NOTE, THEY AREN'T IMPORTANT>.  A GUN RECEIPT IS USED AS A
BOOKMARK.  THE PURCHASER'S NAME IS OBVIOUSLY PHONEY, BUT HANG ON TO THE
RECEIPT ANYWAY.
OKAY, FROM THE BUTLER'S ROOM, GO EAST TWICE TO MONICA'S ROOM, THEN UNLOCK AND
OPEN THE BACK DOOR.  GO EAST INTO THE BACKYARD, THEN SOUTH TWICE TO THE 
OFFICE PATH.  AHA, A MUDDY GUN!  NO FINGERPRINTS, ALAS, BUT YOU MIGHT WANT
TO TAKE IT ALONG WITH YOU, JUST IN CASE.

NOW, GO WEST INTO THE SIDE YARD. HMM, MORE FOOTPRINTS HERE, BUT THEY
AREN'T QUITE THE SAME AS THE ONES ON THE OFFICE PATH.  IN FACT, IT LOOKS LIKE
SOMEONE WAS STANDING HERE FOR AWHILE. WONDER WHO IT MIGHT HAVE BEEN? <NO,
*NOT* SERGEANT DUFFY!>. ANYWAY, GO WEST AGAIN TO THE DRIVEWAY, THEN NORTH AND
EAST INTO THE GARAGE.

UNLOCK AND OPEN BOTH THE GARAGE DOOR AND THE WORKSHOP DOOR, THEN GO EAST INTO
THE WORKSHOP.  THE PLACE LOOKS LIKE AN ELECTRICIAN'S PARADISE, AND THERE 
ISN'T MUCH YOU CAN DO HERE; BUT, THERE ARE SPOOLS OF WIRE HANGING AROUND.  
COULD IT BE...?  EXAMINE SPOOL, AND YOU HAVE ESTABLISHED A LINK OF SORTS 
BETWEEN THIS PLACE AND THE STUDY.  THE GREEN WIRE IS OBVIOUSLY FROM THIS ROOM.
NOW, ALL YOU NEED IS THE PERSON WHO PUT IT THERE.

YOU NOW STAND THERE WAITING FOR MONICA. JUST KEEP WAITING; SHE'LL ARRIVE 
<SAYING "WAIT FOR MONICA" IS EASIEST.  IT WILL TAKE A WHILE, SO IF YOU WANT 
TO HUNT DOWN PHONG AND ASK HIM ABOUT THE GUN RECEIPT, YOU HAVE TIME>.  WHEN 
SHE DOES GET THERE, SHE'LL FIDDLE BRIEFLY WITH THE JUNCTION BOX <VERY 
SUSPICIOUS!> BEFORE NOTICING YOU.  NOW, WAIT UNTIL SHE LEAVES, THEN FOLLOW 
HER.  YOU *MUST* USE DIRECTIONS HERE, JUST SAYING "FOLLOW MONICA" WON'T WORK.
FOLLOW HER ALL THE WAY TO HER ROOM, AND WAIT FOR HER TO COME BACK OUT OF THE
BATHROOM.  WHEN SHE RETURNS, ASK HER ABOUT MR. LINDER.  HER RESPONSE WILL
ESTABLISH THE MOTIVE.  NOW, WAIT SOME MORE, AND SHE WILL EVENTUALLY LEAVE THE
ROOM. FOLLOW HER AGAIN, THIS TIME TO THE OFFICE.

AS SOON AS YOU GET IN THERE, HANDCUFF HER.  SOMEWHERE ALONG THE WAY, SGT. 
DUFFY WILL HAVE LEFT WITH THE BODY, SO YOU CAN'T ARREST HER UNTIL HE COMES
BACK. IN THE MEANTIME, YOU HAVE TO FIND SOME VERY IMPORTANT EVIDENCE.  SO, 
FIRST SEARCH MONICA FOR THE KEY.  WHEN YOU GET IT, UNLOCK THE CLOCK AND OPEN
IT.  SHE'S ALREADY REMOVED THE GUN, BUT YOU CAN SEARCH HER FOR THAT, ALSO.
NOW, JUST WAIT UNTIL DUFFY RETURNS, AND ARREST HER FOR THE MURDER.  AND THAT
SHOULD BE ABOUT IT.  BY THE WAY, IF YOU TRY LEAVING HER AND WAITING IN THE
OFFICE <SO YOU CAN FIND THE GUN IN THE CLOCK>, YOU'LL FIND THAT, HOWEVER HARD
YOU TRY, YOU WON'T BE ABLE TO HANDCUFF HER <WHICH IS NECESSARY SO SHE CAN BE
SEARCHED>.  SO, YOU'LL JUST HAVE TO WAIT AND FOLLOW HER.  AS I SAID IN THE
BEGINNING, IT'S A PRETTY SIMPLE GAME.


     THE GAME "WITNESS" IS
 COPYRIGHTED BY INFOCOM, 1983.
  THIS WALKTHRU IS COPYRIGHTED BY  SCORPIA, 1983.

